#!/usr/bin/env bash
#{{{ MARK:Header
#**************************************************************
##### Author: JACOBMENKE
##### Date: Fri Jul  7 23:52:18 EDT 2017
##### Purpose: bash script to update zsh prompt
##### Notes:
#}}}***********************************************************

#{{{ MARK:PowerLevel9k
#**************************************************************
ZSH_THEME="powerlevel9k/powerlevel9k"
source "$HOME/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir history ssh rbenv root_indicator status vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode command_execution_time dir_writable background_jobs custom_pid)

POWERLEVEL9K_MODE='nerdfont-complete'
ZLE_RPROMPT_INDENT=0

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3
POWERLEVEL9K_TIME_BACKGROUND='green'
POWERLEVEL9K_HISTORY_BACKGROUND='235'
POWERLEVEL9K_HISTORY_FOREGROUND='green'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='235'

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\u256D \n"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\u2570>%K{blue}%F{white} \Uf136 `tty` \uf168 %f%k%F{blue}%f "

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='red'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='blue'

POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='red'

POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='black'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='blue'

#POWERLEVEL9K_DIR_BACKGROUND='white'
POWERLEVEL9K_DIR_HOME_FOREGROUND="red"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

POWERLEVEL9K_CUSTOM_PID='echo -e "\uf258 $$ \uf258  `date +%D` \uf168"'
POWERLEVEL9K_CUSTOM_PID_BACKGROUND="green"
POWERLEVEL9K_CUSTOM_PID_FOREGROUND="black"

POWERLEVEL9K_CUSTOM_NEWLINE="print '\n'"
POWERLEVEL9K_CUSTOM_NEWLINE_BACKGROUND="green"
POWERLEVEL9K_CUSTOM_NEWLINE_FOREGROUND="white"

POWERLEVEL9K_CUSTOM_TTY="tty"
POWERLEVEL9K_CUSTOM_TTY_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_TTY_FOREGROUND="white"

milliamps(){
    amps="$(ioreg -rc AppleSmartBattery | grep CurrentCapacity | awk '{printf "%s mAh\n", $3}')"
    echo -e "$amps \uf168"
}

POWERLEVEL9K_CUSTOM_BATT="milliamps"
POWERLEVEL9K_CUSTOM_BATT_BACKGROUND="red"
POWERLEVEL9K_CUSTOM_BATT_FOREGROUND="black"

#}}}***********************************************************

