brew install aalib
brew install ack
brew install adns
brew install aircrack-ng
brew install alpine
brew install android-platform-tools
brew install angular-cli
brew install animationtutorial
brew install ant
brew install apple-gcc42
brew install apr
brew install apr-util
brew install argon2
brew install asciidoctor
brew install ask-cli
brew install aspcud
brew install aspell
brew install autoconf
brew install automake
brew install autossh
brew install aview
brew install bash
brew install bash-completion
brew install bash-snippets
brew install bdw-gc
brew install bison
brew install bmon
brew install boost
brew install boxes
brew install brotli
brew install bsdmake
brew install c-ares
brew install cabal-install
brew install cairo
brew install camlp4
brew install cassandra
brew install ccrypt
brew install ccze
brew install chmlib
brew install clingo
brew install clisp
brew install clojure
brew install cmake
brew install cmatrix
brew install colordiff
brew install conan
brew install confuse
brew install contacts
brew install coreutils
brew install cscope
brew install ctags
brew install ctop
brew install cython
brew install dart
brew install dbus
brew install dialog
brew install docker
brew install eigen
brew install elixir
brew install emacs
brew install erlang
brew install faad2
brew install ffmpeg
brew install fftw
brew install figlet
brew install fish
brew install flac
brew install fluid-synth
brew install fontconfig
brew install fortune
brew install fpc
brew install fping
brew install freetds
brew install freetype
brew install fswatch
brew install gawk
brew install gcc
brew install gd
brew install gdbm
brew install geckodriver
brew install geoip
brew install gettext
brew install ghc
brew install gifsicle
brew install git
brew install glassfish
brew install glib
brew install gmp
brew install gnu-prolog
brew install gnu-sed
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install gradle
brew install grails
brew install graphicsmagick
brew install grc
brew install greed
brew install grep
brew install groovy
brew install gstreamer
brew install htop
brew install httpd
brew install httrack
brew install hub
brew install icu4c
brew install ifstat
brew install ilmbase
brew install imap-uw
brew install iperf
brew install isl
brew install jansson
brew install jasper
brew install jemalloc
brew install jnettop
brew install jpeg
brew install jvmtop
brew install kotlin
brew install lame
brew install leiningen
brew install libassuan
brew install libcaca
brew install libcuefile
brew install libelf
brew install libev
brew install libevent
brew install libffi
brew install libftdi0
brew install libgcrypt
brew install libgpg-error
brew install libgtop
brew install libid3tag
brew install libidn2
brew install libksba
brew install libmaxminddb
brew install libmikmod
brew install libmodplug
brew install libmpc
brew install libmpdclient
brew install libnet
brew install libogg
brew install libpng
brew install libpq
brew install libreplaygain
brew install libsamplerate
brew install libsigsegv
brew install libsodium
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libvorbis
brew install libxml2
brew install libyaml
brew install libzip
brew install links
brew install lolcat
brew install lua
brew install lua@5.1
brew install luajit
brew install macchanger
brew install macvim
brew install mad
brew install makedepend
brew install man2html
brew install maven
brew install mercurial
brew install midnight-commander
brew install mongodb
brew install mono
brew install mp3blaster
brew install mpc
brew install mpd
brew install mpfr
brew install mplayer
brew install mtr
brew install musepack
brew install mutt
brew install mycli
brew install mysql
brew install mysql-client
brew install mytop
brew install ncmpcpp
brew install ncurses
brew install nettle
brew install nghttp2
brew install ninvaders
brew install nmap
brew install nnn
brew install node
brew install npth
brew install numpy
brew install nvm
brew install ocaml
brew install ocamlbuild
brew install opam
brew install openexr
brew install openssl
brew install openssl@1.1
brew install p11-kit
brew install p7zip
brew install pandoc
brew install pcre
brew install pcre2
brew install perl
brew install pg_top
brew install pgcli
brew install php
brew install php72
brew install pidof
brew install pinentry
brew install pipes-sh
brew install pixman
brew install pkg-config
brew install ponysay
brew install portmidi
brew install postgresql
brew install pstree
brew install pv
brew install python
brew install python3
brew install python@2
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install rlwrap
brew install rsync
brew install ruby
brew install s-lang
brew install s-search
brew install saverun
brew install sbt
brew install scala
brew install screenfetch
brew install sdl
brew install sdl2
brew install sdl2_image
brew install sdl2_mixer
brew install sdl2_ttf
brew install sdl_image
brew install sdl_mixer
brew install sdl_ttf
brew install shellcheck
brew install sl
brew install slurm
brew install smpeg
brew install sntop
brew install sox
brew install speedtest_cli
brew install sphinx-doc
brew install springboot
brew install sqlite
brew install srm
brew install taglib
brew install tal
brew install tbb
brew install tcptraceroute
brew install the_silver_searcher
brew install tmux
brew install toilet
brew install tokyo-cabinet
brew install tomcat
brew install tor
brew install torsocks
brew install tree
brew install unixodbc
brew install urlview
brew install vim
brew install vnstat
brew install w3m
brew install watch
brew install watchman
brew install webp
brew install weechat
brew install wget
brew install wildfly-as
brew install wireshark
brew install with-readline
brew install wxmac
brew install x264
brew install xvid
brew install xz
brew install yasm
brew install youtube-dl
brew install zlib
brew install zplug
brew install zsh
brew install zzz
