brew install aalib
brew install ack
brew install activemq
brew install adns
brew install akka
brew install algol68g
brew install alpine
brew install amap
brew install ant
brew install aom
brew install apache-spark
brew install apr
brew install apr-util
brew install argon2
brew install asciidoctor
brew install aspcud
brew install aspell
brew install atk
brew install autoconf
brew install automake
brew install autossh
brew install aview
brew install bash
brew install bash-completion
brew install bash-snippets
brew install bat
brew install bdw-gc
brew install bison
brew install bmon
brew install boost
brew install boxes
brew install brotli
brew install browserpass
brew install bsdmake
brew install c-ares
brew install cabal-install
brew install cairo
brew install camlp4
brew install cassandra
brew install catimg
brew install ccrypt
brew install ccze
brew install chkrootkit
brew install chmlib
brew install clingo
brew install clisp
brew install clojure
brew install cmake
brew install cmatrix
brew install colordiff
brew install conan
brew install confuse
brew install contacts
brew install coreutils
brew install cowsay
brew install crystal
brew install cscope
brew install ctags
brew install ctop
brew install cunit
brew install curl
brew install curl-openssl
brew install cython
brew install dart
brew install dbus
brew install dhex
brew install dialog
brew install diff-so-fancy
brew install doc
brew install docker
brew install eigen
brew install elixir
brew install emacs
brew install erlang
brew install exa
brew install expat
brew install faac
brew install faad2
brew install fd
brew install ffmpeg
brew install fftw
brew install figlet
brew install fish
brew install flac
brew install fluid-synth
brew install fontconfig
brew install fortune
brew install fpc
brew install fping
brew install freetds
brew install freetype
brew install frei0r
brew install fribidi
brew install fswatch
brew install gawk
brew install gcc
brew install gd
brew install gdb
brew install gdbm
brew install gdk-pixbuf
brew install geckodriver
brew install geoip
brew install gettext
brew install gforth
brew install ghc
brew install giflib
brew install gifsicle
brew install git
brew install glassfish
brew install glib
brew install glib-networking
brew install gmp
brew install gnu-getopt
brew install gnu-prolog
brew install gnu-sed
brew install gnupg
brew install gnutls
brew install go
brew install gobject-introspection
brew install gperftools
brew install gpgme
brew install gradle
brew install grails
brew install graphicsmagick
brew install graphite2
brew install graphviz
brew install grc
brew install greed
brew install grep
brew install groovy
brew install gsasl
brew install gsettings-desktop-schemas
brew install gst-plugins-bad
brew install gst-plugins-base
brew install gst-plugins-good
brew install gst-plugins-ugly
brew install gstreamer
brew install gtk+3
brew install gts
brew install harfbuzz
brew install heroku
brew install heroku-node
brew install hexedit
brew install hicolor-icon-theme
brew install html2text
brew install htop
brew install httpd
brew install httpie
brew install httrack
brew install hub
brew install hwloc
brew install hydra
brew install icu4c
brew install ifstat
brew install ilmbase
brew install imagemagick@6
brew install imap-uw
brew install imlib2
brew install iperf
brew install iperf3
brew install isl
brew install jansson
brew install jasper
brew install jemalloc
brew install jenv
brew install jetty
brew install jnettop
brew install jpeg
brew install jq
brew install jvmtop
brew install kafka
brew install kotlin
brew install lame
brew install leiningen
brew install leptonica
brew install libao
brew install libass
brew install libassuan
brew install libbluray
brew install libcaca
brew install libcroco
brew install libcuefile
brew install libde265
brew install libelf
brew install libepoxy
brew install libev
brew install libevent
brew install libffi
brew install libftdi0
brew install libgcrypt
brew install libgpg-error
brew install libgtop
brew install libheif
brew install libiconv
brew install libid3tag
brew install libidn
brew install libidn2
brew install libksba
brew install libmaxminddb
brew install libmetalink
brew install libmikmod
brew install libmms
brew install libmodplug
brew install libmpc
brew install libmpdclient
brew install libnet
brew install libnfs
brew install libnice
brew install libogg
brew install libomp
brew install libpng
brew install libpq
brew install libpsl
brew install libreplaygain
brew install librsvg
brew install libsamplerate
brew install libscrypt
brew install libshout
brew install libsigsegv
brew install libsmi
brew install libsndfile
brew install libsodium
brew install libsoup
brew install libsoxr
brew install libssh
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libunistring
brew install libupnp
brew install libusb
brew install libusb-compat
brew install libuv
brew install libvidstab
brew install libvorbis
brew install libvpx
brew install libvterm
brew install libxml2
brew install libyaml
brew install libzip
brew install links
brew install little-cms2
brew install llvm
brew install llvm@6
brew install llvm@8
brew install lua
brew install lua@5.1
brew install luajit
brew install lz4
brew install lzo
brew install mad
brew install mailutils
brew install makedepend
brew install man2html
brew install maven
brew install mercurial
brew install meson
brew install midnight-commander
brew install minicom
brew install mit-scheme
brew install mksh
brew install mongodb
brew install mono
brew install moreutils
brew install mp3blaster
brew install mpc
brew install mpd
brew install mpfr
brew install mplayer
brew install msgpack
brew install mtr
brew install musepack
brew install mutt
brew install mycli
brew install mysql
brew install mysql-client
brew install mytop
brew install nasm
brew install ncdu
brew install ncmpcpp
brew install ncurses
brew install neovim
brew install netpbm
brew install nettle
brew install nghttp2
brew install nginx
brew install ninja
brew install ninvaders
brew install nmap
brew install nnn
brew install node
brew install npth
brew install numpy
brew install nvm
brew install nyancat
brew install ocaml
brew install ocamlbuild
brew install oniguruma
brew install opam
brew install open-mpi
brew install openblas
brew install opencore-amr
brew install openexr
brew install openjpeg
brew install openldap
brew install openssl
brew install openssl@1.1
brew install openvpn
brew install opus
brew install opusfile
brew install orc
brew install p11-kit
brew install p7zip
brew install pandoc
brew install pango
brew install pass
brew install pcre
brew install pcre2
brew install peco
brew install perl
brew install pg_top
brew install pgcli
brew install php
brew install pidof
brew install pinentry
brew install pinentry-mac
brew install pipes-sh
brew install pixman
brew install pkcs11-helper
brew install pkg-config
brew install pokemonsay
brew install ponysay
brew install portaudio
brew install portmidi
brew install postgresql
brew install proxychains-ng
brew install pssh
brew install pstree
brew install pv
brew install py2cairo
brew install py3cairo
brew install pygobject3
brew install python
brew install python@2
brew install qrencode
brew install qt
brew install r
brew install ranger
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install ripgrep
brew install rlwrap
brew install rsync
brew install rtmpdump
brew install rubberband
brew install ruby
brew install rust
brew install rustup-init
brew install s-lang
brew install s-search
brew install sbt
brew install scala
brew install screenfetch
brew install sdl
brew install sdl2
brew install sdl2_image
brew install sdl2_mixer
brew install sdl2_ttf
brew install sdl_image
brew install sdl_mixer
brew install sdl_ttf
brew install shared-mime-info
brew install shellcheck
brew install shfmt
brew install sl
brew install slurm
brew install smpeg
brew install snappy
brew install sntop
brew install sox
brew install spaceinvaders-go
brew install spark
brew install speedtest-cli
brew install speex
brew install sphinx-doc
brew install springboot
brew install sqlite
brew install srm
brew install srtp
brew install swig
brew install taglib
brew install tal
brew install tbb
brew install tcl-tk
brew install tcptraceroute
brew install telnet
brew install tesseract
brew install texi2html
brew install texinfo
brew install the_silver_searcher
brew install thefuck
brew install theora
brew install tidy-html5
brew install tig
brew install tmux
brew install toilet
brew install tokei
brew install tokyo-cabinet
brew install tomcat
brew install tomee-plume
brew install tor
brew install torsocks
brew install tree
brew install two-lame
brew install unbound
brew install unibilium
brew install unixodbc
brew install unrar
brew install urlview
brew install vala
brew install valgrind
brew install vim
brew install vnstat
brew install w3m
brew install watch
brew install watchman
brew install webp
brew install weechat
brew install wget
brew install wildfly-as
brew install wireshark
brew install with-readline
brew install wxmac
brew install x264
brew install x265
brew install xvid
brew install xz
brew install yasm
brew install zlib
brew install zookeeper
brew install zplug
brew install zsh
brew install zsh-lovers
brew install zzz
