brew cask install adafruit-arduino
brew cask install adobe-acrobat-reader
brew cask install android-platform-tools
brew cask install android-studio
brew cask install appcode
brew cask install atom
brew cask install bettertouchtool
brew cask install blender
brew cask install clion
brew cask install cycling74-max
brew cask install dash
brew cask install datagrip
brew cask install db-browser-for-sqlite
brew cask install disk-inventory-x
brew cask install duet
brew cask install eclipse-jee
brew cask install electric-sheep
brew cask install etcher
brew cask install filezilla
brew cask install firefox
brew cask install font-codenewroman-nerd-font
brew cask install font-fantasquesansmono-nerd-font
brew cask install font-hack-nerd-font
brew cask install font-inconsolata-nerd-font
brew cask install font-sourcecodepro-nerd-font
brew cask install geekbench
brew cask install genymotion
brew cask install gimp
brew cask install goland
brew cask install google-chrome
brew cask install hex-fiend
brew cask install intellij-idea
brew cask install iterm2
brew cask install java
brew cask install java6
brew cask install java8
brew cask install karabiner
brew cask install keyboard-maestro
brew cask install kicad
brew cask install libreoffice
brew cask install little-snitch
brew cask install macs-fan-control
brew cask install macvim
brew cask install microsoft-office
brew cask install multibit-hd
brew cask install mysqlworkbench
brew cask install netbeans
brew cask install ngrok
brew cask install onyx
brew cask install opera
brew cask install phpstorm
brew cask install postico
brew cask install postman
brew cask install processing
brew cask install pycharm
brew cask install pycharm-ce
brew cask install qt-creator
brew cask install racket
brew cask install rar
brew cask install rider
brew cask install robo-3t
brew cask install rowanj-gitx
brew cask install rubymine
brew cask install scenebuilder
brew cask install skype
brew cask install slack
brew cask install sourcetree
brew cask install spotify
brew cask install sublime-text
brew cask install switchresx
brew cask install sysex-librarian
brew cask install thunderbird
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install vlc
brew cask install vmware-fusion
brew cask install vnc-viewer
brew cask install webstorm
brew cask install wine-stable
brew cask install wireshark
brew cask install xld
brew cask install xquartz
brew cask install zotero
