npm i -g lib
npm i -g cli
npm i -g pkg
npm i -g actionhero
npm i -g appdmg
npm i -g babel-cli
npm i -g cat-me
npm i -g chalksay
npm i -g cli-github
npm i -g coffeescript
npm i -g cowsay
npm i -g create-react-app
npm i -g ember-cli
npm i -g express-generator
npm i -g fix-yarn-global-packages
npm i -g globby
npm i -g grunt-cli
npm i -g how-to-npm
npm i -g how2
npm i -g html-minifier
npm i -g httpster
npm i -g idea
npm i -g istanbul
npm i -g jade
npm i -g learnyoumongo
npm i -g mocha
npm i -g mongo-hacker
npm i -g node
npm i -g node-dev
npm i -g nodemon
npm i -g npm
npm i -g parse-dashboard
npm i -g pug
npm i -g pure-prompt
npm i -g raspberry
npm i -g react-native-cli
npm i -g react-tools
npm i -g reload
npm i -g remote-share-cli
npm i -g rtop
npm i -g should
npm i -g sinon
npm i -g spoof
npm i -g termcolors
npm i -g tv4
npm i -g typescript
npm i -g uglify-js
npm i -g vtop
npm i -g vue-cli
npm i -g webpack
npm i -g yarn
npm i -g yosay


