pip3 install -
pip3 install -andas
pip3 install alabaster
pip3 install aniso8601
pip3 install appnope
pip3 install asn1crypto
pip3 install astroid
pip3 install atomicwrites
pip3 install attrs
pip3 install Babel
pip3 install backcall
pip3 install backports.shutil-get-terminal-size
pip3 install banknumber
pip3 install behave
pip3 install bleach
pip3 install blessings
pip3 install bpython
pip3 install cachetools
pip3 install certifi
pip3 install cffi
pip3 install chardet
pip3 install cli-helpers
pip3 install Click
pip3 install colorama
pip3 install configobj
pip3 install cryptography
pip3 install cursor
pip3 install curtsies
pip3 install cycler
pip3 install Cython
pip3 install decorator
pip3 install defusedxml
pip3 install Django
pip3 install docopt
pip3 install docutils
pip3 install entrypoints
pip3 install enum34
pip3 install flake8
pip3 install Flask
pip3 install Flask-PyMongo
pip3 install Flask-RESTful
pip3 install gpg
pip3 install greenlet
pip3 install h5py
pip3 install halo
pip3 install html5lib
pip3 install humanize
pip3 install idna
pip3 install imageio
pip3 install imageio-ffmpeg
pip3 install imagesize
pip3 install importlib-metadata
pip3 install ipykernel
pip3 install ipython
pip3 install ipython-genutils
pip3 install ipywidgets
pip3 install isort
pip3 install itsdangerous
pip3 install jedi
pip3 install Jinja2
pip3 install joblib
pip3 install jsonschema
pip3 install jupyter-client
pip3 install jupyter-core
pip3 install Kivy
pip3 install Kivy-Garden
pip3 install kiwisolver
pip3 install lazy-object-proxy
pip3 install log-symbols
pip3 install lxml
pip3 install Markdown
pip3 install MarkupSafe
pip3 install matplotlib
pip3 install mccabe
pip3 install mdv
pip3 install meson
pip3 install mistune
pip3 install more-itertools
pip3 install MouseInfo
pip3 install moviepy
pip3 install msgpack
pip3 install mycli
pip3 install mysqlclient
pip3 install nbconvert
pip3 install nbformat
pip3 install notebook
pip3 install numpy
pip3 install olefile
pip3 install opencv-python
pip3 install packaging
pip3 install paho-mqtt
pip3 install pandas
pip3 install pandocfilters
pip3 install parse
pip3 install parse-type
pip3 install parso
pip3 install pexpect
pip3 install pgcli
pip3 install pgspecial
pip3 install pickleshare
pip3 install Pillow
pip3 install pip
pip3 install pluggy
pip3 install powerline-mem-segment
pip3 install powerline-status
pip3 install prettytable
pip3 install proglog
pip3 install prometheus-client
pip3 install prompt-toolkit
pip3 install psutil
pip3 install psycopg2
pip3 install ptyprocess
pip3 install py
pip3 install PyAutoGUI
pip3 install pycairo
pip3 install pycodestyle
pip3 install pycparser
pip3 install pydf
pip3 install pyflakes
pip3 install PyGetWindow
pip3 install Pygments
pip3 install PyGObject
pip3 install pylint
pip3 install pymongo
pip3 install PyMsgBox
pip3 install PyMySQL
pip3 install pynvim
pip3 install pyobjc
pip3 install pyobjc-core
pip3 install pyobjc-framework-Accounts
pip3 install pyobjc-framework-AddressBook
pip3 install pyobjc-framework-AdSupport
pip3 install pyobjc-framework-AppleScriptKit
pip3 install pyobjc-framework-AppleScriptObjC
pip3 install pyobjc-framework-ApplicationServices
pip3 install pyobjc-framework-AuthenticationServices
pip3 install pyobjc-framework-Automator
pip3 install pyobjc-framework-AVFoundation
pip3 install pyobjc-framework-AVKit
pip3 install pyobjc-framework-BusinessChat
pip3 install pyobjc-framework-CalendarStore
pip3 install pyobjc-framework-CFNetwork
pip3 install pyobjc-framework-CloudKit
pip3 install pyobjc-framework-Cocoa
pip3 install pyobjc-framework-Collaboration
pip3 install pyobjc-framework-ColorSync
pip3 install pyobjc-framework-Contacts
pip3 install pyobjc-framework-ContactsUI
pip3 install pyobjc-framework-CoreAudio
pip3 install pyobjc-framework-CoreAudioKit
pip3 install pyobjc-framework-CoreBluetooth
pip3 install pyobjc-framework-CoreData
pip3 install pyobjc-framework-CoreHaptics
pip3 install pyobjc-framework-CoreLocation
pip3 install pyobjc-framework-CoreMedia
pip3 install pyobjc-framework-CoreMediaIO
pip3 install pyobjc-framework-CoreML
pip3 install pyobjc-framework-CoreMotion
pip3 install pyobjc-framework-CoreServices
pip3 install pyobjc-framework-CoreSpotlight
pip3 install pyobjc-framework-CoreText
pip3 install pyobjc-framework-CoreWLAN
pip3 install pyobjc-framework-CryptoTokenKit
pip3 install pyobjc-framework-DeviceCheck
pip3 install pyobjc-framework-DictionaryServices
pip3 install pyobjc-framework-DiscRecording
pip3 install pyobjc-framework-DiscRecordingUI
pip3 install pyobjc-framework-DiskArbitration
pip3 install pyobjc-framework-DVDPlayback
pip3 install pyobjc-framework-EventKit
pip3 install pyobjc-framework-ExceptionHandling
pip3 install pyobjc-framework-ExecutionPolicy
pip3 install pyobjc-framework-ExternalAccessory
pip3 install pyobjc-framework-FileProvider
pip3 install pyobjc-framework-FileProviderUI
pip3 install pyobjc-framework-FinderSync
pip3 install pyobjc-framework-FSEvents
pip3 install pyobjc-framework-GameCenter
pip3 install pyobjc-framework-GameController
pip3 install pyobjc-framework-GameKit
pip3 install pyobjc-framework-GameplayKit
pip3 install pyobjc-framework-ImageCaptureCore
pip3 install pyobjc-framework-IMServicePlugIn
pip3 install pyobjc-framework-InputMethodKit
pip3 install pyobjc-framework-InstallerPlugins
pip3 install pyobjc-framework-InstantMessage
pip3 install pyobjc-framework-Intents
pip3 install pyobjc-framework-IOSurface
pip3 install pyobjc-framework-iTunesLibrary
pip3 install pyobjc-framework-LatentSemanticMapping
pip3 install pyobjc-framework-LaunchServices
pip3 install pyobjc-framework-libdispatch
pip3 install pyobjc-framework-LinkPresentation
pip3 install pyobjc-framework-LocalAuthentication
pip3 install pyobjc-framework-MapKit
pip3 install pyobjc-framework-MediaAccessibility
pip3 install pyobjc-framework-MediaLibrary
pip3 install pyobjc-framework-MediaPlayer
pip3 install pyobjc-framework-MediaToolbox
pip3 install pyobjc-framework-MetalKit
pip3 install pyobjc-framework-ModelIO
pip3 install pyobjc-framework-MultipeerConnectivity
pip3 install pyobjc-framework-NaturalLanguage
pip3 install pyobjc-framework-NetFS
pip3 install pyobjc-framework-Network
pip3 install pyobjc-framework-NetworkExtension
pip3 install pyobjc-framework-NotificationCenter
pip3 install pyobjc-framework-OpenDirectory
pip3 install pyobjc-framework-OSAKit
pip3 install pyobjc-framework-OSLog
pip3 install pyobjc-framework-PencilKit
pip3 install pyobjc-framework-Photos
pip3 install pyobjc-framework-PhotosUI
pip3 install pyobjc-framework-PreferencePanes
pip3 install pyobjc-framework-PubSub
pip3 install pyobjc-framework-PushKit
pip3 install pyobjc-framework-QTKit
pip3 install pyobjc-framework-Quartz
pip3 install pyobjc-framework-QuickLookThumbnailing
pip3 install pyobjc-framework-SafariServices
pip3 install pyobjc-framework-SceneKit
pip3 install pyobjc-framework-ScreenSaver
pip3 install pyobjc-framework-ScriptingBridge
pip3 install pyobjc-framework-SearchKit
pip3 install pyobjc-framework-Security
pip3 install pyobjc-framework-SecurityFoundation
pip3 install pyobjc-framework-SecurityInterface
pip3 install pyobjc-framework-ServiceManagement
pip3 install pyobjc-framework-Social
pip3 install pyobjc-framework-SoundAnalysis
pip3 install pyobjc-framework-Speech
pip3 install pyobjc-framework-SpriteKit
pip3 install pyobjc-framework-StoreKit
pip3 install pyobjc-framework-SyncServices
pip3 install pyobjc-framework-SystemConfiguration
pip3 install pyobjc-framework-SystemExtensions
pip3 install pyobjc-framework-UserNotifications
pip3 install pyobjc-framework-VideoSubscriberAccount
pip3 install pyobjc-framework-VideoToolbox
pip3 install pyobjc-framework-Vision
pip3 install pyobjc-framework-WebKit
pip3 install pyparsing
pip3 install PyPDF2
pip3 install pyperclip
pip3 install PyRect
pip3 install pyrsistent
pip3 install PyScreeze
pip3 install pytest
pip3 install python-dateutil
pip3 install python-docx
pip3 install PyTweening
pip3 install pytz
pip3 install pyzmq
pip3 install relativetimebuilder
pip3 install reppy
pip3 install requests
pip3 install scikit-learn
pip3 install scipy
pip3 install selenium
pip3 install Send2Trash
pip3 install setproctitle
pip3 install setuptools
pip3 install simplegeneric
pip3 install six
pip3 install sklearn
pip3 install snowballstemmer
pip3 install Sphinx
pip3 install sphinxcontrib-applehelp
pip3 install sphinxcontrib-devhelp
pip3 install sphinxcontrib-htmlhelp
pip3 install sphinxcontrib-jsmath
pip3 install sphinxcontrib-qthelp
pip3 install sphinxcontrib-serializinghtml
pip3 install sphinxcontrib-websupport
pip3 install spidy-web-crawler
pip3 install spinners
pip3 install sqlparse
pip3 install tabulate
pip3 install termcolor
pip3 install terminado
pip3 install terminaltables
pip3 install testpath
pip3 install tornado
pip3 install tqdm
pip3 install traitlets
pip3 install typed-ast
pip3 install typing
pip3 install urllib3
pip3 install virtualenv
pip3 install wcwidth
pip3 install webencodings
pip3 install Werkzeug
pip3 install wheel
pip3 install widgetsnbextension
pip3 install wrapt
pip3 install xlrd
pip3 install xlwt
pip3 install yapf
pip3 install zipp
