PAGE_TITLE="Cache Regeneration"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== CACHE REGENERATION ===${N}"
    print "  ${D}// the opposite of cleaning. building the caches back up. //${N}"
    print ""
    print "  ${C}Cleaning removes caches. Regeneration rebuilds them.${N}"
    print "  ${C}These verbs construct the indexes and precomputed data${N}"
    print "  ${C}that make zpwr fast.${N}"
    print ""
    print "  ${B}${Y}REGEN: THE STANDARD REBUILD${N}"
    print "  ${M}  zpwr regen${N}${D}                          # regenerate common caches${N}"
    print ""
    print "  ${D}  Rebuilds the most frequently used caches:${N}"
    print "  ${D}  environment cache, config links, keybindings.${N}"
    print "  ${D}  This is the verb you reach for after editing config files.${N}"
    print ""
    print "  ${B}${Y}REGENALL: THE FULL REBUILD${N}"
    print "  ${M}  zpwr regenall${N}${D}                       # regenerate everything${N}"
    print ""
    print "  ${D}  Every cache. Every index. Every precomputed file.${N}"
    print "  ${D}  This is the thorough version of regen. Takes longer${N}"
    print "  ${D}  but leaves nothing stale.${N}"
    print ""
    print "  ${B}${Y}INDIVIDUAL REGEN VERBS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print ""
    print "  ${G}regenenvcache${N}"
    print "  ${M}  zpwr regenenvcache${N}${D}                  # rebuild environment cache${N}"
    print "  ${D}  Snapshots all env vars to a cache file for fast lookup.${N}"
    print "  ${D}  Used by environmentcachesearch and other env verbs.${N}"
    print ""
    print "  ${G}regenkeybindings${N}"
    print "  ${M}  zpwr regenkeybindings${N}${D}               # rebuild keybinding index${N}"
    print "  ${D}  Re-registers all zpwr keybindings. Run this after${N}"
    print "  ${D}  editing keybinding configuration or after a plugin${N}"
    print "  ${D}  clobbered your bindings.${N}"
    print ""
    print "  ${G}regenconfiglinks${N}"
    print "  ${M}  zpwr regenconfiglinks${N}${D}               # rebuild config symlinks${N}"
    print "  ${D}  Re-creates the symlinks from ~/.zshrc, ~/.vimrc, etc.${N}"
    print "  ${D}  into the zpwr directory tree. Run this after a fresh${N}"
    print "  ${D}  clone or when zpwr doctor reports broken config links.${N}"
    print ""
    print "  ${G}regenhistory${N}"
    print "  ${M}  zpwr regenhistory${N}${D}                   # clean up history file${N}"
    print "  ${D}  Processes the HISTFILE to remove corrupted entries.${N}"
    print "  ${D}  Zsh history files can accumulate broken lines from${N}"
    print "  ${D}  concurrent writes or improper shutdowns.${N}"
    print ""
    print "  ${G}regenpowerline${N}"
    print "  ${M}  zpwr regenpowerline${N}${D}                 # rebuild powerline config${N}"
    print "  ${D}  Regenerates powerline/p10k configuration. Run when${N}"
    print "  ${D}  the prompt looks wrong after a terminal font change.${N}"
    print ""
    print "  ${G}regengitrepocache${N}"
    print "  ${M}  zpwr regengitrepocache${N}${D}              # scan and cache git repos${N}"
    print "  ${D}  Walks the filesystem finding git repos and builds a${N}"
    print "  ${D}  master list. Used by repo navigation and batch verbs.${N}"
    print ""
    print "  ${B}${Y}THE REGEN CHEAT SHEET${N}"
    print "  ${D}  After editing config:     ${M}zpwr regen${N}"
    print "  ${D}  After zpwr update:        ${M}zpwr regenall${N}"
    print "  ${D}  After env var changes:    ${M}zpwr regenenvcache${N}"
    print "  ${D}  After repo changes:       ${M}zpwr regengitrepocache${N}"
    print "  ${D}  After completion issues:  ${M}zpwr regenzsh${N}"
    print ""
}
