PAGE_TITLE="Emacs Integration Overview"
PAGE_CHAPTER="CHAPTER 13: EMACS DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> ENTERING THE EMACS DIMENSION <<<${N}"
    print "  ${D}where M-x is a way of life and pinky fingers go to die${N}"
    print ""
    print "  ${C}You thought there were only vim verbs?${N}"
    print "  ${G}Think again, operative.${N} ZPWR mirrors every vim operation"
    print "  ${G}with an emacs equivalent.${N} Same power, different religion."
    print ""
    print "  ${B}${Y}THE 28 EMACS VERBS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}FILE OPS${N}      emacsall, emacsalledit, emacsautoload"
    print "  ${C}RECENT${N}        emacsrecent, emacsrecentcd, emacsrecentsudo"
    print "  ${C}SEARCH${N}        emacsfilesearch, emacsfilesearchedit"
    print "  ${C}              ${N}emacsfindsearch, emacsfindsearchedit"
    print "  ${C}              ${N}emacslocatesearch, emacslocatesearchedit"
    print "  ${C}              ${N}emacswordsearch, emacswordsearchedit"
    print "  ${C}TAGS${N}          emacsctags, emacsgtags, emacsgtagsedit"
    print "  ${C}CONFIG${N}        emacsconfig, emacsemacsconfig, emacstokens"
    print "  ${C}SERVER${N}        emacsallserver"
    print "  ${C}SCRIPTS${N}       emacsscripts, emacsscriptedit"
    print "  ${C}META${N}          emacsplugincount, emacspluginlist, emacszpwr"
    print ""
    print "  ${B}${G}THE MIRROR PRINCIPLE:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${Y}Every vim verb has an emacs twin.${N} The architecture is"
    print "  ${Y}symmetrical by design.${N} You can swap editors without"
    print "  ${Y}losing any ZPWR functionality.${N}"
    print ""
    print "  ${D}  vim verb              emacs twin${N}"
    print "  ${C}  zpwr vimall${N}     -->   ${M}zpwr emacsall${N}"
    print "  ${C}  zpwr vimrecent${N}  -->   ${M}zpwr emacsrecent${N}"
    print "  ${C}  zpwr vimscripts${N} -->   ${M}zpwr emacsscripts${N}"
    print ""
    print "  ${B}${Y}PHILOSOPHY:${N}"
    print "  ${G}ZPWR does not care about your editor war allegiance.${N}"
    print "  ${G}It arms both sides equally.${N} The real enemy is notepad."
    print ""
    print "  ${D}  // the emacs dimension runs parallel to vim-space${N}"
    print "  ${D}  // choose your weapon, the framework adapts${N}"
    print "  ${D}  // \$ZPWR_EDITOR controls which universe you inhabit${N}"
}
