PAGE_TITLE="Vim Plugin Architecture"
PAGE_CHAPTER="CHAPTER 31: VIM DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== VIM PLUGIN ARCHITECTURE ===${N}"
    print "  ${D}// 15 plugins in .vimrc. each one a force multiplier. //${N}"
    print "  ${C}ZPWR's vim config uses Vundle as the plugin manager and${N}"
    print "  ${C}ships 15 curated plugins that transform vim into a${N}"
    print "  ${C}full IDE with completion, snippets, and tmux integration.${N}"
    print "  ${B}${Y}VUNDLE: THE PLUGIN MANAGER${N}"
    print "  ${D}Plugins live in ~/.vim/bundle/. Managed by Vundle:${N}"
    print "  ${M}  set runtimepath+=~/.vim/bundle/Vundle.vim${N}"
    print "  ${M}  call vundle#begin()${N}"
    print "  ${M}  Plugin 'VundleVim/Vundle.vim'${N}"
    print "  ${M}  ... more plugins ...${N}"
    print "  ${M}  call vundle#end()${N}"
    print "  ${D}Install: ${M}:PluginInstall${D}  Update: ${M}:PluginUpdate${D}  Clean: ${M}:PluginClean${N}"
    print "  ${B}${Y}YouCompleteMe: SEMANTIC COMPLETION${N}"
    print "  ${M}  Plugin 'ycm-core/YouCompleteMe'${N}"
    print "  ${D}The heavyweight champion. Provides semantic completion for:${N}"
    print "  ${D}  C/C++ (via clangd), Python (via jedi), and more.${N}"
    print "  ${D}Config: completion after 1 char, enabled in all file types,${N}"
    print "  ${D}completes in comments. Uses C-n/C-p for selection.${N}"
    print "  ${B}${Y}UltiSnips + vim-snippets: SNIPPET ENGINE${N}"
    print "  ${M}  Plugin 'SirVer/ultisnips'${N}"
    print "  ${M}  Plugin 'honza/vim-snippets'${N}"
    print "  ${D}Tab expands snippets, Tab/Shift-Tab navigate tab stops.${N}"
    print "  ${D}Hundreds of snippets for every language: type 'for<Tab>'${N}"
    print "  ${D}in Python and get a complete for loop with cursor placement.${N}"
    print "  ${B}${Y}SuperTab: TAB COMPLETION GLUE${N}"
    print "  ${M}  Plugin 'ervandew/supertab'${N}"
    print "  ${D}Unifies Tab behavior: C-n cycles forward through completions.${N}"
    print "  ${D}Coordinates with YCM and UltiSnips so Tab does the right${N}"
    print "  ${D}thing in every context (snippet vs completion vs indent).${N}"
    print "  ${B}${Y}vim-auto-save: NEVER :w AGAIN${N}"
    print "  ${M}  Plugin '907th/vim-auto-save'${N}"
    print "  ${D}Saves on InsertLeave, TextChanged, and TextChangedI.${N}"
    print "  ${D}Every edit auto-saves silently. No more 'Unsaved changes' panics.${N}"
    print "  ${D}g:auto_save_silent=1 suppresses the notification.${N}"
    print "  ${B}${Y}rainbow: MATCHING BRACKET COLORS${N}"
    print "  ${M}  Plugin 'luochen1990/rainbow'${N}"
    print "  ${D}Nested brackets get different colors: parentheses in blue,${N}"
    print "  ${D}inner brackets in orange, deeper in cyan, deepest in magenta.${N}"
    print "  ${D}g:rainbow_active=1 enables it globally on startup.${N}"
    print "  ${B}${Y}vim-multiple-cursors: MULTI-CURSOR EDITING${N}"
    print "  ${M}  Plugin 'TerryMa/vim-multiple-cursors'${N}"
    print "  ${D}Sublime Text-style multi-cursor. Ctrl-N selects next match,${N}"
    print "  ${D}then edit all occurrences simultaneously.${N}"
    print "  ${B}${Y}tmux-complete.vim: CROSS-PANE COMPLETION${N}"
    print "  ${M}  Plugin 'wellle/tmux-complete.vim'${N}"
    print "  ${D}Completes words from ALL tmux panes. Writing a command in vim${N}"
    print "  ${D}that references output in another pane? Tab-complete it.${N}"
    print "  ${D}Uses async.vim and asyncomplete.vim for non-blocking operation.${N}"
}
