PAGE_TITLE="Process Monitoring"
PAGE_CHAPTER="CHAPTER 14: TMUX WARFARE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> PROCESS MONITORING: WATCHING THE WATCHERS <<<${N}"
    print "  ${D}every PID tells a story, most of them tragic${N}"
    print ""
    print "  ${B}${Y}zpwr pstreemonitor${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Displays a live process tree. Watch your processes${N}"
    print "  ${G}branch, fork, and occasionally die unexpectedly.${N}"
    print ""
    print "  ${C}  \$ zpwr pstreemonitor${N}          ${D}# live process tree${N}"
    print ""
    print "  ${G}Uses pstree under the hood with continuous refresh.${N}"
    print "  ${G}Like htop's tree view but from the ZPWR command line.${N}"
    print ""
    print "  ${B}${Y}zpwr tty${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Show info about the current terminal/tty.${N}"
    print ""
    print "  ${C}  \$ zpwr tty${N}                    ${D}# current tty info${N}"
    print ""
    print "  ${B}${Y}TMUX + MONITORING WORKFLOW:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}The power move: dedicate a tmux pane to monitoring.${N}"
    print ""
    print "  ${D}  LAYOUT EXAMPLE:${N}"
    print "  ${D}  +-------------------+--------------------+${N}"
    print "  ${D}  |                   |                    |${N}"
    print "  ${D}  |   your work       |  pstreemonitor     |${N}"
    print "  ${D}  |                   |                    |${N}"
    print "  ${D}  +-------------------+--------------------+${N}"
    print "  ${D}  |         zpwr taillog                   |${N}"
    print "  ${D}  +-----------------------------------------+${N}"
    print ""
    print "  ${B}${Y}PROCESS HUNTING:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}ZPWR integrates fzf with ps and lsof for killing.${N}"
    print ""
    print "  ${C}  Ctrl-Y Ctrl-K${N}                  ${D}# fzf kill by ps${N}"
    print "  ${C}  Ctrl-Y Ctrl-L${N}                  ${D}# fzf kill by lsof${N}"
    print ""
    print "  ${D}  // pstreemonitor in a side pane = instant situational awareness${N}"
    print "  ${D}  // you will see zombie processes before they see you${N}"
}
