PAGE_TITLE="Vim Integration Overview"
PAGE_CHAPTER="CHAPTER 5: EDITOR MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== VIM INTEGRATION OVERVIEW ===${N}"
    print ""
    print "  ${C}Vim is not just an editor in zpwr. It is a first-class${N}"
    print "  ${C}citizen with its own verb family. Over 20 verbs,${N}"
    print "  ${C}each opening vim in a specific context.${N}"
    print ""
    print "  ${B}${Y}THE PHILOSOPHY${N}"
    print "  ${G}  Every vim verb answers one question:${N}"
    print "  ${G}  \"What do I want to edit right now?\"${N}"
    print "  ${D}  The answer is always one verb away.${N}"
    print ""
    print "  ${B}${Y}THE vim* VERB FAMILY${N}"
    print "  ${M}  vimall${N}${D} .............. open ALL zpwr files (for :argdo)${N}"
    print "  ${M}  vimalledit${N}${D} .......... pick and edit 1+ zpwr configs${N}"
    print "  ${M}  vimautoload${N}${D} ......... open all autoloads (for :argdo)${N}"
    print "  ${M}  vimcd${N}${D} ............... vim edit, then cd to first dir${N}"
    print "  ${M}  vimconfig${N}${D} ........... edit all zpwr config files${N}"
    print "  ${M}  vimctags${N}${D} ............ vim zpwr ctags${N}"
    print "  ${M}  vimemacsconfig${N}${D} ...... vim edit emacs zpwr configs${N}"
    print "  ${M}  vimfilesearch${N}${D} ....... vim a file found via fzf${N}"
    print "  ${M}  vimfilesearchedit${N}${D} ... vim edit a file found via fzf${N}"
    print "  ${M}  vimfindsearch${N}${D} ....... vim a file from find(1) via fzf${N}"
    print "  ${M}  vimfindsearchedit${N}${D} ... vim edit find result${N}"
    print "  ${M}  vimgtags${N}${D} ............ vim zpwr GNU global tags${N}"
    print "  ${M}  vimgtagsedit${N}${D} ........ vim edit zpwr GNU global tags${N}"
    print "  ${M}  vimlocatesearch${N}${D} ..... vim a file from locate via fzf${N}"
    print "  ${M}  vimlocatesearchedit${N}${D} . vim edit locate result${N}"
    print "  ${M}  vimplugincount${N}${D} ...... count vim plugins${N}"
    print "  ${M}  vimpluginlist${N}${D} ....... list all vim plugins${N}"
    print "  ${M}  vimrecent${N}${D} ........... edit most recent files${N}"
    print "  ${M}  vimrecentcd${N}${D} ......... cd + edit most recent files${N}"
    print "  ${M}  vimrecentsudo${N}${D} ....... sudo edit most recent files${N}"
    print "  ${M}  vimrecentsudocd${N}${D} ..... cd + sudo edit recent files${N}"
    print "  ${M}  vimscripts${N}${D} .......... open all zpwr scripts (for :argdo)${N}"
    print "  ${M}  vimscriptedit${N}${D} ....... pick and edit 1+ scripts${N}"
    print "  ${M}  vimsearch${N}${D} ........... search vim keybindings via fzf${N}"
    print "  ${M}  vimtests${N}${D} ............ edit all zpwr tests${N}"
    print "  ${M}  vimtokens${N}${D} ........... vim the .tokens.sh file${N}"
    print "  ${M}  vimwordsearch${N}${D} ....... vim a file found by content${N}"
    print "  ${M}  vimwordsearchedit${N}${D} ... vim edit file found by content${N}"
    print ""
    print "  ${B}${Y}THE :argdo PATTERN${N}"
    print "  ${C}  Verbs like ${M}vimall${C} and ${M}vimscripts${C} load many files${N}"
    print "  ${C}  into vim's arglist. Then you can:${N}"
    print "  ${M}    :argdo %s/old/new/g | update${N}"
    print "  ${D}  Mass find-and-replace across the entire zpwr codebase.${N}"
    print ""
    print "  ${D}If it can be edited, there is a vim verb for it.${N}"
    print ""
}
