PAGE_TITLE="Path Deduplication"
PAGE_CHAPTER="CHAPTER 9: THE JANITOR'S CLOSET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== PATH DEDUPLICATION ===${N}"
    print "  ${D}// every duplicate entry is a tiny crime against performance //${N}"
    print ""
    print "  ${C}PATH and FPATH grow duplicates like weeds. Every subshell,${N}"
    print "  ${C}every sourced script, every tool that helpfully \"adds itself${N}"
    print "  ${C}to your PATH\" can insert duplicates. The ${M}deduppaths${C} verb${N}"
    print "  ${C}removes them.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr deduppaths${N}${D}                     # deduplicate PATH and FPATH${N}"
    print ""
    print "  ${D}  Removes duplicate entries from both PATH and FPATH while${N}"
    print "  ${D}  preserving the order of first occurrence. If /usr/bin${N}"
    print "  ${D}  appears 3 times, only the first one survives.${N}"
    print ""
    print "  ${B}${Y}WHY DUPLICATES HAPPEN${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  1. Shell inheritance${N}"
    print "  ${D}     Parent shell sets PATH. Child shell re-sources .zshrc.${N}"
    print "  ${D}     PATH grows. Nested tmux sessions make it worse.${N}"
    print ""
    print "  ${G}  2. Multiple init scripts${N}"
    print "  ${D}     Homebrew, nvm, pyenv, rbenv, cargo -- each one adds${N}"
    print "  ${D}     to PATH in their init hook. Source them twice, PATH grows.${N}"
    print ""
    print "  ${G}  3. /etc/zprofile on macOS${N}"
    print "  ${D}     macOS ships with /etc/zprofile that runs path_helper.${N}"
    print "  ${D}     path_helper reads /etc/paths and /etc/paths.d/ and${N}"
    print "  ${D}     prepends entries. This runs on every login shell,${N}"
    print "  ${D}     BEFORE your .zshrc. Duplicates guaranteed.${N}"
    print ""
    print "  ${G}  4. Manual PATH manipulation${N}"
    print "  ${D}     export PATH=\"/my/dir:\$PATH\" in .zshrc.${N}"
    print "  ${D}     Every time .zshrc is sourced, another copy appears.${N}"
    print ""
    print "  ${B}${Y}HOW TO PREVENT DUPLICATES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  Zsh has a built-in mechanism: the ${C}typeset -U${D} flag.${N}"
    print "  ${M}  typeset -U path fpath${N}"
    print "  ${D}  This marks the arrays as \"unique\" -- zsh automatically${N}"
    print "  ${D}  removes duplicates when entries are added. zpwr sets${N}"
    print "  ${D}  this early in startup. But if something adds to PATH${N}"
    print "  ${D}  before zpwr loads, duplicates can sneak in.${N}"
    print ""
    print "  ${B}${Y}DIAGNOSING THE PROBLEM${N}"
    print "  ${M}  zpwr doctor${N}${D}                         # checks for duplicate PATH/FPATH${N}"
    print "  ${M}  print -l \$path | sort | uniq -d${N}${D}     # show only duplicated entries${N}"
    print "  ${M}  echo \$#path${N}${D}                         # count PATH entries${N}"
    print ""
    print "  ${D}  A healthy PATH has 10-30 entries. If you see 50+,${N}"
    print "  ${D}  something is adding entries in a loop.${N}"
    print ""
    print "  ${B}${Y}THE FIX${N}"
    print "  ${M}  zpwr deduppaths${N}${D}                     # instant dedup${N}"
    print "  ${D}  Run it. Then check: ${M}echo \$#path${N}"
    print "  ${D}  If the count dropped, you had duplicates.${N}"
    print "  ${D}  If it drops a lot, investigate the source.${N}"
    print ""
    print "  ${D}  For a permanent fix, find the script that adds duplicates${N}"
    print "  ${D}  and guard it with a check:${N}"
    print "  ${M}  [[ -z \${path[(r)/my/dir]} ]] && path=(/my/dir \$path)${N}"
    print ""
}
