PAGE_TITLE="The Option Matrix"
PAGE_CHAPTER="CHAPTER 8: ENVIRONMENT MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE OPTION MATRIX ===${N}"
    print "  ${D}// zsh has 200+ options. most people know 5. time to fix that. //${N}"
    print ""
    print "  ${C}The zsh option system is a maze of boolean switches that${N}"
    print "  ${C}control everything from globbing to history to error handling.${N}"
    print "  ${C}These verbs help you navigate the labyrinth.${N}"
    print ""
    print "  ${B}${Y}OPTIONS: THE BOOLEAN SWITCHES${N}"
    print "  ${M}  zpwr options${N}${D}                        # list all set options${N}"
    print ""
    print "  ${D}  Shows every zsh option that is currently ON.${N}"
    print "  ${D}  The important ones for zpwr:${N}"
    print "  ${G}  extendedglob${N}${D}      (#, ~, ^ in globs)  -- zpwr needs this${N}"
    print "  ${G}  autopushd${N}${D}         (cd pushes to dirstack)${N}"
    print "  ${G}  histignorealldups${N}${D} (no duplicate history)${N}"
    print "  ${G}  sharehistory${N}${D}      (history shared across sessions)${N}"
    print "  ${G}  completeinword${N}${D}    (tab complete mid-word)${N}"
    print "  ${G}  promptsubst${N}${D}       (parameter expansion in prompts)${N}"
    print ""
    print "  ${D}  If extendedglob is off, half of zpwr's glob tricks die.${N}"
    print "  ${D}  If sharehistory is off, your sessions are islands.${N}"
    print ""
    print "  ${B}${Y}MODULES: THE LOADED EXTENSIONS${N}"
    print "  ${M}  zpwr modules${N}${D}                        # list loaded zsh modules${N}"
    print ""
    print "  ${D}  Zsh modules are C libraries that add features:${N}"
    print "  ${G}  zsh/datetime${N}${D}      EPOCHREALTIME, strftime${N}"
    print "  ${G}  zsh/stat${N}${D}          zstat builtin for file metadata${N}"
    print "  ${G}  zsh/zutil${N}${D}         zparseopts for flag parsing${N}"
    print "  ${G}  zsh/complist${N}${D}       menuselect completion listing${N}"
    print "  ${G}  zsh/parameter${N}${D}      \$functions, \$aliases, \$parameters hashes${N}"
    print "  ${G}  zsh/terminfo${N}${D}       terminal capability strings${N}"
    print ""
    print "  ${D}  If zsh/parameter is not loaded, zpwr env verbs break.${N}"
    print "  ${D}  If zsh/datetime is missing, timing-based verbs fail.${N}"
    print "  ${D}  Load a missing module: ${M}zmodload zsh/modulename${N}"
    print ""
    print "  ${B}${Y}ZSTYLE: THE FINE-TUNING KNOBS${N}"
    print "  ${M}  zpwr zstyle${N}${D}                         # list all zstyle settings${N}"
    print ""
    print "  ${D}  zstyle is zsh's configuration registry. It controls:${N}"
    print "  ${G}  :completion:*${N}${D}     how tab completion behaves${N}"
    print "  ${G}  :vcs_info:*${N}${D}       git/svn info in prompts${N}"
    print "  ${G}  :zpwr:*${N}${D}           zpwr-specific settings${N}"
    print ""
    print "  ${D}  Example styles zpwr sets:${N}"
    print "  ${D}  ${M}zstyle ':completion:*' menu select${N}"
    print "  ${D}  ${M}zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'${N}"
    print "  ${D}  The first enables arrow-key menu selection in tab complete.${N}"
    print "  ${D}  The second makes completion case-insensitive.${N}"
    print ""
    print "  ${B}${Y}DETECTIVE WORK${N}"
    print "  ${D}  Completions acting weird? Check:${N}"
    print "  ${M}  zpwr options${N}${D}    # is completeinword on?${N}"
    print "  ${M}  zpwr modules${N}${D}    # is zsh/complist loaded?${N}"
    print "  ${M}  zpwr zstyle${N}${D}     # what completion styles are set?${N}"
    print "  ${D}  The answer is usually hiding in one of these three.${N}"
    print ""
}
