PAGE_TITLE="Zsh Visual & Menu Select Modes"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ZSH VISUAL & MENU SELECT MODES >>>${N}"
    print "  ${D}text objects, selection, and completion menu navigation.${N}"
    print ""
    print "  ${B}${Y}VISUAL MODE (enter with v/V in vicmd):${N}"
    print "  ${C}Escape${N}                ${D}deactivate region${N}"
    print "  ${C}j / k${N}                ${D}move selection down / up${N}"
    print "  ${C}o${N}                     ${D}exchange point and mark${N}"
    print "  ${C}p${N}                     ${D}put replace selection${N}"
    print "  ${C}x${N}                     ${D}delete selection${N}"
    print "  ${C}u${N}                     ${D}downcase selection${N}"
    print "  ${C}U${N}                     ${D}upcase selection${N}"
    print "  ${C}~${N}                     ${D}swap case of selection${N}"
    print ""
    print "  ${B}${Y}TEXT OBJECTS (a = around, i = inner):${N}"
    print "  ${C}a\" / i\"${N}              ${D}select around/inner double quotes${N}"
    print "  ${C}a' / i'${N}              ${D}select around/inner single quotes${N}"
    print "  ${C}a\` / i\`${N}              ${D}select around/inner backticks${N}"
    print "  ${C}a( / i(${N}              ${D}select around/inner parentheses${N}"
    print "  ${C}a[ / i[${N}              ${D}select around/inner brackets${N}"
    print "  ${C}a{ / i{${N}              ${D}select around/inner braces${N}"
    print "  ${C}a< / i<${N}              ${D}select around/inner angle brackets${N}"
    print "  ${C}aB / iB${N}              ${D}select around/inner block${N}"
    print "  ${C}aw / iw${N}              ${D}select a word / in word${N}"
    print "  ${C}aW / iW${N}              ${D}select a blank word / in blank word${N}"
    print "  ${C}aa / ia${N}              ${D}select a shell word / in shell word${N}"
    print ""
    print "  ${D}Extended quote chars also work as text objects:${N}"
    print "  ${D}  + , - . / : ; = @ | \\\\ are all valid quote delimiters.${N}"
    print ""
    print "  ${B}${Y}MENU SELECT MODE (during completion):${N}"
    print "  ${C}Ctrl-J / Ctrl-K${N}       ${D}move down / up in menu${N}"
    print "  ${C}Ctrl-H / Ctrl-L${N}       ${D}move left / right in menu${N}"
    print "  ${C}Tab / Ctrl-I${N}          ${D}move forward (next item)${N}"
    print "  ${C}Ctrl-S / Shift-Tab${N}    ${D}reverse menu complete${N}"
    print "  ${C}Ctrl-@ (Ctrl-Space)${N}   ${D}accept line${N}"
    print "  ${C}Ctrl-D${N}                ${D}accept and menu complete (stay open)${N}"
    print "  ${C}Ctrl-F${N}                ${D}accept and infer next${N}"
    print "  ${C}Ctrl-M (Enter)${N}        ${D}accept line (.accept-line)${N}"
    print "  ${C}Ctrl-V${N}                ${D}insert mode within menu${N}"
    print "  ${C}Ctrl-N / Ctrl-P${N}       ${D}forward / backward word in menu${N}"
    print "  ${C}Ctrl-X${N}                ${D}incremental search forward in menu${N}"
    print "  ${C}?${N}                     ${D}incremental search backward in menu${N}"
    print "  ${C}.${N}                     ${D}self-insert (exit menu + type dot)${N}"
    print "  ${C}Backspace${N}             ${D}undo last menu selection${N}"
    print ""
    print "  ${D}Menu select uses hjkl-style navigation with Ctrl prefix.${N}"
    print "  ${D}Ctrl-D is key: accept current match but keep menu open.${N}"
    print ""
    print "  ${M}  // visual mode is precision surgery${N}"
    print "  ${M}  // select only what you need, transform only what you touch${N}"
    print ""
}
