PAGE_TITLE="Zconvey: Terminal Communication"
PAGE_CHAPTER="CHAPTER 40: HIDDEN SUBSYSTEMS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== ZCONVEY: TERMINAL COMMUNICATION ===${N}"
    print "  ${D}every terminal screams its identity into the void${N}"
    print "  ${B}${Y}WHAT IS ZCONVEY?${N}"
    print "  ${G}  MenkeTechnologies/zconvey${N}${D} - a zinit plugin${N}"
    print "  ${D}  Allows sending commands between terminal sessions.${N}"
    print "  ${D}  Your terminals can talk to each other. Yes, really.${N}"
    print "  ${D}  Loaded via zinit in ${M}\$ZPWR_INSTALL/.zshplugins${N}"
    print "  ${B}${Y}HOW ZPWR USES IT${N}"
    print "  ${D}  Every time you press Enter, ${G}zpwrAcceptLine${N}${D} fires.${N}"
    print "  ${D}  It calls ${M}zc-rename${N}${D} to label the current terminal with:${N}"
    print "  ${C}    TTY:\${TTY} PID:\${$} CMD:\$BUFFER PWD:\${PWD} DATE:\$(date)${N}"
    print "  ${D}  This broadcasts your terminal's state to the zconvey bus.${N}"
    print "  ${D}  Every pane, every tab, every session - all labeled.${N}"
    print "  ${B}${Y}THE CONVEY VARIABLES${N}"
    print "  ${G}  ZPWR_CONVEY_NAME${N}${D}      the full label string sent to zconvey${N}"
    print "  ${G}  ZPWR_CONVEY_LAST_CMD${N}${D}  the last command (for zconvey commands)${N}"
    print "  ${D}  When you run a zc-* command, it preserves the previous label${N}"
    print "  ${D}  so your terminal doesn't get renamed to \"zc-send ls\".${N}"
    print "  ${B}${Y}THE RENAME LOGIC${N}"
    print "  ${M}  if ! [[ \$(zpwrExpandAliases \$BUFFER) = zc* ]]; then${N}"
    print "  ${M}      ZPWR_CONVEY_NAME=\"TTY:\${TTY} PID:\${$} CMD:...\"${N}"
    print "  ${M}      zc-rename \$ZPWR_CONVEY_NAME${N}"
    print "  ${D}  If BUFFER starts with zc*, keep the old label.${N}"
    print "  ${D}  Otherwise, stamp the terminal with the new command.${N}"
    print "  ${B}${Y}WHY THIS MATTERS${N}"
    print "  ${D}  tmux status bar can show what each pane is running.${N}"
    print "  ${D}  You can identify panes by their last command and PWD.${N}"
    print "  ${D}  Remote debugging: see exactly what terminal ran what.${N}"
    print "  ${D}  It's like process accounting, but for your shell sessions.${N}"
    print "  ${B}${Y}SENDING COMMANDS BETWEEN TERMINALS${N}"
    print "  ${G}  zc-send 2 'cd /tmp && ls'${N}${D}  send command to terminal 2${N}"
    print "  ${G}  zc-all 'echo hello'${N}${D}        broadcast to all terminals${N}"
    print "  ${D}  Your terminals are a mesh network. Act accordingly.${N}"
    print "  ${B}${R}SIGNAL:${N} ${D}zpwrAcceptLine is the heartbeat of zpwr.${N}"
    print "  ${D}  Every Enter keypress: rename terminal, check for clear,${N}"
    print "  ${D}  detect file-modifying commands, send tmux keys.${N}"
    print "  ${D}  zconvey makes that heartbeat visible across sessions.${N}"
}
