PAGE_TITLE="Compilation 101"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== COMPILATION 101 ===${N}"
    print "  ${D}// .zwc files: compiled zsh. faster loading. dark magic. //${N}"
    print ""
    print "  ${C}Zsh can compile scripts to an internal bytecode format${N}"
    print "  ${C}stored in .zwc (Zsh Word Code) files. Loading compiled${N}"
    print "  ${C}files is faster than parsing source text every time.${N}"
    print ""
    print "  ${B}${Y}WHAT IS A .ZWC FILE?${N}"
    print "  ${D}  A .zwc file is the compiled form of a .zsh script or an${N}"
    print "  ${D}  autoload function directory. When zsh finds foo.zwc next${N}"
    print "  ${D}  to foo.zsh, it loads the compiled version -- skipping${N}"
    print "  ${D}  the parsing step entirely.${N}"
    print ""
    print "  ${D}  For individual files: ${C}zcompile foo.zsh${D} -> foo.zsh.zwc${N}"
    print "  ${D}  For directories:      ${C}zcompile dir.zwc dir/*${D} -> dir.zwc${N}"
    print ""
    print "  ${D}  The speed difference is measurable on large files and${N}"
    print "  ${D}  during startup when many files are sourced.${N}"
    print ""
    print "  ${B}${Y}RECOMPILE: BUILD ALL .ZWC FILES${N}"
    print "  ${M}  zpwr recompile${N}${D}                      # compile all zpwr files${N}"
    print "  ${M}  zpwr compile${N}${D}                        # same thing${N}"
    print ""
    print "  ${D}  Scans all zpwr source files and compiles them to .zwc.${N}"
    print "  ${D}  This includes:${N}"
    print "  ${D}  - Autoload function files in \$ZPWR_AUTOLOAD${N}"
    print "  ${D}  - Shell scripts in \$ZPWR_ENV${N}"
    print "  ${D}  - Any .zsh file that has changed since last compile${N}"
    print ""
    print "  ${B}${Y}RELATED COMPILE VERBS${N}"
    print "  ${M}  zpwr recompilefiles${N}${D}                 # compile specific file set${N}"
    print "  ${M}  zpwr compilefiles${N}${D}                   # alias for above${N}"
    print "  ${M}  zpwr recompilefpath${N}${D}                 # compile FPATH directories${N}"
    print "  ${M}  zpwr compilefpath${N}${D}                   # alias for above${N}"
    print ""
    print "  ${B}${Y}DECOMPILE: REMOVE .ZWC FILES${N}"
    print "  ${M}  zpwr decompile${N}${D}                      # remove all .zwc files${N}"
    print "  ${M}  zpwr uncompile${N}${D}                      # alias for above${N}"
    print ""
    print "  ${D}  Deletes all .zwc files in zpwr. After this, zsh falls${N}"
    print "  ${D}  back to parsing source files directly. Useful when:${N}"
    print "  ${D}  - Debugging a function that behaves differently than source${N}"
    print "  ${D}  - You suspect a stale .zwc file is loading old code${N}"
    print "  ${D}  - zpwr doctor reports stale .zwc files${N}"
    print ""
    print "  ${B}${Y}REFRESHZWC: SMART REBUILD${N}"
    print "  ${M}  zpwr refreshzwc${N}${D}                     # refresh only stale .zwc files${N}"
    print ""
    print "  ${D}  Only recompiles .zwc files that are older than their${N}"
    print "  ${D}  source. Faster than a full recompile when only a few${N}"
    print "  ${D}  files changed.${N}"
    print ""
    print "  ${B}${Y}THE COMPILATION WORKFLOW${N}"
    print "  ${D}  After editing zpwr source files:${N}"
    print "  ${M}    zpwr recompile${N}${D}                    # rebuild .zwc files${N}"
    print ""
    print "  ${D}  If something is weird after an update:${N}"
    print "  ${M}    zpwr decompile && zpwr recompile${N}${D}  # clean rebuild${N}"
    print ""
    print "  ${D}  Quick check for stale files:${N}"
    print "  ${M}    zpwr doctor${N}${D}                       # reports stale .zwc files${N}"
    print ""
    print "  ${D}  The .zwc files are safe to delete. They are purely a${N}"
    print "  ${D}  performance cache. Source files are always the authority.${N}"
    print ""
}
