PAGE_TITLE="lsofrs: Practical Usage"
PAGE_CHAPTER="CHAPTER 33: LSOFRS — ENHANCED LSOF"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== LSOFRS: PRACTICAL USAGE ===${N}"
    print "  ${D}// who's listening on port 8080? lsofrs knows. lsofrs always knows. //${N}"
    print "  ${B}${Y}FINDING WHAT'S ON A PORT${N}"
    print "  ${M}  lsofrs -i :8080${N}${D}        # anything on port 8080${N}"
    print "  ${M}  lsofrs -i TCP:443${N}${D}      # TCP connections on 443${N}"
    print "  ${M}  lsofrs -i 4${N}${D}            # all IPv4 connections${N}"
    print "  ${M}  lsofrs -i 6TCP${N}${D}         # IPv6 TCP only${N}"
    print "  ${B}${Y}DISPLAY & OUTPUT${N}"
    print "  ${G}  lsofrs -F [FIELDS]${N}${D}  # machine-readable output fields${N}"
    print "  ${G}  lsofrs -J / --json${N}${D}  # JSON output for piping to jq${N}"
    print "  ${G}  lsofrs -R${N}${D}           # list parent PIDs${N}"
    print "  ${G}  lsofrs -t${N}${D}           # terse: PID only (for scripting)${N}"
    print "  ${G}  lsofrs -0${N}${D}           # NUL field terminator (xargs -0 friendly)${N}"
    print "  ${G}  lsofrs --color MODE${N}${D} # auto, always, or never${N}"
    print "  ${B}${Y}LIVE MONITORING${N}"
    print "  ${G}  lsofrs +r 2${N}${D}         # repeat every 2 seconds${N}"
    print "  ${G}  lsofrs -W / --monitor${N}${D} # live full-screen like top${N}"
    print "  ${G}  lsofrs --delta${N}${D}       # highlight new/gone FDs in repeat mode${N}"
    print "  ${G}  lsofrs --follow PID${N}${D}  # watch one process, highlight opens/closes${N}"
    print "  ${G}  lsofrs --top 20${N}${D}     # live top-N processes by FD count${N}"
    print "  ${G}  lsofrs --watch FILE${N}${D}  # watch who opens/closes a file over time${N}"
    print "  ${B}${Y}DIAGNOSTICS${N}"
    print "  ${G}  lsofrs --leak-detect${N}${D} # detect FD leaks (poll every 5s, 3 rounds)${N}"
    print "  ${G}  lsofrs --stale${N}${D}       # find FDs pointing to deleted files${N}"
    print "  ${G}  lsofrs --ports${N}${D}       # listening ports summary (like ss -tlnp)${N}"
    print "  ${G}  lsofrs --tree${N}${D}        # process tree with FD counts (pstree + lsof)${N}"
    print "  ${G}  lsofrs --summary${N}${D}     # aggregate FD summary by type and user${N}"
    print "  ${B}${Y}COMPARISON${N}"
    print "  ${D}${G}lsof${D}    — the OG. every Unix has it. output is a wall of text.${N}"
    print "  ${D}${G}ss${D}      — socket statistics. fast but sockets only, no files.${N}"
    print "  ${D}${G}netstat${D} — deprecated on Linux. still works on macOS/BSD.${N}"
    print "  ${D}${G}lsofrs${D}  — wraps lsof with color, JSON, live monitoring,${N}"
    print "  ${D}         leak detection, tree views, and the cyberpunk banner${N}"
    print "  ${D}         you get with ${G}lsofrs -h${D}. Built for operators who${N}"
    print "  ${D}         stare at FD tables and like what they see.${N}"
    print "  ${B}${Y}QUICK RECIPES${N}"
    print "  ${M}  lsofrs -t -i :3000 | xargs kill${N}${D}  # kill whatever's on 3000${N}"
    print "  ${M}  lsofrs -c node -a -i TCP${N}${D}          # node's TCP connections${N}"
    print "  ${M}  lsofrs -u \$(whoami) -a -i${N}${D}         # your network connections${N}"
}
