PAGE_TITLE="Emacs Mirror Universe"
PAGE_CHAPTER="CHAPTER 5: EDITOR MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== EMACS MIRROR UNIVERSE ===${N}"
    print ""
    print "  ${C}For every vim verb, there is an emacs verb.${N}"
    print "  ${C}Identical semantics. Different editor. Perfect symmetry.${N}"
    print "  ${C}ZPWR does not take sides in the editor war.${N}"
    print "  ${C}It arms both factions equally.${N}"
    print ""
    print "  ${B}${Y}THE SYMMETRY TABLE${N}"
    print "  ${G}  vim verb              emacs verb${N}"
    print "  ${D}  --------              ----------${N}"
    print "  ${M}  vimall${N}${D} .............. ${M}emacsall${N}"
    print "  ${M}  vimalledit${N}${D} .......... ${M}emacsalledit${N}"
    print "  ${M}  vimautoload${N}${D} ......... ${M}emacsautoload${N}"
    print "  ${M}  vimcd${N}${D} ............... ${M}emacscd${N}"
    print "  ${M}  vimconfig${N}${D} ........... ${M}emacsconfig${N}"
    print "  ${M}  vimctags${N}${D} ............ ${M}emacsctags${N}"
    print "  ${M}  vimfilesearch${N}${D} ....... ${M}emacsfilesearch${N}"
    print "  ${M}  vimfilesearchedit${N}${D} ... ${M}emacsfilesearchedit${N}"
    print "  ${M}  vimfindsearch${N}${D} ....... ${M}emacsfindsearch${N}"
    print "  ${M}  vimfindsearchedit${N}${D} ... ${M}emacsfindsearchedit${N}"
    print "  ${M}  vimgtags${N}${D} ............ ${M}emacsgtags${N}"
    print "  ${M}  vimgtagsedit${N}${D} ........ ${M}emacsgtagsedit${N}"
    print "  ${M}  vimlocatesearch${N}${D} ..... ${M}emacslocatesearch${N}"
    print "  ${M}  vimlocatesearchedit${N}${D} . ${M}emacslocatesearchedit${N}"
    print "  ${M}  vimrecent${N}${D} ........... ${M}emacsrecent${N}"
    print "  ${M}  vimrecentcd${N}${D} ......... ${M}emacsrecentcd${N}"
    print "  ${M}  vimrecentsudo${N}${D} ....... ${M}emacsrecentsudo${N}"
    print "  ${M}  vimrecentsudocd${N}${D} ..... ${M}emacsrecentsudocd${N}"
    print "  ${M}  vimscripts${N}${D} .......... ${M}emacsscripts${N}"
    print "  ${M}  vimscriptedit${N}${D} ....... ${M}emacsscriptedit${N}"
    print "  ${M}  vimtests${N}${D} ............ ${M}emacstests${N}"
    print "  ${M}  vimtokens${N}${D} ........... ${M}emacstokens${N}"
    print "  ${M}  vimwordsearch${N}${D} ....... ${M}emacswordsearch${N}"
    print "  ${M}  vimwordsearchedit${N}${D} ... ${M}emacswordsearchedit${N}"
    print "  ${M}  vimplugincount${N}${D} ...... ${M}emacsplugincount${N}"
    print "  ${M}  vimpluginlist${N}${D} ....... ${M}emacspluginlist${N}"
    print ""
    print "  ${B}${Y}EMACS-SPECIFIC${N}"
    print "  ${M}  zpwr emacsallserver${N}${D}       # emacs all zpwr files (server mode)${N}"
    print "  ${M}  zpwr emacsemacsconfig${N}${D}     # emacs edit emacs-specific configs${N}"
    print "  ${M}  zpwr emacszpwr${N}${D}            # emacs the zpwr directory${N}"
    print ""
    print "  ${D}The lesson: zpwr is editor-agnostic by design.${N}"
    print "  ${D}Replace \"vim\" with \"emacs\" in any verb. It works.${N}"
    print "  ${D}Both sides get the same firepower.${N}"
    print ""
}
