PAGE_TITLE="Tmux Session Management"
PAGE_CHAPTER="CHAPTER 14: TMUX WARFARE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> TMUX WARFARE: TERMINAL MULTIPLEXER COMBAT <<<${N}"
    print "  ${D}one terminal to rule them all, split them, and in panes bind them${N}"
    print ""
    print "  ${B}${Y}zpwr attach${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Attach to an existing tmux session.${N}"
    print "  ${G}If no session exists, one will be summoned.${N}"
    print ""
    print "  ${C}  \$ zpwr attach${N}                 ${D}# rejoin the matrix${N}"
    print ""
    print "  ${B}${Y}zpwr detach${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Detach from current tmux session gracefully.${N}"
    print "  ${G}Your processes keep running in the background.${N}"
    print ""
    print "  ${C}  \$ zpwr detach${N}                 ${D}# leave but don't kill${N}"
    print ""
    print "  ${B}${Y}zpwr killmux${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Kill the tmux server. Nuclear option. Everything dies.${N}"
    print "  ${R}  WARNING: all sessions, windows, and panes -- gone.${N}"
    print ""
    print "  ${C}  \$ zpwr killmux${N}                ${D}# scorched earth${N}"
    print ""
    print "  ${B}${Y}zpwr start${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Start a new tmux session with ZPWR's custom layout.${N}"
    print "  ${G}Preconfigured panes, windows, and keybindings.${N}"
    print ""
    print "  ${C}  \$ zpwr start${N}                  ${D}# bootstrap tmux${N}"
    print ""
    print "  ${B}${Y}zpwr starttabs${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Start tmux with multiple pre-configured tabs.${N}"
    print "  ${G}Each tab gets its own purpose -- dev, logs, git, etc.${N}"
    print ""
    print "  ${C}  \$ zpwr starttabs${N}              ${D}# multi-tab setup${N}"
    print ""
    print "  ${D}  // the tmux lifecycle:${N}"
    print "  ${D}  //   start --> attach --> detach --> attach --> killmux${N}"
    print "  ${D}  //   sessions persist through SSH disconnects${N}"
    print "  ${D}  //   your terminal state is immortal${N}"
}
