PAGE_TITLE="Forgit: Git on Steroids"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FORGIT: GIT ON STEROIDS ===${N}"
    print ""
    print "  ${C}Forgit wraps common git operations with fzf previews.${N}"
    print "  ${C}Every action gets a live preview pane. Every choice${N}"
    print "  ${C}is informed. No more blind git commands.${N}"
    print ""
    print "  ${B}${Y}STAGING AND UNSTAGING${N}"
    print "  ${M}  zpwr forgitadd${N}${D}            # fzf-powered git add${N}"
    print "  ${D}  Shows unstaged files with inline diffs in the preview.${N}"
    print "  ${D}  Select files with tab. Enter to stage. Visual staging.${N}"
    print ""
    print "  ${M}  zpwr forgitreset${N}${D}          # fzf-powered git reset HEAD${N}"
    print "  ${D}  The reverse of forgitadd. Unstage files visually.${N}"
    print ""
    print "  ${B}${Y}VIEWING CHANGES${N}"
    print "  ${M}  zpwr forgitdiff${N}${D}           # fzf-powered git diff viewer${N}"
    print "  ${D}  Browse changed files. Preview shows colorized diffs.${N}"
    print "  ${D}  Side-by-side comparison in your terminal.${N}"
    print ""
    print "  ${M}  zpwr forgitlog${N}${D}            # fzf-powered git log${N}"
    print "  ${D}  Commit history with preview. See the diff for each${N}"
    print "  ${D}  commit without leaving the log view. Beautiful.${N}"
    print ""
    print "  ${B}${Y}STASH OPERATIONS${N}"
    print "  ${M}  zpwr forgitstash${N}${D}          # fzf-powered stash browser${N}"
    print "  ${D}  Lists stashes. Preview shows what each stash contains.${N}"
    print "  ${D}  Pick one, apply it. No more \"was it stash@{3}?\"${N}"
    print ""
    print "  ${B}${Y}CLEANUP${N}"
    print "  ${M}  zpwr forgitclean${N}${D}          # fzf-powered git clean${N}"
    print "  ${D}  Shows untracked files. Select which to delete.${N}"
    print "  ${D}  Preview before you destroy. Civilized cleanup.${N}"
    print ""
    print "  ${M}  zpwr forgitrestore${N}${D}        # fzf-powered git restore${N}"
    print "  ${D}  Discard changes to selected files. With preview.${N}"
    print ""
    print "  ${B}${Y}GITIGNORE MANAGEMENT${N}"
    print "  ${M}  zpwr forgitignore${N}${D}         # browse gitignore templates${N}"
    print "  ${M}  zpwr forgitignoreget${N}${D}      # download a gitignore template${N}"
    print "  ${M}  zpwr forgitignorelist${N}${D}     # list available templates${N}"
    print "  ${M}  zpwr forgitignoreupdate${N}${D}   # update gitignore templates${N}"
    print "  ${M}  zpwr forgitignoreclean${N}${D}    # clean gitignore cache${N}"
    print ""
    print "  ${B}${Y}EXTRAS${N}"
    print "  ${M}  zpwr forgitinfo${N}${D}           # show git repo information${N}"
    print "  ${M}  zpwr forgitwarn${N}${D}           # show forgit warnings${N}"
    print ""
    print "  ${D}Forgit turns git into a visual experience.${N}"
    print "  ${D}Every ${M}forgit*${D} verb is a regular git command with eyes.${N}"
    print ""
}
