PAGE_TITLE="Perl Oneliners: Advanced Patterns"
PAGE_CHAPTER="CHAPTER 39: PERL IN ZPWR"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== PERL ONELINERS: ADVANCED PATTERNS ===${N}"
    print "  ${D}when you need a chainsaw, not a butter knife${N}"
    print ""
    print "  ${B}${Y}PATH QUOTING (zpwrGetFound)${N}"
    print "  ${M}  perl -pe 's@^([~]*)([^~].*)\$@\$1\"\$2\"@;s@\\s+@ @g'${N}"
    print "  ${D}  Wraps non-tilde paths in double quotes and collapses spaces.${N}"
    print "  ${D}  Handles filenames with spaces for safe shell consumption.${N}"
    print ""
    print "  ${B}${Y}FZF RESULT FORMATTING (zpwrAgIntoFzf)${N}"
    print "  ${M}  perl -pe 's@^(.*?):(\\d+):(.*)@+\$2 \"PWD/\$1\"@'${N}"
    print "  ${D}  Converts grep output (file:line:match) into vim args (+line \"file\").${N}"
    print "  ${D}  The brain behind zpwr grep -> fzf -> vim pipeline.${N}"
    print ""
    print "  ${B}${Y}VERB LIST FORMATTING (zpwrVerbsFZF)${N}"
    print "  ${M}  perl -e '@a=<>;for(@a){print \"zpwr \$1\" if m{^(\\S+)\\s+}}'${N}"
    print "  ${D}  Reads verb list, extracts first word, prepends 'zpwr '.${N}"
    print "  ${D}  Builds the command string that fzf executes on selection.${N}"
    print ""
    print "  ${B}${Y}IN-PLACE RENAME (zpwrChangeNameZpwr)${N}"
    print "  ${M}  perl -i -pe 's@\\bOLDNAME\\b@NEWNAME@g' **/*(.)'${N}"
    print "  ${D}  Renames all occurrences across all files. The \\b word boundary${N}"
    print "  ${D}  prevents partial matches. The **(.) glob hits all regular files.${N}"
    print ""
    print "  ${B}${Y}LOGIN COUNTING (zpwrLoginCount)${N}"
    print "  ${M}  perl -e 'print \\`last -f \"\$_\"\\`for</var/log/wtmp*>'${N}"
    print "  ${D}  Reads all wtmp files and runs 'last' on each. The diamond${N}"
    print "  ${D}  operator <> globs and iterates. Then pipes to:${N}"
    print "  ${M}  perl -lane 'print \$F[0] if /\\S+/ && !/wtmp/'${N}"
    print "  ${D}  Extracts username (first field) from non-empty, non-header lines.${N}"
    print ""
    print "  ${B}${Y}FILE COUNT DEDUP (zpwrEnvCounts)${N}"
    print "  ${M}  perl -lne '@l=<>;@u=do{my %seen;grep{!\$seen{\$_}++}@l};'${N}"
    print "  ${D}  Reads all lines, deduplicates with a hash, then checks if${N}"
    print "  ${D}  each unique path is a real file. The densest oneliner in zpwr.${N}"
    print "  ${D}  Counts unique zpwr files across all tracked locations.${N}"
    print ""
    print "  ${B}${Y}IP ADDRESS EXTRACTION (ipa alias)${N}"
    print "  ${M}  ifconfig | perl -lane 'do {print \$F[1]=~s/addr//r;exit0} if /inet\\s/ and !/127/'${N}"
    print "  ${D}  Finds the first non-loopback inet address. The s///r flag${N}"
    print "  ${D}  returns the modified string without changing the original.${N}"
    print ""
    print "  ${B}${Y}WHY PERL OVER SED/AWK?${N}"
    print "  ${D}  1. Perl regex is more powerful (lookahead, backrefs, /x)${N}"
    print "  ${D}  2. -i flag for in-place edit is reliable across OS${N}"
    print "  ${D}  3. Complex logic in one line (if/unless/for/do blocks)${N}"
    print "  ${D}  4. @F autosplit is awk-like but with perl's full stdlib${N}"
    print "  ${D}  5. Perl is installed everywhere (even minimal containers)${N}"
}
