PAGE_TITLE="Tmux Architecture in ZPWR"
PAGE_CHAPTER="CHAPTER 30: TMUX DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== TMUX ARCHITECTURE IN ZPWR ===${N}"
    print "  ${D}// the terminal multiplexer. one screen, infinite shells. //${N}"
    print "  ${C}Tmux is the backbone of the ZPWR workflow. Multiple shells,${N}"
    print "  ${C}persistent sessions, split panes, and code execution across${N}"
    print "  ${C}panes -- all orchestrated from \$ZPWR_TMUX.${N}"
    print "  ${B}${Y}SESSION / WINDOW / PANE MODEL${N}"
    print "  ${G}  Session${N}${D}    Named group of windows (e.g., 'dev', 'zpwr-study')${N}"
    print "  ${G}  Window${N}${D}     A tab inside a session (like browser tabs)${N}"
    print "  ${G}  Pane${N}${D}       A split inside a window (like vim splits)${N}"
    print "  ${D}Typical ZPWR layout: 1 session, 2-4 windows, 2-4 panes each.${N}"
    print "  ${D}Prefix key: Ctrl-B (default). Followed by a command key.${N}"
    print "  ${B}${Y}SESSION PERSISTENCE${N}"
    print "  ${G}  tmux-resurrect${N}${D}   Manual save/restore of sessions${N}"
    print "  ${D}    Save: ${M}prefix + Ctrl-s${N}"
    print "  ${D}    Restore: ${M}prefix + Ctrl-r${N}"
    print "  ${D}    Saves: pane layouts, working directories, running programs.${N}"
    print "  ${D}    @resurrect-processes ':all:' -- saves ALL running programs.${N}"
    print "  ${G}  tmux-continuum${N}${D}    Auto-save every 15 minutes${N}"
    print "  ${D}    Works silently in the background. No manual intervention.${N}"
    print "  ${D}    Combined with resurrect: your tmux state survives reboots.${N}"
    print "  ${B}${Y}THE POWERLINE STATUS BAR${N}"
    print "  ${D}Tmux sources powerline bindings for the status bar:${N}"
    print "  ${M}  source-file ~/.tmux/powerline/bindings/tmux/powerline.conf${N}"
    print "  ${D}The symlink ~/.tmux/powerline points to pip's powerline-status.${N}"
    print "  ${D}powerline-daemon runs in the background for performance.${N}"
    print "  ${D}Status bar shows: session name, window list, hostname, time,${N}"
    print "  ${D}battery level (via tmux-battery plugin).${N}"
    print "  ${B}${Y}\$ZPWR_TMUX: THE CONFIG DIRECTORY${N}"
    print "  ${D}All tmux config lives under \$ZPWR_TMUX:${N}"
    print "  ${M}  init.conf${N}${D}               Main config (bindings, options)${N}"
    print "  ${M}  tmux-mac.conf${N}${D}           macOS-specific overrides${N}"
    print "  ${M}  tmux-linux.conf${N}${D}         Linux-specific overrides${N}"
    print "  ${M}  tmux_ge_21.conf${N}${D}         Tmux >= 2.1 features${N}"
    print "  ${M}  tmux_ge_29.conf${N}${D}         Tmux >= 2.9 features${N}"
    print "  ${M}  tmux_ge_31.conf${N}${D}         Tmux >= 3.1 features${N}"
    print "  ${M}  four-panes.conf${N}${D}         Layout: 4 panes${N}"
    print "  ${M}  sixteen-panes.conf${N}${D}      Layout: 16 panes${N}"
    print "  ${M}  config-files.conf${N}${D}       Opens brc, vrc, trc, zrc in 4 panes${N}"
    print "  ${M}  learn.conf${N}${D}              Study layout${N}"
    print "  ${B}${Y}init.conf HIGHLIGHTS${N}"
    print "  ${D}  - 30,000 line scrollback (ZPWR_TMUX_HISTORY_LIMIT)${N}"
    print "  ${D}  - Vi keybindings in copy mode${N}"
    print "  ${D}  - Prefix S: synchronize-panes (type in all panes at once)${N}"
    print "  ${D}  - Prefix q: display pane numbers for 5 seconds${N}"
    print "  ${D}  - 3-second repeat-time for directional keys${N}"
}
