PAGE_TITLE="Shell State Inspection"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> SHELL STATE: KNOW THY ZSH <<<${N}"
    print "  ${D}introspection: when the shell looks in the mirror${N}"
    print ""
    print "  ${B}${Y}zpwr exists${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Check if a ZPWR component exists (functions, files, etc).${N}"
    print ""
    print "  ${C}  \$ zpwr exists zpwrReload${N}       ${D}# does this exist?${N}"
    print ""
    print "  ${B}${Y}zpwr existscommand${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Check if a command exists in PATH.${N}"
    print "  ${G}Cleaner than 'which' or 'command -v' in scripts.${N}"
    print ""
    print "  ${C}  \$ zpwr existscommand git${N}      ${D}# is git installed?${N}"
    print "  ${C}  \$ zpwr existscommand rg${N}       ${D}# is ripgrep here?${N}"
    print ""
    print "  ${B}${Y}zpwr reload${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Reload the entire ZPWR framework without restarting.${N}"
    print "  ${G}Re-sources configs, rebuilds caches, refreshes state.${N}"
    print ""
    print "  ${C}  \$ zpwr reload${N}                 ${D}# hot reload everything${N}"
    print ""
    print "  ${B}${Y}ZSH INSPECTION TOOLS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}These are built into zsh, but ZPWR makes them accessible:${N}"
    print ""
    print "  ${C}  \$ setopt${N}                      ${D}# list active options${N}"
    print "  ${C}  \$ zmodload${N}                    ${D}# list loaded modules${N}"
    print "  ${C}  \$ zstyle -L${N}                   ${D}# list all zstyles${N}"
    print ""
    print "  ${B}${Y}zpwr copycommand${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Copy a command's path or definition to clipboard.${N}"
    print ""
    print "  ${C}  \$ zpwr copycommand ls${N}         ${D}# copy ls path${N}"
    print ""
    print "  ${B}${Y}zpwr opencommand${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open a command's source file in your editor.${N}"
    print "  ${G}Works for functions, scripts, and binaries.${N}"
    print ""
    print "  ${C}  \$ zpwr opencommand zpwrReload${N}  ${D}# view the source${N}"
    print ""
    print "  ${D}  // existscommand before you call, reload after you change${N}"
    print "  ${D}  // opencommand when you need to understand the internals${N}"
}
