PAGE_TITLE="Usage Intelligence"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== USAGE INTELLIGENCE ===${N}"
    print "  ${D}// your shell keeps a diary. these verbs read it. //${N}"
    print ""
    print "  ${C}You have ${#ZPWR_VERBS} verbs and thousands of aliases.${N}"
    print "  ${C}Which ones do you actually use? ${M}funcrank${C} and ${M}aliasrank${N}"
    print "  ${C}mine your shell history to answer that question.${N}"
    print ""
    print "  ${B}${Y}FUNCRANK: FUNCTION & VERB PROFILER${N}"
    print "  ${M}  zpwr funcrank${N}${D}                       # top 20 functions and verbs${N}"
    print "  ${M}  zpwr funcrank 40${N}${D}                    # top 40${N}"
    print "  ${M}  zpwr funcrank --reset${N}${D}               # nuke cache, rebuild from scratch${N}"
    print "  ${M}  zpwr funcrank --reset 50${N}${D}            # rebuild then show top 50${N}"
    print ""
    print "  ${D}  funcrank scans your HISTFILE for occurrences of known${N}"
    print "  ${D}  function names and zpwr verbs. It produces two ranked lists:${N}"
    print "  ${G}  1. Top functions${N}${D} by history occurrence count${N}"
    print "  ${G}  2. Top zpwr verbs${N}${D} by how often you type \"zpwr <verb>\"${N}"
    print "  ${D}  Each entry gets a Unicode bar chart. The biggest user wins.${N}"
    print ""
    print "  ${B}${Y}ALIASRANK: REVERSE EXPANSION PROFILER${N}"
    print "  ${M}  zpwr aliasrank${N}${D}                      # top 20 by expanded usage${N}"
    print "  ${M}  zpwr aliasrank 50${N}${D}                   # top 50${N}"
    print "  ${M}  zpwr aliasrank --reset${N}${D}              # force cache rebuild${N}"
    print ""
    print "  ${D}  Here is the trick: zpwr uses zsh-expand to expand aliases${N}"
    print "  ${D}  before they hit history. So history contains the ${B}expanded${D}${N}"
    print "  ${D}  form, not the alias name. aliasrank does a reverse lookup:${N}"
    print "  ${D}  it matches history lines against alias ${B}values${D} to figure${N}"
    print "  ${D}  out which alias you would have typed.${N}"
    print ""
    print "  ${B}${Y}THE CACHE SYSTEM${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ZPWR_LOCAL/zpwr-aliasrank-cache.zsh${N}${D}   command counts${N}"
    print "  ${C}  \$ZPWR_LOCAL/zpwr-verbrank-cache.zsh${N}${D}    verb counts${N}"
    print "  ${C}  \$ZPWR_LOCAL/zpwr-rank-stamp${N}${D}            history line watermark${N}"
    print ""
    print "  ${D}  The cache auto-rebuilds when history grows by 1000+ lines.${N}"
    print "  ${D}  The watermark file stores the last-seen history line count.${N}"
    print "  ${D}  No need to rebuild every time -- incremental is the way.${N}"
    print "  ${D}  Use ${M}--reset${D} to force a full rebuild if cache seems stale.${N}"
    print ""
    print "  ${B}${Y}INTERPRETING THE RESULTS${N}"
    print "  ${D}  If your top verb is ${M}help${D}, you are still learning. Good.${N}"
    print "  ${D}  If your top verb is ${M}cleanall${D}, you break things a lot.${N}"
    print "  ${D}  If your top function is ${M}cd${D}, you need more named dirs.${N}"
    print "  ${D}  If an alias never appears, maybe it is too long to remember.${N}"
    print ""
    print "  ${B}${Y}PRACTICAL INTELLIGENCE${N}"
    print "  ${D}  Run funcrank monthly. Notice patterns:${N}"
    print "  ${G}  - Verbs you never use${N}${D} might need better names or keybindings${N}"
    print "  ${G}  - Functions with high counts${N}${D} are candidates for optimization${N}"
    print "  ${G}  - Low-count zpwr verbs${N}${D} might benefit from shorter aliases${N}"
    print ""
    print "  ${D}  Your history is a behavioral log. These verbs turn it into${N}"
    print "  ${D}  actionable intelligence. Know thyself, operative.${N}"
    print ""
}
