PAGE_TITLE="Home Base Operations"
PAGE_CHAPTER="CHAPTER 2: NAVIGATION PROTOCOL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== HOME BASE OPERATIONS ===${N}"
    print ""
    print "  ${C}Every zpwr directory has a one-word teleporter.${N}"
    print "  ${C}No paths. No thinking. Just say where.${N}"
    print ""
    print "  ${B}${Y}THE HOME VERB FAMILY${N}"
    print "  ${M}  zpwr home${N}${D}                # cd \$ZPWR (the root)${N}"
    print "  ${M}  zpwr homelocal${N}${D}           # cd \$ZPWR_LOCAL${N}"
    print "  ${M}  zpwr homescripts${N}${D}         # cd \$ZPWR_SCRIPTS${N}"
    print "  ${M}  zpwr homeenv${N}${D}             # cd \$ZPWR_ENV${N}"
    print "  ${M}  zpwr homeinstall${N}${D}         # cd \$ZPWR_INSTALL${N}"
    print "  ${M}  zpwr homeautoload${N}${D}        # cd \$ZPWR_AUTOLOAD${N}"
    print "  ${M}  zpwr homeautoloadcommon${N}${D}   # cd \$ZPWR_AUTOLOAD_COMMON${N}"
    print "  ${M}  zpwr homecomps${N}${D}           # cd \$ZPWR_COMPS${N}"
    print "  ${M}  zpwr hometest${N}${D}            # cd \$ZPWR_TEST${N}"
    print "  ${M}  zpwr hometmux${N}${D}            # cd \$ZPWR_TMUX${N}"
    print "  ${M}  zpwr homeexercism${N}${D}        # cd \$HOME/Exercism${N}"
    print ""
    print "  ${B}${Y}WHAT LIVES WHERE${N}"
    print "  ${G}  home${N}${D} .............. the zpwr repo root, start of everything${N}"
    print "  ${G}  homelocal${N}${D} ........ gitignored personal configs and tokens${N}"
    print "  ${G}  homescripts${N}${D} ...... executable shell scripts${N}"
    print "  ${G}  homeenv${N}${D} .......... environment variables and init files${N}"
    print "  ${G}  homeinstall${N}${D} ...... installer scripts for dependencies${N}"
    print "  ${G}  homeautoload${N}${D} ..... autoloaded functions (the engine room)${N}"
    print "  ${G}  homeautoloadcommon${N}${D}  platform-independent autoloads${N}"
    print "  ${G}  homecomps${N}${D} ........ zsh completion definitions${N}"
    print "  ${G}  hometest${N}${D} ......... test suite files${N}"
    print "  ${G}  hometmux${N}${D} ......... tmux configuration files${N}"
    print ""
    print "  ${B}${Y}EXAMPLE WORKFLOW${N}"
    print "  ${C}  You want to edit an autoload function:${N}"
    print "  ${M}    zpwr homeautoloadcommon${N}"
    print "  ${D}    # now you are in the autoload directory${N}"
    print "  ${D}    # ls, grep, edit to your heart's content${N}"
    print ""
    print "  ${C}  You want to check your local tokens:${N}"
    print "  ${M}    zpwr homelocal${N}"
    print "  ${D}    # lands you right next to .tokens.sh${N}"
    print ""
    print "  ${D}Every ${M}home*${D} verb is a bookmark you never need to set.${N}"
    print "  ${D}The bookmarks are built into the system.${N}"
    print ""
}
