PAGE_TITLE="Path Audit"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== PATH AUDIT ===${N}"
    print "  ${D}// your PATH is your attack surface. audit it. //${N}"
    print ""
    print "  ${C}zpwr pathaudit inspects PATH, FPATH, and MANPATH for${N}"
    print "  ${C}duplicates, missing directories, and world-writable entries.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr pathaudit${N}${D}             # audit all three arrays${N}"
    print "  ${M}  zpwr pathaudit -v${N}${D}          # verbose: show every entry${N}"
    print ""
    print "  ${B}${Y}WHAT IT CHECKS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${Y}  DUPLICATES${N}"
    print "  ${D}    Same directory appearing more than once.${N}"
    print "  ${D}    Wastes hash lookups and obscures precedence.${N}"
    print "  ${D}    Fix: ${M}zpwr deduppaths${N}"
    print ""
    print "  ${R}  MISSING DIRECTORIES${N}"
    print "  ${D}    PATH entry pointing to a dir that does not exist.${N}"
    print "  ${D}    Slows command lookup — zsh checks every entry.${N}"
    print ""
    print "  ${R}  WORLD-WRITABLE DIRECTORIES${N}"
    print "  ${D}    Any user can write to this directory. If it is in${N}"
    print "  ${D}    your PATH, an attacker can plant a malicious binary${N}"
    print "  ${D}    that shadows a real command. Security risk.${N}"
    print ""
    print "  ${B}${Y}ALL THREE ARRAYS${N}"
    print "  ${G}  PATH${N}${D}     — command lookup for executables${N}"
    print "  ${G}  FPATH${N}${D}    — function autoload lookup for zsh${N}"
    print "  ${G}  MANPATH${N}${D}  — man page lookup for documentation${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr doctor${N}${D}               # broader health check (also checks paths)${N}"
    print "  ${M}  zpwr deduppaths${N}${D}            # remove duplicate entries${N}"
    print "  ${M}  zpwr environmentcounts${N}${D}      # count all env arrays${N}"
    print ""
    print "  ${D}  doctor checks paths as part of a broader scan.${N}"
    print "  ${D}  pathaudit goes deeper with world-writable detection.${N}"
    print ""
}
