PAGE_TITLE="Your First 5 Minutes"
PAGE_CHAPTER="CHAPTER 1: THE RED PILL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== YOUR FIRST 5 MINUTES ===${N}"
    print ""
    print "  ${C}You just installed zpwr. The terminal blinks. What now?${N}"
    print "  ${C}Here is your survival kit for the first 300 seconds.${N}"
    print ""
    print "  ${B}${Y}STEP 1: SEE THE BANNER${N}"
    print "  ${M}  zpwr about${N}${D}              # the ASCII art welcome screen${N}"
    print "  ${M}  zpwr banner${N}${D}             # same thing, different alias${N}"
    print "  ${M}  zpwr bannercounts${N}${D}       # banner + environment statistics${N}"
    print ""
    print "  ${B}${Y}STEP 2: COUNT YOUR ARSENAL${N}"
    print "  ${M}  zpwr environmentcounts${N}${D}  # how many aliases, functions, etc.${N}"
    print "  ${D}  This prints a breakdown of your loaded shell environment:${N}"
    print "  ${D}  aliases, functions, builtins, parameters, completions.${N}"
    print "  ${D}  If the numbers are big, congratulations. You are armed.${N}"
    print ""
    print "  ${B}${Y}STEP 3: DISCOVER THE VERBS${N}"
    print "  ${M}  zpwr help${N}${D}               # colorized list of ALL verbs${N}"
    print "  ${M}  zpwr verbs${N}${D}     # fzf fuzzy search through verbs${N}"
    print ""
    print "  ${G}The ${M}verbs${G} verb is your panic button (alias: subcommandsfzf).${N}"
    print "  ${G}Forgot what a command is called? Fuzzy search it.${N}"
    print "  ${G}This pipes every verb and its description into fzf.${N}"
    print "  ${G}Type a few characters. Watch the list collapse.${N}"
    print "  ${G}Hit enter. Execute.${N}"
    print ""
    print "  ${B}${Y}STEP 4: VERIFY YOUR ENVIRONMENT${N}"
    print "  ${M}  zpwr doctor${N}${D}             # run environment health check${N}"
    print "  ${M}  zpwr envvars${N}${D}            # list all zpwr env vars${N}"
    print "  ${M}  zpwr colortest${N}${D}          # verify your terminal colors${N}"
    print "  ${M}  zpwr colortest256${N}${D}       # the full 256-color palette${N}"
    print ""
    print "  ${B}${Y}STEP 5: TAB COMPLETE EVERYTHING${N}"
    print "  ${C}  Type ${M}zpwr ${C}and press ${B}<tab>${C}. You will see ${#ZPWR_VERBS} verbs.${N}"
    print "  ${C}  Type ${M}zpwr git${C} and press ${B}<tab>${C}. Filtered to git verbs.${N}"
    print "  ${C}  Type ${M}zpwr vim${C} and press ${B}<tab>${C}. Filtered to vim verbs.${N}"
    print "  ${C}  The completion system knows every verb. Trust it.${N}"
    print ""
    print "  ${D}If you only remember one command from this page:${N}"
    print "  ${B}${G}  zpwr verbs${N}"
    print "  ${D}It is the cheat code to everything else.${N}"
    print ""
}
