PAGE_TITLE="The 24-Hour Updater Loop"
PAGE_CHAPTER="CHAPTER 40: HIDDEN SUBSYSTEMS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== THE 24-HOUR UPDATER LOOP ===${N}"
    print "  ${D}your system updates itself while you sleep${N}"
    print "  ${B}${Y}THE INFINITE LOOP${N}"
    print "  ${G}  \$ZPWR_SCRIPTS/autoUpdater.sh${N}${D} runs forever.${N}"
    print "  ${D}  Every 24 hours it wakes up and updates everything.${N}"
    print "  ${M}  while true; do${N}"
    print "  ${M}      bash -l updater.sh -e${N}"
    print "  ${M}      # sleep in 10-minute chunks until 24h elapsed${N}"
    print "  ${M}  done${N}"
    print "  ${D}  Uses Perl Time::Piece to calculate the next update time.${N}"
    print "  ${D}  Logs the time diff on each wake to \$ZPWR_LOGFILE.${N}"
    print "  ${B}${Y}WHAT GETS UPDATED${N}"
    print "  ${D}  updater.sh orchestrates the full update:${N}"
    print "  ${G}  zpwrUpdater${N}${D}      runs the main zpwr update sequence${N}"
    print "  ${G}  zpwrUpdateDeps${N}${D}   updates all package manager dependencies${N}"
    print "  ${D}  Homebrew, npm, pip, gem, go - everything gets refreshed.${N}"
    print "  ${D}  History files backed up. Logs rotated. Deps pinned.${N}"
    print "  ${B}${Y}SYSTEMD SERVICE (LINUX)${N}"
    print "  ${D}  On Linux, autoUpdater.sh runs as a systemd service.${N}"
    print "  ${G}  zpwr restart${N}${D}      restart the zpwr systemd service${N}"
    print "  ${G}  zpwr serviceup${N}${D}    start and enable the systemd service${N}"
    print "  ${G}  zpwr servicedown${N}${D}  stop and disable the systemd service${N}"
    print "  ${D}  On macOS, ${M}\$ZPWR_SCRIPTS/updaterForLaunchCtl.sh${N}${D} is used.${N}"
    print "  ${B}${Y}EMAIL NOTIFICATIONS${N}"
    print "  ${G}  \$ZPWR_SCRIPTS/updaterEmail.sh${N}"
    print "  ${D}  Pipes the update log to email via mutt.${N}"
    print "  ${D}  Wake up to a full report of what changed overnight.${N}"
    print "  ${D}  Your system admin is a bash script. It never sleeps.${N}"
    print "  ${B}${Y}THE SLEEP STRATEGY${N}"
    print "  ${D}  Doesn't sleep for 24h straight (that would drift).${N}"
    print "  ${D}  Sleeps in 10-minute intervals, checks elapsed time:${N}"
    print "  ${M}  ((timediff > \$((3600 * 24)))) && break${N}"
    print "  ${D}  This handles laptop suspends and clock adjustments.${N}"
    print "  ${B}${R}WARNING:${N} ${D}The updater keeps zpwr and all deps current.${N}"
    print "  ${D}  If something breaks after an update, check the log:${N}"
    print "  ${G}  zpwr taillog${N}${D}  to see what the updater did last.${N}"
    print "  ${D}  The machine maintains itself. You just write code.${N}"
}
