PAGE_TITLE="Autocomplete Integration"
PAGE_CHAPTER="CHAPTER 14: TMUX WARFARE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> AUTOCOMPLETE: THE TAB KEY'S FINAL FORM <<<${N}"
    print "  ${D}zsh-autocomplete + tmux = sentient tab completion${N}"
    print ""
    print "  ${B}${Y}zpwr startauto${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Enable the ZPWR autocomplete integration.${N}"
    print "  ${G}Completions appear as you type, no Tab needed.${N}"
    print ""
    print "  ${C}  \$ zpwr startauto${N}              ${D}# enable live complete${N}"
    print ""
    print "  ${B}${Y}zpwr stopauto${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Disable autocomplete. Sometimes you want silence.${N}"
    print ""
    print "  ${C}  \$ zpwr stopauto${N}               ${D}# disable live complete${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS WITH TMUX:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}The autocomplete system hooks into zsh's completion${N}"
    print "  ${G}engine and renders suggestions in real-time.${N}"
    print ""
    print "  ${Y}FEATURES:${N}"
    print "  ${C}  *${N} Live suggestions as you type"
    print "  ${C}  *${N} History-based predictions"
    print "  ${C}  *${N} Path completion with preview"
    print "  ${C}  *${N} Command argument completion"
    print "  ${C}  *${N} Works across all tmux panes independently"
    print ""
    print "  ${B}${Y}TMUX + AUTOCOMPLETE TIPS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  * Each tmux pane runs its own zsh instance${N}"
    print "  ${D}  * Autocomplete state is per-pane${N}"
    print "  ${D}  * startauto/stopauto affects current pane only${N}"
    print "  ${D}  * If completions feel slow, check \$ZPWR_COMPS_CACHE${N}"
    print ""
    print "  ${C}  \$ zpwr stopauto${N}               ${D}# when it gets noisy${N}"
    print "  ${C}  \$ zpwr startauto${N}              ${D}# when you miss it${N}"
    print ""
    print "  ${D}  // autocomplete is like a copilot for your shell${N}"
    print "  ${D}  // it watches, it learns, it suggests${N}"
    print "  ${D}  // toggle it off when you need to think in silence${N}"
}
