PAGE_TITLE="The Matrix"
PAGE_CHAPTER="CHAPTER 22: CREATIVE TOOLS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE MATRIX ===${N}"
    print "  ${D}// not cmatrix. this is YOUR shell, raining. //${N}"
    print ""
    print "  ${C}zpwr matrix is an animated cyberpunk hacker story followed${N}"
    print "  ${C}by an infinite ecosystem rain screensaver. Unlike cmatrix,${N}"
    print "  ${C}it rains YOUR data — verb names, function names, aliases,${N}"
    print "  ${C}env vars, and git repo names. Color-coded by type.${N}"
    print ""
    print "  ${B}${Y}THE STORY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  ACT I${N}${D}    The Signal — the terminal underground survives${N}"
    print "  ${G}  ACT II${N}${D}   The Discovery — curl | zsh changes everything${N}"
    print "  ${G}  ACT III${N}${D}  The Power — bench, flame, doctor, gitwho${N}"
    print "  ${G}  ACT IV${N}${D}   The Choice — VS Code or zpwr matrix?${N}"
    print "  ${D}  Between acts: fake SSH sessions, encrypted transmissions,${N}"
    print "  ${D}  payload downloads with glitchy progress bars.${N}"
    print ""
    print "  ${B}${Y}THE FX${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  CRT scanlines${N}${D}       green sweep top-to-bottom${N}"
    print "  ${C}  VHS tracking${N}${D}        horizontal distortion bands${N}"
    print "  ${C}  Pixel corruption${N}${D}    spreading block static${N}"
    print "  ${C}  Screen tears${N}${D}        offset colored bands${N}"
    print "  ${C}  Figlet chaos${N}${D}        random fonts, random words, dissolve${N}"
    print "  ${C}  Progress bars${N}${D}       with random glitch spikes${N}"
    print "  ${C}  Pulse events${N}${D}        ecosystem facts flash across screen${N}"
    print "  ${C}  Scrolling ticker${N}${D}    horizontal stat crawl${N}"
    print "  ${C}  HUD overlay${N}${D}         live verb/alias/func/repo counters${N}"
    print ""
    print "  ${B}${Y}THE RAIN COLORS${N}"
    print "  ${G}  green${N}${D}   verbs         ${C}cyan${D}    functions${N}"
    print "  ${Y}  yellow${N}${D}  aliases        ${M}magenta${D} env vars${N}"
    print "  ${R}  red${N}${D}     git repos${N}"
    print ""
    print "  ${B}${Y}USAGE${N}"
    print "  ${M}  zpwr matrix${N}${D}                # full story + rain${N}"
    print "  ${M}  zpwr matrix -r${N}${D}             # skip story, rain only${N}"
    print "  ${M}  zpwr matrix -s 7${N}${D}           # faster (1-9)${N}"
    print "  ${M}  zpwr rain${N}${D}                  # alias${N}"
    print "  ${M}  zpwr screensaver${N}${D}           # alias${N}"
    print ""
}
