PAGE_TITLE="Git Archaeology"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT ARCHAEOLOGY ===${N}"
    print ""
    print "  ${C}The past is not dead. It is not even past.${N}"
    print "  ${C}It is stored in .git/objects and zpwr can dig it up.${N}"
    print ""
    print "  ${B}${Y}SEARCHING THE LOG${N}"
    print "  ${M}  zpwr gitsearch${N}${D}             # search for regex in git log${N}"
    print "  ${D}  Uses fzf to grep through your entire commit history.${N}"
    print "  ${D}  That one commit where you \"fixed the thing\"? Found.${N}"
    print ""
    print "  ${M}  zpwr gitcommits${N}${D}            # search git commits with fzf${N}"
    print "  ${D}  Interactive commit browser. Preview diffs inline.${N}"
    print "  ${D}  Like git log but you can actually find things.${N}"
    print ""
    print "  ${B}${Y}COUNTING COMMITS${N}"
    print "  ${M}  zpwr gitcommitcount${N}${D}        # total number of commits${N}"
    print "  ${D}  Just a number. But what a number.${N}"
    print "  ${D}  The sum total of your decisions in this repo.${N}"
    print ""
    print "  ${B}${Y}CONTRIBUTION ANALYSIS${N}"
    print "  ${M}  zpwr gitcontribcount${N}${D}       # contributions by author${N}"
    print "  ${D}  Who committed the most? The leaderboard of blame.${N}"
    print ""
    print "  ${M}  zpwr gitcontribcountdirs${N}${D}   # contributions across dirs${N}"
    print "  ${D}  Same analysis but across multiple repositories.${N}"
    print "  ${D}  Useful for org-wide contribution audits.${N}"
    print ""
    print "  ${M}  zpwr gitcontribcountlines${N}${D}  # lines contributed by author${N}"
    print "  ${D}  Lines of code per author. The metric that lies to you.${N}"
    print "  ${D}  But it is a fun lie.${N}"
    print ""
    print "  ${B}${Y}SIZE ANALYSIS${N}"
    print "  ${M}  zpwr gittotallines${N}${D}         # total line count of git files${N}"
    print "  ${D}  How big is this repo, really? Now you know.${N}"
    print ""
    print "  ${M}  zpwr gitlargest${N}${D}            # largest files in git history${N}"
    print "  ${D}  Shows the biggest blobs stored by git, descending.${N}"
    print "  ${D}  That 50MB binary someone committed in 2019? There it is.${N}"
    print "  ${D}  Now you know what to purge (see page 12).${N}"
    print ""
    print "  ${B}${Y}DIG SESSION EXAMPLE${N}"
    print "  ${G}  # Who wrote the most code in this repo?${N}"
    print "  ${M}  zpwr gitcontribcount${N}"
    print "  ${G}  # What is eating all the disk space?${N}"
    print "  ${M}  zpwr gitlargest${N}"
    print "  ${G}  # Find that commit about the database migration:${N}"
    print "  ${M}  zpwr gitsearch${N}"
    print "  ${D}  # Type \"migration\" in fzf. There it is.${N}"
    print ""
}
