PAGE_TITLE="Autoloading: Lazy Function Loading"
PAGE_CHAPTER="CHAPTER 28: ZSH INTERNALS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== AUTOLOADING: LAZY FUNCTION LOADING ===${N}"
    print "  ${D}// 443 functions. zero parsing until you call one. //${N}"
    print "  ${C}Autoloading is zsh's lazy-loading mechanism. Register a name,${N}"
    print "  ${C}and zsh only reads the function body from disk on first call.${N}"
    print "  ${C}This is why ZPWR can have 443+ functions with negligible startup cost.${N}"
    print "  ${B}${Y}HOW autoload -z WORKS${N}"
    print "  ${D}1. ${M}autoload -z funcname${D} registers 'funcname' as autoloadable.${N}"
    print "  ${D}2. Zsh records the name but does NOT read the file yet.${N}"
    print "  ${D}3. On first call to funcname, zsh searches \$fpath for a file${N}"
    print "  ${D}   named 'funcname' (exact match, no extension).${N}"
    print "  ${D}4. The file is sourced. The function is now defined in memory.${N}"
    print "  ${D}5. The function executes with the original arguments.${N}"
    print "  ${D}6. Subsequent calls use the in-memory version. No more disk.${N}"
    print "  ${B}${Y}THE GLOB IN .zshrc${N}"
    print "  ${M}  builtin autoload -z \$ZPWR_AUTOLOAD_COMMON/*(.:t)${N}"
    print "  ${D}The glob *(.:t) means:${N}"
    print "  ${D}  ${G}*${D}    All files in the directory${N}"
    print "  ${D}  ${G}(.)${D}  Qualifier: regular files only (not dirs or symlinks)${N}"
    print "  ${D}  ${G}:t${D}   Modifier: tail only (strip directory, keep filename)${N}"
    print "  ${D}So it registers every regular file's name as a function.${N}"
    print "  ${D}Same pattern runs for ZPWR_AUTOLOAD_DARWIN or ZPWR_AUTOLOAD_LINUX.${N}"
    print "  ${B}${Y}THE fpath${N}"
    print "  ${D}fpath is the function search path (like PATH but for functions):${N}"
    print "  ${M}  fpath=( \$ZPWR_AUTOLOAD_COMMON \$ZPWR_AUTOLOAD_COMP_UTILS \$ZPWR_COMPS \$fpath )${N}"
    print "  ${D}Order matters: first match wins. ZPWR dirs come first so they${N}"
    print "  ${D}can override system completions if needed.${N}"
    print "  ${D}fpath is NOT exported (typeset +x FPATH) -- child shells don't inherit it.${N}"
    print "  ${B}${Y}THE FUNCTION FILE FORMAT${N}"
    print "  ${D}Each file in the autoload dir contains one function. The file${N}"
    print "  ${D}is named exactly like the function. Inside:${N}"
    print "  ${M}  function zpwrSomething() {${N}"
    print "  ${M}      # function body${N}"
    print "  ${M}  }${N}"
    print "  ${M}  zpwrSomething \"\$@\"${N}"
    print "  ${D}The last line calls the function with args passed through.${N}"
    print "  ${D}This is the ZPWR convention. The function wraps itself.${N}"
    print "  ${B}${Y}WHY AUTOLOADING IS FAST${N}"
    print "  ${D}443 function registrations = 443 hash table entries.${N}"
    print "  ${D}Cost: microseconds. No file I/O, no parsing, no execution.${N}"
    print "  ${D}Compare to sourcing 443 files: hundreds of milliseconds.${N}"
    print "  ${D}Autoloading turns O(n) startup into O(1) with lazy O(1) per call.${N}"
    print "  ${B}${Y}autoload -Uz${N}"
    print "  ${D}-U suppresses alias expansion during loading (safety).${N}"
    print "  ${D}-z forces zsh-style function loading (vs ksh-style).${N}"
    print "  ${D}ZPWR uses -z for its functions, -Uz for system utilities like${N}"
    print "  ${D}zrecompile, zmv, zargs, and compinit.${N}"
}
