PAGE_TITLE="arb --fzf: The Neural Interface"
PAGE_CHAPTER="CHAPTER 29: ARB ARCHITECTURE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== ARB --FZF: THE NEURAL INTERFACE ===${N}"
    print "  ${D}// the universal adapter between data and decisions. //${N}"
    print "  ${C}arb is a TUI for every pipeline. Its ${M}--fzf${C} mode is a${N}"
    print "  ${C}general-purpose command-line filter: pipe anything in,${N}"
    print "  ${C}fuzzy-search interactively, get the selection back on stdout.${N}"
    print "  ${C}ZPWR wires it into dozens of workflows: files, words, git, verbs.${N}"
    print "  ${B}${Y}THE PICKER IS ONE VARIABLE${N}"
    print "  ${D}Every ZPWR picker runs whatever ${M}\$ZPWR_FZF${D} points at:${N}"
    print "  ${M}  export ZPWR_FZF='arb --fzf --ansi'${N}"
    print "  ${D}That is the single switch. Change it and every verb, widget,${N}"
    print "  ${D}global alias and fzf-tab menu follows without further edits.${N}"
    print "  ${B}${Y}THE PATTERN: PIPE | ARB | ACTION${N}"
    print "  ${D}Every picker integration follows the same architecture:${N}"
    print "  ${M}  <data source> | arb --fzf [options] | <action on selection>${N}"
    print "  ${D}The data source generates lines. arb presents them. The action${N}"
    print "  ${D}consumes the selected line(s). Simple. Composable. Powerful.${N}"
    print "  ${B}${Y}FZF_DEFAULT_OPTS${N}"
    print "  ${D}ZPWR sets global picker defaults in zpwrBindFZFLate:${N}"
    print "  ${M}  FZF_DEFAULT_OPTS=\"\$ZPWR_COMMON_FZF_ELEM --reverse --border\"${N}"
    print "  ${D}Plus a Solarized Dark color scheme layered on top:${N}"
    print "  ${M}  --color fg:-1,bg:-1,hl:\$blue,fg+:\$base2,bg+:\$base02${N}"
    print "  ${D}ZPWR_COMMON_FZF_ELEM adds the logo prompt and nav binds:${N}"
    print "  ${M}  --prompt='\$ZPWR_FZF_LOGO ' --bind=ctrl-n:page-down,...${N}"
    print "  ${B}${Y}THE PREVIEW WINDOW${N}"
    print "  ${D}The ${M}--preview${D} flag runs a command per highlighted item:${N}"
    print "  ${M}  arb --fzf --preview 'bat --color=always {}'${N}"
    print "  ${D}ZPWR configures rich previews per context:${N}"
    print "  ${D}  Files:   bat with syntax highlighting, line numbers, grid${N}"
    print "  ${D}  Dirs:    stat output${N}"
    print "  ${D}  Packages: dpkg -I or rpm -qi${N}"
    print "  ${D}  Git:     diff preview, commit log${N}"
    print "  ${D}If bat is installed, it's the default colorizer. Falls back${N}"
    print "  ${D}to pygmentize with terminal256 output.${N}"
    print "  ${B}${Y}fzf-completion (Tab)${N}"
    print "  ${D}The picker replaces default Tab completion with fuzzy search.${N}"
    print "  ${D}Type a command, press Tab, and the picker opens:${N}"
    print "  ${M}  cd **<Tab>${N}${D}     fuzzy-select a subdirectory${N}"
    print "  ${M}  kill <Tab>${N}${D}      fuzzy-select a running process${N}"
    print "  ${M}  ssh **<Tab>${N}${D}     fuzzy-select a known host${N}"
    print "  ${D}FZF_COMPLETION_OPTS controls the preview for these.${N}"
    print "  ${B}${Y}fzf-tab PLUGIN${N}"
    print "  ${D}MenkeTechnologies/fzf-tab replaces zsh's menu completion.${N}"
    print "  ${D}Any time the completion system would show a menu, fzf-tab${N}"
    print "  ${D}intercepts it and shows the picker instead. This means:${N}"
    print "  ${D}  - Fuzzy matching for ${G}every${D} completion, not just ** triggers${N}"
    print "  ${D}  - Previews for file completions, git branches, everything${N}"
    print "  ${D}  - FZF_TAB_OPTS configures behavior (ansi, nth, delimiter)${N}"
    print "  ${D}  - FZF_TAB_COMMAND is set from \$ZPWR_FZF, so it is arb too${N}"
    print "  ${B}${Y}GLOBAL ALIASES FOR ARB${N}"
    print "  ${M}  \${ZPWR_GLOBAL_ALIAS_PREFIX}z${N}${D}   Pipe into arb: ${M}ls | ,,z${N}"
    print "  ${M}  \${ZPWR_GLOBAL_ALIAS_PREFIX}zb${N}${D}  Inline selection: ${M}vim ,,zb${N}"
}
