PAGE_TITLE="Media Creation"
PAGE_CHAPTER="CHAPTER 22: CREATIVE TOOLS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< MEDIA CREATION — ART FROM THE COMMAND LINE >>>${N}"
    print "  ${D}who needs photoshop when you have a terminal?${N}"
    print ""
    print "  ${C}The terminal is not just for text. ZPWR includes verbs${N}"
    print "  ${C}for generating GIFs, rendering ASCII art, and creating${N}"
    print "  ${C}visual content without ever opening a GUI application.${N}"
    print ""
    print "  ${B}${Y}CREATEGIF — SCREEN TO GIF${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr creategif${N}"
    print "  ${G}Creates animated GIFs from your terminal sessions.${N}"
    print "  ${G}Record your workflow, your demos, your flex.${N}"
    print "  ${G}Perfect for README demos and pull request previews.${N}"
    print ""
    print "  ${D}  Your terminal is the camera. The GIF is the film.${N}"
    print "  ${D}  No screen recording software needed.${N}"
    print ""
    print "  ${B}${Y}FIGLETFONTS — THE ASCII ART GALLERY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr figletfonts${N}"
    print "  ${G}Previews all available figlet fonts on your system.${N}"
    print "  ${G}figlet turns text into massive ASCII art banners.${N}"
    print "  ${G}This verb shows you every font so you can pick one.${N}"
    print ""
    print "  ${D}  Ever wondered what your name looks like in 47${N}"
    print "  ${D}  different ASCII art styles? Now you know.${N}"
    print ""
    print "  ${D}  Example output (one of many fonts):${N}"
    print "  ${C}   ________  ____      ____  ____  ____  ${N}"
    print "  ${C}  |___  ___||  _ \\    |  _ \\|  _ \\|  _ \\ ${N}"
    print "  ${C}     / /    | |_) |   | |_) | |_) | |_) |${N}"
    print "  ${C}    / /     |  __/    |  __/|  _ <|  _ < ${N}"
    print "  ${C}   / /      | |       | |   | | \\ | | \\ \\${N}"
    print "  ${C}  /_/       |_|       |_|   |_|  \\|_|  \\_\\${N}"
    print ""
    print "  ${B}${Y}ANIMATE — TERMINAL ANIMATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr animate${N}"
    print "  ${G}Runs terminal animations. Because sometimes the${N}"
    print "  ${G}command line needs to look as cool as it feels.${N}"
    print "  ${G}Eye candy for the operator who has everything.${N}"
    print ""
    print "  ${B}${G}THE CREATIVE TOOLKIT:${N}"
    print "  ${C}  creategif${N}       ${D}record terminal to GIF${N}"
    print "  ${C}  figletfonts${N}     ${D}preview all ASCII art fonts${N}"
    print "  ${C}  animate${N}         ${D}terminal animations${N}"
    print "  ${C}  banner${N}          ${D}the ZPWR startup banner${N}"
    print "  ${C}  bannerlolcat${N}    ${D}rainbow-colored banner${N}"
    print ""
    print "  ${D}  // the terminal is a canvas. most people see a spreadsheet.${N}"
    print "  ${D}  // hackers see a gallery. these verbs are your brushes.${N}"
    print ""
}
