PAGE_TITLE="The Test Suite"
PAGE_CHAPTER="CHAPTER 41: QUALITY ASSURANCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== THE TEST SUITE ===${N}"
    print "  ${D}60 test files standing between you and chaos${N}"
    print "  ${B}${Y}TESTING FRAMEWORK${N}"
    print "  ${D}  zpwr uses ${G}zunit${N}${D} - a testing framework written in zsh.${N}"
    print "  ${D}  Config lives in ${M}\$ZPWR/.zunit.yml${N}"
    print "  ${D}  Tests dir: ${M}\$ZPWR_TEST${N}${D}  Output: ${M}\$ZPWR_TEST/_output${N}"
    print "  ${D}  Support helpers: ${M}\$ZPWR_TEST/_support${N}"
    print "  ${B}${Y}TEST CATEGORIES${N}"
    print "  ${G}  t-autoload-*${N}${D}       verify all autoloaded functions${N}"
    print "  ${D}    load, defined, existence, fpath, whence, type, body${N}"
    print "  ${D}    Every autoload function must: exist, load, have a body.${N}"
    print "  ${G}  t-autoload-subdir-*${N}${D} same checks for subdirectory autoloads${N}"
    print "  ${G}  t-env-*${N}${D}            verify environment variables${N}"
    print "  ${D}    defined, exported, comprehensive, type checks${N}"
    print "  ${D}    Every ZPWR_* var must be defined and exported.${N}"
    print "  ${G}  t-scripts-*${N}${D}        verify script files${N}"
    print "  ${D}    executable, readable, non-empty, have shebangs, valid syntax${N}"
    print "  ${G}  t-verbs-*${N}${D}          verify zpwr verb definitions${N}"
    print "  ${D}    key format, non-empty values, callable, type checks${N}"
    print "  ${B}${Y}MORE TEST FILES${N}"
    print "  ${G}  t-functions.zsh${N}${D}     test core shell functions${N}"
    print "  ${G}  t-callable-fns.zsh${N}${D}  verify functions are callable${N}"
    print "  ${G}  t-navigation.zsh${N}${D}    test directory navigation${N}"
    print "  ${G}  t-install-files.zsh${N}${D} verify installer file integrity${N}"
    print "  ${G}  t-repo-files.zsh${N}${D}    verify repo structure${N}"
    print "  ${G}  t-plugin-counts.zsh${N}${D} verify plugin load counts${N}"
    print "  ${B}${Y}RUNNING TESTS${N}"
    print "  ${G}  zpwr test${N}${D}     run all zpwr tests${N}"
    print "  ${G}  zpwr testall${N}${D}  run ALL env tests (comprehensive sweep)${N}"
    print "  ${D}  fail_fast: true means first failure stops the run.${N}"
    print "  ${D}  verbose: true means you see every assertion.${N}"
    print "  ${B}${R}GUARANTEE:${N} ${D}Every autoload loads. Every env var defined.${N}"
    print "  ${D}  Every script executable. Every verb callable.${N}"
    print "  ${D}  60 test files verify zpwr won't break your shell.${N}"
    print "  ${D}  If tests pass, your environment is sound. Ship it.${N}"
}
