PAGE_TITLE="Stale File Finder"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== STALE FILE FINDER ===${N}"
    print "  ${D}// compiled cruft is invisible cruft. make it visible. //${N}"
    print ""
    print "  ${C}zpwr stale scans the entire zpwr tree for artifacts that${N}"
    print "  ${C}have gone stale, orphaned, or broken.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr stale${N}${D}                 # scan and report${N}"
    print "  ${M}  zpwr stale -f${N}${D}              # delete all stale files${N}"
    print ""
    print "  ${B}${Y}WHAT IT FINDS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${Y}  STALE .zwc${N}"
    print "  ${D}    Source file is newer than its compiled .zwc.${N}"
    print "  ${D}    Your shell is running yesterday's bytecode.${N}"
    print ""
    print "  ${R}  ORPHAN .zwc${N}"
    print "  ${D}    The source file was deleted but the .zwc remains.${N}"
    print "  ${D}    Dead weight taking up space and confusing zsh.${N}"
    print ""
    print "  ${R}  BROKEN SYMLINKS${N}"
    print "  ${D}    Symlinks pointing to files that no longer exist.${N}"
    print "  ${D}    Source of cryptic 'file not found' errors.${N}"
    print ""
    print "  ${Y}  EMPTY CACHE FILES${N}"
    print "  ${D}    Zero-byte files in cache directories.${N}"
    print "  ${D}    Usually left behind by interrupted operations.${N}"
    print ""
    print "  ${B}${Y}THE FIX FLAG${N}"
    print "  ${D}  ${M}zpwr stale -f${D} deletes everything it finds in one pass.${N}"
    print "  ${D}  Follow up with ${M}zpwr recompile${D} to rebuild .zwc files.${N}"
    print ""
    print "  ${B}${Y}WORKFLOW${N}"
    print "  ${M}  zpwr stale${N}${D}                 # see what is stale${N}"
    print "  ${M}  zpwr stale -f${N}${D}              # nuke the cruft${N}"
    print "  ${M}  zpwr recompile${N}${D}             # rebuild fresh .zwc files${N}"
    print "  ${M}  zpwr doctor${N}${D}                # verify everything is clean${N}"
    print ""
}
