PAGE_TITLE="Emacs Config & Server"
PAGE_CHAPTER="CHAPTER 13: EMACS DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> CONFIG & SERVER: THE EMACS MOTHERSHIP <<<${N}"
    print "  ${D}because starting emacs fresh every time is a war crime${N}"
    print ""
    print "  ${B}${Y}zpwr emacsconfig${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit ZPWR's emacs configuration files.${N}"
    print "  ${G}The bridge between the shell framework and emacs-land.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsconfig${N}            ${D}# edit zpwr emacs cfg${N}"
    print ""
    print "  ${B}${Y}zpwr emacsemacsconfig${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit your personal emacs init files (init.el, etc).${N}"
    print "  ${G}Deeper than emacsconfig -- this is YOUR emacs setup.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsemacsconfig${N}       ${D}# edit ~/.emacs.d${N}"
    print ""
    print "  ${B}${Y}zpwr emacsallserver${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Opens files using emacsclient, connecting to a running${N}"
    print "  ${G}emacs daemon. Instant file opens, no startup penalty.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsallserver${N}         ${D}# open via daemon${N}"
    print ""
    print "  ${Y}HOW THE SERVER WORKFLOW WORKS:${N}"
    print "  ${D}  1. Start emacs daemon:  emacs --daemon${N}"
    print "  ${D}  2. Use emacsallserver to open files via emacsclient${N}"
    print "  ${D}  3. Files open instantly in the running emacs instance${N}"
    print "  ${D}  4. No more 3-second startup tax per file${N}"
    print ""
    print "  ${B}${Y}zpwr emacstokens${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit your tokens/secrets file in emacs.${N}"
    print "  ${G}API keys, env vars, the classified stuff.${N}"
    print ""
    print "  ${C}  \$ zpwr emacstokens${N}            ${D}# edit \$ZPWR_LOCAL/.tokens.sh${N}"
    print ""
    print "  ${B}${Y}zpwr emacszpwr${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open the entire ZPWR directory tree in emacs.${N}"
    print ""
    print "  ${C}  \$ zpwr emacszpwr${N}              ${D}# the whole framework${N}"
    print ""
    print "  ${D}  // emacsclient + daemon = the cheat code${N}"
    print "  ${D}  // startup once, open files forever${N}"
    print "  ${D}  // this is how emacs users actually survive${N}"
}
