PAGE_TITLE="Powerlevel10k Configuration"
PAGE_CHAPTER="CHAPTER 26: POWERLEVEL10K & INSTANT PROMPT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== POWERLEVEL10K CONFIGURATION ===${N}"
    print "  ${D}// the prompt is your cockpit HUD. configure it or fly blind. //${N}"
    print "  ${C}The p10k config lives at \$ZPWR_ENV/.p10k.zsh -- a 1700+ line${N}"
    print "  ${C}file that controls every pixel of your prompt. The wizard${N}"
    print "  ${C}generated it, but you own it now.${N}"
    print "  ${B}${Y}LEFT PROMPT SEGMENTS${N}"
    print "  ${D}These appear on the left side, top to bottom across 4 lines:${N}"
    print "  ${M}  Line 1:${N} ${D}custom_env, custom_env_bat, custom_env_editor${N}"
    print "  ${M}  Line 2:${N} ${D}custom_env_term, ip${N}"
    print "  ${M}  Line 3:${N} ${D}context, dir, history, ssh, root_indicator, status, vcs${N}"
    print "  ${M}  Line 4:${N} ${D}custom_tty, prompt_char${N}"
    print "  ${D}The ${G}dir${D} segment shows your current directory using %~ expansion.${N}"
    print "  ${D}The ${G}vcs${D} segment shows git branch, dirty status, ahead/behind.${N}"
    print "  ${D}The ${G}prompt_char${D} shows green on success, red on failure.${N}"
    print "  ${B}${Y}RIGHT PROMPT SEGMENTS${N}"
    print "  ${D}The right side is information-dense. Across 3 lines:${N}"
    print "  ${M}  Line 1:${N} ${D}dir_writable, background_jobs, virtualenv, node_version,${N}"
    print "  ${D}           go_version, rust_version, java_version, package, os_icon...${N}"
    print "  ${M}  Line 2:${N} ${D}load, disk_usage, ram, swap, wifi${N}"
    print "  ${M}  Line 3:${N} ${D}battery, time, command_execution_time, vi_mode, custom_pid${N}"
    print "  ${B}${Y}THE DIR SEGMENT AND %~ EXPANSION${N}"
    print "  ${D}Zsh's %~ prompt expansion replaces known paths with named dirs.${N}"
    print "  ${D}If you ${M}hash -d ZPWR=/Users/you/.zpwr${D}, then /Users/you/.zpwr${N}"
    print "  ${D}shows as ${G}~ZPWR${D} in your prompt. Shorter. Cleaner. Professional.${N}"
    print "  ${D}POWERLEVEL9K_DIR_MAX_LENGTH=80 caps the dir segment width.${N}"
    print "  ${D}POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40 reserves typing space.${N}"
    print "  ${B}${Y}HOW zpwrBindDirs POPULATES NAMED DIRECTORIES${N}"
    print "  ${D}The function runs hash -d for ~20 directories:${N}"
    print "  ${M}  hash -d ZPWR=\"\$ZPWR\"${N}"
    print "  ${M}  hash -d ZPWR_TMUX=\"\$ZPWR_TMUX\"${N}"
    print "  ${M}  hash -d ZPWR_SCRIPTS=\"\$ZPWR_SCRIPTS\"${N}"
    print "  ${M}  hash -d TMUXH=\"\$TMUX_HOME\"${N}"
    print "  ${D}Then it writes them all to \$ZPWR_LOCAL/zpwr-hash-dirs.zsh${N}"
    print "  ${D}for instant prompt to use on next startup. The cache iterates${N}"
    print "  ${D}\${(kv)nameddirs} to capture every registered named directory.${N}"
    print "  ${B}${Y}THE MULTILINE FRAME${N}"
    print "  ${D}The prompt uses box-drawing characters for the frame:${N}"
    print "  ${M}  First line:  %244F-----  ${D}(top connector)${N}"
    print "  ${M}  Middle:      %244F-----  ${D}(mid connector)${N}"
    print "  ${M}  Last line:   %244F-----  ${D}(bottom connector)${N}"
    print "  ${D}Gap fill character is '---' in grey (color 244).${N}"
    print "  ${D}Mode: nerdfont-complete. Separators use Powerline glyphs.${N}"
    print "  ${B}${Y}prompt_char SYMBOLS${N}"
    print "  ${D}Insert mode: ${G}---${D}  Command mode: ${G}---${D}  Visual: ${G}V${D}  Overwrite: ${G}---${N}"
}
