PAGE_TITLE="Zsh Insert Mode: Ctrl-F & Ctrl-V Chords"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ZSH INSERT MODE: CTRL-F & CTRL-V CHORDS >>>${N}"
    print "  ${D}two-key combos that unlock the full zpwr arsenal.${N}"
    print ""
    print "  ${B}${Y}CTRL-F CHORDS (fzf & actions):${N}"
    print "  ${C}Ctrl-F Ctrl-D${N}         ${D}pipe buffer into fzf${N}"
    print "  ${C}Ctrl-F Ctrl-F${N}         ${D}cd + vim fzf file search (accept)${N}"
    print "  ${C}Ctrl-F Ctrl-G${N}         ${D}google search${N}"
    print "  ${C}Ctrl-F Ctrl-H${N}         ${D}lsof into fzf${N}"
    print "  ${C}Ctrl-F Ctrl-I${N}         ${D}ag (silver searcher) into fzf${N}"
    print "  ${C}Ctrl-F Ctrl-J${N}         ${D}zpwr verbs widget (accept)${N}"
    print "  ${C}Ctrl-F Ctrl-K${N}         ${D}alternate quotes around buffer${N}"
    print "  ${C}Ctrl-F Ctrl-L${N}         ${D}list choices${N}"
    print "  ${C}Ctrl-F Ctrl-M${N}         ${D}zzcomplete${N}"
    print "  ${C}Ctrl-F Ctrl-N${N}         ${D}zpwr verbs widget (browse)${N}"
    print "  ${C}Ctrl-F Ctrl-O${N}         ${D}open URL from buffer${N}"
    print "  ${C}Ctrl-F Ctrl-P${N}         ${D}basic sed substitution${N}"
    print "  ${C}Ctrl-F Ctrl-R${N}         ${D}wrap buffer as variable${N}"
    print "  ${C}Ctrl-F Ctrl-S${N}         ${D}git diff check (gacp)${N}"
    print "  ${C}Ctrl-F Ctrl-V${N}         ${D}edit command line in \$EDITOR${N}"
    print "  ${C}Ctrl-F j${N}              ${D}zpwr verbs widget (accept)${N}"
    print "  ${C}Ctrl-F n${N}              ${D}zpwr verbs widget (browse)${N}"
    print ""
    print "  ${B}${Y}CTRL-V CHORDS (vim/fzf/navigation):${N}"
    print "  ${C}Ctrl-V Ctrl-@${N}         ${D}vim fzf (open file in vim)${N}"
    print "  ${C}Ctrl-V Space${N}          ${D}vim fzf (open file in vim)${N}"
    print "  ${C}Ctrl-V Ctrl-F${N}         ${D}fasd fzf (frecency file open)${N}"
    print "  ${C}Ctrl-V Ctrl-G${N}         ${D}fzf cd widget${N}"
    print "  ${C}Ctrl-V Ctrl-K${N}         ${D}emacs fzf${N}"
    print "  ${C}Ctrl-V Ctrl-L${N}         ${D}z fzf (frecency dirs)${N}"
    print "  ${C}Ctrl-V Ctrl-N${N}         ${D}vim fzf sudo${N}"
    print "  ${C}Ctrl-V Ctrl-O${N}         ${D}fzf tab complete${N}"
    print "  ${C}Ctrl-V Ctrl-P${N}         ${D}sudo command line toggle${N}"
    print "  ${C}Ctrl-V Ctrl-R${N}         ${D}history search multi-word${N}"
    print "  ${C}Ctrl-V Ctrl-S${N}         ${D}z fzf (alternate)${N}"
    print "  ${C}Ctrl-V Ctrl-V${N}         ${D}vim all files widget (accept)${N}"
    print "  ${C}Ctrl-V Ctrl-Z${N}         ${D}fzf history widget${N}"
    print "  ${C}Ctrl-V ,${N}              ${D}fzf environment variables${N}"
    print "  ${C}Ctrl-V .${N}              ${D}fzf all keybindings${N}"
    print "  ${C}Ctrl-V //${N}             ${D}locate fzf${N}"
    print "  ${C}Ctrl-V /.${N}             ${D}locate fzf + edit${N}"
    print "  ${C}Ctrl-V ;${N}              ${D}fzf surround${N}"
    print "  ${C}Ctrl-V c${N}              ${D}fzf git commits${N}"
    print "  ${C}Ctrl-V k${N}              ${D}fzf vim keybindings${N}"
    print "  ${C}Ctrl-V m${N}              ${D}vim all files widget (browse)${N}"
    print "  ${C}Ctrl-V v${N}              ${D}vim all files widget (accept)${N}"
    print ""
    print "  ${D}Ctrl-F is the action chord: search, edit, google, diff.${N}"
    print "  ${D}Ctrl-V is the vim/fzf chord: open files, browse, navigate.${N}"
    print ""
    print "  ${M}  // chords are the wizard's combos${N}"
    print "  ${M}  // two keys unlock what single keys cannot reach${N}"
    print ""
}
