PAGE_TITLE="Flame Charts"
PAGE_CHAPTER="CHAPTER 6: PERFORMANCE CULT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FLAME CHARTS ===${N}"
    print ""
    print "  ${C}Bench tells you HOW LONG startup takes.${N}"
    print "  ${C}Flame tells you WHERE the time goes.${N}"
    print ""
    print "  ${B}${Y}THE FLAME VERB${N}"
    print "  ${M}  zpwr flame${N}"
    print "  ${D}  Generates a startup flame chart from zprof data.${N}"
    print "  ${D}  Shows you exactly which functions and files are${N}"
    print "  ${D}  consuming your startup time, in descending order.${N}"
    print ""
    print "  ${B}${Y}READING THE OUTPUT${N}"
    print "  ${C}  The flame chart shows a ranked list of functions:${N}"
    print "  ${D}  Each entry shows:${N}"
    print "  ${D}    - Function/file name${N}"
    print "  ${D}    - Time consumed (milliseconds)${N}"
    print "  ${D}    - Percentage of total startup time${N}"
    print ""
    print "  ${G}  The top of the list is where optimization effort${N}"
    print "  ${G}  pays off the most. If one function takes 40% of${N}"
    print "  ${G}  startup, that is your target.${N}"
    print ""
    print "  ${B}${Y}HOW ZPROF WORKS${N}"
    print "  ${C}  Zsh has a built-in profiler: ${M}zprof${C}.${N}"
    print "  ${C}  When enabled, it instruments every function call${N}"
    print "  ${C}  during shell init and records the wall-clock time.${N}"
    print "  ${C}  The flame verb wraps this into a readable report.${N}"
    print ""
    print "  ${B}${Y}COMMON HOTSPOTS${N}"
    print "  ${D}  What you will typically see at the top:${N}"
    print "  ${Y}  compinit${N}${D} ........... completion system init${N}"
    print "  ${Y}  compaudit${N}${D} .......... completion security check${N}"
    print "  ${Y}  compdump${N}${D} ........... writing completion cache${N}"
    print "  ${Y}  _zpwr_*${N}${D} ............ zpwr autoload functions${N}"
    print "  ${Y}  nvm/pyenv/rbenv${N}${D} .... version manager hooks${N}"
    print ""
    print "  ${B}${Y}OPTIMIZATION TIPS${N}"
    print "  ${G}  1. ${N}${D}If compinit is slow, run ${M}zpwr compile${D} to cache it${N}"
    print "  ${G}  2. ${N}${D}If a version manager dominates, lazy-load it${N}"
    print "  ${G}  3. ${N}${D}If an autoload is slow, check for disk I/O in it${N}"
    print "  ${G}  4. ${N}${D}If compaudit is slow, fix the directory permissions${N}"
    print "  ${G}  5. ${N}${D}After changes, run ${M}zpwr bench${D} to verify improvement${N}"
    print ""
    print "  ${B}${Y}THE OPTIMIZATION LOOP${N}"
    print "  ${M}  zpwr flame${N}${D}      # identify the bottleneck${N}"
    print "  ${D}  ... fix it ...${N}"
    print "  ${M}  zpwr bench${N}${D}      # measure the improvement${N}"
    print "  ${M}  zpwr flame${N}${D}      # find the next bottleneck${N}"
    print "  ${D}  Repeat until you hit diminishing returns.${N}"
    print ""
    print "  ${D}Flame charts turn gut feelings into data.${N}"
    print "  ${D}Stop guessing. Start profiling.${N}"
    print ""
}
