PAGE_TITLE="Cleanup Operations"
PAGE_CHAPTER="CHAPTER 9: THE JANITOR'S CLOSET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== CLEANUP OPERATIONS ===${N}"
    print "  ${D}// entropy is the enemy. the janitor is your friend. //${N}"
    print ""
    print "  ${C}Shell environments accumulate garbage like a hoarder's attic.${N}"
    print "  ${C}Cache files grow stale. Temp dirs fill up. Logs balloon.${N}"
    print "  ${C}These verbs are the Marie Kondo of your \$ZPWR.${N}"
    print ""
    print "  ${B}${Y}CLEANALL: THE THERMONUCLEAR BROOM${N}"
    print "  ${M}  zpwr cleanall${N}${D}                       # clean everything at once${N}"
    print ""
    print "  ${D}  Calls all the individual clean verbs in sequence.${N}"
    print "  ${D}  This is the \"I do not know what is wrong but I want${N}"
    print "  ${D}  a fresh start\" button. Safe but thorough.${N}"
    print ""
    print "  ${B}${Y}INDIVIDUAL CLEAN VERBS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print ""
    print "  ${G}CLEANCACHE${N}"
    print "  ${M}  zpwr cleancache${N}${D}                     # clear general caches${N}"
    print "  ${D}  Wipes cached data that zpwr generates during operation.${N}"
    print "  ${D}  Safe to run any time. Everything rebuilds on demand.${N}"
    print ""
    print "  ${G}CLEANCOMPCACHE${N}"
    print "  ${M}  zpwr cleancompcache${N}${D}                 # clear completion cache${N}"
    print "  ${D}  Removes the zsh completion cache directory.${N}"
    print "  ${D}  Run this when tab completions are showing stale results${N}"
    print "  ${D}  or when a new command does not appear in completions.${N}"
    print "  ${D}  Follow up with ${M}zpwr regenzsh${D} to rebuild zcompdump.${N}"
    print ""
    print "  ${G}CLEANDIRS${N}"
    print "  ${M}  zpwr cleandirs${N}${D}                      # clear cached dir listings${N}"
    print "  ${D}  Removes directory cache files used by navigation commands.${N}"
    print "  ${D}  If directory completions point to dirs that no longer exist,${N}"
    print "  ${D}  this verb fixes that.${N}"
    print ""
    print "  ${G}CLEANTEMP${N}"
    print "  ${M}  zpwr cleantemp${N}${D}                      # clear temp files${N}"
    print "  ${D}  Removes temporary files zpwr created during operation.${N}"
    print "  ${D}  These are transient by nature -- safe to nuke.${N}"
    print ""
    print "  ${G}CLEANDIRSANDTEMP${N}"
    print "  ${M}  zpwr cleandirsandtemp${N}${D}               # dirs + temp combined${N}"
    print "  ${D}  Convenience combo of cleandirs and cleantemp.${N}"
    print ""
    print "  ${G}CLEANLOG${N}"
    print "  ${M}  zpwr cleanlog${N}${D}                       # truncate log files${N}"
    print "  ${D}  The zpwr logfile grows forever if you never clean it.${N}"
    print "  ${D}  This verb truncates or removes old log entries.${N}"
    print "  ${D}  Check log size: ${M}ls -lh \$ZPWR_LOGFILE${N}"
    print ""
    print "  ${B}${Y}THE CLEAN WORKFLOW${N}"
    print "  ${D}  Light cleanup (weekly):${N}"
    print "  ${M}    zpwr cleantemp && zpwr cleanlog${N}"
    print ""
    print "  ${D}  Medium cleanup (monthly):${N}"
    print "  ${M}    zpwr cleancache && zpwr cleancompcache && zpwr regenzsh${N}"
    print ""
    print "  ${D}  Full cleanup (when things feel sluggish):${N}"
    print "  ${M}    zpwr cleanall${N}"
    print ""
    print "  ${D}  None of these delete your configuration or history.${N}"
    print "  ${D}  They only remove regenerable cache and temp data.${N}"
    print ""
}
