PAGE_TITLE="Fortune Cookies"
PAGE_CHAPTER="CHAPTER 22: CREATIVE TOOLS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FORTUNE COOKIES ===${N}"
    print "  ${D}// wisdom from the digital underground //${N}"
    print ""
    print "  ${C}zpwr fortune displays a random hacker quote rendered in a${N}"
    print "  ${C}random figlet font with neon colors. 40 curated quotes from${N}"
    print "  ${C}legends and original ZPWR wisdom.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr fortune${N}${D}                # random quote, random font${N}"
    print "  ${M}  zpwr fortune -p${N}${D}             # plain text with box frame${N}"
    print "  ${M}  zpwr fortune -f doom${N}${D}        # force doom font${N}"
    print "  ${M}  zpwr wisdom${N}${D}                 # alias${N}"
    print "  ${M}  zpwr quote${N}${D}                  # alias${N}"
    print ""
    print "  ${B}${Y}THE QUOTES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  Linus Torvalds${N}${D}    \"Talk is cheap. Show me the code.\"${N}"
    print "  ${G}  Brian Kernighan${N}${D}   \"Controlling complexity is the essence...\"${N}"
    print "  ${G}  Grace Hopper${N}${D}      \"The most dangerous phrase is...\"${N}"
    print "  ${G}  ZPWR${N}${D}              \"Home is where the .zshrc is.\"${N}"
    print "  ${G}  MenkeTechnologies${N}${D}  \"Aliases are love letters to your future self.\"${N}"
    print "  ${D}  ...and 35 more.${N}"
    print ""
    print "  ${B}${Y}THE FONTS${N}"
    print "  ${D}  Randomly selected from: cyberlarge, cybermedium, doom,${N}"
    print "  ${D}  slant, speed, banner, standard. Each quote picks a${N}"
    print "  ${D}  keyword for large figlet rendering, full quote below.${N}"
    print ""
    print "  ${B}${Y}USE CASES${N}"
    print "  ${D}  - Add to .zshrc for a fortune on every new shell${N}"
    print "  ${D}  - Pipe to lolcat: ${M}zpwr fortune -p | lolcat${N}"
    print "  ${D}  - Use as a tmux status-right: too slow, but fun to try${N}"
    print ""
}
