PAGE_TITLE="The Plugin Ecosystem"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE PLUGIN ECOSYSTEM ===${N}"
    print "  ${D}// 30+ custom plugins from MenkeTechnologies //${N}"
    print ""
    print "  ${C}ZPWR loads approximately 95 plugins via zinit. Over 30 are${N}"
    print "  ${C}custom MenkeTechnologies creations that extend zpwr with${N}"
    print "  ${C}additional verbs, aliases, completions, and integrations.${N}"
    print ""
    print "  ${B}${Y}KEY PLUGINS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  zsh-learn${N}${D}              60 verbs, MySQL learning DB${N}"
    print "  ${G}  zsh-git-repo-cache${N}${D}    20 verbs, filesystem repo index${N}"
    print "  ${G}  fzf-zsh-plugin${N}${D}        14 verbs, brew/chrome fzf${N}"
    print "  ${G}  zsh-git-acp${N}${D}           318 aliases, git workflows${N}"
    print "  ${G}  zsh-docker-aliases${N}${D}    148 aliases, Docker shortcuts${N}"
    print "  ${G}  zsh-openshift-aliases${N}${D} 106 aliases, OpenShift${N}"
    print "  ${G}  zsh-expand${N}${D}            spell correct, abbreviation expand${N}"
    print "  ${G}  zsh-more-completions${N}${D}  14,100+ tab completions${N}"
    print "  ${G}  zsh-cargo-completion${N}${D}  32 Rust/Cargo aliases${N}"
    print "  ${G}  zsh-travis${N}${D}            8 functions, CI integration${N}"
    print "  ${G}  zsh-nginx${N}${D}             nginx management${N}"
    print "  ${G}  forgit${N}${D}                fzf-powered git (add, diff, log)${N}"
    print "  ${G}  zsh-z${N}${D}                 frecency directory jumping${N}"
    print "  ${G}  fzf-tab${N}${D}               fzf-powered tab completion${N}"
    print "  ${G}  zconvey${N}${D}               cross-session communication${N}"
    print ""
    print "  ${B}${Y}CONDITIONAL LOADING${N}"
    print "  ${D}  Plugins for docker, dotnet, kubectl, ngrok, rails, and${N}"
    print "  ${D}  systemctl only load if those commands exist. No bloat${N}"
    print "  ${D}  on machines without those tools.${N}"
    print ""
    print "  ${B}${Y}DEFERRED LOADING${N}"
    print "  ${D}  All plugins load with zinit wait'' ice — deferred after${N}"
    print "  ${D}  the prompt appears. Only powerlevel10k loads synchronously${N}"
    print "  ${D}  for instant prompt.${N}"
    print ""
}
