PAGE_TITLE="P10k Prompt Customization"
PAGE_CHAPTER="CHAPTER 26: POWERLEVEL10K & INSTANT PROMPT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== P10K PROMPT CUSTOMIZATION ===${N}"
    print "  ${D}// your prompt is a canvas. paint it with ANSI and Unicode. //${N}"
    print "  ${C}ZPWR ships custom p10k segments beyond the defaults.${N}"
    print "  ${C}These are defined with POWERLEVEL9K_CUSTOM_* variables${N}"
    print "  ${C}in \$ZPWR_ENV/.p10k.zsh.${N}"
    print "  ${B}${Y}CUSTOM SEGMENTS${N}"
    print "  ${G}  custom_tty${N}${D}       Shows \$ZPWR_TTY (e.g. /dev/ttys003)${N}"
    print "  ${D}  Defined as:${N}"
    print "  ${M}  POWERLEVEL9K_CUSTOM_TTY='echo \"%K{blue}%F{white} \$ZPWR_TTY %f%k%F{blue}%f\"'${N}"
    print "  ${G}  custom_env${N}${D}       Environment info (custom shell, OS, etc.)${N}"
    print "  ${G}  custom_env_bat${N}${D}   Shows bat (syntax highlighter) version/status${N}"
    print "  ${G}  custom_env_editor${N}${D} Shows \$EDITOR${N}"
    print "  ${G}  custom_env_term${N}${D}  Shows \$TERM_PROGRAM${N}"
    print "  ${G}  custom_pid${N}${D}       Shows shell PID (right prompt, bottom line)${N}"
    print "  ${B}${Y}ADDING YOUR OWN SEGMENT${N}"
    print "  ${D}1. Define the command that generates output:${N}"
    print "  ${M}  typeset -g POWERLEVEL9K_CUSTOM_MYWIDGET='echo \"hello\"'${N}"
    print "  ${D}2. Set colors:${N}"
    print "  ${M}  typeset -g POWERLEVEL9K_CUSTOM_MYWIDGET_FOREGROUND=255${N}"
    print "  ${M}  typeset -g POWERLEVEL9K_CUSTOM_MYWIDGET_BACKGROUND=24${N}"
    print "  ${D}3. Add 'custom_mywidget' to LEFT or RIGHT PROMPT_ELEMENTS array.${N}"
    print "  ${D}4. Run ${M}p10k reload${D} or ${M}source \$ZPWR_ENV/.p10k.zsh${D} to apply.${N}"
    print "  ${B}${Y}COLORS AND ICONS${N}"
    print "  ${D}p10k uses 256-color indices. Print the color map:${N}"
    print "  ${M}  for i in {0..255}; do print -Pn \"%K{\$i}  %k%F{\$i}\${(l:3::0:)i}%f \"; done${N}"
    print "  ${D}Foreground/background for each segment and state:${N}"
    print "  ${M}  POWERLEVEL9K_DIR_BACKGROUND=4${N}${D}        (blue)${N}"
    print "  ${M}  POWERLEVEL9K_DIR_FOREGROUND=254${N}${D}      (near-white)${N}"
    print "  ${D}Anchor dirs (like .git roots) get bold + brighter color (255).${N}"
    print "  ${B}${Y}TRUNCATION${N}"
    print "  ${D}POWERLEVEL9K_DIR_MAX_LENGTH=80 caps directory width.${N}"
    print "  ${D}POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50 means at least${N}"
    print "  ${D}half the terminal width is reserved for your command input.${N}"
    print "  ${D}SHORTEN_STRATEGY can be set to truncate_to_unique for smart${N}"
    print "  ${D}shortening (commented out by default in zpwr).${N}"
    print "  ${B}${Y}THE .p10k.zsh FILE STRUCTURE${N}"
    print "  ${D}The file is a single anonymous function () { ... } that:${N}"
    print "  ${D}  - Unsets all POWERLEVEL9K_* vars (clean slate)${N}"
    print "  ${D}  - Defines LEFT/RIGHT_PROMPT_ELEMENTS arrays${N}"
    print "  ${D}  - Sets mode, icons, colors, truncation per segment${N}"
    print "  ${D}  - Configures transient prompt, instant prompt, hot reload${N}"
    print "  ${B}${Y}SEEING PROMPT TIMING${N}"
    print "  ${M}  zpwr environmentcounts${N}"
    print "  ${D}Shows promptTimeMs, startupTimeMs, and per-phase timestamps.${N}"
    print "  ${D}This is how you prove your prompt loaded in 0.015 seconds.${N}"
}
