PAGE_TITLE="Alias Cheat Sheet"
PAGE_CHAPTER="CHAPTER 24: TIPS, TRICKS & EASTER EGGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== ALIAS CHEAT SHEET ===${N}"
    print "  ${D}// the short names you will actually use //${N}"
    print ""
    print "  ${C}Many zpwr verbs have short aliases. These are the ones${N}"
    print "  ${C}worth memorizing — one or two keystrokes that replace${N}"
    print "  ${C}entire workflows.${N}"
    print ""
    print "  ${B}${Y}DIAGNOSTICS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr doc${N}${D}          = doctor       ${M}zpwr zprof${N}${D}      = startup${N}"
    print "  ${M}  zpwr check${N}${D}        = lint         ${M}zpwr audit${N}${D}      = pathaudit${N}"
    print "  ${M}  zpwr cruft${N}${D}        = stale        ${M}zpwr rank${N}${D}       = funcrank${N}"
    print "  ${M}  zpwr benchmark${N}${D}    = bench        ${M}zpwr dashboard${N}${D}  = top${N}"
    print "  ${M}  zpwr heatmap${N}${D}      = flame        ${M}zpwr instrument${N}${D} = trace${N}"
    print ""
    print "  ${B}${Y}MONITORING${N}"
    print "  ${M}  zpwr snap${N}${D}         = snapshot     ${M}zpwr load${N}${D}       = restore${N}"
    print "  ${M}  zpwr rerun${N}${D}        = replay       ${M}zpwr onchange${N}${D}   = watch${N}"
    print "  ${M}  zpwr book${N}${D}         = study${N}"
    print ""
    print "  ${B}${Y}CREATIVE${N}"
    print "  ${M}  zpwr rain${N}${D}         = matrix       ${M}zpwr wisdom${N}${D}     = fortune${N}"
    print "  ${M}  zpwr quote${N}${D}        = fortune      ${M}zpwr screensaver${N}${D}= matrix${N}"
    print ""
    print "  ${B}${Y}GIT${N}"
    print "  ${M}  zpwr who${N}${D}          = gitwho       ${M}zpwr gitcontribs${N}${D}= gitwho${N}"
    print ""
    print "  ${B}${Y}INTROSPECTION${N}"
    print "  ${M}  zpwr which${N}${D}        = resolve      ${M}zpwr whatis${N}${D}     = resolve${N}"
    print "  ${M}  zpwr today${N}${D}        = timeline     ${M}zpwr activity${N}${D}   = timeline${N}"
    print ""
    print "  ${B}${Y}LOGGING${N}"
    print "  ${M}  zpwr logs${N}${D}         = taillog${N}"
    print ""
}
