PAGE_TITLE="Plugin System"
PAGE_CHAPTER="CHAPTER 21: ZPWR ENVIRONMENT VARIABLES"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< PLUGIN SYSTEM — THE TURBO LOADER >>>${N}"
    print "  ${D}zinit: loading plugins at the speed of light${N}"
    print ""
    print "  ${C}ZPWR uses zinit (formerly zplugin) as its plugin${N}"
    print "  ${C}manager. But not the basic way. The turbo way.${N}"
    print "  ${C}Plugins load asynchronously after prompt appears.${N}"
    print "  ${C}You see your prompt instantly. Plugins catch up.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_PLUGIN_MANAGER — CHOOSE YOUR LOADER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_PLUGIN_MANAGER${N}${D}   # zinit${N}"
    print "  ${G}Controls which plugin manager ZPWR uses. The default${N}"
    print "  ${G}and recommended value is ${M}zinit${G}. Other managers exist${N}"
    print "  ${G}but zinit's turbo mode is what makes ZPWR fast.${N}"
    print ""
    print "  ${B}${Y}TURBO LOADING EXPLAINED:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  Normal plugin loading:${N}"
    print "  ${D}    source plugin1.zsh  # blocks${N}"
    print "  ${D}    source plugin2.zsh  # blocks${N}"
    print "  ${D}    source plugin3.zsh  # blocks${N}"
    print "  ${D}    # prompt finally appears after ALL plugins load${N}"
    print ""
    print "  ${C}  Zinit turbo loading:${N}"
    print "  ${G}    prompt appears immediately${N}"
    print "  ${G}    plugin1 loads in background ... done${N}"
    print "  ${G}    plugin2 loads in background ... done${N}"
    print "  ${G}    plugin3 loads in background ... done${N}"
    print "  ${G}    # user never notices the delay${N}"
    print ""
    print "  ${B}${Y}PLUGIN INSPECTION:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr zshplugincount${N}${D}     count loaded zsh plugins${N}"
    print "  ${M}  zpwr zshpluginlist${N}${D}      list all loaded zsh plugins${N}"
    print "  ${M}  zpwr vimplugincount${N}${D}     count vim plugins${N}"
    print "  ${M}  zpwr vimpluginlist${N}${D}      list all vim plugins${N}"
    print "  ${M}  zpwr emacsplugincount${N}${D}   count emacs plugins${N}"
    print "  ${M}  zpwr emacspluginlist${N}${D}    list all emacs plugins${N}"
    print ""
    print "  ${B}${Y}UPDATE AND MAINTAIN:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr updatezinit${N}${D}        update zinit itself${N}"
    print "  ${M}  zpwr updatedeps${N}${D}          update all plugin deps${N}"
    print "  ${M}  zpwr plugins${N}${D}             plugin information${N}"
    print ""
    print "  ${D}  // plugins are not bloat. they are force multipliers.${N}"
    print "  ${D}  // but only if they load in zero perceived time.${N}"
    print "  ${D}  // turbo mode makes 50 plugins feel like zero.${N}"
    print ""
}
