PAGE_TITLE="Named Directories"
PAGE_CHAPTER="CHAPTER 2: NAVIGATION PROTOCOL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== NAMED DIRECTORIES ===${N}"
    print ""
    print "  ${C}Zsh has a secret weapon most people never learn:${N}"
    print "  ${C}named directories. They turn env vars into tilde paths.${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${G}When you do ${M}hash -d ZPWR=\$ZPWR${G}, zsh registers a${N}"
    print "  ${G}named directory. Now ${M}~ZPWR${G} expands to \$ZPWR everywhere:${N}"
    print "  ${G}in cd, in tab completion, in prompt, in arguments.${N}"
    print ""
    print "  ${B}${Y}ZPWR'S NAMED DIRECTORIES${N}"
    print "  ${M}  ~ZPWR${N}${D} ................. \$ZPWR root${N}"
    print "  ${M}  ~ZPWR_SCRIPTS${N}${D} ........ \$ZPWR_SCRIPTS${N}"
    print "  ${M}  ~ZPWR_AUTOLOAD${N}${D} ....... \$ZPWR_AUTOLOAD${N}"
    print "  ${M}  ~ZPWR_ENV${N}${D} ............ \$ZPWR_ENV${N}"
    print "  ${M}  ~ZPWR_LOCAL${N}${D} .......... \$ZPWR_LOCAL${N}"
    print "  ${M}  ~ZPWR_INSTALL${N}${D} ........ \$ZPWR_INSTALL${N}"
    print "  ${M}  ~ZPWR_TMUX${N}${D} ........... \$ZPWR_TMUX${N}"
    print "  ${M}  ~ZPWR_TEST${N}${D} ........... \$ZPWR_TEST${N}"
    print "  ${M}  ~ZPWR_COMPS${N}${D} .......... \$ZPWR_COMPS${N}"
    print ""
    print "  ${B}${Y}WHAT THIS MEANS IN PRACTICE${N}"
    print "  ${C}  Your prompt might show:${N}"
    print "  ${G}    ~ZPWR_AUTOLOAD/common${N}${D}  instead of the full path${N}"
    print "  ${C}  You can type:${N}"
    print "  ${M}    cd ~ZPWR_SCRIPTS${N}${D}  and it just works${N}"
    print "  ${M}    vim ~ZPWR_ENV/.zpwr_env.sh${N}${D}  tilde paths everywhere${N}"
    print ""
    print "  ${B}${Y}TAB COMPLETION WITH TILDE${N}"
    print "  ${C}  Type ${M}cd ~ZPWR<tab>${C} and watch zsh expand the options:${N}"
    print "  ${D}    ~ZPWR  ~ZPWR_SCRIPTS  ~ZPWR_ENV  ~ZPWR_LOCAL ...${N}"
    print "  ${D}  This works in any command, not just cd.${N}"
    print ""
    print "  ${B}${Y}THE MECHANISM${N}"
    print "  ${C}  Zsh option ${M}AUTO_NAME_DIRS${C} turns any exported scalar${N}"
    print "  ${C}  parameter into a named directory automatically.${N}"
    print "  ${C}  ZPWR exports its directory variables, so they become${N}"
    print "  ${C}  named directories for free.${N}"
    print ""
    print "  ${D}Think of named directories as human-readable symlinks${N}"
    print "  ${D}that live in your shell's brain instead of the filesystem.${N}"
    print "  ${D}No files created. No cleanup needed. Pure memory.${N}"
    print ""
}
