PAGE_TITLE="Forgit Log & Stash"
PAGE_CHAPTER="CHAPTER 20: FORGIT DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< FORGIT LOG & STASH — VISUAL HISTORY >>>${N}"
    print "  ${D}time travel with a preview window${N}"
    print ""
    print "  ${C}Git log is a river of hashes. Git stash is a pile of${N}"
    print "  ${C}forgotten context. Forgit turns both into something${N}"
    print "  ${C}you can actually navigate without losing your mind.${N}"
    print ""
    print "  ${B}${Y}FORGITLOG — THE COMMIT BROWSER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitlog${N}"
    print "  ${G}Opens your git history in fzf with commit previews.${N}"
    print "  ${G}Each commit shows its full diff in the preview pane.${N}"
    print "  ${G}Search commits by message, author, or hash.${N}"
    print ""
    print "  ${D}  What you see:${N}"
    print "  ${C}  Left pane:  ${N}${D}commit graph with short messages${N}"
    print "  ${C}  Right pane: ${N}${D}full diff of highlighted commit${N}"
    print "  ${C}  Search:     ${N}${D}fuzzy match on any commit field${N}"
    print ""
    print "  ${D}  \"Who wrote this garbage?\" — you, using forgitlog,${N}"
    print "  ${D}  discovering it was also you, three months ago.${N}"
    print ""
    print "  ${B}${Y}FORGITSTASH — THE STASH MANAGER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitstash${N}"
    print "  ${G}Browse your stash entries with preview diffs.${N}"
    print "  ${G}See what is in each stash before applying it.${N}"
    print "  ${G}No more ${Y}git stash pop${G} roulette.${N}"
    print ""
    print "  ${D}  The old way:${N}"
    print "  ${R}  git stash list${N}${D}              # cryptic one-liners${N}"
    print "  ${R}  git stash show -p stash@{2}${N}${D}  # which one was it again?${N}"
    print "  ${R}  git stash pop${N}${D}               # pray${N}"
    print ""
    print "  ${D}  The forgit way:${N}"
    print "  ${M}  zpwr forgitstash${N}${D}            # browse, preview, apply${N}"
    print ""
    print "  ${B}${G}LOG + STASH TOGETHER:${N}"
    print "  ${C}These two verbs give you eyes into the past.${N}"
    print "  ${C}forgitlog shows committed history. forgitstash shows${N}"
    print "  ${C}uncommitted history. Between them, nothing is lost.${N}"
    print ""
    print "  ${D}  // the commit graph is not a wall of text${N}"
    print "  ${D}  // it is a timeline. forgit lets you walk it.${N}"
    print "  ${D}  // stashes are not forgotten. they are filed.${N}"
    print ""
}
