PAGE_TITLE="Vim Sessions & Workflow"
PAGE_CHAPTER="CHAPTER 31: VIM DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== VIM SESSIONS & WORKFLOW ===${N}"
    print "  ${D}// your vim state, frozen in amber. thaw it when you need it. //${N}"
    print "  ${C}Vim sessions save your entire editing state: open buffers,${N}"
    print "  ${C}window layouts, cursor positions. ZPWR integrates sessions${N}"
    print "  ${C}with tmux for a seamless development environment.${N}"
    print "  ${B}${Y}VIM SESSION MANAGEMENT${N}"
    print "  ${D}ZPWR configures vim sessions as manual-save only:${N}"
    print "  ${M}  let g:session_autosave = 'no'${N}"
    print "  ${M}  let g:session_autoload = 'no'${N}"
    print "  ${D}No surprises. Sessions save when you tell them to.${N}"
    print "  ${D}Save: ${M}Ctrl-D q${D} (mapped to :SaveSession! in normal/insert mode).${N}"
    print "  ${B}${Y}CONFIG SESSIONS: vrc, brc, zrc, trc${N}"
    print "  ${D}ZPWR defines verbs for editing its own config files:${N}"
    print "  ${G}  vrc${N}${D}   Open .vimrc in vim${N}"
    print "  ${G}  brc${N}${D}   Open shell aliases file (.zpwr_alias.sh)${N}"
    print "  ${G}  zrc${N}${D}   Open .zshrc in vim${N}"
    print "  ${G}  trc${N}${D}   Open tmux.conf in vim${N}"
    print "  ${D}The tmux layout script config-files.conf opens all four${N}"
    print "  ${D}in a 4-pane arrangement. Prefix+T triggers it.${N}"
    print "  ${D}Each pane runs one of these verbs automatically.${N}"
    print "  ${B}${Y}THE AUXILIARY VIM PLUGINS${N}"
    print "  ${G}  vim-autotag${N}${D}           Auto-regenerate ctags on save${N}"
    print "  ${M}    Plugin 'craigemery/vim-autotag'${N}"
    print "  ${D}    g:autotagStartMethod='fork' -- non-blocking tag generation.${N}"
    print "  ${G}  vim-online-thesaurus${N}${D}   Look up synonyms (visual mode \\K)${N}"
    print "  ${M}    Plugin 'beloglazov/vim-online-thesaurus'${N}"
    print "  ${G}  vim-zsh-completion${N}${D}     Zsh syntax completion in vim${N}"
    print "  ${M}    Plugin 'Valodim/vim-zsh-completion'${N}"
    print "  ${G}  vim-minimap${N}${D}            Sublime-style code minimap${N}"
    print "  ${M}    Plugin 'severin-lemaignan/vim-minimap'${N}"
    print "  ${B}${Y}THE zpwr snapshot/restore INTEGRATION${N}"
    print "  ${D}ZPWR has verbs for full environment snapshots:${N}"
    print "  ${M}  zpwr snapshot${N}${D}    Capture terminal environment state${N}"
    print "  ${M}  zpwr restore${N}${D}     Restore from snapshot${N}"
    print "  ${D}zpwrRestore rebuilds shell state: directory stack, aliases,${N}"
    print "  ${D}parameters, and more. This complements tmux-resurrect:${N}"
    print "  ${D}resurrect restores the tmux layout, snapshot/restore${N}"
    print "  ${D}restores the shell state within each pane.${N}"
    print "  ${B}${Y}THE FULL ZPWR VIM WORKFLOW${N}"
    print "  ${D}1. Open a tmux session with your project layout${N}"
    print "  ${D}2. Vim in left pane, shell in right pane${N}"
    print "  ${D}3. Edit code in vim, Ctrl-V to execute in right pane${N}"
    print "  ${D}4. Visual select + leader-vl to paste into a REPL${N}"
    print "  ${D}5. tmux-complete.vim grabs words from the REPL output${N}"
    print "  ${D}6. Auto-save means you never lose work${N}"
    print "  ${D}7. Prefix+Ctrl-s saves the entire tmux state${N}"
    print "  ${D}This is not an IDE. This is a weapon system.${N}"
}
