PAGE_TITLE="Tmux Prefix Keys: Navigation & Panes"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< TMUX PREFIX KEYS: NAVIGATION & PANES >>>${N}"
    print "  ${D}pane traversal, splitting, resizing. the grid of power.${N}"
    print ""
    print "  ${B}${Y}PANE SELECTION (hjkl repeatable):${N}"
    print "  ${C}prefix h${N}              ${D}select pane left${N}"
    print "  ${C}prefix j${N}              ${D}select pane down${N}"
    print "  ${C}prefix k${N}              ${D}select pane up${N}"
    print "  ${C}prefix l${N}              ${D}select pane right${N}"
    print "  ${C}prefix ;${N}              ${D}last-pane (toggle to previous)${N}"
    print "  ${C}prefix o${N}              ${D}select next pane in order${N}"
    print "  ${C}prefix q${N}              ${D}display-panes (5s timeout)${N}"
    print ""
    print "  ${B}${Y}PANE RESIZE (HJKL repeatable, 5 cells):${N}"
    print "  ${C}prefix H${N}              ${D}resize pane left 5${N}"
    print "  ${C}prefix J${N}              ${D}resize pane down 5${N}"
    print "  ${C}prefix K${N}              ${D}resize pane up 5${N}"
    print "  ${C}prefix L${N}              ${D}resize pane right 5${N}"
    print "  ${C}prefix Ctrl-Up/Down${N}   ${D}resize pane by 1${N}"
    print "  ${C}prefix Alt-Up/Down${N}    ${D}resize pane by 5${N}"
    print ""
    print "  ${B}${Y}PANE SPLITTING:${N}"
    print "  ${C}prefix -${N}              ${D}split vertical (same dir)${N}"
    print "  ${C}prefix \\\\${N}              ${D}split horizontal (same dir)${N}"
    print "  ${C}prefix \"${N}              ${D}split vertical (default dir)${N}"
    print "  ${C}prefix %${N}              ${D}split horizontal (default dir)${N}"
    print "  ${C}prefix |${N}              ${D}split horizontal${N}"
    print "  ${C}prefix _${N}              ${D}split vertical${N}"
    print ""
    print "  ${B}${Y}PANE OPERATIONS:${N}"
    print "  ${C}prefix z${N}              ${D}zoom/unzoom current pane${N}"
    print "  ${C}prefix !${N}              ${D}break pane into own window${N}"
    print "  ${C}prefix x${N}              ${D}kill current pane${N}"
    print "  ${C}prefix m${N}              ${D}mark current pane${N}"
    print "  ${C}prefix +${N}              ${D}split vertical then close prev pane${N}"
    print "  ${C}prefix Y${N}              ${D}split vertical then close prev pane${N}"
    print "  ${C}prefix {${N}              ${D}rotate window${N}"
    print "  ${C}prefix }${N}              ${D}swap pane down${N}"
    print ""
    print "  ${B}${Y}ARROW KEY SELECTION:${N}"
    print "  ${C}prefix Up/Down${N}        ${D}select pane up/down${N}"
    print "  ${C}prefix Left/Right${N}     ${D}select pane left/right${N}"
    print "  ${C}Alt-Up/Down${N}           ${D}select pane (root table, no prefix)${N}"
    print "  ${C}Alt-Left/Right${N}        ${D}select pane (root table, no prefix)${N}"
    print ""
    print "  ${D}All hjkl/HJKL bindings are repeatable (-r flag).${N}"
    print "  ${D}Arrow keys in root table work without prefix for speed.${N}"
    print ""
    print "  ${M}  // the wizard navigates panes by instinct${N}"
    print "  ${M}  // hjkl is muscle memory, arrows are for civilians${N}"
    print ""
}
