PAGE_TITLE="Git Add-Commit-Push"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT ADD-COMMIT-PUSH ===${N}"
    print "  ${D}// 318 aliases for the git power user //${N}"
    print ""
    print "  ${C}The zsh-git-acp plugin provides 318 aliases that collapse${N}"
    print "  ${C}multi-step git workflows into single commands.${N}"
    print ""
    print "  ${B}${Y}THE GACP PATTERN${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  gacp \"message\"${N}${D}              # git add -A, commit, push${N}"
    print "  ${M}  gac \"message\"${N}${D}               # git add -A, commit (no push)${N}"
    print "  ${M}  gcp${N}${D}                          # git commit, push${N}"
    print ""
    print "  ${B}${Y}BRANCH SHORTCUTS${N}"
    print "  ${M}  gcm${N}${D}                          # git checkout main${N}"
    print "  ${M}  gcb <branch>${N}${D}                 # git checkout -b <branch>${N}"
    print "  ${M}  gbd <branch>${N}${D}                 # git branch -d <branch>${N}"
    print ""
    print "  ${B}${Y}ZPWR INTEGRATION${N}"
    print "  ${M}  zpwr gitcommit \"msg\"${N}${D}        # commit and push with message${N}"
    print "  ${M}  zpwr gitcommitcount${N}${D}          # count commits in current repo${N}"
    print ""
    print "  ${D}  The full alias list is enormous — 318 combinations of${N}"
    print "  ${D}  git operations compressed into 2-4 character shortcuts.${N}"
    print "  ${D}  Most follow the pattern: g + operation letter(s).${N}"
    print ""
    print "  ${D}  Plugin: ${C}MenkeTechnologies/zsh-git-acp${N}"
    print ""
}
