PAGE_TITLE="Ponysay, Lolcat & ASCII Art"
PAGE_CHAPTER="CHAPTER 42: COLORIZATION STACK"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== PONYSAY, LOLCAT & ASCII ART ===${N}"
    print "  ${D}enterprise-grade cartoon horse infrastructure${N}"
    print "  ${B}${Y}THE ASCII ART TOOLCHAIN${N}"
    print "  ${G}  ponysay${N}${D}    My Little Pony ASCII art (cowsay but fabulous)${N}"
    print "  ${G}  lolcat${N}${D}     rainbow gradient text output${N}"
    print "  ${G}  figlet${N}${D}     large ASCII text banners from font files${N}"
    print "  ${G}  cowsay${N}${D}     classic ASCII art speech bubbles${N}"
    print "  ${G}  toilet${N}${D}     another ASCII art text renderer${N}"
    print "  ${D}  zpwr combines all of these for its startup banner.${N}"
    print "  ${B}${Y}ZPWR BANNER VERBS${N}"
    print "  ${G}  zpwr bannerpony${N}${D}      hostname banner with ponysay${N}"
    print "  ${G}  zpwr bannerlolcat${N}${D}    ponysay + lolcat rainbow gradient${N}"
    print "  ${G}  zpwr bannernopony${N}${D}    banner without ponysay${N}"
    print "  ${G}  zpwr figletfonts${N}${D}     preview all installed figlet fonts${N}"
    print "  ${D}  Each verb calls a different autoloaded function:${N}"
    print "  ${M}  zpwrPonyBanner, zpwrBannerLolcat, zpwrNoPonyBanner${N}"
    print "  ${B}${Y}THE STARTUP BANNER${N}"
    print "  ${D}  On shell startup, zpwrDarwinBanner / zpwrLinuxBanner fires.${N}"
    print "  ${D}  It picks a ${G}random figlet font${N}${D} each time via:${N}"
    print "  ${M}  \$ZPWR_SCRIPTS/macOnly/figletRandomFontOnce.sh${N}"
    print "  ${D}  ZPWR_BANNER_TYPE controls pony vs no-pony:${N}"
    print "  ${G}    ponies${N}${D}  -> zpwrBannerLolcat (rainbow horse)${N}"
    print "  ${G}    other${N}${D}   -> zpwrNoPonyBanner (figlet only)${N}"
    print "  ${B}${Y}BANNER CONTROL${N}"
    print "  ${G}  ZPWR_BANNER_CLEARLIST${N}${D}  controls startup banner + ls display${N}"
    print "  ${D}  When true: clear screen, show banner, then zpwrListNoClear.${N}"
    print "  ${D}  When false: skip the banner entirely (fast startup).${N}"
    print "  ${B}${Y}FONT LOGGING${N}"
    print "  ${D}  The random figlet font name is logged to:${N}"
    print "  ${M}  \$ZPWR_LOGFILE${N}"
    print "  ${D}  Want to know which font made that gorgeous banner?${N}"
    print "  ${G}  zpwr taillog${N}${D}  and look for the font name.${N}"
    print "  ${D}  Found one you love? Set it permanently in your config.${N}"
    print "  ${B}${R}REALITY CHECK:${N} ${D}A rainbow pony greeting you on every${N}"
    print "  ${D}  terminal open is either peak engineering or peak insanity.${N}"
    print "  ${D}  zpwr does not distinguish between the two.${N}"
    print "  ${D}  Your hostname, rendered in ASCII art, by a cartoon horse.${N}"
    print "  ${D}  This is what unlimited power looks like.${N}"
}
