PAGE_TITLE="Log Surveillance"
PAGE_CHAPTER="CHAPTER 11: MONITORING & AUTOMATION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== LOG SURVEILLANCE ===${N}"
    print "  ${D}// watching logs in glorious technicolor. the ccze way. //${N}"
    print ""
    print "  ${C}zpwr logs everything: startup, errors, plugin loads, debug${N}"
    print "  ${C}messages. The ${M}taillog${C} verb tails these logs with optional${N}"
    print "  ${C}ccze colorization for maximum readability.${N}"
    print ""
    print "  ${B}${Y}BASIC USAGE${N}"
    print "  ${M}  zpwr taillog${N}${D}                        # follow log with colors${N}"
    print "  ${M}  zpwr taillog -n 50${N}${D}                  # last 50 lines, then follow${N}"
    print "  ${M}  zpwr taillog -f${N}${D}                     # colorize without following${N}"
    print "  ${M}  zpwr taillog -r${N}${D}                     # raw output with line numbers${N}"
    print ""
    print "  ${B}${Y}THE FLAGS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}-n, --lines N${N}${D}     Show last N lines before following${N}"
    print "  ${C}-f, --no-follow${N}${D}   Just colorize, do not tail -f${N}"
    print "  ${C}-r, --raw${N}${D}         No ccze, plain output with line numbers${N}"
    print ""
    print "  ${B}${Y}CUSTOM LOGFILE${N}"
    print "  ${M}  zpwr taillog /var/log/system.log${N}"
    print "  ${M}  zpwr taillog /var/log/syslog${N}"
    print ""
    print "  ${D}  The last argument can be any logfile path.${N}"
    print "  ${D}  Default: \$ZPWR_LOGFILE (the zpwr logfile).${N}"
    print ""
    print "  ${B}${Y}CCZE: THE SECRET WEAPON${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  ccze is a log colorizer that understands dozens of log${N}"
    print "  ${D}  formats: syslog, Apache, Postfix, PHP, kernel messages,${N}"
    print "  ${D}  and more. It auto-detects the format and colorizes:${N}"
    print ""
    print "  ${G}  timestamps${N}${D}     in one color${N}"
    print "  ${Y}  warnings${N}${D}       in yellow${N}"
    print "  ${R}  errors${N}${D}         in red${N}"
    print "  ${C}  info${N}${D}           in cyan${N}"
    print "  ${M}  hostnames${N}${D}      in magenta${N}"
    print ""
    print "  ${D}  Install: ${M}brew install ccze${D}  or  ${M}apt install ccze${N}"
    print "  ${D}  If ccze is not found, taillog falls back to plain output${N}"
    print "  ${D}  with a helpful install hint.${N}"
    print ""
    print "  ${B}${Y}THE ZPWR LOGGING VERBS${N}"
    print "  ${D}  taillog consumes logs. These verbs produce them:${N}"
    print "  ${M}  zpwr logdebug <msg>${N}${D}                 # debug level${N}"
    print "  ${M}  zpwr loginfo <msg>${N}${D}                  # info level${N}"
    print "  ${M}  zpwr logerror <msg>${N}${D}                 # error level${N}"
    print "  ${M}  zpwr logtrace <msg>${N}${D}                 # trace level (most verbose)${N}"
    print ""
    print "  ${D}  The *console variants also print to stderr:${N}"
    print "  ${M}  zpwr logdebugconsole <msg>${N}"
    print "  ${M}  zpwr loginfoconsole <msg>${N}"
    print "  ${M}  zpwr logerrorconsole <msg>${N}"
    print "  ${M}  zpwr logtraceconsole <msg>${N}"
    print ""
    print "  ${B}${Y}LOG MAINTENANCE${N}"
    print "  ${D}  Logs grow forever. Clean them periodically:${N}"
    print "  ${M}  zpwr cleanlog${N}${D}                       # truncate the logfile${N}"
    print "  ${D}  Or check the size first: ${M}ls -lh \$ZPWR_LOGFILE${N}"
    print ""
    print "  ${D}  A 100MB logfile means your debug logging is too chatty.${N}"
    print "  ${D}  A 1KB logfile means nothing is being logged. Both are${N}"
    print "  ${D}  worth investigating.${N}"
    print ""
}
