PAGE_TITLE="Zinit Completions & Compinit"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== ZINIT COMPLETIONS & COMPINIT ===${N}"
    print "  ${D}// compinit is the most expensive call in zsh startup. defer it. //${N}"
    print "  ${C}The completion system (compsys) needs compinit to initialize.${N}"
    print "  ${C}But compinit scans all fpath entries and parses completion${N}"
    print "  ${C}files. On a system with 400+ completions, this is slow.${N}"
    print "  ${C}ZPWR defers it behind turbo mode.${N}"
    print "  ${B}${Y}ZINIT COMPINIT OPTIONS${N}"
    print "  ${M}  ZINIT[COMPINIT_OPTS]='-C -u'${N}"
    print "  ${D}-C skips security checks (don't re-verify file ownership).${N}"
    print "  ${D}-u suppresses warnings about insecure directories.${N}"
    print "  ${D}These flags make compinit fast but trust your fpath.${N}"
    print "  ${M}  ZINIT[ZCOMPDUMP_PATH]=\"\$ZSH_COMPDUMP\"${N}"
    print "  ${D}Points compinit to zpwr's zcompdump location.${N}"
    print "  ${B}${Y}THE DEFERRED COMPINIT${N}"
    print "  ${D}Compinit runs in the LAST turbo phase:${N}"
    print "  ${M}  zinit ice lucid nocompile nocd as'null'${N}"
    print "  ${M}    wait\"\${ZPWR_ZINIT_COMPINIT_DELAY}g\"${N}"
    print "  ${M}    atinit'zicompinit; zicdreplay; zpwrBindOverrideOMZCompdefs'${N}"
    print "  ${D}zicompinit: runs compinit with the configured opts.${N}"
    print "  ${D}zicdreplay: replays all compdef calls that were recorded${N}"
    print "  ${D}while compinit wasn't loaded yet. Plugins that called compdef${N}"
    print "  ${D}during turbo load had their calls queued -- now they fire.${N}"
    print "  ${B}${Y}THE OMZ COMPLETION SYMLINK HACK${N}"
    print "  ${D}OMZ completion snippets land in:${N}"
    print "  ${M}  \$ZSH/snippets/OMZP::coffee/_coffee${N}"
    print "  ${D}But compinit needs them in the completions dir. ZPWR${N}"
    print "  ${D}symlinks them using zsh/files builtin:${N}"
    print "  ${M}  zmodload -F zsh/files b:zf_ln${N}"
    print "  ${M}  zf_ln -sfn \$ZSH/snippets/OMZP::\${p%/*}/... \$ZSH/completions/...${N}"
    print "  ${D}zf_ln is a builtin ln(1), no fork needed. Fast.${N}"
    print "  ${B}${Y}zpwrStaleZcompdump${N}"
    print "  ${D}The zcompdump cache gets stale when plugins update.${N}"
    print "  ${D}zpwrStaleZcompdump checks the cache age. If it is older${N}"
    print "  ${D}than ~1 week, it triggers a full compinit rebuild.${N}"
    print "  ${D}This runs automatically every shell startup (cheap check).${N}"
    print "  ${B}${Y}FORCE REBUILD${N}"
    print "  ${M}  zpwr regenzsh${N}"
    print "  ${D}Nukes the zcompdump, re-runs compinit from scratch, and${N}"
    print "  ${D}recompiles everything. Use when completions go missing or${N}"
    print "  ${D}after adding new completion files to fpath.${N}"
    print "  ${B}${Y}ZPWR_ZINIT_COMPINIT_DELAY${N}"
    print "  ${D}Default: 0. Set in \$ZPWR_ENV/.zpwr_env.sh.${N}"
    print "  ${D}Controls the numeric prefix of the wait ice for compinit.${N}"
    print "  ${D}0 = load immediately after prompt. Higher = more delay.${N}"
    print "  ${D}On fast machines, 0 is fine. On slow machines, 1 or 2${N}"
    print "  ${D}lets other plugins finish first.${N}"
}
