PAGE_TITLE="Reset & Recovery"
PAGE_CHAPTER="CHAPTER 18: INSTALLATION & RESET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> RESET & RECOVERY: WHEN THINGS GO WRONG <<<${N}"
    print "  ${D}every system needs a panic button -- here are yours${N}"
    print ""
    print "  ${B}${Y}zpwr reset${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Full framework reset. Clears caches, regenerates${N}"
    print "  ${G}configs, rebuilds completion dumps, relinks everything.${N}"
    print ""
    print "  ${C}  \$ zpwr reset${N}                  ${D}# the big red button${N}"
    print ""
    print "  ${Y}WHEN TO USE:${N}"
    print "  ${D}  * Completions are broken or stale${N}"
    print "  ${D}  * Config changes aren't taking effect${N}"
    print "  ${D}  * Something feels \"off\" and you can't pin it down${N}"
    print "  ${D}  * After a major ZPWR update${N}"
    print ""
    print "  ${B}${Y}zpwr reload${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Hot reload without resetting. Re-sources all configs${N}"
    print "  ${G}and refreshes the environment. Faster than reset.${N}"
    print ""
    print "  ${C}  \$ zpwr reload${N}                 ${D}# hot reload${N}"
    print ""
    print "  ${G}Use reload when you've edited a config and want to${N}"
    print "  ${G}apply changes without nuking caches.${N}"
    print ""
    print "  ${B}${Y}ESCALATION LADDER:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  Level 1: ${C}zpwr reload${N}           ${D}# re-source configs${N}"
    print "  ${D}  Level 2: ${Y}zpwr reset${N}            ${D}# rebuild everything${N}"
    print "  ${D}  Level 3: ${R}zpwr install${N}          ${D}# full reinstall${N}"
    print "  ${D}  Level 4: ${R}rm -rf \$ZPWR && clone${N} ${D}# scorched earth${N}"
    print ""
    print "  ${G}Start at Level 1. Only escalate if the problem persists.${N}"
    print "  ${G}Most issues are fixed by reload. Reset handles the rest.${N}"
    print ""
    print "  ${B}${Y}COMMON RECOVERY SCENARIOS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  \"completions are wrong\"    --> zpwr reset${N}"
    print "  ${D}  \"alias isn't working\"      --> zpwr reload${N}"
    print "  ${D}  \"new plugin not loading\"   --> zpwr reload${N}"
    print "  ${D}  \"everything is broken\"     --> zpwr reset${N}"
    print "  ${D}  \"still broken after reset\" --> zpwr install${N}"
    print ""
    print "  ${D}  // reload is ctrl-r for your shell framework${N}"
    print "  ${D}  // reset is the factory reset you hope to never need${N}"
    print "  ${D}  // but when you do need it, you'll be glad it exists${N}"
}
