PAGE_TITLE="Tmux Prefix Keys: Windows & Sessions"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< TMUX PREFIX KEYS: WINDOWS & SESSIONS >>>${N}"
    print "  ${D}window management, session juggling, the multiplexer core.${N}"
    print ""
    print "  ${B}${Y}WINDOW CREATION & SELECTION:${N}"
    print "  ${C}prefix c${N}              ${D}new window${N}"
    print "  ${C}prefix a${N}              ${D}last-window (toggle to previous)${N}"
    print "  ${C}prefix 0-9${N}            ${D}select window by number${N}"
    print "  ${C}prefix '${N}              ${D}select window by index prompt${N}"
    print "  ${C}prefix n${N}              ${D}next window (repeatable)${N}"
    print "  ${C}prefix p${N}              ${D}previous window (repeatable)${N}"
    print "  ${C}prefix Ctrl-n${N}         ${D}next window${N}"
    print "  ${C}prefix Ctrl-p${N}         ${D}previous window${N}"
    print ""
    print "  ${B}${Y}WINDOW OPERATIONS:${N}"
    print "  ${C}prefix ,${N}              ${D}rename current window${N}"
    print "  ${C}prefix &${N}              ${D}kill window (with confirm)${N}"
    print "  ${C}prefix .${N}              ${D}move window to target${N}"
    print "  ${C}prefix f${N}              ${D}find window by name${N}"
    print "  ${C}prefix w${N}              ${D}choose-tree window view${N}"
    print "  ${C}prefix i${N}              ${D}display-message (window info)${N}"
    print "  ${C}prefix t${N}              ${D}clock-mode${N}"
    print ""
    print "  ${B}${Y}SESSION MANAGEMENT:${N}"
    print "  ${C}prefix \$${N}              ${D}rename current session${N}"
    print "  ${C}prefix (${N}              ${D}switch to previous client (repeatable)${N}"
    print "  ${C}prefix )${N}              ${D}switch to next client (repeatable)${N}"
    print "  ${C}prefix d${N}              ${D}detach client${N}"
    print "  ${C}prefix s${N}              ${D}choose-tree session view${N}"
    print "  ${C}prefix Ctrl-z${N}         ${D}suspend client${N}"
    print ""
    print "  ${B}${Y}RELOAD & PERSIST:${N}"
    print "  ${C}prefix r${N}              ${D}reload tmux config + display confirmation${N}"
    print "  ${C}prefix Ctrl-s${N}         ${D}save session (tmux-resurrect)${N}"
    print "  ${C}prefix Ctrl-r${N}         ${D}restore session (tmux-resurrect)${N}"
    print ""
    print "  ${B}${Y}ROOT TABLE SHORTCUTS:${N}"
    print "  ${C}Ctrl-\\\\${N}               ${D}switch to next client (no prefix)${N}"
    print "  ${C}Ctrl-]${N}               ${D}switch to prev client (no prefix)${N}"
    print ""
    print "  ${B}${Y}META:${N}"
    print "  ${C}prefix ?${N}              ${D}list all keys${N}"
    print "  ${C}prefix :${N}              ${D}command prompt${N}"
    print "  ${C}prefix /${N}              ${D}describe a key binding${N}"
    print "  ${C}prefix ~${N}              ${D}show messages${N}"
    print ""
    print "  ${M}  // sessions are parallel universes${N}"
    print "  ${M}  // the wizard keeps many realities open at once${N}"
    print ""
}
