PAGE_TITLE="Vim Normal Mode Highlights"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< VIM NORMAL MODE: ZPWR HIGHLIGHTS >>>${N}"
    print "  ${D}leader mappings, fzf integration, tmux synergy.${N}"
    print "  ${D}leader key is Space. only zpwr-specific bindings listed.${N}"
    print ""
    print "  ${B}${Y}FILE & BUFFER (Space prefix):${N}"
    print "  ${C}Space w${N}               ${D}:w! (force write)${N}"
    print "  ${C}Space e${N}               ${D}:q! (force quit)${N}"
    print "  ${C}Space q${N}               ${D}:qa! (quit all)${N}"
    print "  ${C}Space wq${N}              ${D}:wq! (write and quit)${N}"
    print "  ${C}Space n / Space p${N}     ${D}next / prev buffer${N}"
    print "  ${C}Space an / Space ap${N}   ${D}next / prev in arglist${N}"
    print "  ${C}Space Tab${N}             ${D}alternate or next buffer${N}"
    print "  ${C}Space t${N}               ${D}new tab${N}"
    print "  ${C}Space s / Space v${N}     ${D}horizontal / vertical split${N}"
    print ""
    print "  ${B}${Y}FZF INTEGRATION (Space prefix):${N}"
    print "  ${C}Space f${N}               ${D}:Files! (fzf files)${N}"
    print "  ${C}Space b${N}               ${D}:Buffers! (fzf buffers)${N}"
    print "  ${C}Space j${N}               ${D}:Lines! (fzf lines)${N}"
    print "  ${C}Space ag${N}              ${D}:Ag (silver searcher)${N}"
    print "  ${C}Space aa${N}              ${D}:Agg (ag variant)${N}"
    print "  ${C}Space rg${N}              ${D}:Rg (ripgrep)${N}"
    print "  ${C}Space z${N}               ${D}:Commits! (fzf git commits)${N}"
    print "  ${C}Space ;${N}               ${D}:Commands! (fzf commands)${N}"
    print "  ${C}Space ,${N}               ${D}:FZFMaps (fzf all mappings)${N}"
    print "  ${C}Space ke / , / m / i${N}  ${D}fzf keys / maps / nmap / imap${N}"
    print "  ${C}Space ta / ma / env${N}  ${D}fzf tags / marks / env vars${N}"
    print "  ${C}Space / / .${N}           ${D}locate all / colorscheme picker${N}"
    print ""
    print "  ${B}${Y}HISTORY (Space prefix):${N}"
    print "  ${C}Space hh${N}              ${D}:History! (fzf file history)${N}"
    print "  ${C}Space h/${N}              ${D}:History/! (fzf search history)${N}"
    print "  ${C}Space h:${N}              ${D}:History:! (fzf command history)${N}"
    print ""
    print "  ${B}${Y}SEARCH & REPLACE (Space prefix):${N}"
    print "  ${C}Space r${N}               ${D}replace word under cursor (whole file)${N}"
    print "  ${C}Space g${N}               ${D}global substitute word under cursor${N}"
    print "  ${C}Space x${N}               ${D}repeat last substitution on line${N}"
    print "  ${C}n / N${N}                 ${D}next / prev search (centered)${N}"
    print "  ${C}z/${N}                    ${D}toggle auto-highlight word under cursor${N}"
    print ""
    print "  ${B}${Y}GIT & TMUX:${N}"
    print "  ${C}Space hs${N}              ${D}GitGutter stage hunk${N}"
    print "  ${C}Space hu${N}              ${D}GitGutter undo hunk${N}"
    print "  ${C}Space hp${N}              ${D}GitGutter preview hunk${N}"
    print "  ${C}[c / ]c${N}              ${D}prev / next git hunk${N}"
    print "  ${C}Space vj${N}              ${D}save + TmuxRepeat file${N}"
    print "  ${C}Space os / ox / oc${N}   ${D}google / open URL / copy word${N}"
    print ""
    print "  ${B}${Y}MINIMAP & COMMENTS:${N}"
    print "  ${C}Space mm${N}              ${D}open minimap${N}"
    print "  ${C}Space mt${N}              ${D}toggle minimap${N}"
    print "  ${C}Space cc${N}              ${D}NERDCommenter comment${N}"
    print "  ${C}Space c Space${N}         ${D}NERDCommenter toggle${N}"
    print "  ${C}Space cu${N}              ${D}NERDCommenter uncomment${N}"
    print ""
    print "  ${M}  // the leader key is Space because power needs room${N}"
    print "  ${M}  // every binding is one thought away from execution${N}"
    print ""
}
