PAGE_TITLE="Emacs Integration"
PAGE_CHAPTER="CHAPTER 13: EMACS DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== EMACS INTEGRATION ===${N}"
    print "  ${D}// 29 verbs for the church of emacs //${N}"
    print ""
    print "  ${C}Every file operation in ZPWR has an emacs variant. Open,${N}"
    print "  ${C}edit, search, and navigate — all wired to emacsclient.${N}"
    print ""
    print "  ${B}${Y}OPEN & EDIT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr emacsall${N}${D}              # emacs all zpwr files for :argdo${N}"
    print "  ${M}  zpwr emacsallserver${N}${D}        # emacs all zpwr files via server${N}"
    print "  ${M}  zpwr emacsalledit${N}${D}          # emacs edit 1 or more configs${N}"
    print "  ${M}  zpwr emacsautoload${N}${D}         # emacs all autoloads :argdo${N}"
    print "  ${M}  zpwr emacsscripts${N}${D}          # emacs all zpwr scripts for :argdo${N}"
    print "  ${M}  zpwr emacsscriptedit${N}${D}       # emacs edit 1 or more scripts${N}"
    print "  ${M}  zpwr emacszpwr${N}${D}             # emacs zpwr dir${N}"
    print ""
    print "  ${B}${Y}CONFIG & TOKENS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr emacsconfig${N}${D}           # emacs all zpwr configs${N}"
    print "  ${M}  zpwr emacsemacsconfig${N}${D}      # emacs edit emacs zpwr configs${N}"
    print "  ${M}  zpwr emacstokens${N}${D}           # emacs the .tokens.sh file${N}"
    print "  ${M}  zpwr emacstests${N}${D}            # emacs edit all zpwr tests${N}"
    print ""
    print "  ${B}${Y}NAVIGATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr emacscd${N}${D}               # emacs edit and cd to first dir${N}"
    print "  ${M}  zpwr emacsrecent${N}${D}           # emacs edit most recent editor files${N}"
    print "  ${M}  zpwr emacsrecentcd${N}${D}         # cd and emacs edit most recent files${N}"
    print "  ${M}  zpwr emacsrecentsudo${N}${D}       # sudo emacs edit most recent files${N}"
    print "  ${M}  zpwr emacsrecentsudocd${N}${D}     # cd and sudo emacs most recent files${N}"
    print ""
    print "  ${B}${Y}SEARCH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr emacsfilesearch${N}${D}       # emacs a file in a sub dir${N}"
    print "  ${M}  zpwr emacsfilesearchedit${N}${D}   # edit emacs a file in a sub dir${N}"
    print "  ${M}  zpwr emacsfindsearch${N}${D}       # emacs find drive for file${N}"
    print "  ${M}  zpwr emacsfindsearchedit${N}${D}   # emacs edit find drive for file${N}"
    print "  ${M}  zpwr emacslocatesearch${N}${D}     # emacs accept locate drive for file${N}"
    print "  ${M}  zpwr emacslocatesearchedit${N}${D} # emacs edit locate drive for file${N}"
    print "  ${M}  zpwr emacswordsearch${N}${D}       # emacs a file in a sub dir by word${N}"
    print "  ${M}  zpwr emacswordsearchedit${N}${D}   # edit emacs a file by word${N}"
    print ""
    print "  ${B}${Y}TAGS & PLUGINS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr emacsctags${N}${D}            # emacs zpwr ctags tags${N}"
    print "  ${M}  zpwr emacsgtags${N}${D}            # emacs zpwr GNU global tags${N}"
    print "  ${M}  zpwr emacsgtagsedit${N}${D}        # emacs edit zpwr GNU global tags${N}"
    print "  ${M}  zpwr emacsplugincount${N}${D}      # total number of emacs plugins${N}"
    print "  ${M}  zpwr emacspluginlist${N}${D}       # total list of emacs plugins${N}"
    print ""
}
