PAGE_TITLE="File Watching"
PAGE_CHAPTER="CHAPTER 11: MONITORING & AUTOMATION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FILE WATCHING ===${N}"
    print "  ${D}// your files change. your command runs. automatically. //${N}"
    print ""
    print "  ${C}The ${M}watch${C} verb monitors files for changes and auto-executes${N}"
    print "  ${C}a command when something is modified. It is the poor man's${N}"
    print "  ${C}CI pipeline, running locally in your terminal.${N}"
    print ""
    print "  ${B}${Y}USAGE${N}"
    print "  ${M}  zpwr watch '<GLOB>' '<COMMAND>'${N}"
    print ""
    print "  ${D}  Two arguments: what to watch, and what to run.${N}"
    print "  ${D}  Quote both arguments to prevent premature expansion.${N}"
    print ""
    print "  ${B}${Y}PRACTICAL EXAMPLES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr watch '*.zsh' 'zpwr recompile'${N}"
    print "  ${D}  Recompile zpwr whenever a .zsh file changes.${N}"
    print "  ${D}  Edit a function, save, and .zwc files auto-rebuild.${N}"
    print ""
    print "  ${M}  zpwr watch 'src/**/*.ts' 'npm run build'${N}"
    print "  ${D}  Build your TypeScript project on every source change.${N}"
    print ""
    print "  ${M}  zpwr watch 'Makefile' 'make'${N}"
    print "  ${D}  Run make whenever the Makefile changes.${N}"
    print ""
    print "  ${M}  zpwr watch '.' 'echo changed'${N}"
    print "  ${D}  Watch the entire current directory.${N}"
    print ""
    print "  ${M}  zpwr watch '*.py' 'python -m pytest'${N}"
    print "  ${D}  Run tests on every Python file change. TDD mode.${N}"
    print ""
    print "  ${B}${Y}PLATFORM BACKEND${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  macOS:${N}${D}   Uses fswatch (brew install fswatch)${N}"
    print "  ${C}  Linux:${N}${D}   Uses inotifywait (apt install inotify-tools)${N}"
    print ""
    print "  ${D}  The verb auto-detects which tool is available.${N}"
    print "  ${D}  If neither is found, it tells you what to install.${N}"
    print ""
    print "  ${B}${Y}THE OUTPUT FORMAT${N}"
    print "  ${D}  Each trigger shows a box with:${N}"
    print "  ${G}  - Trigger count${N}${D} (how many times it has fired)${N}"
    print "  ${G}  - Timestamp${N}${D}      (when the change was detected)${N}"
    print "  ${G}  - Filename${N}${D}       (which file changed)${N}"
    print "  ${G}  - Exit status${N}${D}    (green ok or red exit code)${N}"
    print "  ${G}  - Elapsed time${N}${D}   (how long the command took)${N}"
    print ""
    print "  ${B}${Y}HOW TO STOP${N}"
    print "  ${D}  Press ${B}Ctrl-C${D}. The watcher process terminates cleanly.${N}"
    print ""
    print "  ${B}${Y}GLOB HANDLING${N}"
    print "  ${D}  The glob is split into directory and file filter:${N}"
    print "  ${D}  ${M}'src/**/*.ts'${D} -> watch ${C}src/${D} recursively, filter ${C}*.ts${N}"
    print "  ${D}  ${M}'.'${D}           -> watch current dir, no filter${N}"
    print "  ${D}  ${M}'*.zsh'${D}       -> watch ${C}./${D}, filter ${C}*.zsh${N}"
    print ""
    print "  ${D}  The glob-to-regex conversion handles * and ? patterns.${N}"
    print "  ${D}  For fswatch, it uses -e '.*' -i to exclude-then-include.${N}"
    print "  ${D}  For inotifywait, it uses zsh's glob matching on filenames.${N}"
    print ""
}
