PAGE_TITLE="Shell Introspection"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== SHELL INTROSPECTION ===${N}"
    print "  ${D}// 32 verbs to look inward //${N}"
    print ""
    print "  ${C}Inspect ZPWR itself: banners, counts, plugin lists,${N}"
    print "  ${C}subcommand discovery, and identity checks.${N}"
    print ""
    print "  ${B}${Y}EXISTENCE CHECKS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr exists${N}${D}                # check if identifier is valid${N}"
    print "  ${M}  zpwr existscommand${N}${D}         # check if command is valid${N}"
    print ""
    print "  ${B}${Y}BANNERS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr about${N}${D}                 # show zpwr banner${N}"
    print "  ${M}  zpwr banner${N}${D}                # show zpwr banner${N}"
    print "  ${M}  zpwr bannercounts${N}${D}          # show banner and env counts${N}"
    print "  ${M}  zpwr bannerlolcat${N}${D}          # banner with ponysay and lolcat${N}"
    print "  ${M}  zpwr bannernopony${N}${D}          # show banner without ponysay${N}"
    print "  ${M}  zpwr bannerpony${N}${D}            # show banner with ponysay${N}"
    print ""
    print "  ${B}${Y}COUNTS & LISTS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr autoloadcount${N}${D}         # total number of autoloads${N}"
    print "  ${M}  zpwr autoloadlist${N}${D}          # total list of autoloads${N}"
    print "  ${M}  zpwr scriptcount${N}${D}           # total number of scripts${N}"
    print "  ${M}  zpwr scriptlist${N}${D}            # total list of scripts${N}"
    print "  ${M}  zpwr zshplugincount${N}${D}        # total number of zsh plugins${N}"
    print "  ${M}  zpwr zshpluginlist${N}${D}         # total list of zsh plugins${N}"
    print "  ${M}  zpwr vimplugincount${N}${D}        # total number of vim plugins${N}"
    print "  ${M}  zpwr vimpluginlist${N}${D}         # total list of vim plugins${N}"
    print "  ${M}  zpwr emacsplugincount${N}${D}      # total number of emacs plugins${N}"
    print "  ${M}  zpwr emacspluginlist${N}${D}       # total list of emacs plugins${N}"
    print ""
    print "  ${B}${Y}SUBCOMMANDS & VERBS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr subcommands${N}${D}           # run subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr subcommandscount${N}${D}      # number of subcommands${N}"
    print "  ${M}  zpwr subcommandsedit${N}${D}       # edit subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr subcommandsfzf${N}${D}        # fzf subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr subcommandslist${N}${D}       # list subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr verbs${N}${D}                 # run subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr verbscount${N}${D}            # number of verbs${N}"
    print "  ${M}  zpwr verbsedit${N}${D}             # edit subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr verbsfzf${N}${D}              # fzf subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr verbslist${N}${D}             # list subcommands for zpwr <tab>${N}"
    print "  ${M}  zpwr help${N}${D}                  # list subcommands with color${N}"
    print ""
    print "  ${B}${Y}MISC INTROSPECTION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr tty${N}${D}                   # print current tty${N}"
    print "  ${M}  zpwr relpath${N}${D}               # get relative path to \$PWD${N}"
    print "  ${M}  zpwr printmap${N}${D}              # pretty print maps${N}"
    print ""
}
