PAGE_TITLE="Quick Jumps"
PAGE_CHAPTER="CHAPTER 2: NAVIGATION PROTOCOL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== QUICK JUMPS ===${N}"
    print ""
    print "  ${C}The ${M}home*${C} verbs land you in zpwr directories.${N}"
    print "  ${C}These verbs land you in the ecosystem around zpwr.${N}"
    print ""
    print "  ${B}${Y}ZPWR INTERNALS${N}"
    print "  ${M}  zpwr scripts${N}${D}       # cd to scripts directory${N}"
    print "  ${D}                       shortcut alias: zs${N}"
    print ""
    print "  ${M}  zpwr autoload${N}${D}      # cd to autoload directory${N}"
    print "  ${D}                       shortcut alias: zal${N}"
    print ""
    print "  ${M}  zpwr completions${N}${D}   # cd to completion directory${N}"
    print "  ${M}  zpwr comps${N}${D}         # same thing${N}"
    print "  ${D}                       shortcut alias: zco${N}"
    print ""
    print "  ${B}${Y}PLUGIN ECOSYSTEM${N}"
    print "  ${M}  zpwr plugins${N}${D}       # cd to \$ZSH_CUSTOM/plugins${N}"
    print "  ${D}                       shortcut alias: zpl${N}"
    print "  ${D}  This is where oh-my-zsh custom plugins live.${N}"
    print "  ${D}  Your third-party zsh plugins are neighbors here.${N}"
    print ""
    print "  ${M}  zpwr forked${N}${D}        # cd to \$ZPWR_FORKED_DIR${N}"
    print "  ${M}  zpwr fp${N}${D}            # same thing${N}"
    print "  ${D}  Forked repos that zpwr depends on live here.${N}"
    print "  ${D}  Useful when you need to hack on a dependency.${N}"
    print ""
    print "  ${B}${Y}SPECIAL DIRECTORIES${N}"
    print "  ${M}  zpwr hidden${N}${D}        # cd to \$ZPWR_HIDDEN_DIR${N}"
    print "  ${D}  The hidden directory. Dot-prefixed internal state.${N}"
    print ""
    print "  ${M}  zpwr repo${N}${D}          # cd to \$ZPWR_REPO_NAME${N}"
    print "  ${M}  zpwr zp${N}${D}            # same thing${N}"
    print "  ${M}  zpwr zpwr${N}${D}          # same thing (yes, zpwr zpwr)${N}"
    print ""
    print "  ${B}${Y}THE NAVIGATION CHEAT SHEET${N}"
    print "  ${G}  Use case                      Verb${N}"
    print "  ${D}  --------                      ----${N}"
    print "  ${C}  Edit a script${N}${D} .............. ${M}zpwr scripts${N}"
    print "  ${C}  Fix a completion${N}${D} ........... ${M}zpwr comps${N}"
    print "  ${C}  Add an autoload function${N}${D} .. ${M}zpwr autoload${N}"
    print "  ${C}  Debug a plugin${N}${D} ............ ${M}zpwr plugins${N}"
    print "  ${C}  Patch a fork${N}${D} .............. ${M}zpwr forked${N}"
    print ""
    print "  ${D}Each of these is one verb, zero path typing,${N}"
    print "  ${D}and instant teleportation to where the work is.${N}"
    print ""
}
