PAGE_TITLE="Specialty Completions & Aliases"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== SPECIALTY COMPLETIONS & ALIASES ===${N}"
    print "  ${D}platform-specific plugins loaded conditionally${N}"
    print ""
    print "  ${B}${Y}zsh-cpan-completion${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Tab completion for Perl CPAN modules.${N}"
    print "  ${M}  cpan install <tab>${N}${D}       # complete module names${N}"
    print ""
    print "  ${B}${Y}zsh-dotnet-completion${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Tab completion for .NET CLI (dotnet).${N}"
    print "  ${M}  dotnet <tab>${N}${D}             # complete subcommands${N}"
    print "  ${M}  dotnet add package <tab>${N}${D}  # complete packages${N}"
    print "  ${D}  Loaded conditionally when dotnet is available.${N}"
    print ""
    print "  ${B}${Y}zsh-xcode-completions${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Tab completion for Xcode CLI tools on macOS.${N}"
    print "  ${M}  xcodebuild <tab>${N}${D}         # complete build options${N}"
    print "  ${M}  xcrun <tab>${N}${D}              # complete SDK tools${N}"
    print "  ${D}  macOS only — loaded when Xcode is detected.${N}"
    print ""
    print "  ${B}${Y}kubectl-aliases${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}800+ aliases for kubectl. Every common operation${N}"
    print "  ${G}is a short alias:${N}"
    print "  ${M}  kgp${N}${D}   = kubectl get pods${N}"
    print "  ${M}  kgs${N}${D}   = kubectl get services${N}"
    print "  ${M}  kd${N}${D}    = kubectl describe${N}"
    print "  ${M}  kl${N}${D}    = kubectl logs${N}"
    print "  ${D}  Loaded conditionally when kubectl is available.${N}"
    print ""
    print "  ${B}${Y}jhipster-oh-my-zsh-plugin${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Aliases and completions for JHipster (Java/Spring Boot${N}"
    print "  ${G}scaffold generator).${N}"
    print "  ${M}  jh${N}${D}    = jhipster${N}"
    print "  ${D}  Loaded conditionally when jhipster is available.${N}"
    print ""
    print "  ${D}All plugins: ${C}MenkeTechnologies/*${N}"
    print "  ${D}Conditional loading means zero overhead if the${N}"
    print "  ${D}tool isn't installed on your system.${N}"
    print ""
}
