PAGE_TITLE="GRC, ccze & the Color Pipeline"
PAGE_CHAPTER="CHAPTER 42: COLORIZATION STACK"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== GRC, CCZE & THE COLOR PIPELINE ===${N}"
    print "  ${D}every byte of output deserves to be beautiful${N}"
    print "  ${B}${Y}THE FULL COLORIZATION STACK${N}"
    print "  ${D}  zpwr has a color tool for every type of output:${N}"
    print "  ${B}${C}  FILE LISTING${N}"
    print "  ${G}    eza${N}${D} (color-scale, git status) -> ${G}grc+ls${N}${D} -> ${D}plain ls${N}"
    print "  ${B}${C}  FILE VIEWING${N}"
    print "  ${G}    bat${N}${D} (syntax highlighting) -> ${D}cat${N}"
    print "  ${D}    ZPWR_COLORIZER=bat in ${M}\$ZPWR_ENV/.zpwr_env.sh${N}"
    print "  ${B}${C}  LOG VIEWING${N}"
    print "  ${G}    ccze${N}${D} (log colorizer) -> ${D}plain tail${N}"
    print "  ${D}    zpwrTailLog pipes \$ZPWR_LOGFILE through ccze.${N}"
    print "  ${B}${C}  GIT DIFFS${N}"
    print "  ${G}    delta${N}${D} (syntax-aware diff) -> ${D}plain diff${N}"
    print "  ${D}    delta adds line numbers, word-level highlighting,${N}"
    print "  ${D}    and side-by-side view with Dracula theme.${N}"
    print "  ${B}${Y}CCZE: LOG FILE COLORIZER${N}"
    print "  ${D}  ccze parses log formats and applies semantic colors:${N}"
    print "  ${D}  timestamps, severity levels, PIDs, IP addresses.${N}"
    print "  ${G}  zpwr taillog${N}${D}  uses ccze for colorized log tailing.${N}"
    print "  ${D}  System logs become readable at a glance.${N}"
    print "  ${B}${Y}COLOR TESTING VERBS${N}"
    print "  ${G}  zpwr colortest${N}${D}       test terminal basic 16 colors${N}"
    print "  ${G}  zpwr colortest256${N}${D}    test full 256-color palette${N}"
    print "  ${G}  zpwr pygmentcolors${N}${D}   show all pygment color schemes${N}"
    print "  ${G}  zpwr colorsdiff${N}${D}      colorized side-by-side diff${N}"
    print "  ${D}  Use these to verify your terminal supports the full palette.${N}"
    print "  ${B}${Y}THE FALLBACK PHILOSOPHY${N}"
    print "  ${D}  Every color tool has a plain fallback:${N}"
    print "  ${D}  No eza? grc+ls. No grc? plain ls. No bat? cat.${N}"
    print "  ${D}  zpwr degrades gracefully. Color is never a hard dependency.${N}"
    print "  ${D}  SSH into a minimal server? Everything still works.${N}"
    print "  ${D}  Just less pretty. Function over form, always.${N}"
    print "  ${B}${R}THE RESULT:${N} ${D}In a fully-equipped zpwr terminal:${N}"
    print "  ${D}  File listings glow. Logs are semantic. Diffs are surgical.${N}"
    print "  ${D}  Your eyes never have to parse raw monochrome again.${N}"
    print "  ${D}  The color pipeline is zpwr's cosmetic surgery department.${N}"
}
