PAGE_TITLE="Batch Execution"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== BATCH EXECUTION ===${N}"
    print "  ${D}// one command, many targets. the industrial strength loop. //${N}"
    print ""
    print "  ${C}When you need to run the same operation across multiple${N}"
    print "  ${C}files, directories, or git repos, these verbs replace${N}"
    print "  ${C}hand-rolled for loops with tested, colorized execution.${N}"
    print ""
    print "  ${B}${Y}FOR: THE BASIC ITERATOR${N}"
    print "  ${M}  zpwr for <command>${N}${D}                  # run command in current dir context${N}"
    print ""
    print "  ${D}  Executes a command with zpwr's enhanced output formatting.${N}"
    print "  ${D}  Shows timing, exit status, and colorized output.${N}"
    print ""
    print "  ${B}${Y}FOR10: THE STRESS TEST${N}"
    print "  ${M}  zpwr for10 <command>${N}${D}                # run command 10 times${N}"
    print ""
    print "  ${D}  Executes a command 10 times. Useful for:${N}"
    print "  ${D}  - Benchmarking (is the timing consistent?)${N}"
    print "  ${D}  - Flaky test detection (does it fail intermittently?)${N}"
    print "  ${D}  - Load testing (can it handle rapid repeated execution?)${N}"
    print ""
    print "  ${B}${Y}FORDIR: ITERATE OVER GIT REPOS${N}"
    print "  ${M}  zpwr fordir <command>${N}${D}               # run command in each git repo${N}"
    print ""
    print "  ${D}  Iterates over all cached git repos, cd's into each one,${N}"
    print "  ${D}  and runs the command. Extremely powerful for bulk operations:${N}"
    print ""
    print "  ${M}  zpwr fordir 'git status -s'${N}${D}         # dirty files in all repos${N}"
    print "  ${M}  zpwr fordir 'git pull'${N}${D}              # pull all repos${N}"
    print "  ${M}  zpwr fordir 'git stash list'${N}${D}        # find forgotten stashes${N}"
    print ""
    print "  ${D}  Each repo's output is labeled with its path so you${N}"
    print "  ${D}  know which repo produced which output.${N}"
    print ""
    print "  ${B}${Y}FORDIRUPDATE: PULL ALL REPOS${N}"
    print "  ${M}  zpwr fordirupdate${N}${D}                   # git pull in every repo${N}"
    print ""
    print "  ${D}  Specialized version of fordir that runs git pull in${N}"
    print "  ${D}  every cached repo. Same as ${M}zpwr fordir 'git pull'${D}${N}"
    print "  ${D}  but optimized for the common case.${N}"
    print ""
    print "  ${B}${Y}EXECGLOB: GLOB-BASED EXECUTION${N}"
    print "  ${M}  zpwr execglob <glob> <command>${N}${D}      # run command on glob matches${N}"
    print ""
    print "  ${D}  Finds files matching a glob and runs a command on each:${N}"
    print "  ${M}  zpwr execglob '*.log' 'wc -l'${N}${D}      # line count each log file${N}"
    print "  ${M}  zpwr execglob '*.bak' 'rm'${N}${D}         # delete all .bak files${N}"
    print ""
    print "  ${B}${Y}EXECGLOBPARALLEL: PARALLEL GLOB EXECUTION${N}"
    print "  ${M}  zpwr execglobparallel <glob> <cmd>${N}${D}  # parallel execution${N}"
    print ""
    print "  ${D}  Same as execglob but runs commands in parallel.${N}"
    print "  ${D}  Useful when processing many files that are I/O-bound:${N}"
    print "  ${M}  zpwr execglobparallel '*.png' 'optipng'${N}${D}  # compress images${N}"
    print ""
    print "  ${B}${Y}THE POWER COMBOS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  Find all repos with uncommitted work:${N}"
    print "  ${M}  zpwr fordir 'git diff --stat HEAD'${N}"
    print ""
    print "  ${D}  Count lines in all Python files:${N}"
    print "  ${M}  zpwr execglob '**/*.py' 'wc -l'${N}"
    print ""
    print "  ${D}  Stress test a flaky command:${N}"
    print "  ${M}  zpwr for10 'curl -s localhost:3000/health'${N}"
    print ""
}
