PAGE_TITLE="Shell Lint"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== SHELL LINT ===${N}"
    print "  ${D}// if it parses, it ships. but does it REALLY parse? //${N}"
    print ""
    print "  ${C}zpwr lint runs two levels of analysis on every zpwr file:${N}"
    print "  ${C}syntax checking with zsh -n, and static analysis with shellcheck.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr lint${N}${D}                  # run all checks${N}"
    print "  ${M}  zpwr lint -z${N}${D}               # zsh -n syntax check only${N}"
    print "  ${M}  zpwr lint -s${N}${D}               # shellcheck only${N}"
    print ""
    print "  ${B}${Y}WHAT IT CHECKS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  zsh -n (syntax check)${N}"
    print "  ${D}    Every file in autoload/common, autoload/darwin,${N}"
    print "  ${D}    autoload/linux, env/*.sh, env/*.zsh, install/.zshrc.${N}"
    print "  ${D}    This catches unmatched brackets, bad redirections,${N}"
    print "  ${D}    and broken quoting. Fast — no execution, just parsing.${N}"
    print ""
    print "  ${G}  shellcheck (static analysis)${N}"
    print "  ${D}    Every .sh and .zsh file in scripts/ and install/.${N}"
    print "  ${D}    Catches quoting bugs, unused variables, subshell pitfalls.${N}"
    print "  ${D}    Zsh-incompatible warnings are suppressed (SC1071 etc).${N}"
    print ""
    print "  ${B}${Y}WHEN TO RUN IT${N}"
    print "  ${D}  After editing any zpwr file. Before committing. Before${N}"
    print "  ${D}  pushing. Catch it at the gate, not in production.${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr doctor${N}${D}               # broader health check${N}"
    print "  ${M}  zpwr stale${N}${D}                # find stale compiled files${N}"
    print "  ${M}  zpwr recompile${N}${D}            # rebuild .zwc files after fixes${N}"
    print ""
}
