PAGE_TITLE="fd: find for Humans"
PAGE_CHAPTER="CHAPTER 36: FD-FIND — FIND REPLACEMENT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== FD: FIND FOR HUMANS ===${N}"
    print "  ${D}// find is powerful. fd is powerful AND usable. //${N}"
    print "  ${C}fd is a fast, user-friendly alternative to find, written in${N}"
    print "  ${C}Rust by David Peter (sharkdp — also the author of bat).${N}"
    print "  ${C}It respects .gitignore by default and uses regex, not globs.${N}"
    print "  ${B}${Y}BASIC USAGE${N}"
    print "  ${M}  fd PATTERN${N}${D}           # search current dir recursively${N}"
    print "  ${M}  fd PATTERN path/${N}${D}     # search specific directory${N}"
    print "  ${M}  fd '^test.*\\.zsh\$'${N}${D}  # full regex support${N}"
    print "  ${D}No -name, no -type f, no quoting gymnastics. Just the pattern.${N}"
    print "  ${B}${Y}KEY DIFFERENCES FROM FIND${N}"
    print "  ${D}1. Regex by default (find uses glob with -name)${N}"
    print "  ${D}2. Ignores .git, node_modules, .gitignore entries automatically${N}"
    print "  ${D}3. 5-10x faster than find due to parallel directory traversal${N}"
    print "  ${D}4. Smart case: case-insensitive unless pattern has uppercase${N}"
    print "  ${D}5. Colorized output by default${N}"
    print "  ${B}${Y}COMMON FLAGS${N}"
    print "  ${G}  fd -e zsh${N}${D}           # filter by extension${N}"
    print "  ${G}  fd -t f${N}${D}             # files only${N}"
    print "  ${G}  fd -t d${N}${D}             # directories only${N}"
    print "  ${G}  fd -t l${N}${D}             # symlinks only${N}"
    print "  ${G}  fd -t x${N}${D}             # executables only${N}"
    print "  ${G}  fd -H${N}${D}               # include hidden files${N}"
    print "  ${G}  fd -I${N}${D}               # don't respect .gitignore${N}"
    print "  ${G}  fd -u${N}${D}               # unrestricted (-H -I combined)${N}"
    print "  ${G}  fd -g GLOB${N}${D}          # use glob pattern instead of regex${N}"
    print "  ${B}${Y}EXECUTION${N}"
    print "  ${G}  fd -x cmd {}${N}${D}        # execute command per result (parallel)${N}"
    print "  ${G}  fd -X cmd{}${N}${D}         # execute once with all results as args${N}"
    print "  ${D}Placeholders: {} = path, {/} = basename, {//} = parent dir,${N}"
    print "  ${D}{.} = path without extension, {/.} = basename without extension.${N}"
    print "  ${M}  fd -e jpg -x convert {} {.}.png${N}${D}  # convert all jpgs to png${N}"
    print "  ${D}The -x flag runs in parallel by default — your cores earn their${N}"
    print "  ${D}keep. -X collects all results and passes them as one batch.${N}"
    print "  ${D}This is the find | xargs pattern without the pipe.${N}"
}
