PAGE_TITLE="Searching Content"
PAGE_CHAPTER="CHAPTER 4: THE SEARCH ENGINE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== SEARCHING CONTENT ===${N}"
    print ""
    print "  ${C}Finding files is one thing.${N}"
    print "  ${C}Finding the line inside the file? That is the real game.${N}"
    print ""
    print "  ${B}${Y}WORDSEARCH: CONTENT IN LOCAL TREE${N}"
    print "  ${M}  zpwr wordsearch${N}${D}          # find file by content in sub dir${N}"
    print "  ${D}  Greps through files in the current tree.${N}"
    print "  ${D}  Results show matching lines with filenames.${N}"
    print "  ${D}  Fzf preview shows the file with match highlighted.${N}"
    print "  ${D}  Select one, jump straight to it.${N}"
    print ""
    print "  ${M}  zpwr wordsearchedit${N}${D}      # same but result goes to \$BUFFER${N}"
    print "  ${D}  Puts the selected file path on your command line.${N}"
    print "  ${D}  Useful when you want to pipe or chain commands.${N}"
    print ""
    print "  ${B}${Y}GREP: AG INTO FZF${N}"
    print "  ${M}  zpwr grep${N}${D}               # grep through pwd with ag into fzf${N}"
    print "  ${D}  This is the heavy artillery. Uses the silver searcher${N}"
    print "  ${D}  (ag) piped into fzf for interactive filtering.${N}"
    print "  ${D}  Respects .gitignore. Skips binaries. Fast.${N}"
    print ""
    print "  ${B}${Y}FILESEARCH VS WORDSEARCH${N}"
    print "  ${G}  Know the filename?${N}${D}     Use ${M}filesearch${N}"
    print "  ${G}  Know the content?${N}${D}      Use ${M}wordsearch${N}"
    print "  ${G}  Know nothing?${N}${D}          Use ${M}grep${D} and improvise${N}"
    print ""
    print "  ${B}${Y}THE EDIT SUFFIX PATTERN${N}"
    print "  ${C}  Every search verb has an ${M}edit${C} variant:${N}"
    print "  ${D}    filesearch     -> filesearchedit${N}"
    print "  ${D}    wordsearch     -> wordsearchedit${N}"
    print "  ${D}    findsearch     -> findsearchedit${N}"
    print "  ${D}    locatesearch   -> locatesearchedit${N}"
    print ""
    print "  ${C}  Without ${M}edit${C}: opens the result immediately.${N}"
    print "  ${C}  With ${M}edit${C}: puts the path on your command line.${N}"
    print "  ${D}  This lets you compose: ${M}vim \$(zpwr filesearchedit)${N}"
    print ""
    print "  ${B}${Y}REAL-WORLD EXAMPLES${N}"
    print "  ${G}  # Find where \"ZPWR_VERBS\" is defined:${N}"
    print "  ${M}  zpwr wordsearch${N}"
    print "  ${D}  # type ZPWR_VERBS in fzf, browse the matches${N}"
    print ""
    print "  ${G}  # Quick grep for TODO comments:${N}"
    print "  ${M}  zpwr grep${N}"
    print "  ${D}  # type TODO, see every file that has one${N}"
    print ""
    print "  ${D}The search verbs are your eyes inside the codebase.${N}"
    print "  ${D}Use them before you reach for a GUI.${N}"
    print ""
}
