PAGE_TITLE="The Doctor Is In"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE DOCTOR IS IN ===${N}"
    print "  ${D}// every system needs a physician. yours lives at zpwr doctor. //${N}"
    print ""
    print "  ${C}Your shell is a living organism. It accumulates cruft, grows${N}"
    print "  ${C}tumors in PATH, and occasionally develops broken symlinks.${N}"
    print "  ${C}The doctor runs a full-body scan and tells you what hurts.${N}"
    print ""
    print "  ${B}${Y}INVOKE THE DOCTOR${N}"
    print "  ${M}  zpwr doctor${N}${D}              # full diagnostic scan${N}"
    print "  ${M}  zpwr doctor -h${N}${D}           # help with detailed check list${N}"
    print ""
    print "  ${B}${Y}WHAT IT CHECKS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}1. STALE .zwc FILES${N}"
    print "  ${D}     Compiled zsh files older than their source.${N}"
    print "  ${D}     Your shell is loading yesterday's code today.${N}"
    print "  ${D}     Fix: ${M}zpwr recompile${N}"
    print ""
    print "  ${G}2. ZCOMPDUMP FRESHNESS${N}"
    print "  ${D}     The completion dump file. If it is older than 1 week,${N}"
    print "  ${D}     tab completion may be missing new commands.${N}"
    print "  ${D}     Fix: ${M}zpwr regenzsh${N}"
    print ""
    print "  ${G}3. DUPLICATE PATH ENTRIES${N}"
    print "  ${D}     Every duplicate PATH entry is a wasted hash lookup.${N}"
    print "  ${D}     The doctor counts them and names the offenders.${N}"
    print "  ${D}     Fix: ${M}zpwr deduppaths${N}"
    print ""
    print "  ${G}4. DUPLICATE/MISSING FPATH ENTRIES${N}"
    print "  ${D}     Same disease, different organ. FPATH controls${N}"
    print "  ${D}     where autoloaded functions are found.${N}"
    print ""
    print "  ${G}5. BROKEN SYMLINKS${N}"
    print "  ${D}     Dangling symlinks in \$ZPWR. Every broken link is a${N}"
    print "  ${D}     source of cryptic errors at 3am.${N}"
    print ""
    print "  ${G}6. NAMED DIRECTORIES${N}"
    print "  ${D}     Invalid named dirs (~foo -> /nonexistent) and p10k${N}"
    print "  ${D}     pollution from auto_name_dirs leaking gitstatus vars.${N}"
    print ""
    print "  ${G}7. DEPENDENCIES${N}"
    print "  ${D}     Checks for: git, eza, fzf, tmux, perl, python3, zinit.${N}"
    print "  ${D}     Missing any? The doctor names names.${N}"
    print ""
    print "  ${G}8. HISTORY & BACKUPS${N}"
    print "  ${D}     Is HISTFILE present? How many backup copies exist${N}"
    print "  ${D}     in \$ZPWR_LOCAL/rcBackups? Zero backups = living dangerously.${N}"
    print ""
    print "  ${G}9. CONFIG SYMLINKS${N}"
    print "  ${D}     Checks .zshrc, .vimrc, .tmux.conf, .p10k.zsh.${N}"
    print "  ${D}     Are they symlinks into \$ZPWR? Or rogue files?${N}"
    print ""
    print "  ${B}${Y}READING THE RESULTS${N}"
    print "  ${G}  green checkmark${N}${D}  = healthy, move along${N}"
    print "  ${Y}  yellow warning${N}${D}   = degraded but functional${N}"
    print "  ${R}  red X${N}${D}            = broken, fix it now${N}"
    print ""
    print "  ${B}${Y}THE SIGNAL BAR${N}"
    print "  ${D}  At the bottom: a 10-block signal meter.${N}"
    print "  ${G}  ██████████${D}  = HEALTHY. All green. You are a clean machine.${N}"
    print "  ${Y}  ██████${D}░░░░  = WARNINGS. Stuff works but something is off.${N}"
    print "  ${R}  ██${D}░░░░░░░░  = CRITICAL. Your shell is on fire.${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr stale${N}${D}                # find stale .zwc, orphan caches, broken links${N}"
    print "  ${M}  zpwr pathaudit${N}${D}             # deep PATH/FPATH/MANPATH audit${N}"
    print "  ${M}  zpwr lint${N}${D}                  # shellcheck + zsh -n on all zpwr files${N}"
    print "  ${M}  zpwr startup${N}${D}               # per-function zprof breakdown${N}"
    print "  ${M}  zpwr ports${N}${D}                 # show listening ports with process info${N}"
    print ""
    print "  ${B}${Y}PRO MOVE: CRON IT${N}"
    print "  ${D}  Add ${M}zpwr doctor${D} to your weekly cron. Catch rot early.${N}"
    print "  ${D}  Pair it with ${M}zpwr recompile${D} for a full tune-up.${N}"
    print ""
}
