PAGE_TITLE="Tmux Prefix Keys: Special Operations"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< TMUX PREFIX KEYS: SPECIAL OPERATIONS >>>${N}"
    print "  ${D}multi-pane execution, URL picking, buffers, plugins.${N}"
    print ""
    print "  ${B}${Y}MULTI-PANE EXECUTION:${N}"
    print "  ${C}prefix Space${N}          ${D}run command in all panes (single)${N}"
    print "  ${C}prefix v${N}              ${D}run command in all panes (multi)${N}"
    print "  ${C}prefix b${N}              ${D}open URL/path in all panes${N}"
    print "  ${C}prefix g${N}              ${D}google search in all panes${N}"
    print ""
    print "  ${D}These source \$ZPWR/scripts/allPanes.zsh with different modes.${N}"
    print "  ${D}  Space -> single mode (one command per pane)${N}"
    print "  ${D}  v     -> multi mode (batch operations)${N}"
    print "  ${D}  b     -> single open (open URL in each pane)${N}"
    print "  ${D}  g     -> single google (search in each pane)${N}"
    print ""
    print "  ${B}${Y}URL HANDLING:${N}"
    print "  ${C}prefix e${N}              ${D}fzf URL picker -> open${N}"
    print "  ${C}prefix u${N}              ${D}fzf URL picker -> search${N}"
    print ""
    print "  ${D}Both use tmux-fzf-url plugin with 30s timeout.${N}"
    print ""
    print "  ${B}${Y}PASTE & BUFFERS:${N}"
    print "  ${C}prefix P${N}              ${D}paste buffer${N}"
    print "  ${C}prefix ]${N}              ${D}paste buffer (bracketed)${N}"
    print "  ${C}prefix =${N}              ${D}choose-buffer (fzf style)${N}"
    print "  ${C}prefix #${N}              ${D}list buffers${N}"
    print "  ${C}prefix Ctrl-v${N}         ${D}paste from system clipboard${N}"
    print ""
    print "  ${B}${Y}COPY MODE:${N}"
    print "  ${C}prefix [${N}              ${D}enter copy mode${N}"
    print "  ${C}prefix PgUp${N}           ${D}enter copy mode and page up${N}"
    print ""
    print "  ${B}${Y}PLUGIN MANAGEMENT (TPM):${N}"
    print "  ${C}prefix I${N}              ${D}install plugins${N}"
    print "  ${C}prefix U${N}              ${D}update plugins${N}"
    print "  ${C}prefix Alt-u${N}          ${D}clean unused plugins${N}"
    print ""
    print "  ${B}${Y}SEND PREFIX:${N}"
    print "  ${C}prefix Ctrl-a${N}         ${D}send prefix key to inner tmux${N}"
    print "  ${C}prefix Ctrl-]${N}         ${D}send literal Ctrl-]${N}"
    print ""
    print "  ${D}Use prefix Ctrl-a when nesting tmux sessions.${N}"
    print "  ${D}The outer session captures prefix, Ctrl-a forwards it.${N}"
    print ""
    print "  ${M}  // buffers are the wizard's memory${N}"
    print "  ${M}  // every copy is a spell stored for later${N}"
    print ""
}
