PAGE_TITLE="Emulate & Options"
PAGE_CHAPTER="CHAPTER 28: ZSH INTERNALS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== EMULATE & OPTIONS ===${N}"
    print "  ${D}// zsh has 200+ options. emulate -L zsh resets them all locally. //${N}"
    print "  ${C}Zsh options control fundamental behavior: globbing, word${N}"
    print "  ${C}splitting, quoting, history. ZPWR functions use emulate -L zsh${N}"
    print "  ${C}to guarantee a known environment regardless of user settings.${N}"
    print "  ${B}${Y}emulate -L zsh${N}"
    print "  ${M}  builtin emulate -L zsh${N}"
    print "  ${D}Resets ALL options to zsh defaults for the current function scope.${N}"
    print "  ${D}-L means local: options revert when the function returns.${N}"
    print "  ${D}Without this, a function might inherit noglob from the caller${N}"
    print "  ${D}and break globbing, or inherit shwordsplit and break arrays.${N}"
    print "  ${D}ZPWR functions start with this to be immune to the caller's state.${N}"
    print "  ${B}${Y}KEY OPTIONS IN ZPWR${N}"
    print "  ${G}  extendedglob${N}${D}      ## = one-or-more, (#i) = case-insensitive glob${N}"
    print "  ${D}                     ^pattern = negation. Essential for ZPWR globs.${N}"
    print "  ${G}  glob_dots${N}${D}         Dot files matched by * (no need for .*)${N}"
    print "  ${G}  globstarshort${N}${D}     **.c = **/*.c (recursive glob shorthand)${N}"
    print "  ${G}  braceccl${N}${D}          {abcd0-9} expands as character class${N}"
    print "  ${G}  rc_quotes${N}${D}         '' inside single quotes = literal single quote${N}"
    print "  ${G}  rc_expand_param${N}${D}   Array expansion includes prefix: xx\${arr} = xxA xxB${N}"
    print "  ${G}  nocaseglob${N}${D}        Globs are case-insensitive globally${N}"
    print "  ${G}  numeric_glob_sort${N}${D}  file1 file2 file10 sort numerically${N}"
    print "  ${G}  prompt_subst${N}${D}       Allow \$(...) and \${...} in prompt strings${N}"
    print "  ${G}  transient_rprompt${N}${D}  Right prompt only on current line${N}"
    print "  ${B}${Y}THE noshwordsplit DEFAULT${N}"
    print "  ${D}Bash splits unquoted variables on whitespace by default.${N}"
    print "  ${D}Zsh does NOT (noshwordsplit). This means:${N}"
    print "  ${M}  x=\"hello world\"; print \$x${N}${D}  -> one argument in zsh, two in bash${N}"
    print "  ${D}If a function inherits shwordsplit (e.g., from emulate sh),${N}"
    print "  ${D}arrays and parameter expansions break silently. Another reason${N}"
    print "  ${D}for emulate -L zsh.${N}"
    print "  ${B}${Y}THE local-IN-LOOP BUG${N}"
    print "  ${D}In zsh, 'local' inside a loop prints the variable value as${N}"
    print "  ${D}a side effect when the variable already exists:${N}"
    print "  ${M}  for i in 1 2 3; do local x=\$i; done${N}${D}  # prints x=1 x=2 x=3${N}"
    print "  ${D}This is because 'local' on an existing local acts like typeset,${N}"
    print "  ${D}which prints. Declare locals BEFORE loops, not inside them.${N}"
    print "  ${B}${Y}auto_name_dirs: REMOVED${N}"
    print "  ${D}This option auto-registers any parameter set to a directory${N}"
    print "  ${D}path as a named directory. Sounds nice, but p10k/gitstatus${N}"
    print "  ${D}set internal variables to paths, polluting the named dir table.${N}"
    print "  ${D}ZPWR removed it. Explicit hash -d in zpwrBindDirs handles it.${N}"
    print "  ${D}The comment in .zshrc: ${M}# auto_name_dirs removed: pollutes named${N}"
    print "  ${D}${M}# dirs with p10k/gitstatus internals${N}"
}
