PAGE_TITLE="Cache Search"
PAGE_CHAPTER="CHAPTER 8: ENVIRONMENT MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== CACHE SEARCH ===${N}"
    print "  ${D}// the environment is a haystack. these are your magnets. //${N}"
    print ""
    print "  ${C}zpwr maintains an environment cache for fast lookup.${N}"
    print "  ${C}These verbs let you search, inspect, and edit that cache${N}"
    print "  ${C}without grepping through raw variable dumps.${N}"
    print ""
    print "  ${B}${Y}ENVIRONMENTCACHESEARCH: FZF ENV NAVIGATION${N}"
    print "  ${M}  zpwr environmentcachesearch${N}${D}         # fzf through cached env${N}"
    print ""
    print "  ${D}  Opens an fzf interface over the environment cache.${N}"
    print "  ${D}  Type a few characters to filter. The cache includes:${N}"
    print "  ${D}  - All exported environment variables${N}"
    print "  ${D}  - ZPWR_* configuration variables${N}"
    print "  ${D}  - PATH and FPATH entries${N}"
    print "  ${D}  - Named directory mappings${N}"
    print ""
    print "  ${D}  This is faster than ${M}env | grep${D} because it uses the${N}"
    print "  ${D}  pre-built cache file rather than querying the live env.${N}"
    print ""
    print "  ${B}${Y}ENVACCEPT: ACCEPT A CACHE ENTRY${N}"
    print "  ${M}  zpwr envaccept${N}${D}                      # accept/apply cached env entry${N}"
    print ""
    print "  ${D}  After finding a variable in the cache, this verb${N}"
    print "  ${D}  applies it to your current session. Useful when the${N}"
    print "  ${D}  cache has a value you want but the live env does not.${N}"
    print ""
    print "  ${B}${Y}ENVEDIT: EDIT THE ENVIRONMENT${N}"
    print "  ${M}  zpwr envedit${N}${D}                        # open env cache in \$EDITOR${N}"
    print ""
    print "  ${D}  Opens the environment cache file in your editor.${N}"
    print "  ${D}  Make changes, save, and the cache is updated.${N}"
    print "  ${D}  This is the surgical approach: when you know${N}"
    print "  ${D}  exactly which variable needs tweaking.${N}"
    print ""
    print "  ${B}${Y}THE CACHE LIFECYCLE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  1. zpwr regenenvcache${N}${D}   builds the cache from live env${N}"
    print "  ${G}  2. environmentcachesearch${N}${D} fuzzy-searches the cache${N}"
    print "  ${G}  3. envaccept${N}${D}             applies an entry${N}"
    print "  ${G}  4. envedit${N}${D}               manual edits${N}"
    print ""
    print "  ${D}  The cache lives at \$ZPWR_LOCAL. It is regenerated during${N}"
    print "  ${D}  shell startup and when you run ${M}zpwr regenenvcache${D}.${N}"
    print ""
    print "  ${B}${Y}WORKFLOW EXAMPLE${N}"
    print "  ${D}  \"What is ZPWR_EDITOR set to?\"${N}"
    print "  ${M}  zpwr environmentcachesearch${N}${D}    # type 'EDITOR' in fzf${N}"
    print "  ${D}  Found it: ZPWR_EDITOR=nvim${N}"
    print ""
    print "  ${D}  \"I want to change a bunch of ZPWR_ vars.\"${N}"
    print "  ${M}  zpwr envedit${N}${D}                       # opens in \$EDITOR${N}"
    print "  ${D}  Edit the vars, save, done.${N}"
    print ""
    print "  ${D}  \"Something is off, rebuild the cache.\"${N}"
    print "  ${M}  zpwr regenenvcache${N}${D}                 # fresh cache from live env${N}"
    print ""
    print "  ${B}${Y}PRO TIP${N}"
    print "  ${D}  If you are debugging a missing env var, check two places:${N}"
    print "  ${D}  ${M}zpwr environmentcachesearch${D} (cached) and ${M}zpwr eva${D} (live).${N}"
    print "  ${D}  If cache has it but live does not, run ${M}zpwr regenenvcache${D}.${N}"
    print ""
}
