PAGE_TITLE="Cleanup Arsenal"
PAGE_CHAPTER="CHAPTER 9: THE JANITOR'S CLOSET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== CLEANUP ARSENAL ===${N}"
    print "  ${D}// 14 verbs to sweep the floor //${N}"
    print ""
    print "  ${C}Clean directories, caches, temp files, logs, and git${N}"
    print "  ${C}state. From surgical precision to nuclear wipe.${N}"
    print ""
    print "  ${B}${Y}DIRECTORY CLEANING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cleandirs${N}${D}             # clear all \$ZPWR_DIRS_CLEAN${N}"
    print "  ${M}  zpwr cleandirsandtemp${N}${D}      # clear dirs and temp${N}"
    print "  ${M}  zpwr cleanall${N}${D}              # clear dirs, temp and cache${N}"
    print "  ${M}  zpwr cleantemp${N}${D}             # clean all zpwr temp files${N}"
    print ""
    print "  ${B}${Y}CACHE CLEANING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cleancache${N}${D}            # clean all zpwr cache files${N}"
    print "  ${M}  zpwr cleancompcache${N}${D}        # clean all zpwr compsys cache files${N}"
    print "  ${M}  zpwr cleangitcache${N}${D}         # clean all git repo cache files${N}"
    print "  ${M}  zpwr cleangitdirtycache${N}${D}    # clean git repo dirty cache files${N}"
    print "  ${M}  zpwr cleangitcleancache${N}${D}    # clean git repo clean cache files${N}"
    print ""
    print "  ${B}${Y}LOG & UPDATE CLEANING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cleanlog${N}${D}              # clear \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr cleanrefreshupdate${N}${D}    # clean, refresh zwc, update deps${N}"
    print "  ${M}  zpwr cleanupdatedeps${N}${D}       # clean and update deps${N}"
    print ""
    print "  ${B}${Y}DO EVERYTHING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr a${N}${D}                     # banner, counts, clean, refresh, test, update${N}"
    print "  ${M}  zpwr all${N}${D}                   # banner, counts, clean, refresh, test, update${N}"
    print ""
}
