PAGE_TITLE="Text Operations"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== TEXT OPERATIONS ===${N}"
    print "  ${D}// find and replace. rename. count. transform. //${N}"
    print ""
    print "  ${C}Text manipulation is the bread and butter of shell work.${N}"
    print "  ${C}These verbs handle the common cases: renaming files,${N}"
    print "  ${C}replacing strings, counting lines, and transforming text.${N}"
    print ""
    print "  ${B}${Y}RENAME: FILE RENAMING${N}"
    print "  ${M}  zpwr rename${N}${D}                         # rename files with patterns${N}"
    print ""
    print "  ${D}  Renames files using pattern matching. Safer than raw mv${N}"
    print "  ${D}  because it shows what will happen before doing it.${N}"
    print ""
    print "  ${B}${Y}REPLACER: FIND AND REPLACE IN FILES${N}"
    print "  ${M}  zpwr replacer${N}${D}                       # search and replace in files${N}"
    print ""
    print "  ${D}  Performs find-and-replace across multiple files.${N}"
    print "  ${D}  The codebase refactoring tool. When you renamed a${N}"
    print "  ${D}  function and need to update every call site.${N}"
    print ""
    print "  ${B}${Y}CHANGENAME: RENAME WITH HISTORY${N}"
    print "  ${M}  zpwr changename${N}${D}                     # rename with tracking${N}"
    print ""
    print "  ${D}  Renames files or directories with additional tracking.${N}"
    print "  ${D}  More sophisticated than basic rename for complex${N}"
    print "  ${D}  renaming operations.${N}"
    print ""
    print "  ${B}${Y}CHANGENAMEZPWR: ZPWR-SPECIFIC RENAME${N}"
    print "  ${M}  zpwr changenamezpwr${N}${D}                 # rename within zpwr codebase${N}"
    print ""
    print "  ${D}  Specialized rename for zpwr function and file names.${N}"
    print "  ${D}  Handles the autoload naming convention (file name must${N}"
    print "  ${D}  match function name) and updates references.${N}"
    print ""
    print "  ${B}${Y}LINECOUNT: COUNT LINES${N}"
    print "  ${M}  zpwr linecount${N}${D}                      # count lines in files${N}"
    print ""
    print "  ${D}  Enhanced line counting with formatting and totals.${N}"
    print "  ${D}  Shows per-file counts and a grand total.${N}"
    print "  ${D}  More informative than raw ${M}wc -l${D}.${N}"
    print ""
    print "  ${B}${Y}PRE & POST: TEXT INJECTION${N}"
    print "  ${M}  zpwr pre${N}${D}                            # prepend text to input${N}"
    print "  ${M}  zpwr post${N}${D}                           # append text to input${N}"
    print ""
    print "  ${D}  Pipe filters that add text before or after each line.${N}"
    print "  ${D}  Useful in pipelines for formatting:${N}"
    print "  ${M}  ls | zpwr pre '  - '${N}${D}               # bullet-point file list${N}"
    print "  ${M}  cat urls.txt | zpwr post '/api/v1'${N}${D}  # append to each URL${N}"
    print ""
    print "  ${B}${Y}URLSAFE: URL ENCODING${N}"
    print "  ${M}  zpwr urlsafe${N}${D}                        # URL-encode a string${N}"
    print ""
    print "  ${D}  Converts special characters to percent-encoded form.${N}"
    print "  ${D}  Spaces become %20, ampersands become %26, etc.${N}"
    print "  ${D}  Essential when constructing URLs from user input.${N}"
    print ""
    print "  ${B}${Y}THE TEXT PIPELINE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  zpwr text verbs compose naturally in pipelines:${N}"
    print ""
    print "  ${M}  cat data.txt | zpwr pre 'ROW: ' | zpwr post ' ;'${N}"
    print "  ${D}  Result: ${G}ROW: line1 ;${N}"
    print "  ${D}          ${G}ROW: line2 ;${N}"
    print ""
    print "  ${D}  Rename all .txt to .md:${N}"
    print "  ${M}  zpwr rename${N}${D}                         # interactive rename${N}"
    print ""
    print "  ${D}  Replace 'oldFunc' with 'newFunc' across the codebase:${N}"
    print "  ${M}  zpwr replacer${N}${D}                       # interactive replace${N}"
    print ""
}
