PAGE_TITLE="Building Your Own ARB Verbs"
PAGE_CHAPTER="CHAPTER 29: ARB ARCHITECTURE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== BUILDING YOUR OWN ARB VERBS ===${N}"
    print "  ${D}// once you grok the pattern, everything becomes arb-able. //${N}"
    print "  ${C}The generate | arb --fzf | action pattern is infinitely extensible.${N}"
    print "  ${C}Here's how to build your own arb-powered verbs.${N}"
    print "  ${B}${Y}THE PATTERN${N}"
    print "  ${M}  <generator> | arb --fzf [--preview '<preview-cmd>'] | <consumer>${N}"
    print "  ${D}Generator: anything that outputs lines (find, git, docker, etc.)${N}"
    print "  ${D}Preview: command that shows detail for highlighted line (\{\})${N}"
    print "  ${D}Consumer: action on selected lines (xargs, while read, eval)${N}"
    print "  ${B}${Y}EXAMPLE: ARB THROUGH DOCKER CONTAINERS${N}"
    print "  ${M}  function arb-docker() {${N}"
    print "  ${M}    docker ps -a --format '{{.ID}} {{.Names}} {{.Status}}' |${N}"
    print "  ${M}      arb --fzf --preview 'docker inspect {1} | head -50' |${N}"
    print "  ${M}      awk '{print \$1}' |${N}"
    print "  ${M}      xargs -r docker logs --tail 100${N}"
    print "  ${M}  }${N}"
    print "  ${D}Generator: docker ps. Preview: docker inspect. Consumer: docker logs.${N}"
    print "  ${B}${Y}EXAMPLE: ARB THROUGH TMUX SESSIONS${N}"
    print "  ${M}  function arb-tmux-session() {${N}"
    print "  ${M}    tmux list-sessions -F '#{session_name}: #{session_windows} windows' |${N}"
    print "  ${M}      arb --fzf --preview 'tmux list-windows -t {1}' |${N}"
    print "  ${M}      cut -d: -f1 |${N}"
    print "  ${M}      xargs tmux switch-client -t${N}"
    print "  ${M}  }${N}"
    print "  ${D}Generator: tmux list-sessions. Consumer: tmux switch-client.${N}"
    print "  ${B}${Y}THE ACCEPT vs EDIT PATTERN${N}"
    print "  ${D}ZPWR verbs come in two flavors:${N}"
    print "  ${G}  Accept verbs${N}${D}  Execute the selection immediately${N}"
    print "  ${D}    Example: verbsfzf selects a verb and runs it.${N}"
    print "  ${G}  Edit verbs${N}${D}    Insert the selection into \$BUFFER for editing${N}"
    print "  ${D}    Example: filesearch inserts the path into your command line.${N}"
    print "  ${D}The difference is in the consumer. Accept uses eval/exec.${N}"
    print "  ${D}Edit uses BUFFER=\$selection + zle redisplay.${N}"
    print "  ${B}${Y}MAKING IT A ZLE WIDGET${N}"
    print "  ${D}To bind your arb --fzf verb to a key:${N}"
    print "  ${M}  function my-arb-widget() {${N}"
    print "  ${M}    BUFFER=\$(my-generator | arb --fzf)${N}"
    print "  ${M}    CURSOR=\${#BUFFER}${N}"
    print "  ${M}    zle redisplay${N}"
    print "  ${M}  }${N}"
    print "  ${M}  zle -N my-arb-widget${N}"
    print "  ${M}  bindkey '^F^X' my-arb-widget${N}"
    print "  ${D}Now Ctrl-F Ctrl-X triggers your custom arb --fzf workflow.${N}"
    print "  ${B}${Y}TIPS FOR GOOD ARB EXPERIENCES${N}"
    print "  ${D}  - Use --ansi if your generator outputs color codes${N}"
    print "  ${D}  - Use --delimiter and --nth to control what arb --fzf matches on${N}"
    print "  ${D}  - Use -m for multi-select (toggle with Tab)${N}"
    print "  ${D}  - Use --header for context hints at the top${N}"
    print "  ${D}  - Preview window size: --preview-window=right:50%:wrap${N}"
    print "  ${D}  - Test with: ${M}echo 'a\nb\nc' | arb --fzf --preview 'echo {}'${N}"
}
