PAGE_TITLE="Snapshots & Time Travel"
PAGE_CHAPTER="CHAPTER 8: ENVIRONMENT MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== SNAPSHOTS & TIME TRAVEL ===${N}"
    print "  ${D}// save your universe. restore it when everything goes wrong. //${N}"
    print ""
    print "  ${C}The ${M}snapshot${C} verb captures your entire terminal environment${N}"
    print "  ${C}to a portable directory. The ${M}restore${C} verb brings it back.${N}"
    print "  ${C}This is git for your shell state.${N}"
    print ""
    print "  ${B}${Y}TAKING A SNAPSHOT${N}"
    print "  ${M}  zpwr snapshot${N}${D}                       # timestamp-named snapshot${N}"
    print "  ${M}  zpwr snapshot myproject${N}${D}              # named snapshot${N}"
    print "  ${M}  zpwr snapshot before-refactor${N}${D}        # meaningful name${N}"
    print ""
    print "  ${B}${Y}WHAT GETS CAPTURED${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  hash dirs${N}${D}         named directory mappings (hash -d)${N}"
    print "  ${G}  aliases${N}${D}           regular + global + suffix aliases${N}"
    print "  ${G}  env vars${N}${D}          all exported variables (secrets excluded)${N}"
    print "  ${G}  zpwr vars${N}${D}         ZPWR_VARS associative array${N}"
    print "  ${G}  functions${N}${D}         user function count tracking${N}"
    print "  ${G}  history${N}${D}           full shell history dump${N}"
    print "  ${G}  tmux${N}${D}             sessions, windows, panes, resurrect state${N}"
    print "  ${G}  vim sessions${N}${D}      saved vim session files${N}"
    print "  ${G}  dir stack${N}${D}         current directory and pushd stack${N}"
    print "  ${G}  git status${N}${D}        branch, commit, dirty state of cwd${N}"
    print ""
    print "  ${D}  Storage: ${C}\$ZPWR_LOCAL/snapshots/<name>/${N}"
    print "  ${D}  Each snapshot is a directory of plain zsh files.${N}"
    print "  ${D}  Human-readable. Sourceable. Portable.${N}"
    print ""
    print "  ${B}${Y}RESTORING A SNAPSHOT${N}"
    print "  ${M}  zpwr restore${N}${D}                        # list available snapshots${N}"
    print "  ${M}  zpwr restore myproject${N}${D}               # restore everything${N}"
    print "  ${M}  zpwr restore myproject aliases env${N}${D}    # restore only aliases+env${N}"
    print "  ${M}  zpwr restore myproject dirs${N}${D}           # just cd to saved pwd${N}"
    print ""
    print "  ${B}${Y}SELECTIVE RESTORE COMPONENTS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  all${N}${D}       everything (default when no component given)${N}"
    print "  ${C}  hash${N}${D}      named directories only${N}"
    print "  ${C}  aliases${N}${D}   regular, global, suffix aliases${N}"
    print "  ${C}  env${N}${D}       environment variables${N}"
    print "  ${C}  tmux${N}${D}      stage tmux-resurrect file (press prefix+Ctrl-r)${N}"
    print "  ${C}  vim${N}${D}       vim session files to ~/.vim/sessions${N}"
    print "  ${C}  history${N}${D}   merge snapshot history into current session${N}"
    print "  ${C}  dirs${N}${D}      cd to the saved working directory${N}"
    print ""
    print "  ${B}${Y}WHEN TO USE SNAPSHOTS${N}"
    print "  ${D}  ${G}Before a big update:${N}${D}     zpwr snapshot before-update${N}"
    print "  ${D}  ${G}Before experiments:${N}${D}      zpwr snapshot stable-state${N}"
    print "  ${D}  ${G}Switching projects:${N}${D}      zpwr snapshot projectA${N}"
    print "  ${D}  ${G}New machine setup:${N}${D}       copy snapshot dir, restore on new host${N}"
    print ""
    print "  ${R}${B}NOTE:${N}${R} Sensitive vars (PASSWORD, SECRET, TOKEN, AWS_SECRET*,${N}"
    print "  ${R}GITHUB_TOKEN) are automatically excluded from env snapshots.${N}"
    print "  ${R}Your secrets stay secret.${N}"
    print ""
    print "  ${D}  History merge is additive -- it does not overwrite your${N}"
    print "  ${D}  current history. It uses ${M}fc -R${D} to load entries.${N}"
    print ""
}
