PAGE_TITLE="All 408 Verbs T-Z + Epilogue"
PAGE_CHAPTER="CHAPTER 25: THE COMPLETE REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ALL 408 VERBS: refreshzwc through zstyle (3/3) >>>${N}"
    print "  ${D}the final stretch. the end of the alphabet. the beginning of mastery.${N}"
    print ""
    print "  ${C}refreshzwc${N}                 ${D}refresh compiled wordcode${N}"
    print "  ${C}regen${N}                      ${D}regenerate single component${N}"
    print "  ${C}regenall${N}                   ${D}regenerate everything${N}"
    print "  ${C}regenconfiglinks${N}           ${D}regenerate config symlinks${N}"
    print "  ${C}regenctags${N}                 ${D}regenerate ctags${N}"
    print "  ${C}regenenvcache${N}              ${D}regenerate env cache${N}"
    print "  ${C}regengitdirtyrepocache${N}     ${D}regen dirty repo cache${N}"
    print "  ${C}regengitrepocache${N}          ${D}regen git repo cache${N}"
    print "  ${C}regengtags${N}                 ${D}regenerate gtags${N}"
    print "  ${C}regengtagspygments${N}         ${D}regen gtags + pygments${N}"
    print "  ${C}regengtagstype${N}             ${D}regen gtags by type${N}"
    print "  ${C}regenhistory${N}               ${D}regenerate history${N}"
    print "  ${C}regenkeybindings${N}           ${D}regen keybindings${N}"
    print "  ${C}regenpowerline${N}             ${D}regenerate powerline${N}"
    print "  ${C}regenzsh${N}                   ${D}regenerate zsh config${N}"
    print "  ${C}reload${N}                     ${D}reload shell config${N}"
    print "  ${C}relpath${N}                    ${D}get relative path${N}"
    print "  ${C}rename${N}                     ${D}rename files${N}"
    print "  ${C}replacer${N}                   ${D}find and replace${N}"
    print "  ${C}replay${N}                     ${D}replay commands${N}"
    print "  ${C}repo${N}                       ${D}repository info${N}"
    print "  ${C}reset${N}                      ${D}reset shell state${N}"
    print "  ${C}restart${N}                    ${D}restart shell${N}"
    print "  ${C}restore${N}                    ${D}restore configuration${N}"
    print "  ${C}restorehistory${N}             ${D}restore history backup${N}"
    print "  ${C}return2${N}                    ${D}return to previous dir${N}"
    print "  ${C}reveal${N}                     ${D}open repo in browser${N}"
    print "  ${C}revealrecurse${N}              ${D}reveal recursively${N}"
    print "  ${C}reverse${N}                    ${D}reverse input${N}"
    print "  ${C}rmconfiglinks${N}              ${D}remove config symlinks${N}"
    print "  ${C}rvs${N}                        ${D}reverse shortcut${N}"
    print "  ${C}scriptcount${N}                ${D}count scripts${N}"
    print "  ${C}scriptlist${N}                 ${D}list all scripts${N}"
    print "  ${C}scriptnew${N}                  ${D}create new script${N}"
    print "  ${C}scripts${N}                    ${D}browse scripts${N}"
    print "  ${C}scripttopdf${N}                ${D}convert script to PDF${N}"
    print "  ${C}testsall${N}                   ${D}run all env tests (alias: testall)${N}"
    print "  ${C}upload${N}                     ${D}upload file with curl${N}"
    print "  ${C}verbsedit${N}                  ${D}edit verb selection${N}"
    print "  ${C}zpwrCloneToForked${N}          ${D}clone zpwr to forked dir${N}"
    print "  ${C}zpwrgithub${N}                 ${D}open zpwr GitHub page${N}"
    print ""
    print "  ${D}Run zpwr verbs for the complete live list.${N}"
}
