PAGE_TITLE="GitHub & Travis CI"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GITHUB & TRAVIS CI ===${N}"
    print "  ${D}// 16 verbs for the hosted world //${N}"
    print ""
    print "  ${C}Verbs for GitHub repo management, contribution counting,${N}"
    print "  ${C}and Travis CI browser integration.${N}"
    print ""
    print "  ${B}${Y}GITHUB NAVIGATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gh${N}${D}                    # open github profile${N}"
    print "  ${M}  zpwr github${N}${D}                # open github profile${N}"
    print "  ${M}  zpwr mygithub${N}${D}              # open github profile${N}"
    print "  ${M}  zpwr ghz${N}${D}                   # open zpwr github repo${N}"
    print "  ${M}  zpwr githubzpwr${N}${D}            # open zpwr github repo${N}"
    print "  ${M}  zpwr zpwrgithub${N}${D}            # open zpwr github${N}"
    print ""
    print "  ${B}${Y}GITHUB REPO MANAGEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr githubcreate${N}${D}          # create remote github repo${N}"
    print "  ${M}  zpwr githubdelete${N}${D}          # delete remote github repo${N}"
    print "  ${M}  zpwr hc${N}${D}                    # create remote github repo${N}"
    print "  ${M}  zpwr hd${N}${D}                    # delete remote github repo${N}"
    print ""
    print "  ${B}${Y}CONTRIBUTION STATS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr ghcontribcount${N}${D}        # count github contribs in last year${N}"
    print "  ${M}  zpwr githubcontribcount${N}${D}    # count github contribs in last year${N}"
    print ""
    print "  ${B}${Y}TRAVIS CI${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr travis${N}${D}                # open current travis project${N}"
    print "  ${M}  zpwr travisbranch${N}${D}          # open current travis branches${N}"
    print "  ${M}  zpwr travisbuild${N}${D}           # open current travis builds${N}"
    print "  ${M}  zpwr travispr${N}${D}              # open current travis PRs${N}"
    print ""
}
