PAGE_TITLE="Git Operations Reference"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT OPERATIONS REFERENCE ===${N}"
    print "  ${D}// 33 verbs for git mastery //${N}"
    print ""
    print "  ${C}Core git verbs for commits, config, history rewriting,${N}"
    print "  ${C}contributor stats, and multi-repo operations.${N}"
    print ""
    print "  ${B}${Y}COMMIT & PUSH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitcommit${N}${D}             # commit and push with arg message${N}"
    print "  ${M}  zpwr gitcommitcount${N}${D}        # count commits in current repo${N}"
    print "  ${M}  zpwr gitcommits${N}${D}            # search git commits with fzf${N}"
    print "  ${M}  zpwr clone${N}${D}                 # clone and cd to arg${N}"
    print ""
    print "  ${B}${Y}CONFIG & IGNORES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitconfig${N}${D}             # edit git config file${N}"
    print "  ${M}  zpwr gitglobalconfig${N}${D}       # edit git config file${N}"
    print "  ${M}  zpwr gitignore${N}${D}             # \$EDITOR ~/.git/info/exclude${N}"
    print "  ${M}  zpwr gitignores${N}${D}            # edit git ignores file${N}"
    print "  ${M}  zpwr gitglobalignores${N}${D}      # edit git ignores file${N}"
    print ""
    print "  ${B}${Y}EMAIL & HISTORY REWRITING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitemail${N}${D}              # change email with git filter-branch${N}"
    print "  ${M}  zpwr gitcemail${N}${D}             # change committer email${N}"
    print "  ${M}  zpwr gitaemail${N}${D}             # change author email${N}"
    print "  ${M}  zpwr gitclearcommit${N}${D}        # remove matching commits from history${N}"
    print "  ${M}  zpwr gitclearcache${N}${D}         # clear old git refs and objects${N}"
    print "  ${M}  zpwr gitclearfile${N}${D}          # rm file from all git refs/objects${N}"
    print ""
    print "  ${B}${Y}STATS & INFO${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitcontribcount${N}${D}       # count git contributions by author${N}"
    print "  ${M}  zpwr gitcontribcountdirs${N}${D}   # contributions by author for dirs${N}"
    print "  ${M}  zpwr gitcontribcountlines${N}${D}  # count lines contributed by author${N}"
    print "  ${M}  zpwr gittotallines${N}${D}         # total line count of git files${N}"
    print "  ${M}  zpwr gitlargest${N}${D}            # show largest files stored by git${N}"
    print "  ${M}  zpwr gitremotes${N}${D}            # list all git remotes${N}"
    print "  ${M}  zpwr gitdir${N}${D}                # check if pwd is git dir${N}"
    print "  ${M}  zpwr gitwho${N}${D}                # aggregate contributor stats${N}"
    print "  ${M}  zpwr gitsearch${N}${D}             # search for regex in git log${N}"
    print ""
    print "  ${B}${Y}MULTI-REPO & TAGS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitforalldir${N}${D}          # run cmd in all git dirs${N}"
    print "  ${M}  zpwr gitfordirdevelop${N}${D}      # git wipe to develop in git dirs${N}"
    print "  ${M}  zpwr gitfordirmain${N}${D}         # git wipe to main in git dirs${N}"
    print "  ${M}  zpwr gitupdatefordir${N}${D}       # run git updates in all git dirs${N}"
    print "  ${M}  zpwr gitzfordir${N}${D}            # git wipe on branch in git dirs${N}"
    print "  ${M}  zpwr gitzfordirdevelop${N}${D}     # z and git wipe to develop${N}"
    print "  ${M}  zpwr gitzfordirmain${N}${D}        # z and git wipe to main${N}"
    print "  ${M}  zpwr gitupdatetag${N}${D}          # print tag and latest msg${N}"
    print "  ${M}  zpwr gitedittag${N}${D}            # print tag to \$BUFFER${N}"
    print ""
}
