PAGE_TITLE="Backup & Restore"
PAGE_CHAPTER="CHAPTER 11: MONITORING & AUTOMATION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== BACKUP & RESTORE ===${N}"
    print "  ${D}// your history is priceless. these verbs are the insurance policy. //${N}"
    print ""
    print "  ${C}Your shell history is years of accumulated knowledge:${N}"
    print "  ${C}every command you ran, every fix you found at 2am, every${N}"
    print "  ${C}pipeline you crafted. Losing it is losing institutional${N}"
    print "  ${C}memory. These verbs prevent that.${N}"
    print ""
    print "  ${B}${Y}BACKUP: THE GENERAL BACKUP${N}"
    print "  ${M}  zpwr backup${N}${D}                         # backup zpwr configuration${N}"
    print ""
    print "  ${D}  Creates a timestamped backup of zpwr configuration files.${N}"
    print "  ${D}  This captures your local settings, tokens, and any${N}"
    print "  ${D}  customizations in \$ZPWR_LOCAL.${N}"
    print ""
    print "  ${D}  Backup destination: \$ZPWR_LOCAL/rcBackups/${N}"
    print "  ${D}  Each backup is timestamped so you can have many.${N}"
    print ""
    print "  ${B}${Y}BACKUPHISTORY: THE HISTORY VAULT${N}"
    print "  ${M}  zpwr backuphistory${N}${D}                  # backup HISTFILE${N}"
    print ""
    print "  ${D}  Copies your HISTFILE to the backup directory with a${N}"
    print "  ${D}  timestamp. This is the most important backup in zpwr.${N}"
    print ""
    print "  ${D}  Your HISTFILE can be corrupted by:${N}"
    print "  ${G}  - Power loss${N}${D} during write${N}"
    print "  ${G}  - Concurrent sessions${N}${D} fighting over the file${N}"
    print "  ${G}  - Disk full${N}${D} causing truncated writes${N}"
    print "  ${G}  - Bad .zsh_history format${N}${D} from import/merge${N}"
    print ""
    print "  ${D}  A weekly ${M}zpwr backuphistory${D} gives you a safety net.${N}"
    print ""
    print "  ${B}${Y}RESTOREHISTORY: THE TIME MACHINE${N}"
    print "  ${M}  zpwr restorehistory${N}${D}                 # restore from backup${N}"
    print ""
    print "  ${D}  Restores HISTFILE from the most recent backup.${N}"
    print "  ${D}  Use when your history is corrupted or accidentally${N}"
    print "  ${D}  truncated.${N}"
    print ""
    print "  ${D}  The restore process:${N}"
    print "  ${G}  1.${N}${D} Finds the latest backup in \$ZPWR_LOCAL/rcBackups${N}"
    print "  ${G}  2.${N}${D} Backs up the current (possibly broken) HISTFILE${N}"
    print "  ${G}  3.${N}${D} Copies the backup over HISTFILE${N}"
    print "  ${G}  4.${N}${D} Reloads history with fc -R${N}"
    print ""
    print "  ${B}${Y}SNAPSHOTS VS BACKUPS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  snapshot${N}${D}          captures full env state (aliases, vars, tmux)${N}"
    print "  ${C}  backup${N}${D}            copies config files to safety${N}"
    print "  ${C}  backuphistory${N}${D}     specifically targets HISTFILE${N}"
    print ""
    print "  ${D}  Use snapshots for environment state.${N}"
    print "  ${D}  Use backups for file safety.${N}"
    print "  ${D}  They complement each other.${N}"
    print ""
    print "  ${B}${Y}THE SAFETY PROTOCOL${N}"
    print "  ${D}  Before a big change:${N}"
    print "  ${M}    zpwr snapshot before-change${N}"
    print "  ${M}    zpwr backuphistory${N}"
    print "  ${M}    zpwr backup${N}"
    print ""
    print "  ${D}  Now you have three layers of protection:${N}"
    print "  ${D}  env snapshot, history backup, and config backup.${N}"
    print "  ${D}  If the change goes sideways, you can recover everything.${N}"
    print ""
    print "  ${B}${Y}CRON IT${N}"
    print "  ${D}  Add to your crontab (${M}crontab -e${D}):${N}"
    print "  ${M}  0 3 * * 0 zsh -c 'source ~/.zshrc; zpwr backuphistory'${N}"
    print "  ${D}  Every Sunday at 3am. Automatic insurance.${N}"
    print ""
}
