PAGE_TITLE="Autoload System"
PAGE_CHAPTER="CHAPTER 21: ZPWR ENVIRONMENT VARIABLES"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< THE AUTOLOAD SYSTEM — LAZY LOADING FOR HACKERS >>>${N}"
    print "  ${D}why load everything when you can load nothing until needed?${N}"
    print ""
    print "  ${C}Zsh autoloading is the secret to ZPWR's fast startup.${N}"
    print "  ${C}Functions are not loaded into memory until you call them.${N}"
    print "  ${C}The shell knows they exist, but their code stays on disk${N}"
    print "  ${C}until the moment of invocation. Maximum laziness. Maximum speed.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_AUTOLOAD — THE FUNCTION WAREHOUSE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_AUTOLOAD${N}${D}   # \$ZPWR/autoload${N}"
    print "  ${G}The root of the autoload tree. Every file in this tree${N}"
    print "  ${G}becomes a function name. The filename IS the function.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_AUTOLOAD_COMMON — CROSS-PLATFORM FUNCTIONS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_AUTOLOAD_COMMON${N}${D}   # \$ZPWR/autoload/common${N}"
    print "  ${G}Functions that work on every OS. The common denominator.${N}"
    print "  ${G}macOS, Linux, BSD — these functions do not care.${N}"
    print ""
    print "  ${B}${Y}HOW AUTOLOADING WORKS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  1. ${N}Zsh scans \$fpath directories at startup${N}"
    print "  ${C}  2. ${N}Each filename is registered as a function stub${N}"
    print "  ${C}  3. ${N}When you call the function, zsh reads the file${N}"
    print "  ${C}  4. ${N}The file contents replace the stub${N}"
    print "  ${C}  5. ${N}The function executes with the loaded code${N}"
    print ""
    print "  ${D}  This means hundreds of autoload stubs cost near-zero at startup.${N}"
    print "  ${D}  Only the ones you actually use consume memory.${N}"
    print ""
    print "  ${B}${Y}THE COMPILE ACCELERATION:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr compile${N}${D}       # compile autoloads to .zwc${N}"
    print "  ${M}  zpwr recompile${N}${D}     # recompile all${N}"
    print "  ${M}  zpwr uncompile${N}${D}     # remove compiled files${N}"
    print "  ${G}Compiled .zwc files load faster than raw source.${N}"
    print "  ${G}ZPWR compiles its autoload dirs into wordcode files.${N}"
    print "  ${G}It is like bytecode for your shell functions.${N}"
    print ""
    print "  ${B}${G}INSPECTION VERBS:${N}"
    print "  ${M}  zpwr autoload${N}${D}          show the autoload system${N}"
    print "  ${M}  zpwr autoloadcount${N}${D}     count autoloaded functions${N}"
    print "  ${M}  zpwr autoloadlist${N}${D}      list all autoloaded functions${N}"
    print ""
    print "  ${D}  // the fastest code is code that never runs${N}"
    print "  ${D}  // autoloading is the art of deferred execution${N}"
    print "  ${D}  // 400 functions, zero startup cost. that is the deal.${N}"
    print ""
}
