PAGE_TITLE="Miscellaneous Arsenal (2/2)"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== MISCELLANEOUS ARSENAL (2/2) ===${N}"
    print "  ${D}// looping, testing, system, and services //${N}"
    print ""
    print "  ${B}${Y}LOOPING & BACKGROUND${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr background${N}${D}            # run arg in background${N}"
    print "  ${M}  zpwr for${N}${D}                   # run first arg times for command${N}"
    print "  ${M}  zpwr for10${N}${D}                 # run 10 times for command${N}"
    print "  ${M}  zpwr fordir${N}${D}                # run first arg in following dirs${N}"
    print "  ${M}  zpwr fordirupdate${N}${D}          # run git updaters in following dirs${N}"
    print "  ${M}  zpwr whiletrue${N}${D}             # run command forever${N}"
    print "  ${M}  zpwr whilesleep${N}${D}            # run command and sleep N seconds${N}"
    print ""
    print "  ${B}${Y}TESTING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr test${N}${D}                  # run all zpwr tests${N}"
    print "  ${M}  zpwr tests${N}${D}                 # run all zpwr tests${N}"
    print "  ${M}  zpwr testall${N}${D}               # run all env tests${N}"
    print "  ${M}  zpwr testsall${N}${D}              # run all env tests${N}"
    print ""
    print "  ${B}${Y}SYSTEM & MISC${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr curl${N}${D}                  # custom curl with cleaned output${N}"
    print "  ${M}  zpwr deduppaths${N}${D}            # deduplicate PATH fpath manpath${N}"
    print "  ${M}  zpwr edit${N}${D}                  # exec \$EDITOR${N}"
    print "  ${M}  zpwr editor${N}${D}                # exec \$EDITOR${N}"
    print "  ${M}  zpwr install${N}${D}               # run configure, make, make install${N}"
    print "  ${M}  zpwr loadjenv${N}${D}              # lazy load jenv${N}"
    print "  ${M}  zpwr prettyprint${N}${D}           # pretty print with color${N}"
    print "  ${M}  zpwr altprettyprint${N}${D}        # pretty with alternating color${N}"
    print "  ${M}  zpwr reset${N}${D}                 # reset repo to latest main${N}"
    print "  ${M}  zpwr reveal${N}${D}                # show remote repo in browser${N}"
    print "  ${M}  zpwr revealrecurse${N}${D}         # recursively reveal hidden dirs${N}"
    print "  ${M}  zpwr rmconfiglinks${N}${D}         # remove sym links to \$HOME${N}"
    print "  ${M}  zpwr startauto${N}${D}             # start autocomplete${N}"
    print "  ${M}  zpwr stopauto${N}${D}              # stop autocomplete${N}"
    print "  ${M}  zpwr timer${N}${D}                 # timer one or more commands${N}"
    print "  ${M}  zpwr uninstall${N}${D}             # uninstall all zpwr configs${N}"
    print "  ${M}  zpwr post${N}${D}                  # postfix all output${N}"
    print "  ${M}  zpwr pre${N}${D}                   # prefix all output${N}"
    print "  ${M}  zpwr zpwrCloneToForked${N}${D}     # clone repo to \$ZPWR_FORKED_DIR${N}"
    print ""
    print "  ${B}${Y}SYSTEMD SERVICES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr serviceup${N}${D}             # start and enable systemd service${N}"
    print "  ${M}  zpwr servicedown${N}${D}           # stop and disable systemd service${N}"
    print "  ${M}  zpwr restart${N}${D}               # restart zpwr systemd service${N}"
    print ""
}
