PAGE_TITLE="GRC: Generic Colorizer"
PAGE_CHAPTER="CHAPTER 42: COLORIZATION STACK"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== GRC: GENERIC COLORIZER ===${N}"
    print "  ${D}because monochrome ls is a crime against humanity${N}"
    print "  ${B}${Y}WHAT IS GRC?${N}"
    print "  ${D}  grc wraps commands and adds color output via regex rules.${N}"
    print "  ${D}  It reads a config file that maps patterns to colors.${N}"
    print "  ${D}  Any command's output can be colorized. Zero modifications.${N}"
    print "  ${B}${Y}GRC IN zpwrListNoClear${N}"
    print "  ${D}  The fallback chain when listing files:${N}"
    print "  ${G}  1. eza${N}${D}              preferred (color-scale, git status)${N}"
    print "  ${G}  2. grc + ls${N}${D}         fallback (colorized via conf.gls)${N}"
    print "  ${G}  3. plain ls${N}${D}         last resort (no color config)${N}"
    print "  ${B}${Y}PLATFORM-SPECIFIC COMMANDS${N}"
    print "  ${D}  macOS:${N}"
    print "  ${M}    grc -c \$HOME/conf.gls gls -iFlhA --color=always${N}"
    print "  ${D}  Linux:${N}"
    print "  ${M}    grc -c \$HOME/conf.gls ls -iFlhA --color=always${N}"
    print "  ${D}  macOS uses ${G}gls${N}${D} (GNU ls from coreutils) because BSD ls${N}"
    print "  ${D}  doesn't support all the flags. Linux uses native ls.${N}"
    print "  ${B}${Y}THE conf.gls CONFIG${N}"
    print "  ${D}  Custom color configuration for ls output, lives at:${N}"
    print "  ${M}  \$HOME/conf.gls${N}"
    print "  ${D}  Maps file types, permissions, sizes to ANSI colors.${N}"
    print "  ${D}  Directories, executables, symlinks - all distinct colors.${N}"
    print "  ${B}${Y}OTHER GRC TARGETS${N}"
    print "  ${D}  grc can colorize almost any command:${N}"
    print "  ${G}  ping${N}${D}         latency numbers in color${N}"
    print "  ${G}  traceroute${N}${D}   hop-by-hop color coding${N}"
    print "  ${G}  make${N}${D}         errors red, warnings yellow${N}"
    print "  ${G}  gcc${N}${D}          compiler output colorized${N}"
    print "  ${G}  netstat${N}${D}      connection states highlighted${N}"
    print "  ${G}  diff${N}${D}         additions green, deletions red${N}"
    print "  ${B}${Y}GRC IN LOG COLORIZATION${N}"
    print "  ${D}  ${M}\$ZPWR_SCRIPTS/colorLogger.sh${N}${D} uses grc for system logs.${N}"
    print "  ${D}  tmux control windows show colorized live log output.${N}"
    print "  ${B}${R}TIP:${N} ${D}If eza is missing and ls looks dull, install grc.${N}"
    print "  ${D}  It's the middle tier of zpwr's color fallback chain.${N}"
    print "  ${D}  One package, instant color for dozens of commands.${N}"
}
