PAGE_TITLE="Log Levels"
PAGE_CHAPTER="CHAPTER 16: THE LOGGING SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> LOG LEVELS: SIGNAL VS NOISE <<<${N}"
    print "  ${D}if a tree falls in the forest and nobody tails the log...${N}"
    print ""
    print "  ${G}ZPWR has a full structured logging system with four levels.${N}"
    print "  ${G}Each level has a file variant and a console variant.${N}"
    print ""
    print "  ${B}${Y}LEVEL 1: TRACE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr logtrace 'entering func'${N}  ${D}# most verbose${N}"
    print ""
    print "  ${G}The firehose. Every function entry, variable assignment,${N}"
    print "  ${G}and internal state change. Use for deep debugging only.${N}"
    print ""
    print "  ${B}${Y}LEVEL 2: DEBUG${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr logdebug 'cache miss'${N}    ${D}# developer detail${N}"
    print ""
    print "  ${G}Detailed info for development. Cache behavior,${N}"
    print "  ${G}branch decisions, intermediate values.${N}"
    print ""
    print "  ${B}${Y}LEVEL 3: INFO${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr loginfo 'update done'${N}    ${D}# normal operations${N}"
    print ""
    print "  ${G}Standard operational messages. \"Started\", \"Completed\",${N}"
    print "  ${G}\"Loaded 47 plugins\". The daily heartbeat.${N}"
    print ""
    print "  ${B}${Y}LEVEL 4: ERROR${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr logerror 'file not found'${N} ${D}# something broke${N}"
    print ""
    print "  ${R}Things that should not have happened but did.${N}"
    print "  ${R}Missing files, failed commands, broken assumptions.${N}"
    print ""
    print "  ${B}${Y}SEVERITY PYRAMID:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}            ┌───────┐${N}"
    print "  ${D}            │${R} ERROR ${N}${D}│  rare, always investigate${N}"
    print "  ${D}          ┌─┴───────┴─┐${N}"
    print "  ${D}          │${Y}   INFO    ${N}${D}│  daily operations${N}"
    print "  ${D}        ┌─┴───────────┴─┐${N}"
    print "  ${D}        │${C}    DEBUG     ${N}${D}│  development detail${N}"
    print "  ${D}      ┌─┴───────────────┴─┐${N}"
    print "  ${D}      │${M}      TRACE       ${N}${D}│  the firehose${N}"
    print "  ${D}      └───────────────────┘${N}"
}
