PAGE_TITLE="Clipboard & Buffer Operations"
PAGE_CHAPTER="CHAPTER 14: TMUX WARFARE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> CLIPBOARD OPS: COPY-PASTE ON STEROIDS <<<${N}"
    print "  ${D}because Ctrl-C Ctrl-V is so last millennium${N}"
    print ""
    print "  ${B}${Y}zpwr pastebuffer${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Paste from the tmux paste buffer into the terminal.${N}"
    print "  ${G}Tmux has its own clipboard, separate from the system.${N}"
    print ""
    print "  ${C}  \$ zpwr pastebuffer${N}            ${D}# paste tmux buffer${N}"
    print ""
    print "  ${B}${Y}zpwr pastestring${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Paste a specific string into the active pane.${N}"
    print "  ${G}Programmatic pasting -- useful in scripts.${N}"
    print ""
    print "  ${C}  \$ zpwr pastestring 'echo hello'${N} ${D}# paste literal text${N}"
    print ""
    print "  ${B}${Y}zpwr pastecommand${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Paste and execute a command in the active pane.${N}"
    print "  ${G}Like pastestring but hits enter for you.${N}"
    print ""
    print "  ${C}  \$ zpwr pastecommand 'ls -la'${N}  ${D}# paste + execute${N}"
    print ""
    print "  ${B}${Y}zpwr google${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open a Google search in your default browser.${N}"
    print "  ${G}Because sometimes you need to leave the terminal.${N}"
    print ""
    print "  ${C}  \$ zpwr google 'zsh completion'${N} ${D}# search the web${N}"
    print ""
    print "  ${B}${Y}zpwr openurl${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open any URL in the default browser.${N}"
    print ""
    print "  ${C}  \$ zpwr openurl https://github.com${N} ${D}# open URL${N}"
    print ""
    print "  ${D}  // the clipboard pipeline:${N}"
    print "  ${D}  //   terminal output --> tmux buffer --> pastebuffer${N}"
    print "  ${D}  //   system clipboard --> pastestring --> pane${N}"
    print "  ${D}  //   brain --> google --> browser --> back to terminal${N}"
}
