PAGE_TITLE="Startup Profile"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== STARTUP PROFILE ===${N}"
    print "  ${D}// bench tells you HOW FAST. startup tells you WHERE the time goes. //${N}"
    print ""
    print "  ${C}zpwr bench measures total wall time over multiple iterations.${N}"
    print "  ${C}zpwr startup gives a single-shot, per-function breakdown${N}"
    print "  ${C}using zsh's built-in zprof profiler.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr startup${N}${D}               # top 30 functions (default)${N}"
    print "  ${M}  zpwr startup 50${N}${D}            # top 50 functions${N}"
    print "  ${M}  zpwr startup 100${N}${D}           # full breakdown${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. Launches a fresh zsh with ZPWR_PROFILING=true${N}"
    print "  ${D}  2. zprof runs at the end of the init sequence${N}"
    print "  ${D}  3. Output is captured and colorized by self-time:${N}"
    print "  ${R}     >= 10%  RED${N}${D}       — hot path, optimize here${N}"
    print "  ${Y}     >= 3%   YELLOW${N}${D}    — warm, worth investigating${N}"
    print "  ${C}     >= 1%   CYAN${N}${D}      — normal${N}"
    print "  ${D}     < 1%    DIM${N}${D}       — negligible${N}"
    print ""
    print "  ${B}${Y}THE PERFORMANCE QUARTET${N}"
    print "  ${G}  ${M}zpwr bench${G}    -> how fast is total startup?${N}"
    print "  ${G}  ${M}zpwr flame${G}    -> ASCII flame chart of function hotspots${N}"
    print "  ${G}  ${M}zpwr startup${G}  -> per-function zprof breakdown${N}"
    print "  ${G}  ${M}zpwr top${G}      -> what is loaded right now?${N}"
    print ""
    print "  ${D}Four verbs. Four perspectives. Your shell is transparent.${N}"
    print ""
}
