PAGE_TITLE="eza: ls Evolved"
PAGE_CHAPTER="CHAPTER 34: EZA — THE MODERN LS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== EZA: LS EVOLVED ===${N}"
    print "  ${D}// ls is dead. long live ls. //${N}"
    print "  ${C}eza is the modern Rust replacement for ls, formerly known as${N}"
    print "  ${C}exa. Maintained by eza-community after exa's author went AWOL.${N}"
    print "  ${C}In zpwr, it's the default file lister for everything.${N}"
    print "  ${B}${Y}\$ZPWR_EXA_COMMAND — THE CONFIGURED INVOCATION${N}"
    print "  ${M}  command eza --git -il --classify=always -H --color-scale -g -a --colour=always${N}"
    print "  ${D}Every flag earns its place:${N}"
    print "  ${G}  --git${N}${D}              # git status per file (M modified, N new, I ignored)${N}"
    print "  ${G}  -i${N}${D}                 # show inode numbers${N}"
    print "  ${G}  -l${N}${D}                 # long listing format${N}"
    print "  ${G}  --classify=always${N}${D}  # / after dirs, * after executables, always${N}"
    print "  ${G}  -H${N}${D}                 # show hard link count${N}"
    print "  ${G}  --color-scale${N}${D}      # gradient colors for file sizes and ages${N}"
    print "  ${G}  -g${N}${D}                 # show group ownership${N}"
    print "  ${G}  -a${N}${D}                 # show hidden files (dotfiles)${N}"
    print "  ${G}  --colour=always${N}${D}    # force color even when piped${N}"
    print "  ${B}${Y}WHY --classify=always?${N}"
    print "  ${D}Not just -F. Under p10k instant prompt, stdout gets redirected${N}"
    print "  ${D}during init. eza's --classify auto-detects terminal capabilities${N}"
    print "  ${D}and when stdout is redirected, it drops the indicators. The${N}"
    print "  ${D}=always suffix forces classification regardless of fd state.${N}"
    print "  ${D}Without it, your login banner loses all the / and * markers.${N}"
    print "  ${B}${Y}WHERE IT'S USED${N}"
    print "  ${D}zpwrClearList and zpwrListNoClear both eval \$ZPWR_EXA_COMMAND.${N}"
    print "  ${D}The fallback chain: eza -> grc + gls -> raw ls.${N}"
    print "  ${D}zpwrListNoClear checks for eza first, falls back to gls on${N}"
    print "  ${D}macOS (with grc for colorization) or plain ls on Linux.${N}"
    print "  ${M}  alias eza=\"\$ZPWR_EXA_COMMAND\"${N}${D}  # bound in zpwrBindAliasesLate${N}"
    print "  ${M}  alias lr=\"\$ZPWR_EXA_COMMAND -R --tree | less -rMN\"${N}"
    print "  ${D}The ${G}lr${D} alias gives you a recursive tree piped through less${N}"
    print "  ${D}with line numbers — a full filesystem X-ray.${N}"
    print "  ${B}${Y}EXTENDED ATTRIBUTES${N}"
    print "  ${D}Set ${M}ZPWR_EXA_EXTENDED=true${D} in .zpwr_env.sh to add --extended,${N}"
    print "  ${D}which shows xattr metadata on macOS (com.apple.quarantine etc).${N}"
}
