PAGE_TITLE="Neovim: Configuration & Tips"
PAGE_CHAPTER="CHAPTER 38: NEOVIM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== NEOVIM: CONFIGURATION & TIPS ===${N}"
    print "  ${D}// one vimrc. two editors. zero compromises. //${N}"
    print "  ${B}${Y}THE SHARED CONFIG PHILOSOPHY${N}"
    print "  ${D}zpwr's init.vim just sources ~/.vimrc. This means:${N}"
    print "  ${D}  1. Every plugin in .vimbundle works in both vim and nvim${N}"
    print "  ${D}  2. All keybindings, settings, and autocmds are shared${N}"
    print "  ${D}  3. One file to edit: ${G}zpwr vrc${D} opens .vimrc${N}"
    print "  ${D}  4. No divergent configs to maintain across editors${N}"
    print "  ${D}The .vimrc is the single source of truth. init.vim is a shim.${N}"
    print "  ${B}${Y}NEOVIM-SPECIFIC SETTINGS${N}"
    print "  ${D}Guard nvim-only settings with has('nvim'):${N}"
    print "  ${M}  if has('nvim')${N}"
    print "  ${M}    set inccommand=nosplit   \" live substitution preview${N}"
    print "  ${M}    set pumblend=15          \" popup menu transparency${N}"
    print "  ${M}    set winblend=15          \" floating window transparency${N}"
    print "  ${M}  endif${N}"
    print "  ${D}inccommand is a killer feature: :s/old/new shows replacements${N}"
    print "  ${D}live as you type. No more guessing what your regex will do.${N}"
    print "  ${B}${Y}:checkhealth${N}"
    print "  ${D}Run this in nvim to diagnose your setup. It checks:${N}"
    print "  ${D}  - python3/node providers (pynvim, neovim npm package)${N}"
    print "  ${D}  - clipboard support (pbcopy on macOS, xclip on Linux)${N}"
    print "  ${D}  - terminal capabilities, true color support${N}"
    print "  ${D}  - plugin health (many plugins register health checks)${N}"
    print "  ${D}First thing to run when something feels wrong.${N}"
    print "  ${B}${Y}SESSION TRACKING${N}"
    print "  ${D}tpope/vim-obsession (in .vimbundle) tracks sessions:${N}"
    print "  ${M}  :Obsession${N}${D}           # start tracking session to Session.vim${N}"
    print "  ${M}  :Obsession!${N}${D}          # stop tracking and delete Session.vim${N}"
    print "  ${M}  nvim -S Session.vim${N}${D}  # restore session${N}"
    print "  ${D}Works in both vim and nvim since it's a VimScript plugin.${N}"
    print "  ${B}${Y}WHY ZPWR SUPPORTS BOTH${N}"
    print "  ${D}nvim is better locally — async, LSP, Lua, true color. But:${N}"
    print "  ${D}  - Remote servers often only have vim (or vi)${N}"
    print "  ${D}  - Docker containers ship vim, not nvim${N}"
    print "  ${D}  - macOS ships vim in /usr/bin/vim${N}"
    print "  ${D}The shared .vimrc means your muscle memory works everywhere.${N}"
    print "  ${D}nvim when you can, vim when you must, same config either way.${N}"
    print "  ${B}${Y}ZPWR EDITOR VERBS${N}"
    print "  ${M}  zpwr vrc${N}${D}             # edit .vimrc (shared by both)${N}"
    print "  ${D}Both editors, one config, zero excuses. The way it should be.${N}"
}
