PAGE_TITLE="The 32-Pane REPL Layout"
PAGE_CHAPTER="CHAPTER 40: HIDDEN SUBSYSTEMS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== THE 32-PANE REPL LAYOUT ===${N}"
    print "  ${D}every language, one screen, zero excuses${N}"
    print "  ${B}${Y}THE TMUX KEYBINDINGS${N}"
    print "  ${G}  prefix R${N}${D}  source ${M}\$ZPWR_TMUX/thirtytwo-panes-repl.conf${N}"
    print "  ${G}  prefix O${N}${D}  source ${M}\$ZPWR_TMUX/sixteen-panes.conf${N}"
    print "  ${G}  prefix G${N}${D}  source ${M}\$ZPWR_TMUX/eight-panes.conf${N}"
    print "  ${G}  prefix F${N}${D}  source ${M}\$ZPWR_TMUX/four-panes.conf${N}"
    print "  ${D}  One keystroke splits your terminal into a REPL army.${N}"
    print "  ${B}${Y}THE 32 REPLs (prefix R)${N}"
    print "  ${C}  pane 0:  lua          pane 1:  swift        pane 2:  ghci${N}"
    print "  ${C}  pane 3:  clisp        pane 4:  ocaml        pane 5:  clojure${N}"
    print "  ${C}  pane 6:  pry (ruby)   pane 7:  bpython      pane 8:  php -a${N}"
    print "  ${C}  pane 9:  groovysh     pane 10: csharp       pane 11: kotlinc${N}"
    print "  ${C}  pane 12: node         pane 13: coffee       pane 14: tclsh${N}"
    print "  ${C}  pane 15: ksh          pane 16: bash         pane 17: csh${N}"
    print "  ${C}  pane 18: perl -dE1    pane 19: gore (go)    pane 20: jshell${N}"
    print "  ${C}  pane 21: mycli        pane 22: pgcli        pane 23: python2${N}"
    print "  ${C}  pane 24: nslookup     pane 25: mongo        pane 26: irb${N}"
    print "  ${C}  pane 27: scala        pane 28: utop         pane 29: iex${N}"
    print "  ${C}  pane 30: bc           pane 31: gforth${N}"
    print "  ${D}  32 languages. 32 panes. One tmux window. Absolute madness.${N}"
    print "  ${B}${Y}THE VIM-TMUX EXECUTION PIPELINE${N}"
    print "  ${D}  Write code in vim, send it to a REPL pane:${N}"
    print "  ${D}  Supported languages for vim-to-tmux execution:${N}"
    print "  ${G}  zsh, bash, python, ruby, perl, node, go${N}"
    print "  ${G}  java, scala, R, octave${N}"
    print "  ${D}  Select code in vim, fire it into the matching pane.${N}"
    print "  ${D}  Edit-run-edit-run without ever leaving vim.${N}"
    print "  ${B}${Y}PROGRESSIVE LAYOUTS${N}"
    print "  ${D}  Don't need 32 languages? Scale down:${N}"
    print "  ${G}  prefix G${N}${D}  8 panes   - quick polyglot session${N}"
    print "  ${G}  prefix O${N}${D}  16 panes  - serious multi-language work${N}"
    print "  ${G}  prefix R${N}${D}  32 panes  - full REPL matrix (needs big screen)${N}"
    print "  ${D}  Each layout is a tmux conf file in ${M}\$ZPWR_TMUX/${N}"
    print "  ${B}${R}NOTE:${N} ${D}prefix R on a 13\" laptop is an act of hubris.${N}"
    print "  ${D}  You'll need at least a 27\" monitor to read anything.${N}"
    print "  ${D}  But hey, it works. And it's glorious.${N}"
}
