PAGE_TITLE="Tor Integration"
PAGE_CHAPTER="CHAPTER 15: NETWORK & CONTAINERS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> TOR INTEGRATION: ANONYMOUS MODE ENGAGED <<<${N}"
    print "  ${D}the onion router: because privacy is not a crime${N}"
    print ""
    print "  ${B}${Y}zpwr torip${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Check your current Tor exit node IP address.${N}"
    print "  ${G}Confirms you're routing through the onion network.${N}"
    print ""
    print "  ${C}  \$ zpwr torip${N}                  ${D}# show tor exit IP${N}"
    print ""
    print "  ${G}If Tor is running, this shows the exit node's IP.${N}"
    print "  ${G}If not, it'll tell you Tor isn't connected.${N}"
    print ""
    print "  ${B}${Y}zpwr toriprenew${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Request a new Tor circuit. Get a fresh exit node${N}"
    print "  ${G}and a new apparent IP address.${N}"
    print ""
    print "  ${C}  \$ zpwr toriprenew${N}             ${D}# new identity${N}"
    print ""
    print "  ${Y}BEFORE YOU START:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Tor must be installed and running as a service.${N}"
    print ""
    print "  ${D}  macOS:   brew install tor && brew services start tor${N}"
    print "  ${D}  Linux:   sudo apt install tor && sudo systemctl start tor${N}"
    print ""
    print "  ${B}${Y}THE ANONYMOUS WORKFLOW:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. Start tor service${N}"
    print "  ${D}  2. \$ zpwr torip            # confirm you're connected${N}"
    print "  ${D}  3. Do your thing${N}"
    print "  ${D}  4. \$ zpwr toriprenew       # rotate identity${N}"
    print "  ${D}  5. \$ zpwr torip            # verify new IP${N}"
    print ""
    print "  ${R}  DISCLAIMER:${N}"
    print "  ${R}  Tor provides anonymity, not invincibility.${N}"
    print "  ${R}  DNS leaks, browser fingerprinting, and OPSEC${N}"
    print "  ${R}  failures can still expose you. Use responsibly.${N}"
    print ""
    print "  ${D}  // \"I am become anonymous, destroyer of logs\"${N}"
    print "  ${D}  //   -- J. Robert Oppenheimer, probably not${N}"
}
