PAGE_TITLE="GitHub Integration"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GITHUB INTEGRATION ===${N}"
    print ""
    print "  ${C}GitHub is not a website. It is an API with a website.${N}"
    print "  ${C}ZPWR treats it accordingly.${N}"
    print ""
    print "  ${B}${Y}CREATE AND DESTROY${N}"
    print "  ${M}  zpwr githubcreate${N}${D}      # create a remote GitHub repo${N}"
    print "  ${M}  zpwr hc${N}${D}               # same thing, two letters${N}"
    print "  ${D}  Creates a repo on GitHub from your current directory.${N}"
    print "  ${D}  Sets up the remote. Ready to push.${N}"
    print ""
    print "  ${M}  zpwr githubdelete${N}${D}      # delete a remote GitHub repo${N}"
    print "  ${M}  zpwr hd${N}${D}               # same thing, two letters${N}"
    print "  ${R}  This is permanent. It asks for confirmation.${N}"
    print "  ${R}  But once confirmed, the repo is gone. Poof.${N}"
    print ""
    print "  ${B}${Y}BROWSE YOUR GITHUB${N}"
    print "  ${M}  zpwr github${N}${D}            # open your GitHub profile in browser${N}"
    print "  ${M}  zpwr gh${N}${D}               # same thing${N}"
    print "  ${M}  zpwr mygithub${N}${D}          # same thing${N}"
    print "  ${D}  Opens your profile page. Quick ego check.${N}"
    print ""
    print "  ${M}  zpwr githubzpwr${N}${D}        # open zpwr repo on GitHub${N}"
    print "  ${M}  zpwr ghz${N}${D}              # same thing${N}"
    print "  ${D}  Jump straight to the zpwr source. File issues.${N}"
    print "  ${D}  Star it. You know you want to.${N}"
    print ""
    print "  ${B}${Y}CONTRIBUTION STATS${N}"
    print "  ${M}  zpwr githubcontribcount${N}${D} # count GitHub contribs in last year${N}"
    print "  ${D}  Tells you how green your contribution graph is.${N}"
    print "  ${D}  The number that keeps you pushing commits at 2 AM.${N}"
    print ""
    print "  ${B}${Y}REVEAL: THE BROWSER SHORTCUT${N}"
    print "  ${M}  zpwr reveal${N}${D}            # show current repo in browser${N}"
    print "  ${D}  You are in a git repo. You want to see it on GitHub.${N}"
    print "  ${D}  One word. Browser opens. You are there.${N}"
    print ""
    print "  ${B}${Y}WORKFLOW EXAMPLE${N}"
    print "  ${G}  # Start a new project from scratch:${N}"
    print "  ${M}  mkdir new-project && cd new-project${N}"
    print "  ${M}  git init${N}"
    print "  ${M}  zpwr hc${N}${D}               # repo created on GitHub${N}"
    print "  ${M}  zpwr gitcommit \"initial commit\"${N}"
    print "  ${M}  zpwr reveal${N}${D}            # admire it in the browser${N}"
    print ""
    print "  ${D}From zero to pushed repo in four commands.${N}"
    print "  ${D}That is the GitHub integration promise.${N}"
    print ""
}
