PAGE_TITLE="zsh-sudo: Privilege Escalation"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== ZSH-SUDO: PRIVILEGE ESCALATION ===${N}"
    print "  ${D}toggle sudo on the current command line with one keybind${N}"
    print ""
    print "  ${B}${Y}THE KEYBINDING${N}"
    print "  ${C}  Ctrl-S${N}${D}   (or Escape Escape in some configs)${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${G}  sudo not on the line?${N}${D} .... it gets prepended${N}"
    print "  ${G}  sudo already there?${N}${D} ...... it gets stripped${N}"
    print "  ${G}  empty line?${N}${D} .............. pulls last command from history with sudo${N}"
    print ""
    print "  ${B}${Y}WHAT IT STRIPS${N}"
    print "  ${D}  When removing sudo, it also strips:${N}"
    print "  ${D}  ${M}builtin${D}, ${M}command${D}, ${M}env${D}, and all their arguments.${N}"
    print "  ${D}  So ${M}sudo -E env PATH=... command foo${D} becomes just ${M}foo${D}.${N}"
    print ""
    print "  ${B}${Y}EXAMPLE${N}"
    print "  ${D}  You type:  ${M}vim /etc/hosts${N}"
    print "  ${D}  Hit Ctrl-S: ${M}sudo vim /etc/hosts${N}"
    print "  ${D}  Hit Ctrl-S again: ${M}vim /etc/hosts${N}"
    print ""
    print "  ${D}  Empty line + Ctrl-S: pulls your last command back${N}"
    print "  ${D}  with sudo prepended. No retyping. No arrow keys.${N}"
    print ""
    print "  ${D}Plugin: ${C}MenkeTechnologies/zsh-sudo${N}"
    print ""
}
