PAGE_TITLE="fzf-zsh-plugin: Brew & Chrome"
PAGE_CHAPTER="CHAPTER 29: ARB ARCHITECTURE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FZF-ZSH-PLUGIN: BREW & CHROME ===${N}"
    print "  ${D}// fuzzy finding extends to your package manager and browser //${N}"
    print ""
    print "  ${C}The fzf-zsh-plugin adds fuzzy interfaces to Homebrew package${N}"
    print "  ${C}management and Chrome browser data. It ships its own picker${N}"
    print "  ${C}rather than going through \$ZPWR_FZF.${N}"
    print ""
    print "  ${B}${Y}HOMEBREW VERBS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr brewinstall${N}${D}            # fuzzy install formula${N}"
    print "  ${M}  zpwr brewuninstall${N}${D}          # fuzzy uninstall formula${N}"
    print "  ${M}  zpwr brewcaskinstall${N}${D}        # fuzzy install cask${N}"
    print "  ${M}  zpwr brewcaskuninstall${N}${D}      # fuzzy uninstall cask${N}"
    print "  ${M}  zpwr brewupdate${N}${D}             # fuzzy update formula${N}"
    print ""
    print "  ${D}  Each command pipes the available packages into the picker${N}"
    print "  ${D}  with multi-select. Pick one or many, then install/remove in${N}"
    print "  ${D}  one shot. No more googling package names.${N}"
    print ""
    print "  ${B}${Y}CHROME VERBS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr chromehistory${N}${D}          # fuzzy search Chrome history${N}"
    print "  ${M}  zpwr chromebookmarks${N}${D}        # fuzzy search Chrome bookmarks${N}"
    print ""
    print "  ${D}  Reads Chrome's SQLite databases directly. Select a URL${N}"
    print "  ${D}  from the picker and open it in the browser.${N}"
    print ""
    print "  ${D}  Plugin: ${C}MenkeTechnologies/fzf-zsh-plugin${N}"
    print ""
}
