PAGE_TITLE="Parameter Expansion Magic"
PAGE_CHAPTER="CHAPTER 28: ZSH INTERNALS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== PARAMETER EXPANSION MAGIC ===${N}"
    print "  ${D}// zsh parameter expansion is a programming language in itself. //${N}"
    print "  ${C}Zsh's \${...} syntax can do transformations that would${N}"
    print "  ${C}require sed, awk, basename, dirname, tr, and cut in bash.${N}"
    print "  ${C}No forks. No subshells. Pure in-process string manipulation.${N}"
    print "  ${B}${Y}PARAMETER EXPANSION FLAGS (the parenthesized letters)${N}"
    print "  ${G}  \${(k)assoc}${N}${D}          Keys of associative array${N}"
    print "  ${G}  \${(v)assoc}${N}${D}          Values of associative array${N}"
    print "  ${G}  \${(kv)assoc}${N}${D}         Key-value pairs interleaved${N}"
    print "  ${G}  \${(s:/:)var}${N}${D}         Split string on / into array${N}"
    print "  ${G}  \${(j:,:)array}${N}${D}       Join array elements with ,${N}"
    print "  ${G}  \${(L)var}${N}${D}            Lowercase the entire string${N}"
    print "  ${G}  \${(U)var}${N}${D}            Uppercase the entire string${N}"
    print "  ${G}  \${(f)var}${N}${D}            Split on newlines (lines to array)${N}"
    print "  ${G}  \${(F)array}${N}${D}          Join with newlines (array to lines)${N}"
    print "  ${G}  \${(t)var}${N}${D}            Type of variable (scalar, array, etc.)${N}"
    print "  ${G}  \${(q)var}${N}${D}            Quote the value for re-use in eval${N}"
    print "  ${G}  \${(Q)var}${N}${D}            Remove one level of quoting${N}"
    print "  ${G}  \${(z)var}${N}${D}            Split into words like the shell parser${N}"
    print "  ${G}  \${(o)array}${N}${D}          Sort ascending${N}"
    print "  ${G}  \${(O)array}${N}${D}          Sort descending${N}"
    print "  ${B}${Y}MODIFIERS (the colon letters)${N}"
    print "  ${G}  \${var:t}${N}${D}             Tail: basename (/a/b/c.txt -> c.txt)${N}"
    print "  ${G}  \${var:h}${N}${D}             Head: dirname (/a/b/c.txt -> /a/b)${N}"
    print "  ${G}  \${var:r}${N}${D}             Root: remove extension (file.txt -> file)${N}"
    print "  ${G}  \${var:e}${N}${D}             Extension: (file.txt -> txt)${N}"
    print "  ${G}  \${var:A}${N}${D}             Absolute path (resolve symlinks)${N}"
    print "  ${G}  \${var:l}${N}${D}             Lowercase (zsh 5.0+)${N}"
    print "  ${G}  \${var:u}${N}${D}             Uppercase (zsh 5.0+)${N}"
    print "  ${B}${Y}SUBSTITUTION AND PATTERN MATCHING${N}"
    print "  ${G}  \${var//pat/rep}${N}${D}       Global substitution${N}"
    print "  ${G}  \${var/pat/rep}${N}${D}        First match substitution${N}"
    print "  ${G}  \${var#pat}${N}${D}            Remove shortest prefix match${N}"
    print "  ${G}  \${var##pat}${N}${D}           Remove longest prefix match${N}"
    print "  ${G}  \${var%pat}${N}${D}            Remove shortest suffix match${N}"
    print "  ${G}  \${var%%pat}${N}${D}           Remove longest suffix match${N}"
    print "  ${B}${Y}ZPWR EXAMPLES${N}"
    print "  ${D}From zpwrBindDirs (writing hash dir cache):${N}"
    print "  ${M}  print -r \"hash -d \${k}=\${(q)v}\"${N}${D}  -- (q) quotes the value safely${N}"
    print "  ${D}From zpwrAcceptLine (parsing command buffer):${N}"
    print "  ${M}  mywords=( \${(z)cmdstr} )${N}${D}           -- (z) shell-word splits${N}"
    print "  ${M}  cmd=\${mywords[1]#=}${N}${D}                -- strip leading = from =cmd${N}"
    print "  ${D}From zpwrBindPrecmd (removing duplicates from array):${N}"
    print "  ${M}  \${(@)precmd_functions:#zpwrPrecmd}${N}${D}  -- remove matching element${N}"
    print "  ${D}These are not academic exercises. They replace forks.${N}"
}
