PAGE_TITLE="Display & Banners"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== DISPLAY & BANNERS ===${N}"
    print "  ${D}// because aesthetics matter. even in a terminal. //${N}"
    print ""
    print "  ${C}zpwr ships with a fleet of display verbs that produce${N}"
    print "  ${C}ASCII art, colorized output, and terminal animations.${N}"
    print "  ${C}Some are informational. Some are just cool to look at.${N}"
    print ""
    print "  ${B}${Y}THE BANNER FAMILY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr about${N}${D}                          # the welcome banner${N}"
    print "  ${M}  zpwr banner${N}${D}                         # same as about${N}"
    print "  ${M}  zpwr bannercounts${N}${D}                   # banner + environment stats${N}"
    print ""
    print "  ${D}  The core banner shows the zpwr ASCII logo with version,${N}"
    print "  ${D}  author, and system info. bannercounts adds the environment${N}"
    print "  ${D}  census (alias count, function count, etc.).${N}"
    print ""
    print "  ${M}  zpwr bannerlolcat${N}${D}                   # banner piped through lolcat${N}"
    print "  ${D}  Rainbow gradient banner. Requires: ${M}gem install lolcat${N}"
    print "  ${D}  For when monochrome is not enough and you need to${N}"
    print "  ${D}  assert terminal dominance with a rainbow.${N}"
    print ""
    print "  ${M}  zpwr bannerpony${N}${D}                     # banner with ponysay${N}"
    print "  ${D}  Displays the banner inside an ASCII pony speech bubble.${N}"
    print "  ${D}  Requires: ${M}pip install ponysay${N}"
    print "  ${D}  Peak terminal culture.${N}"
    print ""
    print "  ${M}  zpwr bannernopony${N}${D}                   # banner without the pony${N}"
    print "  ${D}  For the pony-averse. All the info, none of the horse.${N}"
    print ""
    print "  ${B}${Y}PRETTY PRINTING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr prettyprint${N}${D}                    # formatted text output${N}"
    print "  ${M}  zpwr altprettyprint${N}${D}                 # alternate format${N}"
    print "  ${M}  zpwr printmap${N}${D}                       # print associative array${N}"
    print ""
    print "  ${D}  prettyprint is used internally by many zpwr verbs to${N}"
    print "  ${D}  format output with consistent color and spacing.${N}"
    print "  ${D}  printmap formats associative arrays as aligned key-value${N}"
    print "  ${D}  tables. Useful for debugging hash tables.${N}"
    print ""
    print "  ${B}${Y}COLOR TESTING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr colortest${N}${D}                      # test basic terminal colors${N}"
    print "  ${M}  zpwr colortest256${N}${D}                   # full 256-color palette${N}"
    print ""
    print "  ${D}  Run these after changing terminals, fonts, or color${N}"
    print "  ${D}  schemes. colortest shows the 16 ANSI colors. colortest256${N}"
    print "  ${D}  shows the full 256-color grid. If colors look wrong,${N}"
    print "  ${D}  your TERM or terminal emulator config needs adjustment.${N}"
    print ""
    print "  ${B}${Y}ANIMATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr animate${N}${D}                        # terminal animation${N}"
    print ""
    print "  ${D}  Plays an ASCII animation in the terminal.${N}"
    print "  ${D}  Because sometimes you need to entertain yourself${N}"
    print "  ${D}  while waiting for a build.${N}"
    print ""
    print "  ${B}${Y}THE DISPLAY ARSENAL AT A GLANCE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  Impress a colleague:      ${M}zpwr bannerlolcat${N}"
    print "  ${D}  Debug your terminal:       ${M}zpwr colortest256${N}"
    print "  ${D}  Count your weapons:        ${M}zpwr bannercounts${N}"
    print "  ${D}  Maximum absurdity:         ${M}zpwr bannerpony${N}"
    print "  ${D}  Format a hash table:       ${M}zpwr printmap${N}"
    print "  ${D}  Kill time aesthetically:   ${M}zpwr animate${N}"
    print ""
}
