PAGE_TITLE="Console vs File Logging"
PAGE_CHAPTER="CHAPTER 16: THE LOGGING SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> CONSOLE VS FILE: TWO DESTINATIONS <<<${N}"
    print "  ${D}to stderr or to disk, that is the question${N}"
    print ""
    print "  ${G}Every log verb comes in two flavors:${N}"
    print ""
    print "  ${B}${Y}FILE VARIANTS (write to \$ZPWR_LOGFILE):${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr logtrace 'msg'${N}          ${D}# --> logfile${N}"
    print "  ${C}  \$ zpwr logdebug 'msg'${N}          ${D}# --> logfile${N}"
    print "  ${C}  \$ zpwr loginfo 'msg'${N}           ${D}# --> logfile${N}"
    print "  ${C}  \$ zpwr logerror 'msg'${N}          ${D}# --> logfile${N}"
    print ""
    print "  ${G}These write silently to the log file. No terminal${N}"
    print "  ${G}output. Perfect for background operations and scripts.${N}"
    print ""
    print "  ${B}${Y}CONSOLE VARIANTS (write to stderr AND logfile):${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr logtraceconsole 'msg'${N}   ${D}# --> stderr + file${N}"
    print "  ${C}  \$ zpwr logdebugconsole 'msg'${N}   ${D}# --> stderr + file${N}"
    print "  ${C}  \$ zpwr loginfoconsole 'msg'${N}    ${D}# --> stderr + file${N}"
    print "  ${C}  \$ zpwr logerrorconsole 'msg'${N}   ${D}# --> stderr + file${N}"
    print ""
    print "  ${G}These print to your terminal AND write to the log.${N}"
    print "  ${G}For interactive debugging when you need to see it live.${N}"
    print ""
    print "  ${B}${Y}THE LOGFILE:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ZPWR_LOGFILE${N} = ${M}\$ZPWR_LOCAL/zpwr.log${N}"
    print ""
    print "  ${D}  \$ cat \$ZPWR_LOGFILE | tail -20${N}   ${D}# recent entries${N}"
    print "  ${D}  \$ wc -l \$ZPWR_LOGFILE${N}           ${D}# how big is it?${N}"
    print ""
    print "  ${B}${Y}CHOOSING YOUR VARIANT:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${Y}  SCENARIO                          USE${N}"
    print "  ${D}  Background script running          ${C}loginfo${N}"
    print "  ${D}  Debugging interactively             ${C}logdebugconsole${N}"
    print "  ${D}  Tracking a rare bug                 ${C}logtraceconsole${N}"
    print "  ${D}  Production error handling           ${C}logerror${N}"
    print ""
    print "  ${D}  // file = silent, persistent, searchable${N}"
    print "  ${D}  // console = loud, immediate, ephemeral${N}"
    print "  ${D}  // use both strategically${N}"
}
