PAGE_TITLE="ZLE: The Zsh Line Editor"
PAGE_CHAPTER="CHAPTER 28: ZSH INTERNALS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== ZLE: THE ZSH LINE EDITOR ===${N}"
    print "  ${D}// the engine behind every keystroke. readline on steroids. //${N}"
    print "  ${C}ZLE (Zsh Line Editor) is the subsystem that handles your${N}"
    print "  ${C}command line input. Every key press triggers a ZLE widget.${N}"
    print "  ${C}ZPWR rewires dozens of these widgets for custom behavior.${N}"
    print "  ${B}${Y}WIDGETS: NAMED EDITOR ACTIONS${N}"
    print "  ${D}A widget is a named action that ZLE can execute:${N}"
    print "  ${M}  .accept-line${N}${D}          Built-in: execute the current line${N}"
    print "  ${M}  .backward-delete-char${N}${D}  Built-in: backspace${N}"
    print "  ${M}  .self-insert${N}${D}           Built-in: insert the typed character${N}"
    print "  ${D}The dot prefix means 'built-in widget'. User-defined widgets${N}"
    print "  ${D}can override them. ZPWR defines custom widgets like:${N}"
    print "  ${M}  zpwrMagicEnter${N}${D}         Custom Enter key behavior${N}"
    print "  ${M}  zpwrExpandTerminateSpace${N}${D} Custom Space key behavior${N}"
    print "  ${M}  zpwrAcceptLine${N}${D}          Custom line acceptance${N}"
    print "  ${B}${Y}bindkey: MAPPING KEYS TO WIDGETS${N}"
    print "  ${D}bindkey connects key sequences to widgets:${N}"
    print "  ${M}  bindkey '^M' zpwrMagicEnter${N}${D}    Enter key${N}"
    print "  ${M}  bindkey ' ' zpwrExpandTerminateSpace${N}${D}  Space key${N}"
    print "  ${M}  bindkey -v${N}${D}                     Switch to vi mode${N}"
    print "  ${M}  bindkey -e${N}${D}                     Switch to emacs mode${N}"
    print "  ${D}ZPWR_BINDKEY_VI controls which mode: true=vi, false=emacs.${N}"
    print "  ${B}${Y}HOW zpwrMagicEnter WORKS${N}"
    print "  ${D}On empty line (just pressing Enter):${N}"
    print "  ${D}  - If in a git dir: runs ${M}git status -u .${N}"
    print "  ${D}  - If not: runs ${M}ls -lh .${N}"
    print "  ${D}  - Resets the prompt via _p9k_precmd_impl + zle reset-prompt${N}"
    print "  ${D}On non-empty line: delegates to zle accept-line (zpwrAcceptLine).${N}"
    print "  ${B}${Y}HOW zpwrAcceptLine WORKS${N}"
    print "  ${D}The accept-line replacement does serious work:${N}"
    print "  ${D}  1. Updates zconvey name with current command + TTY + PID${N}"
    print "  ${D}  2. Detects commands that modify files (rm, mv, cp, mkdir...)${N}"
    print "  ${D}     and sets ZPWR_WILL_CLEAR=true for post-exec ls refresh${N}"
    print "  ${D}  3. Handles sudo + grc colorization for aliased commands${N}"
    print "  ${D}  4. Prevents global alias expansion in first position${N}"
    print "  ${D}  5. Optionally expands aliases before execution${N}"
    print "  ${D}  6. Calls .accept-line (the real built-in)${N}"
    print "  ${B}${Y}THE Ctrl-F CHORD PREFIX SYSTEM${N}"
    print "  ${D}ZPWR binds Ctrl-F as a prefix key for multi-key chords:${N}"
    print "  ${M}  Ctrl-F Ctrl-D${N}${D}   FZF file search${N}"
    print "  ${M}  Ctrl-F Ctrl-I${N}${D}   FZF word search (ag/grep)${N}"
    print "  ${M}  Ctrl-F Ctrl-G${N}${D}   FZF git operations${N}"
    print "  ${D}This gives you an entire second keymap layer without${N}"
    print "  ${D}conflicting with normal editing keys. Like tmux prefix${N}"
    print "  ${D}but for your command line.${N}"
}
