PAGE_TITLE="Directory Warfare"
PAGE_CHAPTER="CHAPTER 2: NAVIGATION PROTOCOL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== DIRECTORY WARFARE ===${N}"
    print ""
    print "  ${C}In the filesystem, speed is survival.${N}"
    print "  ${C}Typing full paths is for people who have given up on life.${N}"
    print ""
    print "  ${B}${Y}FORWARD AND REVERSE${N}"
    print "  ${M}  zpwr forward <dir>${N}${D}  # cd into a child directory${N}"
    print "  ${M}  zpwr f <dir>${N}${D}        # same thing, shorter${N}"
    print "  ${M}  zpwr fwd <dir>${N}${D}      # same thing, medium length${N}"
    print ""
    print "  ${M}  zpwr reverse <dir>${N}${D}  # cd UP the tree to a parent matching <dir>${N}"
    print "  ${M}  zpwr r <dir>${N}${D}        # same thing, one letter${N}"
    print "  ${M}  zpwr rvs <dir>${N}${D}      # same thing, three letters${N}"
    print "  ${M}  zpwr cdup <dir>${N}${D}     # same thing, cd-up style${N}"
    print ""
    print "  ${G}Example: you are in ~/code/myproject/src/lib/utils${N}"
    print "  ${M}  zpwr r myproject${N}${D}    # jumps UP to ~/code/myproject${N}"
    print "  ${D}  No more ../../../../ chains. Navigate like a human.${N}"
    print ""
    print "  ${B}${Y}BASIC CD${N}"
    print "  ${M}  zpwr cd <path>${N}${D}      # cd to directory arg${N}"
    print "  ${D}  Seems redundant but integrates with zpwr's dispatch.${N}"
    print ""
    print "  ${B}${Y}Z: FRECENCY JUMPING${N}"
    print "  ${M}  zpwr z <query>${N}${D}      # jump to frecency-ranked directory${N}"
    print "  ${D}  z tracks where you go. The more you visit a directory,${N}"
    print "  ${D}  the higher it ranks. Type a fragment, land at the top match.${N}"
    print ""
    print "  ${M}  zpwr zcd${N}${D}            # fzf list of z-ranked dirs, pick one${N}"
    print "  ${D}  When you cannot remember the exact fragment,${N}"
    print "  ${D}  zcd shows you the full ranked list in fzf.${N}"
    print ""
    print "  ${B}${Y}PRACTICAL COMBOS${N}"
    print "  ${G}  zpwr z proj${N}${D}         # land in your most-visited \"proj\" dir${N}"
    print "  ${G}  zpwr r src${N}${D}          # climb back up to the \"src\" parent${N}"
    print "  ${G}  zpwr f tests${N}${D}        # dive into the \"tests\" child${N}"
    print ""
    print "  ${D}The pattern is: ${M}z${D} for teleportation, ${M}f${D} for descent,${N}"
    print "  ${D}${M}r${D} for ascent. Three directions. Total coverage.${N}"
    print ""
    print "  ${R}${B}PROTIP:${N}${R} If you are still typing ${M}cd ../../../${R},${N}"
    print "  ${R}this is your intervention.${N}"
    print ""
}
