PAGE_TITLE="Install & Uninstall"
PAGE_CHAPTER="CHAPTER 18: INSTALLATION & RESET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> INSTALL & UNINSTALL: SETUP AND TEARDOWN <<<${N}"
    print "  ${D}easy to install, clean to remove -- no malware energy${N}"
    print ""
    print "  ${B}${Y}zpwr install${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Run the full ZPWR installation process.${N}"
    print "  ${G}Installs dependencies, links configs, sets up plugins.${N}"
    print ""
    print "  ${C}  \$ zpwr install${N}                ${D}# full installation${N}"
    print ""
    print "  ${Y}WHAT IT DOES:${N}"
    print "  ${D}  1. Installs system dependencies (brew/apt)${N}"
    print "  ${D}  2. Links config files to their proper locations${N}"
    print "  ${D}  3. Installs zsh, vim, and emacs plugins${N}"
    print "  ${D}  4. Generates caches and completion dumps${N}"
    print "  ${D}  5. Sets up tmux configuration${N}"
    print ""
    print "  ${B}${Y}zpwr uninstall${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Remove ZPWR configuration. Restores your shell to${N}"
    print "  ${G}its pre-ZPWR state. Clean breakup, no hard feelings.${N}"
    print ""
    print "  ${C}  \$ zpwr uninstall${N}              ${D}# remove zpwr config${N}"
    print ""
    print "  ${B}${Y}CONFIG LINK MANAGEMENT:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}ZPWR uses symlinks to place configs where tools expect them.${N}"
    print ""
    print "  ${D}  How it works:${N}"
    print "  ${D}  \$ZPWR/configs/.zshrc  -->  ~/.zshrc     (symlink)${N}"
    print "  ${D}  \$ZPWR/configs/.vimrc  -->  ~/.vimrc     (symlink)${N}"
    print "  ${D}  \$ZPWR/configs/.tmux   -->  ~/.tmux.conf (symlink)${N}"
    print ""
    print "  ${G}The source of truth lives in \$ZPWR, the symlinks${N}"
    print "  ${G}just point there. Version controlled, portable, clean.${N}"
    print ""
    print "  ${B}${Y}PARTIAL OPERATIONS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Sometimes you don't want the full install/uninstall.${N}"
    print "  ${G}You just need to fix the symlinks:${N}"
    print ""
    print "  ${D}  regenconfiglinks = recreate all config symlinks${N}"
    print "  ${D}  rmconfiglinks    = remove symlinks only${N}"
    print ""
    print "  ${D}  // install is idempotent -- run it again when things drift${N}"
    print "  ${D}  // uninstall is clean -- your system goes back to stock${N}"
}
