PAGE_TITLE="Updates & Dependencies"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== UPDATES & DEPENDENCIES ===${N}"
    print "  ${D}// staying current without breaking everything. a balancing act. //${N}"
    print ""
    print "  ${C}zpwr is a living system that depends on external tools,${N}"
    print "  ${C}plugins, and its own git repository. These verbs keep${N}"
    print "  ${C}everything synchronized.${N}"
    print ""
    print "  ${B}${Y}UPDATE: THE CORE UPDATE${N}"
    print "  ${M}  zpwr update${N}${D}                         # update zpwr itself${N}"
    print ""
    print "  ${D}  Pulls the latest zpwr from the git remote.${N}"
    print "  ${D}  This is a git pull on \$ZPWR.${N}"
    print "  ${D}  Your local config in \$ZPWR_LOCAL is not touched.${N}"
    print ""
    print "  ${B}${Y}UPDATEALL: THE EVERYTHING UPDATE${N}"
    print "  ${M}  zpwr updateall${N}${D}                      # update zpwr + all plugins${N}"
    print ""
    print "  ${D}  Updates zpwr, zinit plugins, and other managed components.${N}"
    print "  ${D}  This is the weekly maintenance verb. Run it when you want${N}"
    print "  ${D}  the latest of everything.${N}"
    print ""
    print "  ${B}${Y}UPDATEDEPS: DEPENDENCY UPDATES${N}"
    print "  ${M}  zpwr updatedeps${N}${D}                     # update external dependencies${N}"
    print ""
    print "  ${D}  Updates the external tools zpwr depends on: zinit plugins,${N}"
    print "  ${D}  zsh-autosuggestions, zsh-syntax-highlighting, etc.${N}"
    print "  ${D}  Does not touch zpwr's own code.${N}"
    print ""
    print "  ${B}${Y}UPDATEDEPSCLEAN: CLEAN + UPDATE DEPS${N}"
    print "  ${M}  zpwr updatedepsclean${N}${D}                # fresh dependency install${N}"
    print ""
    print "  ${D}  Cleans stale dependency state first, then updates.${N}"
    print "  ${D}  Use when updatedeps alone does not fix plugin issues.${N}"
    print ""
    print "  ${B}${Y}UPDATEZINIT: ZINIT ONLY${N}"
    print "  ${M}  zpwr updatezinit${N}${D}                    # update zinit plugin manager${N}"
    print ""
    print "  ${D}  Updates just the zinit plugin manager binary, not the${N}"
    print "  ${D}  plugins it manages. Use when zinit itself has a bug or${N}"
    print "  ${D}  you need a newer zinit feature.${N}"
    print ""
    print "  ${B}${Y}UPDATEPULL: GIT PULL ALL REPOS${N}"
    print "  ${M}  zpwr updatepull${N}${D}                     # pull all tracked git repos${N}"
    print ""
    print "  ${D}  Iterates over all cached git repos and runs git pull.${N}"
    print "  ${D}  Useful when you have many repos that track remotes and${N}"
    print "  ${D}  you want them all current.${N}"
    print ""
    print "  ${B}${Y}THE UPDATE HIERARCHY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  update${N}${D}              just zpwr (git pull)${N}"
    print "  ${C}  updatedeps${N}${D}          just plugins and tools${N}"
    print "  ${C}  updatezinit${N}${D}         just the plugin manager${N}"
    print "  ${C}  updateall${N}${D}           zpwr + plugins + tools${N}"
    print "  ${C}  updatepull${N}${D}          all tracked git repos${N}"
    print "  ${C}  updatedepsclean${N}${D}     clean slate + update deps${N}"
    print ""
    print "  ${B}${Y}RECOMMENDED UPDATE SCHEDULE${N}"
    print "  ${D}  Weekly:      ${M}zpwr updateall${N}"
    print "  ${D}  After update: ${M}zpwr recompile${N}"
    print "  ${D}  If broken:   ${M}zpwr updatedepsclean${N}"
    print ""
    print "  ${D}  Always recompile after updating. New source files need${N}"
    print "  ${D}  new .zwc files. The old compiled versions will load${N}"
    print "  ${D}  stale code until you recompile.${N}"
    print ""
}
