PAGE_TITLE="FZF Everywhere"
PAGE_CHAPTER="CHAPTER 24: TIPS, TRICKS & EASTER EGGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< FZF EVERYWHERE — THE FUZZY FINDER CONSPIRACY >>>${N}"
    print "  ${D}fzf is not a tool. it is a religion. ZPWR is its cathedral.${N}"
    print ""
    print "  ${C}fzf (fuzzy finder) is woven into the fabric of ZPWR.${N}"
    print "  ${C}Dozens of verbs pipe their output through fzf for${N}"
    print "  ${C}interactive selection. If a verb ends in 'fzf', it is${N}"
    print "  ${C}the fuzzy-interactive variant. But many others use it too.${N}"
    print ""
    print "  ${B}${Y}DEDICATED FZF VERBS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr verbs${N}${D}     browse subcommands in fzf${N}"
    print "  ${M}  zpwr verbs${N}${D}           browse all verbs in fzf${N}"
    print ""
    print "  ${B}${Y}VERBS THAT USE FZF INTERNALLY:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  forgit* verbs:${N}"
    print "  ${D}    forgitadd, forgitdiff, forgitlog, forgitstash,${N}"
    print "  ${D}    forgitreset, forgitrestore, forgitclean${N}"
    print "  ${D}    All use fzf for interactive selection with previews.${N}"
    print ""
    print "  ${C}  Search + edit verbs:${N}"
    print "  ${D}    filesearchedit, findsearchedit, locatesearchedit,${N}"
    print "  ${D}    wordsearchedit — search with fzf, open selection.${N}"
    print ""
    print "  ${C}  Recent file verbs:${N}"
    print "  ${D}    vimrecent, vimrecentcd, emacsrecent, emacsrecentcd${N}"
    print "  ${D}    Browse recent files with fzf preview.${N}"
    print ""
    print "  ${C}  Editor verbs:${N}"
    print "  ${D}    vimalledit, emacsalledit — select files to edit.${N}"
    print ""
    print "  ${C}  Git tag verbs:${N}"
    print "  ${D}    vimgtagsedit, emacsgtagsedit — browse tags in fzf.${N}"
    print ""
    print "  ${B}${Y}THE FZF PATTERN:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}The pattern is always the same:${N}"
    print "  ${C}  1. ${N}Generate a list of candidates${N}"
    print "  ${C}  2. ${N}Pipe through fzf with a preview command${N}"
    print "  ${C}  3. ${N}Take the selection and act on it${N}"
    print ""
    print "  ${D}  This pattern turns every list into a menu.${N}"
    print "  ${D}  Every menu into a decision. Every decision into action.${N}"
    print ""
    print "  ${B}${Y}FZF CUSTOMIZATION:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Set FZF_DEFAULT_OPTS in your tokens file:${N}"
    print "  ${M}  export FZF_DEFAULT_OPTS='--height 80% --reverse --border'${N}"
    print ""
    print "  ${D}  // if you can list it, you can fzf it${N}"
    print "  ${D}  // if you can fzf it, you can act on it${N}"
    print "  ${D}  // fzf is the universal adapter between data and decisions${N}"
    print ""
}
