PAGE_TITLE="bat: Syntax Highlighting for Everything"
PAGE_CHAPTER="CHAPTER 35: BAT — CAT WITH WINGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== BAT: SYNTAX HIGHLIGHTING FOR EVERYTHING ===${N}"
    print "  ${D}// cat is for reading files. bat is for understanding them. //${N}"
    print "  ${C}bat is a cat clone with syntax highlighting, git integration,${N}"
    print "  ${C}and automatic paging. Written in Rust. In zpwr it's the${N}"
    print "  ${C}default colorizer: ${M}ZPWR_COLORIZER=bat${C} in .zpwr_env.sh.${N}"
    print "  ${B}${Y}CORE FEATURES${N}"
    print "  ${D}Line numbers in the gutter. Git diff markers (+/-/~) in the${N}"
    print "  ${D}margin. Syntax highlighting for 200+ languages. Automatic${N}"
    print "  ${D}paging via less when output exceeds terminal height.${N}"
    print "  ${B}${Y}DISCOVERY${N}"
    print "  ${G}  bat --list-themes${N}${D}    # see all available color themes${N}"
    print "  ${G}  bat --list-languages${N}${D} # every syntax bat can highlight${N}"
    print "  ${B}${Y}HOW ZPWR USES BAT${N}"
    print "  ${D}bat is the preview engine for fzf throughout zpwr:${N}"
    print "  ${M}  fzf --preview 'bat --color=always {}'${N}"
    print "  ${D}The full zpwr colorizer invocation:${N}"
    print "  ${M}  bat --paging never --wrap character --color always${N}"
    print "  ${M}      --style=\"numbers,grid,changes,header\"${N}"
    print "  ${D}This is stored in \$ZPWR_COLORIZER and expanded into:${N}"
    print "  ${D}  ${G}FZF_COLORIZER${D}          — preview for generic fzf${N}"
    print "  ${D}  ${G}FZF_COLORIZER_FILE${D}     — preview for file-specific fzf${N}"
    print "  ${D}  ${G}FZF_COLORIZER_FILE_TEXT${D} — text file preview (uses -l ASP)${N}"
    print "  ${D}When bat is unavailable, zpwr falls back to pygmentize.${N}"
    print "  ${B}${Y}ZPWR VERBS${N}"
    print "  ${D}zpwr filesearch and zpwr wordsearch both use bat in their${N}"
    print "  ${D}fzf preview windows. vimfilesearch, vimwordsearch, and the${N}"
    print "  ${D}emacs variants (emacsfilesearch, emacswordsearch) all inherit${N}"
    print "  ${D}the same bat-powered preview pipeline.${N}"
    print "  ${B}${Y}STANDALONE USAGE${N}"
    print "  ${M}  bat src/main.rs${N}${D}              # highlighted source view${N}"
    print "  ${M}  bat -l json data.txt${N}${D}         # force language detection${N}"
    print "  ${M}  bat --diff${N}${D}                    # show only git-changed lines${N}"
    print "  ${M}  bat -A${N}${D}                        # show non-printable chars${N}"
    print "  ${M}  bat --plain${N}${D}                   # no line numbers, no border${N}"
    print "  ${M}  bat -r 10:20 file.zsh${N}${D}        # show only lines 10-20${N}"
    print "  ${D}The -r (--line-range) flag is perfect for surgical code review.${N}"
}
