PAGE_TITLE="Travis CI & External Services"
PAGE_CHAPTER="CHAPTER 23: EXERCISM & EXTERNAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< TRAVIS CI & EXTERNAL SERVICES >>>${N}"
    print "  ${D}CI/CD from your terminal, not your browser${N}"
    print ""
    print "  ${C}ZPWR integrates with external services so you can${N}"
    print "  ${C}monitor builds, check statuses, and manage CI/CD${N}"
    print "  ${C}pipelines without opening a single browser tab.${N}"
    print ""
    print "  ${B}${Y}TRAVIS — THE CI DASHBOARD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr travis${N}"
    print "  ${G}Travis CI integration. View build status, logs, and${N}"
    print "  ${G}pipeline information from your terminal.${N}"
    print ""
    print "  ${B}${Y}TRAVISBUILD — BUILD STATUS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr travisbuild${N}"
    print "  ${G}Check the current build status. Green, red, or pending.${N}"
    print "  ${G}No need to refresh a web page in a loop.${N}"
    print ""
    print "  ${B}${Y}TRAVISBRANCH — BRANCH BUILDS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr travisbranch${N}"
    print "  ${G}View build status for a specific branch. When you push${N}"
    print "  ${G}to a feature branch and want to know if CI passed.${N}"
    print ""
    print "  ${B}${Y}TRAVISPR — PULL REQUEST BUILDS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr travispr${N}"
    print "  ${G}Check build status for pull requests. The merge button${N}"
    print "  ${G}is only as good as the CI behind it.${N}"
    print ""
    print "  ${B}${Y}OTHER EXTERNAL INTEGRATIONS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr goclean${N}${D}          clean Go build cache${N}"
    print "  ${M}  zpwr google <query>${N}${D}    search Google from terminal${N}"
    print "  ${M}  zpwr digs <domain>${N}${D}     DNS lookups${N}"
    print "  ${M}  zpwr torip${N}${D}            check your Tor IP address${N}"
    print "  ${M}  zpwr toriprenew${N}${D}       renew your Tor circuit${N}"
    print "  ${M}  zpwr curl${N}${D}             enhanced curl operations${N}"
    print ""
    print "  ${B}${G}THE EXTERNAL SERVICES PHILOSOPHY:${N}"
    print "  ${C}  The browser is a context switch. Every tab you open${N}"
    print "  ${C}  is a distraction vector. ZPWR brings the services${N}"
    print "  ${C}  to you, in the terminal, where you already are.${N}"
    print ""
    print "  ${D}  // the terminal is the cockpit${N}"
    print "  ${D}  // external services are instruments on the dashboard${N}"
    print "  ${D}  // you read them. you do not visit them.${N}"
    print ""
}
