PAGE_TITLE="Live Dashboard"
PAGE_CHAPTER="CHAPTER 6: PERFORMANCE CULT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== LIVE DASHBOARD ===${N}"
    print ""
    print "  ${C}Bench is a snapshot. Flame is a profile.${N}"
    print "  ${C}Top is a live feed of your shell's vital signs.${N}"
    print ""
    print "  ${B}${Y}THE TOP VERB${N}"
    print "  ${M}  zpwr top${N}"
    print "  ${D}  Launches a live shell resource dashboard.${N}"
    print "  ${D}  Think htop, but for your zsh environment.${N}"
    print ""
    print "  ${B}${Y}WHAT EACH SECTION SHOWS${N}"
    print ""
    print "  ${G}  Shell Environment${N}"
    print "  ${D}  - Number of aliases currently defined${N}"
    print "  ${D}  - Number of functions loaded${N}"
    print "  ${D}  - Number of parameters (variables) in scope${N}"
    print "  ${D}  - Builtin and keyword counts${N}"
    print ""
    print "  ${G}  Completion System${N}"
    print "  ${D}  - Completion functions registered${N}"
    print "  ${D}  - Cache file sizes and freshness${N}"
    print ""
    print "  ${G}  Resource Usage${N}"
    print "  ${D}  - Memory footprint of the shell process${N}"
    print "  ${D}  - History file size and entry count${N}"
    print "  ${D}  - Autoload function count${N}"
    print ""
    print "  ${B}${Y}INTERPRETING THE DATA${N}"
    print "  ${C}  High alias count?${N}${D}    Normal for zpwr. 1000+ is fine.${N}"
    print "  ${C}  High function count?${N}${D} Also normal. Autoloaded functions${N}"
    print "  ${D}                         are lazy-loaded, they cost nothing${N}"
    print "  ${D}                         until called.${N}"
    print "  ${C}  Large HISTFILE?${N}${D}      Consider ${M}zpwr backuphistory${D} and trim.${N}"
    print "  ${C}  Stale cache?${N}${D}         Run ${M}zpwr compile${D} to refresh.${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr environmentcounts${N}${D}   # one-shot environment stats${N}"
    print "  ${M}  zpwr autoloadcount${N}${D}       # total number of autoloads${N}"
    print "  ${M}  zpwr autoloadlist${N}${D}        # list all autoloads${N}"
    print "  ${M}  zpwr vimplugincount${N}${D}      # count vim plugins${N}"
    print "  ${M}  zpwr emacsplugincount${N}${D}    # count emacs plugins${N}"
    print "  ${D}  Use these for quick spot checks without the full dashboard.${N}"
    print ""
    print "  ${B}${Y}THE PERFORMANCE QUARTET${N}"
    print "  ${G}  ${M}zpwr bench${G}    -> how fast is total startup?${N}"
    print "  ${G}  ${M}zpwr flame${G}    -> ASCII flame chart of function hotspots${N}"
    print "  ${G}  ${M}zpwr startup${G}  -> per-function zprof breakdown${N}"
    print "  ${G}  ${M}zpwr top${G}      -> what is loaded right now?${N}"
    print ""
    print "  ${D}Four verbs. Four perspectives. Complete observability.${N}"
    print "  ${D}Your shell is no longer a black box. It is an open book.${N}"
    print ""
}
