PAGE_TITLE="Plugin Troubleshooting"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== PLUGIN TROUBLESHOOTING ===${N}"
    print "  ${D}// when plugins misbehave, you need diagnostic tools. //${N}"
    print "  ${C}Zinit ships with built-in debugging commands.${N}"
    print "  ${C}When something breaks, these are your first responders.${N}"
    print "  ${B}${Y}DIAGNOSTIC COMMANDS${N}"
    print "  ${G}  zinit report <plugin>${N}${D}      Show load status, errors, files${N}"
    print "  ${M}    zinit report zsh-users/zsh-autosuggestions${N}"
    print "  ${D}    Shows: source file, ice modifiers used, compdef calls,${N}"
    print "  ${D}    functions defined, aliases created, PATH changes.${N}"
    print "  ${G}  zinit times${N}${D}               Show plugin load times${N}"
    print "  ${D}    Sorted by load time. Find the slowest plugin.${N}"
    print "  ${D}    If something takes >50ms, investigate.${N}"
    print "  ${G}  zinit loaded${N}${D}              List all loaded plugins${N}"
    print "  ${G}  zinit unload <plugin>${N}${D}      Unload a plugin from current session${N}"
    print "  ${D}    Useful for debugging conflicts. Does not persist.${N}"
    print "  ${G}  zinit list${N}${D}                List all registered plugins${N}"
    print "  ${G}  zinit cd <plugin>${N}${D}          cd into plugin directory${N}"
    print "  ${B}${Y}COMMON ISSUES${N}"
    print "  ${R}  Plugin not loading?${N}"
    print "  ${D}    - Check if 'wait' ice is set (turbo mode defers loading)${N}"
    print "  ${D}    - Run zinit report to see if it errored silently${N}"
    print "  ${D}    - The 'lucid' ice suppresses messages -- remove it to debug${N}"
    print "  ${R}  Completion missing after plugin install?${N}"
    print "  ${D}    - Run ${M}zpwr regenzsh${D} to rebuild zcompdump${N}"
    print "  ${D}    - Check fpath: ${M}print -l \$fpath | grep <plugin>${N}"
    print "  ${D}    - Ensure the plugin uses as'completion' or adds to fpath${N}"
    print "  ${R}  Keybinding conflicts?${N}"
    print "  ${D}    - Load order matters. Plugins loaded later override earlier ones.${N}"
    print "  ${D}    - ZPWR uses wait'0a' through wait'0e' to control this.${N}"
    print "  ${D}    - zpwrBindOverrideZLE fires in the 0a phase to win conflicts.${N}"
    print "  ${B}${Y}ADDING CUSTOM PLUGINS${N}"
    print "  ${D}Add to ZPWR_GH_PLUGINS in \$ZPWR_LOCAL/.tokens.sh:${N}"
    print "  ${M}  ZPWR_GH_PLUGINS+=( your-user/your-plugin )${N}"
    print "  ${D}The .tokens.sh file is sourced before plugin loading starts${N}"
    print "  ${D}(via zpwrTokenPre), so your additions join the array in time.${N}"
    print "  ${D}For conditional loading:${N}"
    print "  ${M}  zpwrCommandExists myapp && ZPWR_GH_PLUGINS+=( user/zsh-myapp )${N}"
    print "  ${B}${Y}UPDATING PLUGINS${N}"
    print "  ${M}  zpwr updatezinit${N}"
    print "  ${D}Runs zinit update --all to pull latest from all repos.${N}"
    print "  ${D}After updating, run ${M}zpwr regenzsh${D} to rebuild completions.${N}"
    print "  ${B}${Y}NUCLEAR OPTION${N}"
    print "  ${D}If zinit is truly broken, nuke and rebuild:${N}"
    print "  ${M}  rm -rf \$ZPWR_PLUGIN_MANAGER_HOME${N}"
    print "  ${D}Next shell start auto-clones zinit and re-downloads everything.${N}"
    print "  ${D}Slow but thorough. The cockroach approach to debugging.${N}"
}
