PAGE_TITLE="The Doctor Is In (2/2)"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE DOCTOR (continued) ===${N}"
    print ""
    print "  ${G}6. NAMED DIRECTORIES${N}"
    print "  ${D}     Invalid named dirs and p10k pollution from${N}"
    print "  ${D}     auto_name_dirs leaking gitstatus vars.${N}"
    print ""
    print "  ${G}7. DEPENDENCIES${N}"
    print "  ${D}     Checks: git, eza, fzf, tmux, perl, python3, zinit.${N}"
    print ""
    print "  ${G}8. HISTORY & BACKUPS${N}"
    print "  ${D}     Is HISTFILE present? How many backups exist?${N}"
    print ""
    print "  ${G}9. CONFIG SYMLINKS${N}"
    print "  ${D}     Checks .zshrc, .vimrc, .tmux.conf are symlinks.${N}"
    print ""
    print "  ${B}${Y}READING THE RESULTS${N}"
    print "  ${G}  green checkmark${N}${D}  = healthy${N}"
    print "  ${Y}  yellow warning${N}${D}   = degraded but functional${N}"
    print "  ${R}  red X${N}${D}            = broken, fix now${N}"
    print ""
    print "  ${B}${Y}THE SIGNAL BAR${N}"
    print "  ${G}  ██████████${D}  = HEALTHY${N}"
    print "  ${Y}  ██████${D}░░░░  = WARNINGS${N}"
    print "  ${R}  ██${D}░░░░░░░░  = CRITICAL${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr stale${N}${D}                # stale .zwc, orphan caches${N}"
    print "  ${M}  zpwr pathaudit${N}${D}             # deep PATH/FPATH audit${N}"
    print "  ${M}  zpwr lint${N}${D}                  # shellcheck + zsh -n${N}"
    print "  ${M}  zpwr startup${N}${D}               # zprof breakdown${N}"
    print "  ${M}  zpwr ports${N}${D}                 # listening ports${N}"
    print ""
    print "  ${B}${Y}PRO MOVE${N}"
    print "  ${D}  Add ${M}zpwr doctor${D} to weekly cron. Catch rot early.${N}"
    print ""
}
