PAGE_TITLE="Vim Insert & Visual Mode + Keybinding Search"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< VIM INSERT & VISUAL MODE + KEYBINDING SEARCH >>>${N}"
    print "  ${D}vim mode highlights and how to find any keybinding.${N}"
    print ""
    print "  ${B}${Y}VIM INSERT MODE HIGHLIGHTS:${N}"
    print "  ${C}Ctrl-A${N}                ${D}jump to first non-blank (like ^)${N}"
    print "  ${C}Ctrl-E${N}                ${D}end of line or dismiss popup${N}"
    print "  ${C}Ctrl-D${N}                ${D}delete char forward or default${N}"
    print "  ${C}Ctrl-F${N}                ${D}move right or scroll${N}"
    print "  ${C}Ctrl-S${N}                ${D}isurround (surround insert)${N}"
    print "  ${C}Ctrl-G s / S${N}          ${D}isurround / ISurround (line)${N}"
    print "  ${C}Ctrl-Tab${N}              ${D}list ultisnips snippets${N}"
    print "  ${C}Shift-Tab${N}             ${D}SuperTab backward completion${N}"
    print "  ${C}Alt-d${N}                 ${D}delete word forward${N}"
    print "  ${C}\" ' ( ) [ ] \` { }${N}    ${D}delimitMate auto-pairing${N}"
    print ""
    print "  ${B}${Y}VIM VISUAL MODE HIGHLIGHTS:${N}"
    print "  ${C}Space r${N}               ${D}replace word in selection range${N}"
    print "  ${C}Space g${N}               ${D}global substitute in selection range${N}"
    print "  ${C}Space x${N}               ${D}repeat last sub on selected lines${N}"
    print "  ${C}Space \" ' \` ( [ {${N}    ${D}surround selection with quote/bracket${N}"
    print "  ${C}Space b${N}               ${D}copy selection to tmux buffer${N}"
    print "  ${C}Space = / Space -${N}     ${D}grow / shrink selection (4 lines)${N}"
    print "  ${C}J / K${N}                ${D}move selected lines down / up${N}"
    print "  ${C}Y${N}                     ${D}yank and move to end${N}"
    print "  ${C}< / >${N}                ${D}indent / outdent (stay in visual)${N}"
    print "  ${C}S${N}                     ${D}vim-surround visual surround${N}"
    print "  ${C}go${N}                    ${D}copy selection + open as URL${N}"
    print "  ${C}gs${N}                    ${D}copy selection + google search${N}"
    print "  ${C}Space vl / vk / vj${N}   ${D}TmuxRepeat repl / visual / file${N}"
    print "  ${C}Space em / ev / ef${N}   ${D}extract method / variable / fold${N}"
    print ""
    print "  ${B}${Y}SNEAK & MOTION:${N}"
    print "  ${C}s / S${N}                ${D}sneak forward / backward (2-char)${N}"
    print "  ${C}f / F / t / T${N}        ${D}sneak-enhanced find char${N}"
    print "  ${C}; / ,${N}                ${D}repeat / reverse last sneak/find${N}"
    print "  ${C}w / b / e${N}            ${D}CamelCaseMotion word movement${N}"
    print ""
    print "  ${B}${R}========================================${N}"
    print "  ${B}${Y}HOW TO SEARCH KEYBINDINGS:${N}"
    print "  ${B}${R}========================================${N}"
    print ""
    print "  ${C}zpwr allsearch${N}        ${D}search ALL keybindings in fzf${N}"
    print "  ${C}zpwr vimsearch${N}        ${D}search vim keybindings in fzf${N}"
    print "  ${C}zpwr zshsearch${N}        ${D}search zsh keybindings in fzf${N}"
    print ""
    print "  ${B}${Y}KEYBINDING CACHE FILES:${N}"
    print "  ${D}  \$ZPWR_LOCAL/zpwrAllKeybindings.txt${N}"
    print "  ${D}  \$ZPWR_LOCAL/zpwr{Vim,Zsh,Tmux}Keybindings.txt${N}"
    print ""
    print "  ${B}${Y}REGENERATE:${N}"
    print "  ${C}zpwr regenkeybindings${N}  ${D}regenerate all keybinding caches${N}"
    print ""
    print "  ${D}Cache files are auto-generated. Run regenkeybindings after${N}"
    print "  ${D}adding new bindings to refresh the searchable index.${N}"
    print ""
    print "  ${M}  // the wizard does not memorize 4000 keybindings${N}"
    print "  ${M}  // the wizard searches them at the speed of thought${N}"
    print "  ${M}  // fzf is the oracle, the cache is the grimoire${N}"
    print ""
}
