PAGE_TITLE="Compsys Cache"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== COMPSYS CACHE ===${N}"
    print "  ${D}// tab completion is a religion. the zcompdump is its scripture. //${N}"
    print ""
    print "  ${C}The zsh completion system (compsys) is the most complex${N}"
    print "  ${C}part of zsh. It maintains a dump file (zcompdump) that${N}"
    print "  ${C}caches all registered completions. When it breaks, tab${N}"
    print "  ${C}completion goes haywire. Here is how to fix it.${N}"
    print ""
    print "  ${B}${Y}WHAT IS ZCOMPDUMP?${N}"
    print "  ${D}  A file (usually ~/.zcompdump or in \$ZPWR_LOCAL) that${N}"
    print "  ${D}  contains all compdef registrations. When zsh starts,${N}"
    print "  ${D}  it sources this file instead of re-scanning all completion${N}"
    print "  ${D}  functions. This saves 100-500ms of startup time.${N}"
    print ""
    print "  ${D}  Location: ${C}\$ZSH_COMPDUMP${N}"
    print "  ${D}  The file starts with #files:TIMESTAMP and contains${N}"
    print "  ${D}  compdef calls for every registered completion.${N}"
    print ""
    print "  ${B}${Y}REGENZSH: THE COMPLETION RESET${N}"
    print "  ${M}  zpwr regenzsh${N}${D}                       # regenerate zcompdump${N}"
    print ""
    print "  ${D}  Deletes the old zcompdump and forces compinit to rebuild it.${N}"
    print "  ${D}  This is the #1 fix for completion problems:${N}"
    print ""
    print "  ${D}  ${R}Symptom:${N}${D} New command installed but tab complete ignores it${N}"
    print "  ${D}  ${G}Fix:${N}${D}     ${M}zpwr regenzsh${N}"
    print ""
    print "  ${D}  ${R}Symptom:${N}${D} Tab shows wrong completions for a command${N}"
    print "  ${D}  ${G}Fix:${N}${D}     ${M}zpwr cleancompcache && zpwr regenzsh${N}"
    print ""
    print "  ${D}  ${R}Symptom:${N}${D} \"command not found: compdef\" errors on startup${N}"
    print "  ${D}  ${G}Fix:${N}${D}     ${M}zpwr regenzsh${N}"
    print ""
    print "  ${D}  ${R}Symptom:${N}${D} Startup is slow (500ms+ for completion init)${N}"
    print "  ${D}  ${G}Fix:${N}${D}     ${M}zpwr regenzsh${D} (forces fresh, optimized dump)${N}"
    print ""
    print "  ${B}${Y}THE COMPLETION CACHE DIRECTORY${N}"
    print "  ${D}  Separate from zcompdump, zsh also caches individual${N}"
    print "  ${D}  completion results (like package names, hostnames, etc.)${N}"
    print "  ${D}  in a cache directory.${N}"
    print ""
    print "  ${M}  zpwr cleancompcache${N}${D}                 # wipe the cache directory${N}"
    print ""
    print "  ${D}  This forces completions to re-query their sources.${N}"
    print "  ${D}  Useful when package lists or hostnames changed.${N}"
    print ""
    print "  ${B}${Y}WHY COMPLETIONS BREAK${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  1.${N}${D} Stale zcompdump -- new compdef not registered${N}"
    print "  ${G}  2.${N}${D} Corrupted zcompdump -- syntax error in dump file${N}"
    print "  ${G}  3.${N}${D} Missing FPATH entry -- completion function not found${N}"
    print "  ${G}  4.${N}${D} Wrong function loaded -- .zwc has old version${N}"
    print "  ${G}  5.${N}${D} Plugin conflict -- two plugins register for same cmd${N}"
    print ""
    print "  ${B}${Y}THE NUCLEAR FIX${N}"
    print "  ${M}  zpwr cleancompcache${N}"
    print "  ${M}  zpwr decompile${N}"
    print "  ${M}  zpwr regenzsh${N}"
    print "  ${M}  zpwr recompile${N}"
    print "  ${D}  Four commands: nuke cache, remove .zwc, regen dump, recompile.${N}"
    print "  ${D}  This fixes 99% of completion problems. The remaining 1%${N}"
    print "  ${D}  is probably a bug in the completion function itself.${N}"
    print ""
}
