PAGE_TITLE="Forgit Reset & Restore"
PAGE_CHAPTER="CHAPTER 20: FORGIT DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< FORGIT RESET & RESTORE — UNDO WITH EYES OPEN >>>${N}"
    print "  ${D}the nuclear options, but with a safety preview${N}"
    print ""
    print "  ${C}Git reset and restore are the most terrifying commands${N}"
    print "  ${C}in version control. Forgit wraps them in bubble wrap${N}"
    print "  ${C}and gives you a preview before you pull the trigger.${N}"
    print ""
    print "  ${B}${Y}FORGITRESET — UNSTAGE WITH PREVIEW${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitreset${N}"
    print "  ${G}Shows staged files in fzf with diff previews.${N}"
    print "  ${G}Select files to unstage. Like git reset HEAD but${N}"
    print "  ${G}you can see exactly what you are unstaging first.${N}"
    print ""
    print "  ${D}  Use case: you ran git add -A like a maniac${N}"
    print "  ${D}  and now you need to surgically remove files.${N}"
    print "  ${M}  zpwr forgitreset${N}${D}    # browse and unstage selectively${N}"
    print ""
    print "  ${B}${Y}FORGITRESTORE — DISCARD CHANGES SAFELY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitrestore${N}"
    print "  ${G}Shows modified files with diff previews. Select files${N}"
    print "  ${G}to restore to their last committed state.${N}"
    print "  ${R}  This discards changes permanently. No undo.${N}"
    print ""
    print "  ${D}  The preview saves you. You see the diff before${N}"
    print "  ${D}  the changes evaporate into the void.${N}"
    print ""
    print "  ${B}${Y}FORGITWARN — THE SAFETY NET${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitwarn${N}"
    print "  ${G}Displays warnings about uncommitted changes, diverged${N}"
    print "  ${G}branches, and other hazardous states. Your pre-flight${N}"
    print "  ${G}checklist before doing anything destructive.${N}"
    print ""
    print "  ${B}${Y}FORGITINFO — THE STATUS DASHBOARD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitinfo${N}"
    print "  ${G}Comprehensive repo information at a glance.${N}"
    print "  ${G}Branch, remotes, recent commits, dirty state.${N}"
    print "  ${G}Everything you need before making decisions.${N}"
    print ""
    print "  ${B}${G}THE FORGIT COMPLETE ARSENAL:${N}"
    print "  ${C}  forgitadd${N}        ${D}interactive stage${N}"
    print "  ${C}  forgitdiff${N}       ${D}browse diffs${N}"
    print "  ${C}  forgitlog${N}        ${D}commit history browser${N}"
    print "  ${C}  forgitstash${N}      ${D}stash manager${N}"
    print "  ${C}  forgitreset${N}      ${D}interactive unstage${N}"
    print "  ${C}  forgitrestore${N}    ${D}discard changes with preview${N}"
    print "  ${C}  forgitclean${N}      ${D}purge untracked files${N}"
    print "  ${C}  forgitignore*${N}    ${D}gitignore template management${N}"
    print "  ${C}  forgitwarn${N}       ${D}hazard warnings${N}"
    print "  ${C}  forgitinfo${N}       ${D}repo dashboard${N}"
    print ""
    print "  ${D}  // forgit is not a git replacement${N}"
    print "  ${D}  // it is git with eyes. git with a UI. git for humans.${N}"
    print ""
}
