PAGE_TITLE="temprs: The Stack Machine"
PAGE_CHAPTER="CHAPTER 32: TEMPRS — TEMPORARY FILE STACK MANAGER"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== TEMPRS: THE STACK MACHINE ===${N}"
    print "  ${D}// your filesystem is a stack. you just didn't know it yet. //${N}"
    print "  ${C}temprs is a Rust-based temporary file stack manager by${N}"
    print "  ${C}MenkeTechnologies. Think of it as a LIFO/FIFO clipboard that${N}"
    print "  ${C}persists across shell sessions using actual tempfiles on disk.${N}"
    print "  ${C}Version 2.9.3. Every operation is instant. No databases, no${N}"
    print "  ${C}daemons — just a master record file and a directory of tempfiles.${N}"
    print "  ${B}${Y}THE STACK PARADIGM${N}"
    print "  ${D}temprs models your scratch data as a stack with both ends open:${N}"
    print "  ${D}push (default), pop, shift, unshift — like a Perl array on disk.${N}"
    print "  ${B}${Y}CORE OPERATIONS${N}"
    print "  ${G}  temprs${N}${D}              # no args: create new tempfile, push to top${N}"
    print "  ${G}  temprs -o INDEX${N}${D}     # read contents of tempfile at INDEX to stdout${N}"
    print "  ${G}  temprs -i INDEX${N}${D}     # write stdin into tempfile at INDEX${N}"
    print "  ${G}  temprs -p${N}${D}           # pop from top of stack (print + remove)${N}"
    print "  ${G}  temprs -s${N}${D}           # shift from bottom of stack (print + remove)${N}"
    print "  ${G}  temprs -u${N}${D}           # unshift: push stdin to bottom (silent)${N}"
    print "  ${G}  temprs -a INDEX${N}${D}     # insert new tempfile at INDEX${N}"
    print "  ${G}  temprs -r INDEX${N}${D}     # remove tempfile at INDEX${N}"
    print "  ${B}${Y}THE MASTER RECORD${N}"
    print "  ${D}temprs keeps a master record file that maps stack positions to${N}"
    print "  ${D}actual tempfile paths on disk. The temprs directory holds the${N}"
    print "  ${D}files themselves. Both are in your system's temp directory.${N}"
    print "  ${G}  temprs -d${N}${D}           # list the temprs directory contents${N}"
    print "  ${G}  temprs -m${N}${D}           # list the master record file path${N}"
    print "  ${B}${Y}PIPELINE INTEGRATION${N}"
    print "  ${D}temprs reads stdin when available — perfect for pipelines:${N}"
    print "  ${M}  echo 'stash this' | temprs -u${N}${D}  # silent push to bottom${N}"
    print "  ${M}  curl -s api.io/data | temprs${N}${D}    # push response to top${N}"
    print "  ${M}  temprs -o 0 | jq .${N}${D}             # read top, pipe to jq${N}"
    print "  ${D}The ${G}-u${D} unshift flag reads stdin and produces no stdout —${N}"
    print "  ${D}ideal for mid-pipeline stashing without breaking the flow.${N}"
    print "  ${B}${Y}POSITIONAL ARGUMENT${N}"
    print "  ${G}  temprs myfile.txt${N}${D}   # read file into new tempfile on stack${N}"
    print "  ${D}If both stdin and a file arg are present, stdin takes priority.${N}"
    print "  ${D}Your data flows in, gets a stack address, and waits for recall.${N}"
}
