PAGE_TITLE="Exercism Integration"
PAGE_CHAPTER="CHAPTER 23: EXERCISM & EXTERNAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< EXERCISM INTEGRATION — LEVEL UP YOUR CODE >>>${N}"
    print "  ${D}practice makes perfect. ZPWR makes practice frictionless.${N}"
    print ""
    print "  ${C}Exercism.org is a free coding practice platform with${N}"
    print "  ${C}mentor-reviewed exercises in 50+ languages. ZPWR wraps${N}"
    print "  ${C}the exercism CLI so you never leave your terminal.${N}"
    print ""
    print "  ${B}${Y}EXERCISM — THE LAUNCHER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr exercism${N}"
    print "  ${G}The base exercism command integration. Manages your${N}"
    print "  ${G}exercism workspace, configuration, and submission${N}"
    print "  ${G}workflow from within ZPWR.${N}"
    print ""
    print "  ${D}  Your exercism workspace lives under \$ZPWR and is${N}"
    print "  ${D}  accessible via ${M}zpwr homeexercism${D} for quick navigation.${N}"
    print ""
    print "  ${B}${Y}EXERCISMDOWNLOAD — FETCH EXERCISES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr exercismdownload${N}"
    print "  ${G}Downloads an exercise to your local workspace.${N}"
    print "  ${G}The exercise appears, ready to solve. Tests included.${N}"
    print "  ${G}No browser clicking. No manual downloads.${N}"
    print ""
    print "  ${D}  The workflow:${N}"
    print "  ${C}  1. Browse exercises on exercism.org${N}"
    print "  ${C}  2. ${M}zpwr exercismdownload${C} to fetch it${N}"
    print "  ${C}  3. Solve the exercise in your editor${N}"
    print "  ${C}  4. Run the tests locally${N}"
    print "  ${C}  5. Submit when you pass${N}"
    print ""
    print "  ${B}${Y}EXERCISMEDIT — SOLVE IN YOUR EDITOR${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr exercismedit${N}"
    print "  ${G}Opens exercism exercises directly in your configured${N}"
    print "  ${G}editor. Download, edit, test, submit — all from the${N}"
    print "  ${G}terminal. The browser is optional.${N}"
    print ""
    print "  ${B}${G}WHY EXERCISM + ZPWR:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  The exercism CLI is good. ZPWR makes it seamless.${N}"
    print "  ${C}  No context switching. No browser tabs. No friction.${N}"
    print ""
    print "  ${D}  Languages supported by exercism:${N}"
    print "  ${G}  Python, Go, Rust, Elixir, JavaScript, TypeScript,${N}"
    print "  ${G}  C, C++, Java, Ruby, Haskell, Clojure, Kotlin,${N}"
    print "  ${G}  Swift, Bash, and 35+ more.${N}"
    print ""
    print "  ${D}  // coding practice should be as easy as${N}"
    print "  ${D}  // opening a terminal and typing three words${N}"
    print "  ${D}  // zpwr exercismdownload. done. now solve.${N}"
    print ""
}
