PAGE_TITLE="Script Management"
PAGE_CHAPTER="CHAPTER 22: CREATIVE TOOLS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< SCRIPT MANAGEMENT — THE STRYKE >>>${N}"
    print "  ${D}create scripts. count scripts. print scripts to PDF. ship scripts.${N}"
    print ""
    print "  ${C}ZPWR manages its own script collection and gives you${N}"
    print "  ${C}tools to create new ones, inventory them, and even${N}"
    print "  ${C}export them to PDF for documentation or review.${N}"
    print ""
    print "  ${B}${Y}SCRIPTNEW — THE SCRIPT GENERATOR${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr scriptnew <name>${N}"
    print "  ${G}Creates a new script with proper boilerplate. Shebang,${N}"
    print "  ${G}error handling, argument parsing — all pre-wired.${N}"
    print "  ${G}Stop writing boilerplate. Start writing logic.${N}"
    print ""
    print "  ${D}  The script lands in \$ZPWR_SCRIPTS, already executable,${N}"
    print "  ${D}  already on your PATH. Zero friction from idea to tool.${N}"
    print ""
    print "  ${B}${Y}SCRIPTTOPDF — THE DOCUMENTER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr scripttopdf${N}"
    print "  ${G}Converts scripts to syntax-highlighted PDFs.${N}"
    print "  ${G}For code reviews, documentation, or printing out${N}"
    print "  ${G}and framing on your wall like the art it is.${N}"
    print ""
    print "  ${D}  Send your code to a printer. Assert dominance.${N}"
    print ""
    print "  ${B}${Y}SCRIPTCOUNT — THE CENSUS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr scriptcount${N}"
    print "  ${G}How many scripts live in \$ZPWR_SCRIPTS? This tells you.${N}"
    print "  ${G}Track the growth of your personal armory over time.${N}"
    print ""
    print "  ${B}${Y}SCRIPTLIST — THE INVENTORY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr scriptlist${N}"
    print "  ${G}Lists every script in the collection. Names, paths,${N}"
    print "  ${G}the full manifest of your executable arsenal.${N}"
    print ""
    print "  ${B}${G}THE SCRIPT LIFECYCLE:${N}"
    print "  ${C}  1. ${M}zpwr scriptnew myutil${C}     create the script${N}"
    print "  ${C}  2. ${M}zpwr vimscriptedit${C}        edit scripts with vim/fzf${N}"
    print "  ${C}  3. ${M}zpwr scriptcount${C}          check your inventory${N}"
    print "  ${C}  4. ${M}zpwr scriptlist${C}           browse the collection${N}"
    print "  ${C}  5. ${M}zpwr scripttopdf${C}          export for documentation${N}"
    print ""
    print "  ${B}${Y}ALSO RELATED:${N}"
    print "  ${M}  zpwr makedir <name>${N}${D}     create a directory${N}"
    print "  ${M}  zpwr makefile <name>${N}${D}    create a file${N}"
    print "  ${G}Simple creation verbs. No boilerplate, just mkdir/touch${N}"
    print "  ${G}with ZPWR's logging and validation baked in.${N}"
    print ""
    print "  ${D}  // a script unwritten is a problem unsolved${N}"
    print "  ${D}  // a script uncounted is a tool forgotten${N}"
    print "  ${D}  // the stryke never closes. the armory always grows.${N}"
    print ""
}
