PAGE_TITLE="Git Cache Hygiene"
PAGE_CHAPTER="CHAPTER 9: THE JANITOR'S CLOSET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT CACHE HYGIENE ===${N}"
    print "  ${D}// zpwr tracks your git repos. the cache needs a bath sometimes. //${N}"
    print ""
    print "  ${C}zpwr maintains caches of git repository locations so that${N}"
    print "  ${C}repo-aware verbs (navigation, status, batch operations) do not${N}"
    print "  ${C}have to scan the filesystem every time. Three verbs manage${N}"
    print "  ${C}these caches.${N}"
    print ""
    print "  ${B}${Y}CLEANGITCACHE: THE GENERAL REPO CACHE${N}"
    print "  ${M}  zpwr cleangitcache${N}${D}                  # clear all git repo caches${N}"
    print ""
    print "  ${D}  Wipes the master list of known git repositories.${N}"
    print "  ${D}  This cache is built by scanning for .git directories${N}"
    print "  ${D}  and is used by verbs like ${M}zpwr fordir${D} and repo${N}"
    print "  ${D}  navigation commands.${N}"
    print ""
    print "  ${D}  When to use it:${N}"
    print "  ${D}  - You moved or deleted git repos${N}"
    print "  ${D}  - Navigation is suggesting repos that no longer exist${N}"
    print "  ${D}  - You cloned new repos and they are not showing up${N}"
    print ""
    print "  ${D}  After clearing, run ${M}zpwr regengitrepocache${D} to rebuild.${N}"
    print ""
    print "  ${B}${Y}CLEANGITCLEANCACHE: CLEAN REPOS ONLY${N}"
    print "  ${M}  zpwr cleangitcleancache${N}${D}             # clear clean repo cache${N}"
    print ""
    print "  ${D}  zpwr separately tracks which repos have a clean working${N}"
    print "  ${D}  tree (no uncommitted changes). This cache speeds up${N}"
    print "  ${D}  operations that only care about clean repos.${N}"
    print ""
    print "  ${D}  Clear this when:${N}"
    print "  ${D}  - The \"clean repos\" list seems wrong${N}"
    print "  ${D}  - You committed in a repo but it still shows as dirty${N}"
    print ""
    print "  ${B}${Y}CLEANGITDIRTYCACHE: DIRTY REPOS ONLY${N}"
    print "  ${M}  zpwr cleangitdirtycache${N}${D}             # clear dirty repo cache${N}"
    print ""
    print "  ${D}  The mirror of the clean cache. Tracks repos with${N}"
    print "  ${D}  uncommitted changes. Clear this when:${N}"
    print "  ${D}  - A repo shows as dirty but you already committed${N}"
    print "  ${D}  - The dirty count in the banner seems wrong${N}"
    print ""
    print "  ${D}  Rebuild with: ${M}zpwr regengitdirtyrepocache${N}"
    print ""
    print "  ${B}${Y}THE GIT CACHE ARCHITECTURE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  regengitrepocache${N}${D}        scans for all git repos${N}"
    print "  ${C}  regengitdirtyrepocache${N}${D}   classifies clean vs dirty${N}"
    print "  ${C}  cleangitcache${N}${D}            wipes the master list${N}"
    print "  ${C}  cleangitcleancache${N}${D}       wipes the clean-only list${N}"
    print "  ${C}  cleangitdirtycache${N}${D}       wipes the dirty-only list${N}"
    print ""
    print "  ${D}  The caches live in \$ZPWR_LOCAL as plain text files.${N}"
    print "  ${D}  One repo path per line. Grep-friendly. Human-readable.${N}"
    print ""
    print "  ${B}${Y}THE FULL REFRESH${N}"
    print "  ${M}  zpwr cleangitcache${N}"
    print "  ${M}  zpwr regengitrepocache${N}"
    print "  ${M}  zpwr regengitdirtyrepocache${N}"
    print "  ${D}  Three commands. Fresh git cache. Takes a few seconds${N}"
    print "  ${D}  depending on how many repos you have scattered around.${N}"
    print ""
}
