PAGE_TITLE="Docker & Container Aliases"
PAGE_CHAPTER="CHAPTER 15: NETWORK & CONTAINERS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== DOCKER & CONTAINER ALIASES ===${N}"
    print "  ${D}// 148 aliases for the containerized world //${N}"
    print ""
    print "  ${C}The zsh-docker-aliases plugin provides 148 aliases for${N}"
    print "  ${C}Docker and Docker Compose operations.${N}"
    print ""
    print "  ${B}${Y}DOCKER SHORTCUTS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  dps${N}${D}                          # docker ps${N}"
    print "  ${M}  dpsa${N}${D}                         # docker ps -a${N}"
    print "  ${M}  di${N}${D}                           # docker images${N}"
    print "  ${M}  drm${N}${D}                          # docker rm${N}"
    print "  ${M}  drmi${N}${D}                         # docker rmi${N}"
    print "  ${M}  dex${N}${D}                          # docker exec -it${N}"
    print "  ${M}  dl${N}${D}                           # docker logs -f${N}"
    print ""
    print "  ${B}${Y}DOCKER COMPOSE${N}"
    print "  ${M}  dcu${N}${D}                          # docker compose up -d${N}"
    print "  ${M}  dcd${N}${D}                          # docker compose down${N}"
    print "  ${M}  dcl${N}${D}                          # docker compose logs -f${N}"
    print "  ${M}  dcr${N}${D}                          # docker compose restart${N}"
    print ""
    print "  ${B}${Y}ZPWR INTEGRATION${N}"
    print "  ${M}  zpwr dockerwipe${N}${D}              # nuke all images/containers${N}"
    print "  ${M}  zpwr dfimage <ID>${N}${D}            # extract Dockerfile from image${N}"
    print ""
    print "  ${D}  Plugin: ${C}MenkeTechnologies/zsh-docker-aliases${N}"
    print ""
}
