PAGE_TITLE="Command Autopsy"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== COMMAND AUTOPSY ===${N}"
    print "  ${D}// when you need to know why a command is slow, fat, or dead //${N}"
    print ""
    print "  ${C}The ${M}trace${C} verb is a command profiler. It wraps any command${N}"
    print "  ${C}in instrumentation and reports wall time, CPU time, memory,${N}"
    print "  ${C}context switches, page faults, and more.${N}"
    print ""
    print "  ${B}${Y}BASIC USAGE${N}"
    print "  ${M}  zpwr trace ls -la${N}${D}                   # full trace of ls -la${N}"
    print "  ${M}  zpwr trace -q make${N}${D}                  # quick: timing + resources only${N}"
    print "  ${M}  zpwr trace -h${N}${D}                       # full help${N}"
    print ""
    print "  ${B}${Y}THE FLAGS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}-q, --quick${N}${D}      Timing + resource stats only (runs once)${N}"
    print "  ${C}-s, --strace${N}${D}     Syscall counts only (Linux; no ltrace)${N}"
    print "  ${C}-l, --ltrace${N}${D}     C library calls only (Linux; no strace)${N}"
    print "  ${C}-a, --all${N}${D}        Both strace + ltrace (default behavior)${N}"
    print ""
    print "  ${B}${Y}WHAT YOU GET: THE RESOURCE CARD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  exit code${N}${D}          green = 0, red = nonzero${N}"
    print "  ${G}  wall time${N}${D}          real clock time with rating:${N}"
    print "  ${D}                     INSTANT (<100ms), FAST (<1s),${N}"
    print "  ${D}                     NOMINAL (<5s), SLOW (<30s), HEAVY (30s+)${N}"
    print "  ${G}  user/sys time${N}${D}      CPU time in user/kernel space${N}"
    print "  ${G}  peak RSS${N}${D}           max resident memory (auto-scaled B/KB/MB/GB)${N}"
    print "  ${G}  ctx switches${N}${D}       voluntary + involuntary context switches${N}"
    print "  ${G}  page reclaims${N}${D}      soft faults (memory mapped in from cache)${N}"
    print "  ${G}  page faults${N}${D}        hard faults (actual disk I/O for memory)${N}"
    print "  ${G}  block I/O${N}${D}          filesystem reads and writes${N}"
    print "  ${G}  signals recv${N}${D}       number of signals delivered${N}"
    print "  ${G}  IPC messages${N}${D}       sent/received inter-process messages${N}"
    print "  ${G}  shell delta${N}${D}        memory change of the parent shell${N}"
    print "  ${G}  child procs${N}${D}        before/after child process count${N}"
    print ""
    print "  ${B}${Y}PLATFORM DIFFERENCES${N}"
    print "  ${C}  macOS:${N}${D}  /usr/bin/time -l for resource stats.${N}"
    print "  ${D}          SIP blocks dtruss/dtrace on most binaries.${N}"
    print "  ${D}          You get timing + memory + kernel stats.${N}"
    print "  ${C}  Linux:${N}${D}  strace -c for syscall counts, ltrace -c for${N}"
    print "  ${D}          C library calls. Command re-runs for each tool.${N}"
    print ""
    print "  ${B}${Y}PRACTICAL EXAMPLES${N}"
    print "  ${M}  zpwr trace git status${N}${D}              # is git status slow in this repo?${N}"
    print "  ${M}  zpwr trace -q rm -rf node_modules${N}${D}  # quick mode for destructive ops${N}"
    print "  ${M}  zpwr trace -s npm install${N}${D}          # syscalls only (Linux)${N}"
    print "  ${M}  zpwr trace zsh -c 'source ~/.zshrc'${N}${D} # profile shell startup${N}"
    print ""
    print "  ${B}${Y}THE SIGNAL BAR${N}"
    print "  ${D}  Bottom of output: a 10-block performance signal.${N}"
    print "  ${G}  ██████████${D}  score 10 = under 100ms. Lightning.${N}"
    print "  ${Y}  ██████${D}░░░░  score 6  = under 2s. Acceptable.${N}"
    print "  ${R}  ██${D}░░░░░░░░  score 2  = under 30s. Go get coffee.${N}"
    print ""
    print "  ${R}${B}WARNING:${N}${R} Default mode re-runs the command for strace/ltrace.${N}"
    print "  ${R}Use ${M}-q${R} for destructive commands (rm, truncate, etc).${N}"
    print ""
}
