PAGE_TITLE="The .zwc Compilation System"
PAGE_CHAPTER="CHAPTER 28: ZSH INTERNALS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== THE .zwc COMPILATION SYSTEM ===${N}"
    print "  ${D}// bytecode for your shell. because even scripts deserve a compiler. //${N}"
    print "  ${C}Zsh can compile scripts to .zwc (Zsh Word Code) bytecode.${N}"
    print "  ${C}These files skip the parsing phase on load, going straight${N}"
    print "  ${C}to execution. ZPWR compiles 50+ files for speed.${N}"
    print "  ${B}${Y}WHAT .zwc FILES ARE${N}"
    print "  ${D}A .zwc file is a binary representation of parsed zsh code.${N}"
    print "  ${D}When zsh sources a .zsh file, it checks for a .zwc sibling.${N}"
    print "  ${D}If the .zwc exists and is newer than the source, zsh loads${N}"
    print "  ${D}the bytecode directly. No lexing, no parsing.${N}"
    print "  ${D}Speedup: 2-5x for large files. Marginal for tiny ones.${N}"
    print "  ${B}${Y}zrecompile${N}"
    print "  ${D}The zrecompile utility compiles only if the source is newer:${N}"
    print "  ${M}  autoload -Uz zrecompile${N}"
    print "  ${M}  zrecompile -p -U \$ZPWR_ENV_FILE${N}"
    print "  ${D}-p means 'check pairs' (source vs .zwc timestamps).${N}"
    print "  ${D}-U suppresses alias expansion during compilation.${N}"
    print "  ${D}If the .zwc is current, zrecompile is a no-op.${N}"
    print "  ${B}${Y}zpwrRecompileFiles: WHAT GETS COMPILED${N}"
    print "  ${D}The function compiles two categories of files:${N}"
    print "  ${G}  Local files (~47):${N}"
    print "  ${D}    ~/.zshrc, ~/.zshenv, ~/.zlogout, ~/.zlogin${N}"
    print "  ${D}    p10k-instant-prompt-*.zsh, p10k-dump-*.zsh${N}"
    print "  ${D}    \$ZSH_COMPDUMP, \$ZPWR_ALIAS_FILE, \$ZPWR_PROMPT_FILE${N}"
    print "  ${D}    \$ZPWR_LOCAL/.tokens.sh, \$ZPWR_ENV_FILE, \$ZPWR_RE_ENV_FILE${N}"
    print "  ${D}    All .zsh/.sh in \$ZPWR_ENV/, all .zsh in \$ZPWR_SCRIPTS/${N}"
    print "  ${D}    All plugin .zsh files under \$ZPWR_PLUGIN_MANAGER_HOME/bin/${N}"
    print "  ${D}    OMZ lib, plugin, theme, and custom files${N}"
    print "  ${G}  Global files (~8):${N}"
    print "  ${D}    /etc/profile, /etc/zshrc, /etc/zshenv, /etc/zprofile, etc.${N}"
    print "  ${D}    These need sudo (compiled with sudo zsh -c zrecompile).${N}"
    print "  ${B}${Y}ZPWR VERBS FOR COMPILATION${N}"
    print "  ${M}  zpwr recompile${N}${D}       Compile all known files (zpwrRecompileFiles)${N}"
    print "  ${M}  zpwr decompile${N}${D}       Remove .zwc files (zpwrUncompile)${N}"
    print "  ${M}  zpwr refreshzwc${N}${D}      Remove + recompile (clean rebuild)${N}"
    print "  ${B}${Y}THE zsh/files MODULE${N}"
    print "  ${D}Zsh can load builtin file operations via zmodload:${N}"
    print "  ${M}  zmodload -F zsh/files b:zf_ln b:zf_rm b:zf_mkdir${N}"
    print "  ${D}These are shell builtins that replace ln, rm, mkdir.${N}"
    print "  ${D}No fork, no exec -- pure kernel syscalls from the shell process.${N}"
    print "  ${D}ZPWR uses zf_ln for the OMZ completion symlink hack.${N}"
    print "  ${D}In a loop creating 12 symlinks, this saves 12 fork+exec pairs.${N}"
    print "  ${B}${Y}OTHER USEFUL MODULES${N}"
    print "  ${M}  zsh/datetime${N}${D}    \$EPOCHREALTIME, \$EPOCHSECONDS${N}"
    print "  ${M}  zsh/complist${N}${D}    Menu-select completion mode${N}"
    print "  ${M}  zsh/zprof${N}${D}       Profiler (ZPWR_PROFILING=true enables it)${N}"
    print "  ${D}Modules are loaded with: ${M}zmodload zsh/datetime${N}"
}
