PAGE_TITLE="eza: Colors & Integration"
PAGE_CHAPTER="CHAPTER 34: EZA — THE MODERN LS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== EZA: COLORS & INTEGRATION ===${N}"
    print "  ${D}// a file listing without color is just noise. //${N}"
    print "  ${B}${Y}EZA_COLORS ENVIRONMENT VARIABLE${N}"
    print "  ${D}eza uses EZA_COLORS (or EXA_COLORS for compat) to customize${N}"
    print "  ${D}colors beyond the defaults. Format is colon-separated key=value:${N}"
    print "  ${M}  export EZA_COLORS=\"di=34:ln=35:so=32:pi=33:ex=31\"${N}"
    print "  ${D}Keys match LS_COLORS extensions. eza also adds its own:${N}"
    print "  ${D}  ${G}da${D}=date, ${G}sn${D}=file size number, ${G}sb${D}=file size unit,${N}"
    print "  ${D}  ${G}uu${D}=current user, ${G}un${D}=other user, ${G}gu${D}=current group.${N}"
    print "  ${B}${Y}LS_COLORS COMPATIBILITY${N}"
    print "  ${D}eza reads LS_COLORS as a fallback. If you have a vivid or${N}"
    print "  ${D}dircolors setup, eza inherits it. EZA_COLORS overrides.${N}"
    print "  ${B}${Y}TREE VIEW${N}"
    print "  ${M}  eza --tree${N}${D}          # recursive tree (like tree command)${N}"
    print "  ${M}  eza --tree -L 3${N}${D}     # limit depth to 3 levels${N}"
    print "  ${M}  eza --tree --git-ignore${N}${D} # respect .gitignore in tree${N}"
    print "  ${D}The tree integrates with --git, so you see git status markers${N}"
    print "  ${D}inline with the tree structure. New files glow green.${N}"
    print "  ${B}${Y}THE FALLBACK CHAIN IN zpwrListNoClear${N}"
    print "  ${D}1. If eza exists: eval \$ZPWR_EXA_COMMAND${N}"
    print "  ${D}2. macOS + grc: ${M}grc -c ~/conf.gls gls -iFlhA --color=always${N}"
    print "  ${D}3. macOS bare: ${M}ls -iFlhAO${N}${D} (O = macOS file flags)${N}"
    print "  ${D}4. Linux + grc: ${M}grc -c ~/conf.gls ls -iFlhA --color=always${N}"
    print "  ${D}5. Linux bare: ${M}ls -ifhlA${N}"
    print "  ${D}grc (Generic Colouriser) wraps ls output with conf.gls rules.${N}"
    print "  ${D}It's the middle ground between raw ls and eza.${N}"
    print "  ${B}${Y}ZPWR VERBS USING EZA${N}"
    print "  ${D}zpwrClearList clears the terminal then runs the listing.${N}"
    print "  ${D}It's called on every cd via the chpwd hook — so you always${N}"
    print "  ${D}see what's in the directory you just landed in.${N}"
    print "  ${D}zpwrListNoClear does the same listing without clearing.${N}"
    print "  ${B}${Y}SORTING & FILTERING${N}"
    print "  ${M}  eza --sort=modified${N}${D}  # sort by modification time${N}"
    print "  ${M}  eza --sort=size${N}${D}      # sort by file size${N}"
    print "  ${M}  eza -r${N}${D}               # reverse sort order${N}"
    print "  ${M}  eza --group-directories-first${N}${D} # dirs at top${N}"
    print "  ${M}  eza -I '*.pyc|__pycache__'${N}${D}   # ignore patterns${N}"
    print "  ${D}Combine with --git-ignore to hide everything in .gitignore.${N}"
    print "  ${D}Your file listings become as curated as your code.${N}"
}
