PAGE_TITLE="Perl Oneliners: The Secret Weapon"
PAGE_CHAPTER="CHAPTER 39: PERL IN ZPWR"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== PERL ONELINERS: THE SECRET WEAPON ===${N}"
    print "  ${D}sed wishes it could do this. awk cries in a corner.${N}"
    print ""
    print "  ${C}Perl is zpwr's scalpel for text surgery. Where sed and awk${N}"
    print "  ${C}stumble on complex patterns, perl oneliners slice clean.${N}"
    print "  ${C}zpwr uses perl throughout for text transformation, parsing,${N}"
    print "  ${C}delimiter handling, and file manipulation.${N}"
    print ""
    print "  ${B}${Y}THE KEY FLAGS${N}"
    print "  ${C}-e 'code'${N}     ${D}execute code${N}"
    print "  ${C}-n${N}            ${D}loop over input lines (like sed)${N}"
    print "  ${C}-p${N}            ${D}loop and print each line (like sed -p)${N}"
    print "  ${C}-l${N}            ${D}chomp newlines, add them back on print${N}"
    print "  ${C}-a${N}            ${D}autosplit into @F array (like awk)${N}"
    print "  ${C}-F'sep'${N}       ${D}set field separator for -a${N}"
    print "  ${C}-i${N}            ${D}in-place edit (like sed -i)${N}"
    print "  ${C}-E${N}            ${D}enable say, state, switch (modern perl)${N}"
    print ""
    print "  ${B}${Y}WHITESPACE CLEANUP (scripts/lib.sh)${N}"
    print "  ${M}  perl -pi -e 's@\\s+\$@\\n@g; s@\\x09\$@    @g'${N}"
    print "  ${D}  Strips trailing whitespace, converts trailing tabs to spaces.${N}"
    print "  ${D}  The -pi combo: -p loops, -i edits in place. zpwr's file cleaner.${N}"
    print ""
    print "  ${B}${Y}PRINT SEPARATOR LINES${N}"
    print "  ${M}  perl -le \"print '#'x80\"${N}"
    print "  ${D}  Prints 80 # characters. The x operator repeats a string.${N}"
    print "  ${D}  Used in zpwrPrettyPrint for visual separators.${N}"
    print ""
    print "  ${B}${Y}DELIMITER TRANSFORMATION${N}"
    print "  ${M}  perl -F\"\$ZPWR_DELIMITER_CHAR\" -anE 'say ...'${N}"
    print "  ${D}  Splits lines on ZPWR_DELIMITER_CHAR into @F fields.${N}"
    print "  ${D}  Used heavily in zpwrContribCount, zpwrTotalLines for${N}"
    print "  ${D}  reformatting git contribution data into tabular output.${N}"
    print ""
    print "  ${B}${Y}FILTER BLANK LINES${N}"
    print "  ${M}  perl -ne 'print if /\\S/'${N}"
    print "  ${D}  Only prints lines containing non-whitespace.${N}"
    print "  ${D}  Used in zpwrRegenAllKeybindingsCache to clean keybinding dumps.${N}"
    print ""
    print "  ${B}${Y}THE PERL REPL ALIAS${N}"
    print "  ${M}  plr${N} ${D}(alias for rlwrap perl -wnE'say eval()//\$@')${N}"
    print "  ${D}  Interactive perl REPL with readline. Type expressions, get results.${N}"
}
