PAGE_TITLE="Key Duplication -- Multi-Pane Workflow"
PAGE_CHAPTER="CHAPTER 14: TMUX WARFARE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> KEY DUPLICATION: TYPE ONCE, EXECUTE EVERYWHERE <<<${N}"
    print "  ${D}the closest thing to being in two places at once${N}"
    print ""
    print "  ${B}${Y}zpwr startsend${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Send keystrokes to ALL panes in the current window.${N}"
    print "  ${G}Whatever you type goes to every pane simultaneously.${N}"
    print ""
    print "  ${C}  \$ zpwr startsend${N}              ${D}# enable key broadcast${N}"
    print ""
    print "  ${Y}USE CASE:${N} You have 4 panes SSHed into 4 servers."
    print "  ${Y}You need to run the same command on all of them.${N}"
    print "  ${G}startsend + type once = executed on all 4.${N}"
    print ""
    print "  ${B}${Y}zpwr startsendfull${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Like startsend, but broadcasts across ALL windows${N}"
    print "  ${G}and ALL panes in the entire tmux session.${N}"
    print ""
    print "  ${C}  \$ zpwr startsendfull${N}          ${D}# global broadcast${N}"
    print ""
    print "  ${R}  DANGER: every pane in every window receives input.${N}"
    print "  ${R}  Make sure you know what you are doing.${N}"
    print ""
    print "  ${B}${Y}zpwr stopsend${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Turn off key broadcasting. Back to single-pane input.${N}"
    print ""
    print "  ${C}  \$ zpwr stopsend${N}               ${D}# disable broadcast${N}"
    print ""
    print "  ${B}${Y}THE MULTI-PANE WORKFLOW:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. \$ zpwr start                   # launch tmux${N}"
    print "  ${D}  2. Split into 4 panes (Ctrl-b %)${N}"
    print "  ${D}  3. SSH into different servers in each${N}"
    print "  ${D}  4. \$ zpwr startsend               # enable broadcast${N}"
    print "  ${D}  5. Type: sudo apt update && sudo apt upgrade -y${N}"
    print "  ${D}  6. All 4 servers update simultaneously${N}"
    print "  ${D}  7. \$ zpwr stopsend                # back to normal${N}"
    print ""
    print "  ${D}  // sysadmins call this poor mans ansible${N}"
    print "  ${D}  // but honestly it is faster for quick ops${N}"
}
