PAGE_TITLE="Tmux Copy Mode (vi)"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< TMUX COPY MODE (VI BINDINGS) >>>${N}"
    print "  ${D}scrollback navigation, selection, copy, search. pure vi.${N}"
    print ""
    print "  ${B}${Y}ENTER/EXIT:${N}"
    print "  ${C}prefix [${N}              ${D}enter copy mode${N}"
    print "  ${C}q${N}                     ${D}cancel and exit copy mode${N}"
    print "  ${C}Escape${N}                ${D}clear selection${N}"
    print ""
    print "  ${B}${Y}SELECTION & COPY:${N}"
    print "  ${C}v${N}                     ${D}begin selection${N}"
    print "  ${C}V${N}                     ${D}select entire line${N}"
    print "  ${C}Ctrl-v${N}               ${D}toggle rectangle selection${N}"
    print "  ${C}Space${N}                 ${D}begin selection (alternate)${N}"
    print "  ${C}y${N}                     ${D}copy selection to clipboard (no clear)${N}"
    print "  ${C}Enter${N}                 ${D}copy selection to clipboard and cancel${N}"
    print "  ${C}D${N}                     ${D}copy to end of line and cancel${N}"
    print "  ${C}A${N}                     ${D}append selection and cancel${N}"
    print ""
    print "  ${B}${Y}NAVIGATION:${N}"
    print "  ${C}h/j/k/l${N}              ${D}cursor movement${N}"
    print "  ${C}Ctrl-h/j/k/l${N}         ${D}move cursor 4 cells at a time${N}"
    print "  ${C}w/b/e${N}                ${D}word forward/backward/end${N}"
    print "  ${C}W/B/E${N}                ${D}WORD (space-delimited) movement${N}"
    print "  ${C}0 / \$${N}                ${D}start/end of line${N}"
    print "  ${C}^${N}                     ${D}first non-blank character${N}"
    print "  ${C}g / G${N}                ${D}top / bottom of history${N}"
    print "  ${C}H / M / L${N}            ${D}top / middle / bottom of screen${N}"
    print ""
    print "  ${B}${Y}SCROLLING:${N}"
    print "  ${C}Ctrl-u / Ctrl-d${N}      ${D}half page up / down${N}"
    print "  ${C}Ctrl-b / Ctrl-f${N}      ${D}full page up / down${N}"
    print "  ${C}Ctrl-y / Ctrl-e${N}      ${D}scroll up / down one line${N}"
    print "  ${C}J / K${N}                ${D}scroll down / up one line${N}"
    print ""
    print "  ${B}${Y}SEARCH:${N}"
    print "  ${C}/${N}                     ${D}search forward (incremental)${N}"
    print "  ${C}?${N}                     ${D}search backward (incremental)${N}"
    print "  ${C}n / N${N}                ${D}next / previous match${N}"
    print "  ${C}*${N}                     ${D}search forward for word under cursor${N}"
    print "  ${C}#${N}                     ${D}search backward for word under cursor${N}"
    print ""
    print "  ${B}${Y}ZPWR EXTENSIONS:${N}"
    print "  ${C}s${N}                     ${D}copy + google search selection${N}"
    print "  ${C}x${N}                     ${D}copy + open URL selection${N}"
    print "  ${C}z${N}                     ${D}copy + google search selection${N}"
    print "  ${C}RightClick${N}            ${D}copy + google search selection${N}"
    print ""
    print "  ${D}Copy goes to system clipboard via reattach-to-user-namespace pbcopy.${N}"
    print "  ${D}ZPWR extends vi copy mode with instant google/open actions.${N}"
    print ""
    print "  ${M}  // in copy mode the wizard moves through time${N}"
    print "  ${M}  // scrollback is archaeology, search is divination${N}"
    print ""
}
