PAGE_TITLE="gh_reveal: Open Repo in Browser"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GH_REVEAL: OPEN REPO IN BROWSER ===${N}"
    print "  ${D}quickly open the current git project in your browser${N}"
    print ""
    print "  ${B}${Y}THE COMMAND${N}"
    print "  ${M}  zpwr reveal${N}${D}              # open current repo on GitHub${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${G}  Reads the git remote URL from the current repo,${N}"
    print "  ${G}  converts it to an HTTPS URL, and opens it in${N}"
    print "  ${G}  your default browser. Works with GitHub, GitLab,${N}"
    print "  ${G}  Bitbucket, and any git remote.${N}"
    print ""
    print "  ${B}${Y}USE CASES${N}"
    print "  ${D}  - Check the PR page for the branch you are on${N}"
    print "  ${D}  - View the README without cat-ing it locally${N}"
    print "  ${D}  - Jump to Issues or Actions from the terminal${N}"
    print "  ${D}  - Share a repo link with a coworker fast${N}"
    print ""
    print "  ${D}Also accessible as ${M}zpwr revealrecurse${D} to search${N}"
    print "  ${D}up the directory tree for a git repo.${N}"
    print ""
    print "  ${D}Plugin: ${C}MenkeTechnologies/gh_reveal${N}"
    print ""
}
