PAGE_TITLE="All 408 Verbs A-G"
PAGE_CHAPTER="CHAPTER 25: THE COMPLETE REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ALL 408 VERBS: A through G (1/3) >>>${N}"
    print "  ${D}the complete arsenal. memorize at your own peril.${N}"
    print ""
    print "  ${C}a${N}                          ${D}quick autoload access${N}"
    print "  ${C}about${N}                      ${D}display ZPWR about info${N}"
    print "  ${C}alacritty${N}                  ${D}alacritty terminal config${N}"
    print "  ${C}aliasrank${N}                  ${D}rank aliases by usage frequency${N}"
    print "  ${C}all${N}                        ${D}show all ZPWR info${N}"
    print "  ${C}allsearch${N}                  ${D}search across all sources${N}"
    print "  ${C}altprettyprint${N}             ${D}alternate syntax-highlighted print${N}"
    print "  ${C}animate${N}                    ${D}terminal animations${N}"
    print "  ${C}attach${N}                     ${D}attach to tmux session${N}"
    print "  ${C}autoload${N}                   ${D}show autoload system${N}"
    print "  ${C}autoloadcount${N}              ${D}count autoloaded functions${N}"
    print "  ${C}autoloadlist${N}               ${D}list all autoloaded functions${N}"
    print "  ${C}background${N}                 ${D}run command in background${N}"
    print "  ${C}backup${N}                     ${D}backup ZPWR configuration${N}"
    print "  ${C}backuphistory${N}              ${D}backup shell history${N}"
    print "  ${C}banner${N}                     ${D}display ZPWR banner${N}"
    print "  ${C}bannercounts${N}               ${D}banner with counts${N}"
    print "  ${C}bannerlolcat${N}               ${D}rainbow banner via lolcat${N}"
    print "  ${C}bannernopony${N}               ${D}banner without ponysay${N}"
    print "  ${C}bannerpony${N}                 ${D}banner with ponysay${N}"
    print "  ${C}bench${N}                      ${D}benchmark shell startup${N}"
    print "  ${C}brc${N}                        ${D}source bashrc${N}"
    print "  ${C}c${N}                          ${D}cat / view file${N}"
    print "  ${C}cat${N}                        ${D}enhanced cat${N}"
    print "  ${C}catcd${N}                      ${D}cat file and cd to its dir${N}"
    print "  ${C}catnviminforecentf${N}         ${D}cat nvim info recent files${N}"
    print "  ${C}catrecentfviminfo${N}          ${D}cat recent files from viminfo${N}"
    print "  ${C}catviminfo${N}                 ${D}cat viminfo file${N}"
    print "  ${C}cd${N}                         ${D}enhanced cd${N}"
    print "  ${C}cdup${N}                       ${D}cd up one directory${N}"
    print "  ${C}cfasd${N}                      ${D}cd via fasd frecency${N}"
    print "  ${C}changename${N}                 ${D}rename files interactively${N}"
    print "  ${C}changenamezpwr${N}             ${D}rename ZPWR components${N}"
    print "  ${C}cleanall${N}                   ${D}clean everything${N}"
    print "  ${C}cleancache${N}                 ${D}clean caches${N}"
    print "  ${C}cleancompcache${N}             ${D}clean completion cache${N}"
    print "  ${C}color2${N}                     ${D}turn on stderr color filter${N}"
    print "  ${C}environmentvariables${N}       ${D}list zpwr env vars (alias: envvars)${N}"
    print "  ${C}environmentvariablesall${N}    ${D}list all env vars (alias: envvarsall)${N}"
    print "  ${C}environmentvars${N}            ${D}list zpwr env vars (alias: envvars)${N}"
    print "  ${C}environmentvarsall${N}         ${D}list all env vars (alias: envvarsall)${N}"
    print ""
    print "  ${D}... continued. Run zpwr verbs for the complete list.${N}"
}
