PAGE_TITLE="Alias Chains"
PAGE_CHAPTER="CHAPTER 24: TIPS, TRICKS & EASTER EGGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ALIAS CHAINS — COMPOUND OPERATIONS >>>${N}"
    print "  ${D}one verb triggers another. the cascade begins.${N}"
    print ""
    print "  ${C}ZPWR verbs do not exist in isolation. They chain.${N}"
    print "  ${C}They compose. They call each other. This is not an${N}"
    print "  ${C}accident — it is the architecture.${N}"
    print ""
    print "  ${B}${Y}THE SHORTHAND ALIASES:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}ZPWR is aliased to shorter forms for speed:${N}"
    print "  ${M}  zpwr${N}${D}   the full command${N}"
    print "  ${M}  zp${N}${D}     shorter${N}"
    print "  ${M}  zpz${N}${D}    alternate short form${N}"
    print ""
    print "  ${D}  All three are equivalent:${N}"
    print "  ${M}  zpwr help${N}${D}  ==  ${M}zp help${D}  ==  ${M}zpz help${N}"
    print ""
    print "  ${B}${Y}COMPOUND VERB PATTERNS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Many verbs are compounds that do two things:${N}"
    print ""
    print "  ${C}  filesearch + edit${N}     ${D}= ${M}zpwr filesearchedit${N}"
    print "  ${C}  findsearch + edit${N}     ${D}= ${M}zpwr findsearchedit${N}"
    print "  ${C}  locatesearch + edit${N}   ${D}= ${M}zpwr locatesearchedit${N}"
    print "  ${C}  wordsearch + edit${N}     ${D}= ${M}zpwr wordsearchedit${N}"
    print "  ${C}  vimrecent + cd${N}        ${D}= ${M}zpwr vimrecentcd${N}"
    print "  ${C}  vimrecent + sudo${N}      ${D}= ${M}zpwr vimrecentsudo${N}"
    print ""
    print "  ${G}The pattern: ${Y}action + modifier = compound verb${N}"
    print "  ${G}Search, then edit. Browse, then cd. Open, then sudo.${N}"
    print ""
    print "  ${B}${Y}THE CLEAN CHAIN:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cleanall${N}${D}             clean everything${N}"
    print "  ${M}  zpwr cleancache${N}${D}           clean caches only${N}"
    print "  ${M}  zpwr cleancompcache${N}${D}       clean completion cache${N}"
    print "  ${M}  zpwr cleangitcache${N}${D}        clean git repo cache${N}"
    print "  ${M}  zpwr cleangitcleancache${N}${D}   clean git clean cache${N}"
    print "  ${M}  zpwr cleangitdirtycache${N}${D}   clean git dirty cache${N}"
    print "  ${M}  zpwr cleantemp${N}${D}            clean temp files${N}"
    print "  ${M}  zpwr cleanrefreshupdate${N}${D}   clean + refresh + update${N}"
    print ""
    print "  ${B}${Y}THE GIT CHAIN:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitforalldir${N}${D}     run git cmd in all dirs${N}"
    print "  ${M}  zpwr gitfordirmain${N}${D}    run git cmd in dirs on main${N}"
    print "  ${M}  zpwr gitzfordir${N}${D}       z-style git for all dirs${N}"
    print ""
    print "  ${D}  // verbs are words. chains are sentences.${N}"
    print "  ${D}  // the grammar of ZPWR is combinatorial.${N}"
    print "  ${D}  // learn the words, and the sentences write themselves.${N}"
    print ""
}
