PAGE_TITLE="Display & Input"
PAGE_CHAPTER="CHAPTER 21: ZPWR ENVIRONMENT VARIABLES"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< DISPLAY & INPUT — THE HUMAN INTERFACE LAYER >>>${N}"
    print "  ${D}how the machine talks to you, and how you talk back${N}"
    print ""
    print "  ${C}These variables control what you see and how fast${N}"
    print "  ${C}the shell responds to your keystrokes. Milliseconds${N}"
    print "  ${C}matter when your fingers are moving at light speed.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_EXA_COMMAND — THE LS REPLACEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_EXA_COMMAND${N}${D}   # exa or eza${N}"
    print "  ${G}Controls which modern ls replacement ZPWR uses.${N}"
    print "  ${G}exa is the original, eza is the maintained fork.${N}"
    print "  ${G}Both give you colored, git-aware directory listings.${N}"
    print ""
    print "  ${D}  ZPWR verbs like ${M}zpwr ls${D} and ${M}zpwr clearls${D} use this.${N}"
    print "  ${D}  Set it in your tokens file to override the default.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_KEYTIMEOUT — KEYSTROKE LATENCY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_KEYTIMEOUT${N}${D}   # in hundredths of a second${N}"
    print "  ${G}How long zsh waits for the next key in a multi-key${N}"
    print "  ${G}sequence. Lower = snappier. Too low = missed sequences.${N}"
    print "  ${G}Default is tuned for fast typists.${N}"
    print ""
    print "  ${D}  If vi-mode feels laggy on Esc, lower this.${N}"
    print "  ${D}  If key combos misfire, raise this.${N}"
    print "  ${D}  Sweet spot is personal. Experiment.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_EXPAND_PRE_EXEC — ALIAS EXPANSION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_EXPAND_PRE_EXEC${N}"
    print "  ${G}Controls whether ZPWR expands aliases before execution.${N}"
    print "  ${G}When enabled, you type the alias and see the full${N}"
    print "  ${G}command in your history. Transparency mode.${N}"
    print ""
    print "  ${D}  With expansion:    you type ${M}ga${D}  -> history shows ${M}git add${N}"
    print "  ${D}  Without expansion: you type ${M}ga${D}  -> history shows ${M}ga${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_SEND_KEYS_FULL — TMUX KEY PASSTHROUGH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_SEND_KEYS_FULL${N}"
    print "  ${G}Controls full send-keys behavior in tmux integration.${N}"
    print "  ${G}When ZPWR manages tmux panes, this determines how${N}"
    print "  ${G}keystrokes are forwarded to target panes.${N}"
    print ""
    print "  ${B}${G}TUNING GUIDE:${N}"
    print "  ${C}  Feeling laggy?${N}       ${D}Lower ZPWR_KEYTIMEOUT${N}"
    print "  ${C}  Missing combos?${N}      ${D}Raise ZPWR_KEYTIMEOUT${N}"
    print "  ${C}  Want transparency?${N}   ${D}Enable ZPWR_EXPAND_PRE_EXEC${N}"
    print "  ${C}  Using eza?${N}           ${D}Set ZPWR_EXA_COMMAND=eza${N}"
    print ""
    print "  ${D}  // the interface is not decoration. it is velocity.${N}"
    print "  ${D}  // every millisecond of latency is a papercut.${N}"
    print "  ${D}  // tune these until your shell feels like thought.${N}"
    print ""
}
