PAGE_TITLE="FZF in Practice"
PAGE_CHAPTER="CHAPTER 29: FZF ARCHITECTURE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== FZF IN PRACTICE ===${N}"
    print "  ${D}// the theory is simple. the practice is where it gets good. //${N}"
    print "  ${C}ZPWR ships dozens of fzf-powered workflows. Each follows${N}"
    print "  ${C}the generate | fzf | action pattern. Here are the heaviest hitters.${N}"
    print "  ${B}${Y}FILE SEARCH (zpwr filesearch / Ctrl-F Ctrl-D)${N}"
    print "  ${D}Pattern: find files | fzf --preview 'bat' | open in editor${N}"
    print "  ${D}  1. find/fd generates a file list (respecting .gitignore)${N}"
    print "  ${D}  2. fzf shows files with bat-powered syntax-highlighted preview${N}"
    print "  ${D}  3. Selected file opens in \$EDITOR at the matched location${N}"
    print "  ${D}FZF_CTRL_T_OPTS configures the preview command.${N}"
    print "  ${B}${Y}WORD SEARCH (zpwr wordsearch / Ctrl-F Ctrl-I)${N}"
    print "  ${D}Pattern: ag/rg search | fzf --preview 'context' | open at line${N}"
    print "  ${D}  1. ag (silver searcher) or rg searches file contents${N}"
    print "  ${D}  2. fzf shows matches with file:line:content format${N}"
    print "  ${D}  3. Selection opens the file at the exact line number${N}"
    print "  ${D}FZF_AG_OPTS: delimiter ':', match on 3rd+ field (skip file:line).${N}"
    print "  ${B}${Y}GIT ADD (forgitadd)${N}"
    print "  ${D}Pattern: git diff --stat | fzf --preview 'git diff' | git add${N}"
    print "  ${D}  1. Lists modified files with diff stats${N}"
    print "  ${D}  2. Preview pane shows the actual diff for each file${N}"
    print "  ${D}  3. Toggle files with Tab, confirm to stage them${N}"
    print "  ${D}  Part of forgit: the git + fzf integration plugin.${N}"
    print "  ${B}${Y}VERB SEARCH (zpwr verbsfzf)${N}"
    print "  ${D}Pattern: ZPWR_VERBS keys | fzf --preview 'help' | eval${N}"
    print "  ${D}  1. All ${#ZPWR_VERBS}+ zpwr verbs piped into fzf${N}"
    print "  ${D}  2. Preview shows the verb description and command${N}"
    print "  ${D}  3. Select a verb to execute it immediately${N}"
    print "  ${D}  FZF_ENV_OPTS_VERBS configures the preview for verbs.${N}"
    print "  ${B}${Y}CUSTOM FZF KEY BINDINGS${N}"
    print "  ${D}The Ctrl-F prefix opens ZPWR's fzf keymap layer:${N}"
    print "  ${M}  Ctrl-F Ctrl-D${N}${D}   File search (find + fzf + editor)${N}"
    print "  ${M}  Ctrl-F Ctrl-I${N}${D}   Word search (ag + fzf + editor)${N}"
    print "  ${M}  Ctrl-F Ctrl-G${N}${D}   Git search (git log + fzf)${N}"
    print "  ${M}  Ctrl-F Ctrl-R${N}${D}   History search with fzf${N}"
    print "  ${D}These are ZLE widgets bound via zpwrBindOverrideZLE.${N}"
    print "  ${B}${Y}zpwrIntoFzf AND zpwrIntoFzfAg${N}"
    print "  ${D}Two core ZLE widgets that bridge the command line with fzf:${N}"
    print "  ${G}  zpwrIntoFzf${N}${D}     File-oriented fzf (Ctrl-T style)${N}"
    print "  ${G}  zpwrIntoFzfAg${N}${D}   Content-oriented fzf (ag/grep style)${N}"
    print "  ${D}Both capture fzf output and insert it into the command line${N}"
    print "  ${D}buffer (\$BUFFER). You select files/matches, they appear${N}"
    print "  ${D}at your cursor. Seamless integration between search and input.${N}"
    print "  ${B}${Y}THE COLORIZER CHAIN${N}"
    print "  ${D}ZPWR_COLORIZER preference: bat > pygmentize.${N}"
    print "  ${D}bat uses themes (BAT_THEME=\$ZPWR_BAT_THEME).${N}"
    print "  ${D}pygmentize uses PYGMENTIZE_COLOR style.${N}"
    print "  ${D}Language-specific colorizers: FZF_COLORIZER_C, _SH, _YAML, _JAVA.${N}"
}
