PAGE_TITLE="temprs: Advanced Operations"
PAGE_CHAPTER="CHAPTER 32: TEMPRS — TEMPORARY FILE STACK MANAGER"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== TEMPRS: ADVANCED OPERATIONS ===${N}"
    print "  ${D}// the stack goes deeper. every tempfile has a story. //${N}"
    print "  ${B}${Y}LISTING & INSPECTION${N}"
    print "  ${G}  temprs -l${N}${D}           # list all tempfile paths on the stack${N}"
    print "  ${G}  temprs -n${N}${D}           # list numbered (index + path)${N}"
    print "  ${G}  temprs -L${N}${D}           # list all tempfile contents${N}"
    print "  ${G}  temprs -N${N}${D}           # list numbered with full contents${N}"
    print "  ${G}  temprs -k${N}${D}           # count tempfiles on the stack${N}"
    print "  ${G}  temprs -I INDEX${N}${D}     # show metadata for tempfile at INDEX${N}"
    print "  ${B}${Y}EDITING & TAGGING${N}"
    print "  ${G}  temprs -e INDEX${N}${D}     # open tempfile at INDEX in \$EDITOR${N}"
    print "  ${G}  temprs -w NAME${N}${D}      # tag a tempfile with an alias name${N}"
    print "  ${G}  temprs -R OLD NEW${N}${D}   # rename tag from OLD to NEW${N}"
    print "  ${D}Tags let you retrieve tempfiles by name instead of index.${N}"
    print "  ${D}Your stack positions shift; your tags don't.${N}"
    print "  ${B}${Y}SEARCH & CONCATENATE${N}"
    print "  ${G}  temprs -g PATTERN${N}${D}   # grep through all tempfile contents${N}"
    print "  ${G}  temprs -C 0 2 5${N}${D}    # concatenate tempfiles at indices to stdout${N}"
    print "  ${D}The grep flag searches across every tempfile on the stack —${N}"
    print "  ${D}like a personal knowledge base with instant full-text search.${N}"
    print "  ${B}${Y}STACK MANIPULATION${N}"
    print "  ${G}  temprs -D 0 1${N}${D}      # diff two tempfiles by index or name${N}"
    print "  ${G}  temprs -M 0 3${N}${D}      # move tempfile from position 0 to 3${N}"
    print "  ${G}  temprs -x INDEX${N}${D}     # duplicate tempfile onto top of stack${N}"
    print "  ${G}  temprs -S 0 2${N}${D}      # swap two tempfiles by index or name${N}"
    print "  ${G}  temprs --rev${N}${D}        # reverse the entire stack order${N}"
    print "  ${G}  temprs -A INDEX${N}${D}     # append stdin to existing tempfile${N}"
    print "  ${B}${Y}HOUSEKEEPING${N}"
    print "  ${G}  temprs -c${N}${D}           # clear/purge ALL tempfiles from stack${N}"
    print "  ${G}  temprs --expire 24${N}${D}  # purge tempfiles older than 24 hours${N}"
    print "  ${G}  temprs --wc INDEX${N}${D}   # print line count of tempfile${N}"
    print "  ${G}  temprs --size INDEX${N}${D} # print byte size of tempfile${N}"
    print "  ${G}  temprs --path INDEX${N}${D} # print the actual filesystem path${N}"
    print "  ${G}  temprs --sort mtime${N}${D} # sort stack by name, size, or mtime${N}"
    print "  ${B}${Y}MODE FLAGS${N}"
    print "  ${G}  temprs -q${N}${D}           # quiet mode: suppress output on create${N}"
    print "  ${G}  temprs -v${N}${D}           # verbose mode: extra diagnostic output${N}"
    print "  ${B}${Y}THE CYBERPUNK -h${N}"
    print "  ${D}Run ${G}temprs -h${D} for the full ASCII art banner with the${N}"
    print "  ${D}TEMPRS logo, status bar, and signal meter. Because even${N}"
    print "  ${D}help text should look like a console from a Gibson novel.${N}"
    print "  ${D}Also: ${G}--head INDEX N${D} and ${G}--tail INDEX N${D} for partial reads,${N}"
    print "  ${D}and ${G}--replace INDEX PAT REPL${D} for in-place sed-style edits.${N}"
}
