PAGE_TITLE="FZF: The Neural Interface"
PAGE_CHAPTER="CHAPTER 29: FZF ARCHITECTURE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== FZF: THE NEURAL INTERFACE ===${N}"
    print "  ${D}// the universal adapter between data and decisions. //${N}"
    print "  ${C}fzf (fuzzy finder) is a general-purpose command-line filter.${N}"
    print "  ${C}Pipe anything into it, fuzzy-search interactively, get results.${N}"
    print "  ${C}ZPWR wraps fzf into dozens of workflows: files, words, git, verbs.${N}"
    print "  ${B}${Y}THE PATTERN: PIPE | FZF | ACTION${N}"
    print "  ${D}Every fzf integration follows the same architecture:${N}"
    print "  ${M}  <data source> | fzf [options] | <action on selection>${N}"
    print "  ${D}The data source generates lines. fzf presents them. The action${N}"
    print "  ${D}consumes the selected line(s). Simple. Composable. Powerful.${N}"
    print "  ${B}${Y}FZF_DEFAULT_OPTS${N}"
    print "  ${D}ZPWR sets global fzf defaults in zpwrBindFZFLate:${N}"
    print "  ${M}  FZF_DEFAULT_OPTS=\"\$ZPWR_COMMON_FZF_ELEM --reverse --border --height 100%\"${N}"
    print "  ${D}Plus a Solarized Dark color scheme layered on top:${N}"
    print "  ${M}  --color fg:-1,bg:-1,hl:\$blue,fg+:\$base2,bg+:\$base02,hl+:\$blue${N}"
    print "  ${D}ZPWR_COMMON_FZF_ELEM adds the logo prompt and navigation binds:${N}"
    print "  ${M}  --prompt='\$ZPWR_FZF_LOGO ' --bind=ctrl-n:page-down,...${N}"
    print "  ${B}${Y}THE PREVIEW WINDOW${N}"
    print "  ${D}fzf's --preview flag runs a command for each highlighted item:${N}"
    print "  ${M}  fzf --preview 'bat --color=always {}'${N}"
    print "  ${D}ZPWR configures rich previews per context:${N}"
    print "  ${D}  Files:   bat with syntax highlighting, line numbers, grid${N}"
    print "  ${D}  Dirs:    stat output${N}"
    print "  ${D}  Packages: dpkg -I or rpm -qi${N}"
    print "  ${D}  Git:     diff preview, commit log${N}"
    print "  ${D}If bat is installed, it's the default colorizer. Falls back${N}"
    print "  ${D}to pygmentize with terminal256 output.${N}"
    print "  ${B}${Y}fzf-completion (Tab)${N}"
    print "  ${D}fzf replaces the default Tab completion with a fuzzy finder.${N}"
    print "  ${D}Type a command, press Tab, and fzf opens with completions:${N}"
    print "  ${M}  cd **<Tab>${N}${D}     fzf through subdirectories${N}"
    print "  ${M}  kill <Tab>${N}${D}      fzf through running processes${N}"
    print "  ${M}  ssh **<Tab>${N}${D}     fzf through known hosts${N}"
    print "  ${D}FZF_COMPLETION_OPTS controls the preview for these.${N}"
    print "  ${B}${Y}fzf-tab PLUGIN${N}"
    print "  ${D}MenkeTechnologies/fzf-tab replaces zsh's menu completion with fzf.${N}"
    print "  ${D}Any time the completion system would show a menu, fzf-tab${N}"
    print "  ${D}intercepts it and shows fzf instead. This means:${N}"
    print "  ${D}  - Fuzzy matching for ${G}every${D} completion, not just ** triggers${N}"
    print "  ${D}  - Previews for file completions, git branches, everything${N}"
    print "  ${D}  - FZF_TAB_OPTS configures the behavior (ansi, nth, delimiter)${N}"
    print "  ${D}  - FZF_TAB_COMMAND sets which fzf binary to use${N}"
    print "  ${B}${Y}GLOBAL ALIASES FOR FZF${N}"
    print "  ${M}  \${ZPWR_GLOBAL_ALIAS_PREFIX}z${N}${D}   Pipe into fzf: ${M}ls | ,,z${N}"
    print "  ${M}  \${ZPWR_GLOBAL_ALIAS_PREFIX}zb${N}${D}  Inline fzf selection: ${M}vim ,,zb${N}"
}
