PAGE_TITLE="Config Sessions"
PAGE_CHAPTER="CHAPTER 18: INSTALLATION & RESET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> CONFIG SESSIONS: EDIT EVERYTHING FROM HERE <<<${N}"
    print "  ${D}one verb to open any config, no path memorization${N}"
    print ""
    print "  ${G}ZPWR provides shortcut verbs for every config file${N}"
    print "  ${G}you'll ever need to edit. No more 'vim ~/.zshrc'.${N}"
    print ""
    print "  ${B}${Y}zpwr brc${N}  ${D}-- Bash RC${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit your .bashrc. For when bash compatibility matters.${N}"
    print ""
    print "  ${C}  \$ zpwr brc${N}                    ${D}# edit .bashrc${N}"
    print ""
    print "  ${B}${Y}zpwr zrc${N}  ${D}-- Zsh RC${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit your .zshrc. The most-touched config in ZPWR.${N}"
    print ""
    print "  ${C}  \$ zpwr zrc${N}                    ${D}# edit .zshrc${N}"
    print ""
    print "  ${B}${Y}zpwr vrc${N}  ${D}-- Vim RC${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit your .vimrc or init.vim/init.lua.${N}"
    print ""
    print "  ${C}  \$ zpwr vrc${N}                    ${D}# edit vim config${N}"
    print ""
    print "  ${B}${Y}zpwr trc${N}  ${D}-- Tmux RC${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit your .tmux.conf. Keybindings, statusbar, the works.${N}"
    print ""
    print "  ${C}  \$ zpwr trc${N}                    ${D}# edit tmux config${N}"
    print ""
    print "  ${B}${Y}zpwr tokens${N}  ${D}-- Secrets File${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit \$ZPWR_LOCAL/.tokens.sh. API keys, secrets, env vars.${N}"
    print ""
    print "  ${C}  \$ zpwr tokens${N}                 ${D}# edit tokens/secrets${N}"
    print "  ${C}  \$ zpwr vimtokens${N}              ${D}# same, force vim${N}"
    print "  ${C}  \$ zpwr emacstokens${N}            ${D}# same, force emacs${N}"
    print ""
    print "  ${B}${Y}zpwr zcompdump${N}  ${D}-- Completion Cache${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Inspect or regenerate the zsh completion dump file.${N}"
    print "  ${G}When completions act weird, this is where you look.${N}"
    print ""
    print "  ${C}  \$ zpwr zcompdump${N}              ${D}# inspect comp cache${N}"
    print ""
    print "  ${D}  // brc, zrc, vrc, trc -- four letters, four configs${N}"
    print "  ${D}  // tokens for secrets, zcompdump for completion fixes${N}"
}
