PAGE_TITLE="Listing Everything"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> LISTING EVERYTHING: THE INVENTORY MANIFEST <<<${N}"
    print "  ${D}counting is nice, but names are power${N}"
    print ""
    print "  ${G}Counts tell you how many. Lists tell you WHAT.${N}"
    print "  ${G}Every count verb has a list counterpart.${N}"
    print ""
    print "  ${B}${Y}zpwr autoloadlist${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}List every autoloaded function by name.${N}"
    print ""
    print "  ${C}  \$ zpwr autoloadlist${N}            ${D}# all function names${N}"
    print "  ${C}  \$ zpwr autoloadlist | grep fzf${N} ${D}# find fzf funcs${N}"
    print ""
    print "  ${B}${Y}zpwr scriptlist${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}List every script in the scripts directory.${N}"
    print ""
    print "  ${C}  \$ zpwr scriptlist${N}              ${D}# all scripts${N}"
    print ""
    print "  ${B}${Y}zpwr zshpluginlist${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}List installed zsh plugins with their sources.${N}"
    print ""
    print "  ${C}  \$ zpwr zshpluginlist${N}           ${D}# all zsh plugins${N}"
    print ""
    print "  ${B}${Y}zpwr vimpluginlist${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}List installed vim/neovim plugins.${N}"
    print ""
    print "  ${C}  \$ zpwr vimpluginlist${N}           ${D}# all vim plugins${N}"
    print ""
    print "  ${B}${Y}zpwr emacspluginlist${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}List installed emacs packages.${N}"
    print ""
    print "  ${C}  \$ zpwr emacspluginlist${N}         ${D}# all emacs packages${N}"
    print ""
    print "  ${B}${Y}POWER COMBOS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr autoloadlist | wc -l${N}    ${D}# quick count${N}"
    print "  ${C}  \$ zpwr autoloadlist | fzf${N}      ${D}# fuzzy browse${N}"
    print "  ${C}  \$ zpwr scriptlist | sort${N}       ${D}# alphabetical${N}"
    print ""
    print "  ${D}  // lists are grep-able, fzf-able, pipe-able${N}"
    print "  ${D}  // the raw material for your own exploration${N}"
    print "  ${D}  // pipe into fzf for interactive discovery${N}"
}
