PAGE_TITLE="Know Your Shell"
PAGE_CHAPTER="CHAPTER 8: ENVIRONMENT MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== KNOW YOUR SHELL ===${N}"
    print "  ${D}// you cannot master what you cannot measure //${N}"
    print ""
    print "  ${C}Three verbs to audit your environment. Each one reveals a${N}"
    print "  ${C}different cross-section of the machine you live inside.${N}"
    print ""
    print "  ${B}${Y}ENVVARS: THE ZPWR VARIABLES${N}"
    print "  ${M}  zpwr envvars${N}${D}                        # list all ZPWR_* env vars${N}"
    print "  ${M}  zpwr ev${N}${D}                              # same thing, shorter${N}"
    print ""
    print "  ${D}  Shows every environment variable starting with ZPWR_.${N}"
    print "  ${D}  These are the knobs and dials of the framework:${N}"
    print "  ${D}  paths, flags, plugin manager config, colorscheme, etc.${N}"
    print "  ${D}  If something is misconfigured, this is where you look.${N}"
    print ""
    print "  ${B}${Y}ENVVARSALL: THE FULL PICTURE${N}"
    print "  ${M}  zpwr envvarsall${N}${D}                     # every env var, all of them${N}"
    print "  ${M}  zpwr eva${N}${D}                             # same thing, shorter${N}"
    print ""
    print "  ${D}  Dumps every exported variable. This includes ZPWR_*,${N}"
    print "  ${D}  PATH, HOME, EDITOR, LANG, and everything else.${N}"
    print "  ${D}  Pipe it to fzf when you are hunting for a specific var:${N}"
    print "  ${M}  zpwr eva | fzf${N}"
    print ""
    print "  ${B}${Y}ENVIRONMENTCOUNTS: THE NUMBERS GAME${N}"
    print "  ${M}  zpwr environmentcounts${N}${D}              # full environment statistics${N}"
    print "  ${M}  zpwr envcounts${N}${D}                      # alias${N}"
    print "  ${M}  zpwr e${N}${D}                               # shortest form${N}"
    print ""
    print "  ${D}  This is the census. It counts everything loaded in your${N}"
    print "  ${D}  current shell session:${N}"
    print ""
    print "  ${G}  aliases${N}${D}         regular + global + suffix aliases${N}"
    print "  ${G}  functions${N}${D}       autoloaded + defined functions${N}"
    print "  ${G}  builtins${N}${D}        zsh builtin commands${N}"
    print "  ${G}  parameters${N}${D}      shell variables (scalar, array, assoc)${N}"
    print "  ${G}  completions${N}${D}     registered completion functions${N}"
    print "  ${G}  modules${N}${D}         loaded zsh modules${N}"
    print "  ${G}  named dirs${N}${D}      hash -d entries${N}"
    print "  ${G}  PATH entries${N}${D}    directories in PATH${N}"
    print "  ${G}  FPATH entries${N}${D}   directories in FPATH${N}"
    print ""
    print "  ${D}  The numbers tell you how armed you are.${N}"
    print "  ${D}  A fresh zpwr install might show 3000+ aliases,${N}"
    print "  ${D}  500+ functions, and 100+ completions.${N}"
    print "  ${D}  If the numbers are low, something failed to load.${N}"
    print ""
    print "  ${B}${Y}PRO TIP: PAIR THEM${N}"
    print "  ${M}  zpwr doctor${N}${D}                   # is anything broken?${N}"
    print "  ${M}  zpwr e${N}${D}                         # how much loaded?${N}"
    print "  ${M}  zpwr ev${N}${D}                        # are my zpwr vars right?${N}"
    print "  ${D}  Run all three after installing or updating zpwr.${N}"
    print "  ${D}  They are your post-deployment smoke test.${N}"
    print ""
}
