PAGE_TITLE="Dependency Cartography"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== DEPENDENCY CARTOGRAPHY ===${N}"
    print "  ${D}// mapping the call graph. who calls whom. who dies alone. //${N}"
    print ""
    print "  ${C}zpwr has hundreds of functions. They call each other in a${N}"
    print "  ${C}tangled web of dependencies. The ${M}deps${C} verb maps that web.${N}"
    print "  ${C}Think of it as Google Maps for your function call graph.${N}"
    print ""
    print "  ${B}${Y}BASIC USAGE${N}"
    print "  ${M}  zpwr deps${N}${D}                          # summary overview${N}"
    print "  ${M}  zpwr deps zpwrClearList${N}${D}             # what does zpwrClearList call?${N}"
    print "  ${M}  zpwr deps -h${N}${D}                        # full help${N}"
    print ""
    print "  ${B}${Y}THE FLAGS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}-r, --reverse${N}${D}    Who calls this function? (reverse lookup)${N}"
    print "  ${C}-o, --orphans${N}${D}    Functions called by nobody internally${N}"
    print "  ${C}-s, --summary${N}${D}    Overview stats (default when no args)${N}"
    print "  ${C}-d, --dot${N}${D}        Output dot format for graphviz rendering${N}"
    print ""
    print "  ${B}${Y}FORWARD LOOKUP: WHAT DOES X CALL?${N}"
    print "  ${M}  zpwr deps zpwrDoctor${N}"
    print "  ${D}  Shows every function zpwrDoctor calls, plus depth-2 callees.${N}"
    print "  ${D}  Output:  zpwrDoctor -> zpwrPrettyPrint -> [zpwrLogDebug, ...]${N}"
    print ""
    print "  ${B}${Y}REVERSE LOOKUP: WHO CALLS X?${N}"
    print "  ${M}  zpwr deps -r zpwrPrettyPrint${N}"
    print "  ${D}  Answers: \"Who depends on zpwrPrettyPrint?\"${N}"
    print "  ${D}  If the answer is 30 functions, that function is load-bearing.${N}"
    print "  ${D}  Touch it carefully.${N}"
    print ""
    print "  ${B}${Y}ORPHAN DETECTION${N}"
    print "  ${M}  zpwr deps --orphans${N}"
    print "  ${D}  Lists functions that no other zpwr function calls.${N}"
    print "  ${D}  These are either entry points (user-invoked) or dead code.${N}"
    print "  ${D}  Orphans are not necessarily bad -- many are top-level verbs${N}"
    print "  ${D}  or zinit hooks. But if you wrote zpwrFoo and nobody calls it,${N}"
    print "  ${D}  maybe zpwrFoo was a fever dream.${N}"
    print ""
    print "  ${B}${Y}GRAPHVIZ EXPORT${N}"
    print "  ${M}  zpwr deps --dot > graph.dot${N}"
    print "  ${M}  dot -Tsvg graph.dot -o graph.svg${N}"
    print "  ${D}  Produces a visual dependency graph. Nodes are functions,${N}"
    print "  ${D}  edges are call relationships. The dot output uses cyberpunk${N}"
    print "  ${D}  colors: dark background, cyan nodes, magenta edges.${N}"
    print "  ${D}  Open graph.svg in a browser and behold the nervous system.${N}"
    print ""
    print "  ${B}${Y}THE SUMMARY VIEW${N}"
    print "  ${D}  With no args, deps shows two ranked lists:${N}"
    print "  ${G}  TOP 10 MOST DEPENDENCIES${N}${D} (functions that call the most others)${N}"
    print "  ${G}  TOP 10 MOST DEPENDED ON${N}${D}  (functions called by the most others)${N}"
    print "  ${D}  Plus stats: total functions, orphan count, total call edges.${N}"
    print "  ${D}  The bar charts use Unicode block characters. Very aesthetic.${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${D}  Scans autoload dirs: common, darwin, linux, comp_utils.${N}"
    print "  ${D}  Reads each function body and string-matches against all${N}"
    print "  ${D}  other function names. Also scans \$ZPWR_SCRIPTS/lib.sh.${N}"
    print "  ${D}  It is O(n^2) and proud of it. Your function count is not${N}"
    print "  ${D}  big enough to matter.${N}"
    print ""
}
