PAGE_TITLE="Debug Mode"
PAGE_CHAPTER="CHAPTER 16: THE LOGGING SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> DEBUG MODE: WHEN THINGS GO SIDEWAYS <<<${N}"
    print "  ${D}enabling verbose output is how you stop guessing${N}"
    print ""
    print "  ${B}${Y}ZPWR_DEBUG${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Set this env var to enable debug-level logging.${N}"
    print "  ${G}More detail in the log, more signal for your hunt.${N}"
    print ""
    print "  ${C}  \$ export ZPWR_DEBUG=true${N}       ${D}# enable debug${N}"
    print "  ${C}  \$ zpwr reload${N}                  ${D}# reload with debug${N}"
    print "  ${C}  \$ zpwr taillog${N}                 ${D}# watch debug output${N}"
    print ""
    print "  ${B}${Y}ZPWR_TRACE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Maximum verbosity. Every function entry and exit,${N}"
    print "  ${G}every variable, every decision point.${N}"
    print ""
    print "  ${C}  \$ export ZPWR_TRACE=true${N}       ${D}# enable trace${N}"
    print "  ${C}  \$ zpwr reload${N}                  ${D}# reload with trace${N}"
    print ""
    print "  ${R}  WARNING: Trace mode generates MASSIVE log output.${N}"
    print "  ${R}  Your logfile will grow fast. Use sparingly.${N}"
    print ""
    print "  ${B}${Y}DEBUGGING WORKFLOW:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. Reproduce the problem once to confirm it${N}"
    print "  ${D}  2. \$ export ZPWR_DEBUG=true${N}"
    print "  ${D}  3. \$ zpwr reload${N}"
    print "  ${D}  4. Reproduce the problem again${N}"
    print "  ${D}  5. \$ zpwr taillog              # find the smoking gun${N}"
    print "  ${D}  6. Still lost? Escalate:${N}"
    print "  ${D}  7. \$ export ZPWR_TRACE=true${N}"
    print "  ${D}  8. \$ zpwr reload && reproduce${N}"
    print ""
    print "  ${B}${Y}DISABLING DEBUG:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ unset ZPWR_DEBUG ZPWR_TRACE${N}  ${D}# back to normal${N}"
    print "  ${C}  \$ zpwr reload${N}                  ${D}# reload clean${N}"
    print ""
    print "  ${D}  // debug mode: \"trust but verify\" in action${N}"
    print "  ${D}  // trace mode: \"verify everything, trust nothing\"${N}"
    print "  ${D}  // always disable after debugging or your log eats disk${N}"
}
