PAGE_TITLE="Ice Modifiers Deep Dive"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== ICE MODIFIERS DEEP DIVE ===${N}"
    print "  ${D}// ice modifiers are the spice of zinit. season generously. //${N}"
    print "  ${C}Every zinit load/snippet can be preceded by 'zinit ice'${N}"
    print "  ${C}with modifiers that control HOW the plugin loads.${N}"
    print "  ${C}Ice melts after one use -- it applies only to the next command.${N}"
    print "  ${B}${Y}CORE ICE MODIFIERS USED BY ZPWR${N}"
    print "  ${G}  lucid${N}${D}          Suppress the 'Loaded plugin' message${N}"
    print "  ${D}                  ZPWR uses this on every plugin. No spam.${N}"
    print "  ${G}  nocompile${N}${D}      Skip .zwc compilation of the plugin${N}"
    print "  ${D}                  Useful when zpwrRecompileFiles handles it globally.${N}"
    print "  ${G}  nocd${N}${D}           Don't cd to plugin dir before sourcing${N}"
    print "  ${D}                  Prevents p10k internals from polluting named dirs.${N}"
    print "  ${G}  nocompletions${N}${D}  Don't install completions from this plugin${N}"
    print "  ${D}                  Used for zsh-more-completions (fpath-only approach).${N}"
    print "  ${G}  as'completion'${N}${D} Load the file as a completion, not a plugin${N}"
    print "  ${D}                  Used for OMZ completion snippets like _ng, _coffee.${N}"
    print "  ${G}  as'program'${N}${D}    Add the pick'd file to \$PATH as executable${N}"
    print "  ${D}                  Used for fzf binary and git-fuzzy.${N}"
    print "  ${G}  as'null'${N}${D}       Don't source anything -- just run hooks${N}"
    print "  ${D}                  Used for the compinit phase (atinit only).${N}"
    print "  ${G}  pick'null'${N}${D}     Don't source any file from the plugin dir${N}"
    print "  ${D}                  Used with as'completion' for OMZ comp snippets.${N}"
    print "  ${G}  pick'bin/fzf'${N}${D}  Source or add this specific file${N}"
    print "  ${D}                  With as'program', adds bin/fzf to PATH.${N}"
    print "  ${B}${Y}HOOK ICE MODIFIERS${N}"
    print "  ${G}  atinit${N}${D}         Code to run BEFORE the plugin sources${N}"
    print "  ${G}  atload${N}${D}         Code to run AFTER the plugin sources${N}"
    print "  ${D}Example from ZPWR:${N}"
    print "  ${M}  zinit ice lucid nocompile wait atinit='zpwrBindOverrideOMZ;zpwrBindForGit'${N}"
    print "  ${M}  zinit load MenkeTechnologies/forgit${N}"
    print "  ${D}Before forgit loads, zpwrBindOverrideOMZ runs to clear OMZ${N}"
    print "  ${D}aliases that would conflict with forgit's git shortcuts.${N}"
    print "  ${B}${Y}HOW ZPWR USES ICE BY CATEGORY${N}"
    print "  ${D}OMZ completions: ${M}lucid nocompile as'completion' pick'null' wait${N}"
    print "  ${D}OMZ libs:        ${M}lucid nocompile wait atload='zpwrOmzOverrides'${N}"
    print "  ${D}OMZ plugins:     ${M}lucid nocompile wait${N}"
    print "  ${D}GH plugins:      ${M}lucid nocompile wait${N}"
    print "  ${D}Programs:        ${M}as'program' lucid nocompile pick'bin/fzf' wait${N}"
    print "  ${D}Syntax highlight:${M}lucid nocompile wait\"\${ZPWR_ZINIT_COMPINIT_DELAY}h\"${N}"
    print "  ${B}${Y}ICE STACKING${N}"
    print "  ${D}Multiple ices combine. Order doesn't matter (mostly).${N}"
    print "  ${D}The = syntax for atload/atinit works with single quotes:${N}"
    print "  ${M}  atload='zpwrBindAliasesLate; zpwrCreateAliasCache'${N}"
    print "  ${D}Or with quoted strings:${N}"
    print "  ${M}  atinit'zpwrBindZdharma' atload'zpwrBindZdharmaPost'${N}"
}
