PAGE_TITLE="File & Text Utilities"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FILE & TEXT UTILITIES ===${N}"
    print "  ${D}// 31 verbs for file wrangling //${N}"
    print ""
    print "  ${C}Cat, list, grep, search, rename, and transform files.${N}"
    print "  ${C}The everyday toolkit for text manipulation.${N}"
    print ""
    print "  ${B}${Y}VIEW & LIST${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cat${N}${D}                   # zpwr cat args${N}"
    print "  ${M}  zpwr c${N}${D}                     # zpwr cat args${N}"
    print "  ${M}  zpwr ls${N}${D}                    # list the files with no args${N}"
    print "  ${M}  zpwr list${N}${D}                  # list the files with no args${N}"
    print "  ${M}  zpwr clearlist${N}${D}             # clear and list the files${N}"
    print "  ${M}  zpwr clearls${N}${D}               # clear and list the files${N}"
    print "  ${M}  zpwr info${N}${D}                  # get info on command type with args${N}"
    print ""
    print "  ${B}${Y}SEARCH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr grep${N}${D}                  # grep through pwd with ag into fzf${N}"
    print "  ${M}  zpwr search${N}${D}                # recursive grep search with context${N}"
    print "  ${M}  zpwr filesearch${N}${D}            # cat a file in a sub dir via fzf${N}"
    print "  ${M}  zpwr filesearchedit${N}${D}        # edit a file in a sub dir via fzf${N}"
    print "  ${M}  zpwr wordsearch${N}${D}            # cat a file by word via fzf${N}"
    print "  ${M}  zpwr wordsearchedit${N}${D}        # edit a file by word via fzf${N}"
    print "  ${M}  zpwr findsearch${N}${D}            # cat find drive for file via fzf${N}"
    print "  ${M}  zpwr findsearchedit${N}${D}        # edit find drive for file via fzf${N}"
    print "  ${M}  zpwr locatesearch${N}${D}          # accept locate drive for file${N}"
    print "  ${M}  zpwr locatesearchedit${N}${D}      # edit locate drive for file${N}"
    print "  ${M}  zpwr linecount${N}${D}             # get line count of search term${N}"
    print "  ${M}  zpwr cfasd${N}${D}                 # cat the fasd frecency ranked file${N}"
    print ""
    print "  ${B}${Y}TRANSFORM & MANAGE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr replacer${N}${D}              # find and replace text in files${N}"
    print "  ${M}  zpwr rename${N}${D}                # rename files${N}"
    print "  ${M}  zpwr man${N}${D}                   # fzf through man pages${N}"
    print "  ${M}  zpwr open${N}${D}                  # open with system${N}"
    print "  ${M}  zpwr opencommand${N}${D}           # get the command to open with system${N}"
    print ""
    print "  ${B}${Y}CONVERT & UPLOAD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr scripttopdf${N}${D}           # convert script to PDF${N}"
    print "  ${M}  zpwr creategif${N}${D}             # create GIF from file with ffmpeg${N}"
    print "  ${M}  zpwr upload${N}${D}                # upload with curl${N}"
    print "  ${M}  zpwr urlsafe${N}${D}               # base64 encode${N}"
    print "  ${M}  zpwr execglob${N}${D}              # exec on globbed files${N}"
    print "  ${M}  zpwr execglobparallel${N}${D}      # parallel exec on globbed files${N}"
    print ""
}
