PAGE_TITLE="Colorful Manuals & Package Completions"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== COLORFUL MANUALS & PACKAGE COMPLETIONS ===${N}"
    print "  ${D}the smaller plugins that make everything nicer${N}"
    print ""
    print "  ${B}${Y}zsh-very-colorful-manuals${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Custom colorscheme for man pages. Headers in bold cyan,${N}"
    print "  ${G}underlines in magenta, flags in green. Makes man pages${N}"
    print "  ${G}actually readable instead of a wall of white text.${N}"
    print "  ${D}Works automatically — no commands needed.${N}"
    print ""
    print "  ${B}${Y}zsh-gem-completion${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Enhanced Ruby gem completion. Includes all OMZ gem${N}"
    print "  ${G}completion plus remote gem search:${N}"
    print "  ${M}  gem install <tab>${N}${D}         # completes remote gems${N}"
    print "  ${D}  Results come from ${M}gem search${D} output.${N}"
    print ""
    print "  ${B}${Y}zsh-pip-description-completion${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Enhanced pip completion. All OMZ pip completion plus${N}"
    print "  ${G}remote package search:${N}"
    print "  ${M}  pip install <tab>${N}${D}         # completes remote packages${N}"
    print "  ${D}  Results come from ${M}pip search${D} output with descriptions.${N}"
    print ""
    print "  ${B}${Y}zsh-better-npm-completion${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Better npm completion. Context-aware:${N}"
    print "  ${M}  npm install <tab>${N}${D}         # completes package names${N}"
    print "  ${M}  npm run <tab>${N}${D}             # completes scripts from package.json${N}"
    print "  ${M}  npm uninstall <tab>${N}${D}       # completes installed packages${N}"
    print "  ${D}  Each subcommand gets the right completions.${N}"
    print ""
    print "  ${D}All plugins: ${C}MenkeTechnologies/*${N}"
    print ""
}
