PAGE_TITLE="Live Dashboard & Sparklines"
PAGE_CHAPTER="CHAPTER 11: MONITORING & AUTOMATION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== LIVE DASHBOARD & SPARKLINES ===${N}"
    print "  ${D}your shell's vital signs, in real time${N}"
    print ""
    print "  ${B}${Y}zpwr top${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}A live-updating dashboard of your shell's resource usage.${N}"
    print "  ${G}Runs in alternate screen buffer. Press q to quit.${N}"
    print ""
    print "  ${M}  zpwr top${N}${D}       # refresh every 2s${N}"
    print "  ${M}  zpwr top 1${N}${D}     # fast refresh${N}"
    print "  ${M}  zpwr top 5${N}${D}     # slow refresh${N}"
    print "  ${M}  zpwr dashboard${N}${D} # same verb${N}"
    print "  ${M}  zpwr live${N}${D}      # same verb${N}"
    print ""
    print "  ${B}${Y}WHAT IT SHOWS${N}"
    print "  ${G}  Memory${N}${D} ............ RSS bar graph, virtual memory${N}"
    print "  ${G}  Shell objects${N}${D} ..... functions, aliases, completions, params${N}"
    print "  ${G}  Delta tracking${N}${D} .... changes between refreshes in yellow${N}"
    print "  ${G}  Loaded modules${N}${D} .... all zsh modules currently loaded${N}"
    print "  ${G}  Paths${N}${D} ............ fpath, path, named dirs, dir stack${N}"
    print "  ${G}  Context${N}${D} .......... git branch, tmux info, startup time${N}"
    print "  ${G}  Top 5 functions${N}${D} .. largest functions with size bars${N}"
    print "  ${G}  Top 5 paths${N}${D} ...... longest PATH entries${N}"
    print ""
    print "  ${B}${Y}SPARKLINES${N}"
    print "  ${C}  Startup time history: last 40 shell starts${N}"
    print "  ${D}  Color-coded: ${G}green${D}=fast ${Y}yellow${D}=mid ${R}red${D}=slow${N}"
    print "  ${D}  Shows min/max/avg stats below the graph.${N}"
    print ""
    print "  ${C}  Commit velocity: commits per day over 30 days${N}"
    print "  ${D}  Visualizes your development pace as a mini bar chart.${N}"
    print ""
    print "  ${D}Startup times are logged automatically on each shell init${N}"
    print "  ${D}to \$ZPWR_LOCAL/startup_history.log.${N}"
    print ""
}
