PAGE_TITLE="The Nuclear Options"
PAGE_CHAPTER="CHAPTER 9: THE JANITOR'S CLOSET"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE NUCLEAR OPTIONS ===${N}"
    print "  ${D}// when gentle cleanup is not enough. when you need to nuke from orbit. //${N}"
    print ""
    print "  ${C}Most clean verbs are surgical. These two are orbital strikes.${N}"
    print "  ${C}They clean, regenerate, rebuild, and update in one shot.${N}"
    print "  ${C}Use them when you want a fresh start without reinstalling.${N}"
    print ""
    print "  ${B}${Y}CLEANREFRESHUPDATE: THE BIG RED BUTTON${N}"
    print "  ${M}  zpwr cleanrefreshupdate${N}${D}             # clean + regen + update${N}"
    print ""
    print "  ${D}  This is the full-cycle maintenance verb. It:${N}"
    print "  ${G}  1.${N}${D} Cleans all caches (equivalent to cleanall)${N}"
    print "  ${G}  2.${N}${D} Regenerates compiled files, completions, env cache${N}"
    print "  ${G}  3.${N}${D} Runs the update cycle for zpwr and plugins${N}"
    print ""
    print "  ${D}  Think of it as \"factory reset without losing data.\"${N}"
    print "  ${D}  Your configuration, history, and local files survive.${N}"
    print "  ${D}  Everything else gets rebuilt from source.${N}"
    print ""
    print "  ${D}  When to use it:${N}"
    print "  ${D}  - Shell startup feels slow and you have tried individual fixes${N}"
    print "  ${D}  - After a major zsh or macOS upgrade${N}"
    print "  ${D}  - When individual clean verbs did not solve the problem${N}"
    print "  ${D}  - When you want to feel powerful${N}"
    print ""
    print "  ${R}${B}  TIME COST:${N}${R} Several minutes. This is not instant.${N}"
    print "  ${D}  It downloads plugin updates and recompiles everything.${N}"
    print ""
    print "  ${B}${Y}CLEANUPDATEDEPS: THE DEPENDENCY PURGE${N}"
    print "  ${M}  zpwr cleanupdatedeps${N}${D}                # clean deps + update them${N}"
    print ""
    print "  ${D}  Focused on external dependencies rather than caches.${N}"
    print "  ${D}  This verb:${N}"
    print "  ${G}  1.${N}${D} Cleans stale dependency state${N}"
    print "  ${G}  2.${N}${D} Updates all managed dependencies${N}"
    print ""
    print "  ${D}  When to use it:${N}"
    print "  ${D}  - Plugin versions are stuck at old commits${N}"
    print "  ${D}  - A dependency update broke something${N}"
    print "  ${D}  - You want the latest of everything${N}"
    print ""
    print "  ${B}${Y}DECISION MATRIX${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  Symptom                          Verb${N}"
    print "  ${D}  ─────────────────────────────────────────────────────${N}"
    print "  ${D}  Stale completions                ${M}zpwr cleancompcache${N}"
    print "  ${D}  Slow startup                     ${M}zpwr recompile${N}"
    print "  ${D}  Missing new repos in nav         ${M}zpwr cleangitcache${N}"
    print "  ${D}  General weirdness                ${M}zpwr cleanall${N}"
    print "  ${D}  Everything is broken              ${M}zpwr cleanrefreshupdate${N}"
    print "  ${D}  Plugins are ancient               ${M}zpwr cleanupdatedeps${N}"
    print ""
    print "  ${B}${Y}THE ESCALATION PATH${N}"
    print "  ${D}  Always start small and escalate:${N}"
    print "  ${M}  zpwr cleantemp${N}${D}                      # level 1: temp files${N}"
    print "  ${M}  zpwr cleancache${N}${D}                     # level 2: all caches${N}"
    print "  ${M}  zpwr cleanall${N}${D}                       # level 3: everything${N}"
    print "  ${M}  zpwr cleanrefreshupdate${N}${D}             # level 4: clean + rebuild + update${N}"
    print "  ${D}  Do not start with level 4. That is like calling an airstrike${N}"
    print "  ${D}  because you saw a spider.${N}"
    print ""
}
