PAGE_TITLE="Emacs Search & Tags"
PAGE_CHAPTER="CHAPTER 13: EMACS DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> SEARCH & TAGS: FIND ANYTHING, ANYWHERE <<<${N}"
    print "  ${D}grep is for amateurs, we have fzf-powered search beams${N}"
    print ""
    print "  ${B}${Y}FILE SEARCH (by filename):${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr emacsfilesearch${N}        ${D}# fzf filename search${N}"
    print "  ${C}  \$ zpwr emacsfilesearchedit${N}    ${D}# search + edit${N}"
    print ""
    print "  ${G}Searches file NAMES across the ZPWR tree.${N}"
    print "  ${G}Fast, fuzzy, and feeds results into emacs.${N}"
    print ""
    print "  ${B}${Y}WORD SEARCH (by content):${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr emacswordsearch${N}        ${D}# search file content${N}"
    print "  ${C}  \$ zpwr emacswordsearchedit${N}    ${D}# content search + edit${N}"
    print ""
    print "  ${G}Searches INSIDE files for patterns. Like ag/rg but${N}"
    print "  ${G}with fzf preview and direct-to-emacs piping.${N}"
    print ""
    print "  ${B}${Y}FIND & LOCATE SEARCH:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr emacsfindsearch${N}        ${D}# find-based search${N}"
    print "  ${C}  \$ zpwr emacsfindsearchedit${N}    ${D}# find + edit${N}"
    print "  ${C}  \$ zpwr emacslocatesearch${N}      ${D}# locate db search${N}"
    print "  ${C}  \$ zpwr emacslocatesearchedit${N}  ${D}# locate + edit${N}"
    print ""
    print "  ${B}${Y}TAGS -- CODE NAVIGATION:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr emacsctags${N}             ${D}# ctags generation${N}"
    print "  ${C}  \$ zpwr emacsgtags${N}             ${D}# GNU Global tags${N}"
    print "  ${C}  \$ zpwr emacsgtagsedit${N}         ${D}# gtags + jump to def${N}"
    print ""
    print "  ${G}Tags let emacs jump to function definitions instantly.${N}"
    print "  ${G}ctags for basic tagging, gtags for cross-reference.${N}"
    print ""
    print "  ${D}  // the search hierarchy:${N}"
    print "  ${D}  //   wordsearch  = grep inside files (content)${N}"
    print "  ${D}  //   filesearch  = find by filename (path)${N}"
    print "  ${D}  //   locatesearch = system locate db (everywhere)${N}"
    print "  ${D}  //   findsearch  = find command (directory tree)${N}"
    print "  ${D}  //   tags        = jump to definitions (symbols)${N}"
}
