PAGE_TITLE="ripgrep: grep Reimagined"
PAGE_CHAPTER="CHAPTER 37: RIPGREP — GREP AT LIGHT SPEED"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== RIPGREP: GREP REIMAGINED ===${N}"
    print "  ${D}// grep -r is a campfire. ripgrep is a directed energy weapon. //${N}"
    print "  ${C}ripgrep (rg) is a blazing-fast recursive grep written in Rust${N}"
    print "  ${C}by Andrew Gallant (BurntSushi). It respects .gitignore, skips${N}"
    print "  ${C}binary files, and uses Rust's regex engine for raw speed.${N}"
    print "  ${C}5-100x faster than grep -r on large codebases. Not a typo.${N}"
    print "  ${B}${Y}BASIC USAGE${N}"
    print "  ${M}  rg PATTERN${N}${D}           # search current dir recursively${N}"
    print "  ${M}  rg PATTERN path/${N}${D}     # search specific directory${N}"
    print "  ${M}  rg 'fn main'${N}${D}         # literal or regex — rg auto-detects${N}"
    print "  ${D}Output is colorized by default: filenames in magenta, line${N}"
    print "  ${D}numbers in green, matches highlighted. Grouped by file.${N}"
    print "  ${B}${Y}KEY FLAGS${N}"
    print "  ${G}  rg -i PATTERN${N}${D}       # case insensitive search${N}"
    print "  ${G}  rg -l PATTERN${N}${D}       # files with matches only (paths)${N}"
    print "  ${G}  rg -c PATTERN${N}${D}       # count matches per file${N}"
    print "  ${G}  rg -w PATTERN${N}${D}       # whole word matches only${N}"
    print "  ${G}  rg -F PATTERN${N}${D}       # fixed string (no regex interpretation)${N}"
    print "  ${G}  rg -v PATTERN${N}${D}       # invert match (lines NOT matching)${N}"
    print "  ${B}${Y}FILE TYPE FILTERING${N}"
    print "  ${G}  rg -t zsh PATTERN${N}${D}   # search only zsh files${N}"
    print "  ${G}  rg -T js PATTERN${N}${D}    # exclude javascript files${N}"
    print "  ${G}  rg -g '*.zsh' PAT${N}${D}   # glob filter (include)${N}"
    print "  ${G}  rg -g '!*.min.js' PAT${N}${D} # glob filter (exclude)${N}"
    print "  ${D}rg --type-list shows all built-in type definitions.${N}"
    print "  ${B}${Y}CONTEXT LINES${N}"
    print "  ${G}  rg -A 3 PATTERN${N}${D}     # 3 lines after each match${N}"
    print "  ${G}  rg -B 3 PATTERN${N}${D}     # 3 lines before each match${N}"
    print "  ${G}  rg -C 3 PATTERN${N}${D}     # 3 lines before AND after${N}"
    print "  ${B}${Y}MULTILINE MATCHING${N}"
    print "  ${G}  rg -U PATTERN${N}${D}       # --multiline: match across lines${N}"
    print "  ${M}  rg -U 'struct \\{[\\s\\S]*?\\}'${N}${D} # match entire struct blocks${N}"
    print "  ${D}Without -U, patterns match within single lines only.${N}"
    print "  ${B}${Y}THE COMPETITION${N}"
    print "  ${D}${G}grep -r${D}  — universal, slow, no .gitignore, no parallelism${N}"
    print "  ${D}${G}ag${D}      — the silver searcher. fast, .gitignore aware.${N}"
    print "  ${D}          rg is 2-5x faster on most benchmarks.${N}"
    print "  ${D}${G}ack${D}     — Perl-based, pioneered the \"better grep\" category.${N}"
    print "  ${D}          slower than both ag and rg. still has loyal users.${N}"
}
