PAGE_TITLE="Docker Management"
PAGE_CHAPTER="CHAPTER 15: NETWORK & CONTAINERS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> DOCKER MANAGEMENT: CONTAINER WARFARE <<<${N}"
    print "  ${D}it works on my machine --> we ship the machine${N}"
    print ""
    print "  ${B}${Y}zpwr dockerwipe${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}The nuclear option for Docker. Removes EVERYTHING:${N}"
    print "  ${G}containers, images, volumes, networks -- all of it.${N}"
    print ""
    print "  ${C}  \$ zpwr dockerwipe${N}             ${D}# purge all docker${N}"
    print ""
    print "  ${R}  WARNING: This is not gentle. It will:${N}"
    print "  ${R}    - Stop all running containers${N}"
    print "  ${R}    - Remove all containers${N}"
    print "  ${R}    - Remove all images${N}"
    print "  ${R}    - Remove all volumes${N}"
    print "  ${R}    - Prune everything${N}"
    print ""
    print "  ${Y}WHEN TO USE:${N}"
    print "  ${G}  * Disk space emergency (docker images love eating disk)${N}"
    print "  ${G}  * Fresh start after a botched experiment${N}"
    print "  ${G}  * When 'docker system df' shows 50GB of shame${N}"
    print ""
    print "  ${B}${Y}zpwr dfimage${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Reverse-engineer a Docker image to show its Dockerfile.${N}"
    print "  ${G}See how an image was built without the source.${N}"
    print ""
    print "  ${C}  \$ zpwr dfimage nginx:latest${N}   ${D}# reverse Dockerfile${N}"
    print "  ${C}  \$ zpwr dfimage myapp:v2${N}       ${D}# inspect any image${N}"
    print ""
    print "  ${G}Useful for auditing third-party images.${N}"
    print "  ${G}Trust but verify what's in that container.${N}"
    print ""
    print "  ${B}${Y}DOCKER TRIAGE:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. \$ docker system df              # how bad is it?${N}"
    print "  ${D}  2. \$ zpwr dfimage suspect:latest   # what's inside?${N}"
    print "  ${D}  3. \$ zpwr dockerwipe               # burn it all down${N}"
    print "  ${D}  4. \$ docker system df              # ahh, fresh disk${N}"
    print ""
    print "  ${D}  // dockerwipe: for when docker system prune isn't angry enough${N}"
    print "  ${D}  // dfimage: for when you don't trust the README${N}"
}
