PAGE_TITLE="Matrix: The Full Experience"
PAGE_CHAPTER="CHAPTER 22: CREATIVE TOOLS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== MATRIX: THE FULL EXPERIENCE ===${N}"
    print "  ${D}8 acts, 6 characters, and your ecosystem raining down${N}"
    print ""
    print "  ${B}${Y}THE STORY${N}"
    print "  ${M}  zpwr matrix${N}${D}               # 4-act story + rain${N}"
    print "  ${M}  zpwr matrix --extended${N}${D}     # full 8-act saga${N}"
    print ""
    print "  ${B}${Y}THE CHARACTERS${N}"
    print "  ${M}  zpwr matrix --cast${N}${D}         # show character bios${N}"
    print "  ${G}  Null Pointer${N}${D} .... protagonist, zpwr operator${N}"
    print "  ${Y}  Segfault${N}${D} ........ bash loyalist in recovery${N}"
    print "  ${C}  Chmod777${N}${D} ........ reckless, sudo for everything${N}"
    print "  ${M}  DevNull${N}${D} ......... silent assassin${N}"
    print "  ${R}  Chad Electron${N}${D} ... MegaCorp VP, 64GB for Slack${N}"
    print "  ${G}  The Kernel${N}${D} ...... mythical elder, speaks in dmesg${N}"
    print ""
    print "  ${B}${Y}VISUAL FX${N}"
    print "  ${M}  zpwr matrix --noir${N}${D}         # monochrome green${N}"
    print "  ${M}  zpwr matrix --vhs${N}${D}          # VHS tracking distortion${N}"
    print "  ${M}  zpwr matrix --crt${N}${D}          # CRT scanlines${N}"
    print "  ${M}  zpwr matrix --glitch${N}${D}       # extra corruption${N}"
    print "  ${M}  zpwr matrix --sound${N}${D}        # terminal bells${N}"
    print "  ${M}  zpwr matrix --no-fx${N}${D}        # disable all FX${N}"
    print "  ${M}  zpwr matrix -c 10${N}${D}          # chaos level 1-10${N}"
    print ""
    print "  ${B}${Y}PLAYBACK CONTROL${N}"
    print "  ${M}  zpwr matrix -s 7${N}${D}           # speed 1-9${N}"
    print "  ${M}  zpwr matrix --turbo${N}${D}        # skip all pauses${N}"
    print "  ${M}  zpwr matrix -a 5${N}${D}           # jump to act 5${N}"
    print "  ${M}  zpwr matrix -r${N}${D}             # skip story, rain only${N}"
    print ""
    print "  ${B}${Y}MULTIPLAYER${N}"
    print "  ${M}  zpwr matrix --battle${N}${D}       # 2-player tmux typing battle${N}"
    print "  ${D}  Player 1 (Null Pointer) vs Player 2 (Chad Electron).${N}"
    print "  ${D}  Type zpwr commands faster than your opponent.${N}"
    print "  ${D}  HP bars, taunts, and a winner-takes-all endgame.${N}"
    print "  ${D}  Requires tmux. Auto-splits into two panes.${N}"
    print ""
    print "  ${B}${Y}INFO${N}"
    print "  ${M}  zpwr matrix --stats${N}${D}        # ecosystem stats${N}"
    print "  ${M}  zpwr matrix --credits${N}${D}      # end credits roll${N}"
    print ""
}
