PAGE_TITLE="Regen & Compile"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== REGEN & COMPILE ===${N}"
    print "  ${D}// 24 verbs to rebuild the world //${N}"
    print ""
    print "  ${C}Regenerate caches, recompile zsh word code, and rebuild${N}"
    print "  ${C}tags. The engine room of ZPWR maintenance.${N}"
    print ""
    print "  ${B}${Y}REGEN CACHES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr regen${N}${D}                 # regen caches except git drive search${N}"
    print "  ${M}  zpwr regenall${N}${D}              # regen all caches${N}"
    print "  ${M}  zpwr regenpdf${N}${D}              # regenerate encyclopedia PDF${N}"
    print "  ${M}  zpwr regenenvcache${N}${D}         # regen search env to zpwrEnv files${N}"
    print "  ${M}  zpwr regengitrepocache${N}${D}     # regen list of all git repos${N}"
    print "  ${M}  zpwr regengitdirtyrepocache${N}${D}# regen list of dirty git repos${N}"
    print "  ${M}  zpwr regenhistory${N}${D}          # regen \$HISTFILE${N}"
    print "  ${M}  zpwr regenkeybindings${N}${D}      # regen all keybindings cache${N}"
    print "  ${M}  zpwr regenconfiglinks${N}${D}      # regen sym links to \$HOME${N}"
    print "  ${M}  zpwr regenpowerline${N}${D}        # regen powerline sym link${N}"
    print "  ${M}  zpwr regenzsh${N}${D}              # regen compsys cache${N}"
    print ""
    print "  ${B}${Y}REGEN TAGS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr regengtags${N}${D}            # regen gtags files to \$HOME${N}"
    print "  ${M}  zpwr regenctags${N}${D}            # regen ctags files to \$HOME${N}"
    print "  ${M}  zpwr regengtagspygments${N}${D}    # regen GNU gtags with pygments${N}"
    print "  ${M}  zpwr regengtagstype${N}${D}        # regen GNU gtags with specified parser${N}"
    print ""
    print "  ${B}${Y}COMPILE & DECOMPILE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr compile${N}${D}               # recompile all cache comps${N}"
    print "  ${M}  zpwr compilefpath${N}${D}          # recompile all fpath cache comps${N}"
    print "  ${M}  zpwr compilefiles${N}${D}          # recompile all files cache comps${N}"
    print "  ${M}  zpwr recompile${N}${D}             # recompile all cache comps${N}"
    print "  ${M}  zpwr recompilefpath${N}${D}        # recompile all fpath cache comps${N}"
    print "  ${M}  zpwr recompilefiles${N}${D}        # recompile all files cache comps${N}"
    print "  ${M}  zpwr refreshzwc${N}${D}            # delete then regen compiled zsh word code${N}"
    print "  ${M}  zpwr decompile${N}${D}             # delete all cache comps${N}"
    print "  ${M}  zpwr uncompile${N}${D}             # delete all cache comps${N}"
    print ""
}
