PAGE_TITLE="Git Repo Cache System"
PAGE_CHAPTER="CHAPTER 19: BATCH OPERATIONS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT REPO CACHE SYSTEM ===${N}"
    print "  ${D}// index every repo on your machine. operate on all of them. //${N}"
    print ""
    print "  ${C}The zsh-git-repo-cache plugin scans your entire filesystem${N}"
    print "  ${C}for git repos, caches the list, and lets you search, filter,${N}"
    print "  ${C}and broadcast commands across all of them.${N}"
    print ""
    print "  ${B}${Y}CACHE GENERATION${N}"
    print "  ${M}  zpwr regengitrepocache${N}${D}      # scan filesystem with fd/find${N}"
    print "  ${M}  zpwr regengitdirtyrepocache${N}${D}  # scan only dirty repos${N}"
    print ""
    print "  ${B}${Y}SEARCH & BROWSE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr gitrepos${N}${D}               # all repos into fzf${N}"
    print "  ${M}  zpwr gitreposclean${N}${D}          # clean repos into fzf${N}"
    print "  ${M}  zpwr gitreposdirty${N}${D}          # dirty repos into fzf${N}"
    print "  ${M}  zpwr gitreposlist${N}${D}           # list all repos (no fzf)${N}"
    print "  ${M}  zpwr gitreposcleanlist${N}${D}      # list clean repos${N}"
    print "  ${M}  zpwr gitreposdirtylist${N}${D}      # list dirty repos${N}"
    print ""
    print "  ${B}${Y}CACHED VARIANTS${N}"
    print "  ${M}  zpwr gitreposcleancache${N}${D}     # clean repos from cache${N}"
    print "  ${M}  zpwr gitreposdirtycache${N}${D}     # dirty repos from cache${N}"
    print "  ${M}  zpwr gitreposcleancachelist${N}${D}  # list clean from cache${N}"
    print "  ${M}  zpwr gitreposdirtycachelist${N}${D}  # list dirty from cache${N}"
    print ""
    print "  ${B}${Y}BATCH OPERATIONS${N}"
    print "  ${M}  zpwr gitreposexec <cmd>${N}${D}      # run cmd in all cached repos${N}"
    print "  ${M}  zpwr gitreposdirtyexec <cmd>${N}${D} # run cmd in dirty repos${N}"
    print "  ${M}  zpwr gitreposcleanexec <cmd>${N}${D} # run cmd in clean repos${N}"
    print "  ${M}  zpwr gitwho${N}${D}                 # contributor stats across all repos${N}"
    print ""
    print "  ${B}${Y}CACHE FILES${N}"
    print "  ${D}  \$ZPWR_ALL_GIT_DIRS       — all repos${N}"
    print "  ${D}  \$ZPWR_ALL_GIT_DIRS_CLEAN — clean repos only${N}"
    print "  ${D}  \$ZPWR_ALL_GIT_DIRS_DIRTY — dirty repos only${N}"
    print ""
    print "  ${D}  Plugin: ${C}MenkeTechnologies/zsh-git-repo-cache${N}"
    print ""
}
