PAGE_TITLE="Miscellaneous Arsenal (1/2)"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== MISCELLANEOUS ARSENAL (1/2) ===${N}"
    print "  ${D}// the verbs that defy categorization //${N}"
    print ""
    print "  ${B}${Y}TERMINAL & COLOR${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr animate${N}${D}               # run terminal animation${N}"
    print "  ${M}  zpwr alacritty${N}${D}             # edit alacritty config${N}"
    print "  ${M}  zpwr color2${N}${D}                # turn on stderr filter${N}"
    print "  ${M}  zpwr return2${N}${D}               # turn off stderr filter${N}"
    print "  ${M}  zpwr colorsdiff${N}${D}            # colorized side diff${N}"
    print "  ${M}  zpwr colortest${N}${D}             # test colors${N}"
    print "  ${M}  zpwr colortest256${N}${D}          # test 256 colors${N}"
    print "  ${M}  zpwr figletfonts${N}${D}           # show all figlet fonts${N}"
    print "  ${M}  zpwr pygmentcolors${N}${D}         # show all pygment colors${N}"
    print ""
    print "  ${B}${Y}BACKUP & HISTORY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr backup${N}${D}                # backup files${N}"
    print "  ${M}  zpwr backuphistory${N}${D}         # backup \$HISTFILE${N}"
    print "  ${M}  zpwr hist${N}${D}                  # exec history command via fzf${N}"
    print "  ${M}  zpwr histedit${N}${D}              # edit history command via fzf${N}"
    print "  ${M}  zpwr histfile${N}${D}              # edit history file${N}"
    print ""
    print "  ${B}${Y}FILE & DIR CREATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr makedir${N}${D}               # make a dir tree${N}"
    print "  ${M}  zpwr makefile${N}${D}              # make a dir tree with file at end${N}"
    print "  ${M}  zpwr scriptnew${N}${D}             # create new script without editor${N}"
    print "  ${M}  zpwr changename${N}${D}            # mv dir into namespace and sed sub${N}"
    print "  ${M}  zpwr changenamezpwr${N}${D}        # mv into zpwr namespace and sed sub${N}"
    print ""
    print "  ${B}${Y}DOCKER & GO${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr dfimage${N}${D}               # cat Dockerfile from IMAGE_ID${N}"
    print "  ${M}  zpwr dockerwipe${N}${D}            # wipe all docker images${N}"
    print "  ${M}  zpwr goclean${N}${D}               # clean Go package artifacts${N}"
    print ""
    print "  ${B}${Y}EXERCISM${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr exercism${N}${D}              # go to Exercism home page${N}"
    print "  ${M}  zpwr exercismedit${N}${D}          # edit file in \$HOME/Exercism${N}"
    print "  ${M}  zpwr exercismdownload${N}${D}      # download all for track${N}"
    print ""
}
