PAGE_TITLE="Git Battalion Operations"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT BATTALION OPERATIONS ===${N}"
    print ""
    print "  ${C}One repo is easy. Twenty repos is a war.${N}"
    print "  ${C}These verbs let you run commands across all of them.${N}"
    print ""
    print "  ${B}${Y}THE GENERAL: FORALLDIR${N}"
    print "  ${M}  zpwr gitforalldir <cmd>${N}${D}   # run cmd in ALL git dirs${N}"
    print "  ${D}  Walks every git directory it can find and runs your${N}"
    print "  ${D}  command inside each one. The nuclear option.${N}"
    print ""
    print "  ${B}${Y}CACHED REPOS${N}"
    print "  ${M}  zpwr gitreposexec <cmd>${N}${D}    # run cmd in cached git dirs${N}"
    print "  ${D}  Uses the cached list of known repos. Faster than${N}"
    print "  ${D}  foralldir because it does not rescan the filesystem.${N}"
    print ""
    print "  ${B}${Y}CLEAN VS DIRTY TARGETING${N}"
    print "  ${M}  zpwr gitreposcleanexec <cmd>${N}${D}       # refresh + run in clean repos${N}"
    print "  ${M}  zpwr gitreposcleancacheexec <cmd>${N}${D}  # run in cached clean repos${N}"
    print "  ${M}  zpwr gitreposdirtyexec <cmd>${N}${D}       # refresh + run in dirty repos${N}"
    print "  ${M}  zpwr gitreposdirtycacheexec <cmd>${N}${D}  # run in cached dirty repos${N}"
    print ""
    print "  ${G}  Clean repos have no uncommitted changes.${N}"
    print "  ${G}  Dirty repos have pending work.${N}"
    print "  ${G}  Target your commands accordingly.${N}"
    print ""
    print "  ${B}${Y}MASS UPDATE${N}"
    print "  ${M}  zpwr gitupdatefordir${N}${D}      # run git updates in all git dirs${N}"
    print "  ${D}  Pulls latest, updates submodules, the full sync.${N}"
    print "  ${D}  Run this on a Monday morning. Coffee. Wait.${N}"
    print ""
    print "  ${B}${Y}BRANCH WIPE OPERATIONS${N}"
    print "  ${M}  zpwr gitfordirmain${N}${D}        # wipe to main branch in git dirs${N}"
    print "  ${M}  zpwr gitfordirdevelop${N}${D}     # wipe to develop branch in git dirs${N}"
    print ""
    print "  ${M}  zpwr gitzfordir <branch> [z]${N}${D}       # wipe to any branch + z jump${N}"
    print "  ${M}  zpwr gitzfordirmain [z]${N}${D}            # z jump + wipe to main${N}"
    print "  ${M}  zpwr gitzfordirdevelop [z]${N}${D}         # z jump + wipe to develop${N}"
    print ""
    print "  ${B}${Y}THE REPOS FILE${N}"
    print "  ${M}  zpwr gitreposfile${N}${D}         # edit the git repos file${N}"
    print "  ${D}  This file lists all known repositories.${N}"
    print "  ${D}  Edit it to add or remove repos from batch operations.${N}"
    print ""
    print "  ${B}${Y}EXAMPLE: STATUS CHECK ALL REPOS${N}"
    print "  ${M}  zpwr gitreposexec git status -s${N}"
    print "  ${D}  Runs git status -s in every cached repo.${N}"
    print "  ${D}  Instantly see which repos have uncommitted work.${N}"
    print ""
    print "  ${D}Battalion ops turn you from a developer${N}"
    print "  ${D}into a fleet commander.${N}"
    print ""
}
