PAGE_TITLE="Finding Files"
PAGE_CHAPTER="CHAPTER 4: THE SEARCH ENGINE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FINDING FILES ===${N}"
    print ""
    print "  ${C}The filesystem is vast. You are small.${N}"
    print "  ${C}But you have fzf and a verb for every search strategy.${N}"
    print ""
    print "  ${B}${Y}FILESEARCH: LOCAL TREE${N}"
    print "  ${M}  zpwr filesearch${N}${D}          # find and open a file in a sub dir${N}"
    print "  ${D}  Recursively lists files under \$PWD into fzf.${N}"
    print "  ${D}  Type fragments of the filename. Fuzzy match. Enter.${N}"
    print "  ${D}  Opens the file in your pager.${N}"
    print ""
    print "  ${M}  zpwr filesearchedit${N}${D}      # same but puts path on command line${N}"
    print "  ${D}  Instead of opening immediately, the selected path${N}"
    print "  ${D}  lands on your \$BUFFER for further editing.${N}"
    print "  ${D}  Append commands, pipe it, whatever you want.${N}"
    print ""
    print "  ${B}${Y}DIRSEARCH: DIRECTORIES ONLY${N}"
    print "  ${M}  zpwr dirsearch${N}${D}           # cd to a sub directory via fzf${N}"
    print "  ${D}  Same idea but only directories. Pick one, land in it.${N}"
    print "  ${D}  Faster than cd-tab-tab-tab-tab.${N}"
    print ""
    print "  ${B}${Y}FINDSEARCH: FULL DISK${N}"
    print "  ${M}  zpwr findsearch${N}${D}          # find across the entire drive${N}"
    print "  ${D}  Uses find(1) to search the whole filesystem.${N}"
    print "  ${D}  Results feed into fzf. Pick one, open it.${N}"
    print "  ${D}  Slow on first run. Worth the wait.${N}"
    print ""
    print "  ${M}  zpwr findsearchedit${N}${D}      # same but result goes to \$BUFFER${N}"
    print ""
    print "  ${B}${Y}LOCATESEARCH: INDEX-BASED${N}"
    print "  ${M}  zpwr locatesearch${N}${D}        # search the locate database${N}"
    print "  ${D}  Uses locate(1) which searches a pre-built index.${N}"
    print "  ${D}  Blazing fast. But only as fresh as your last updatedb.${N}"
    print ""
    print "  ${M}  zpwr locatesearchedit${N}${D}    # same but result goes to \$BUFFER${N}"
    print ""
    print "  ${B}${Y}THE SEARCH HIERARCHY${N}"
    print "  ${G}  Speed    Scope          Verb${N}"
    print "  ${D}  -----    -----          ----${N}"
    print "  ${C}  Fast${N}${D} ... current tree .. ${M}filesearch${N}"
    print "  ${C}  Fast${N}${D} ... dirs only ..... ${M}dirsearch${N}"
    print "  ${C}  Slow${N}${D} ... entire disk ... ${M}findsearch${N}"
    print "  ${C}  Instant${N}${D}  indexed disk .. ${M}locatesearch${N}"
    print ""
    print "  ${D}Start with ${M}filesearch${D} for local work.${N}"
    print "  ${D}Escalate to ${M}locatesearch${D} when you need the whole disk.${N}"
    print "  ${D}Fall back to ${M}findsearch${D} when the index is stale.${N}"
    print ""
}
