PAGE_TITLE="History Archaeology"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> HISTORY ARCHAEOLOGY: DIGGING UP THE PAST <<<${N}"
    print "  ${D}your terminal remembers everything, even the mistakes${N}"
    print ""
    print "  ${B}${Y}zpwr hist${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Browse command history with fzf. Search, preview,${N}"
    print "  ${G}and re-execute past commands interactively.${N}"
    print ""
    print "  ${C}  \$ zpwr hist${N}                   ${D}# fzf history browser${N}"
    print ""
    print "  ${B}${Y}zpwr histedit${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Edit the history file directly. Surgically remove${N}"
    print "  ${G}embarrassing commands or fix typos in saved history.${N}"
    print ""
    print "  ${C}  \$ zpwr histedit${N}               ${D}# edit history file${N}"
    print ""
    print "  ${Y}  Use with care. History surgery is delicate work.${N}"
    print ""
    print "  ${B}${Y}zpwr histfile${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Show the path to the current history file.${N}"
    print "  ${G}Useful when you're not sure which histfile is active.${N}"
    print ""
    print "  ${C}  \$ zpwr histfile${N}               ${D}# show histfile path${N}"
    print ""
    print "  ${B}${Y}zpwr catviminfo${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Display vim's recent file history from viminfo.${N}"
    print "  ${G}What files has vim touched recently?${N}"
    print ""
    print "  ${C}  \$ zpwr catviminfo${N}             ${D}# vim file history${N}"
    print ""
    print "  ${B}${Y}zpwr catrecentfviminfo / catnviminforecentf${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Cross-reference vim/nvim recent files with the${N}"
    print "  ${G}recentf list. Where vim and shell history intersect.${N}"
    print ""
    print "  ${C}  \$ zpwr catrecentfviminfo${N}      ${D}# vim+recentf cross${N}"
    print "  ${C}  \$ zpwr catnviminforecentf${N}     ${D}# nvim+recentf cross${N}"
    print ""
    print "  ${D}  // your history is a goldmine of workflow patterns${N}"
    print "  ${D}  // hist + fzf = instant command recall${N}"
    print "  ${D}  // histedit = revisionist history (use responsibly)${N}"
}
