PAGE_TITLE="Cross-Platform Installer"
PAGE_CHAPTER="CHAPTER 40: HIDDEN SUBSYSTEMS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== CROSS-PLATFORM INSTALLER ===${N}"
    print "  ${D}one repo to rule them all, one script to install them${N}"
    print "  ${B}${Y}INSTALLER SCRIPTS IN \$ZPWR_INSTALL${N}"
    print "  ${G}  formulae.sh${N}${D}        Homebrew formulae (macOS/Linux)${N}"
    print "  ${G}  casks.sh${N}${D}           Homebrew casks (macOS GUI apps)${N}"
    print "  ${G}  mincasks.sh${N}${D}        minimal cask set for lean installs${N}"
    print "  ${G}  taps.sh${N}${D}            Homebrew tap repositories${N}"
    print "  ${G}  npm_install.sh${N}${D}     Node.js packages via npm${N}"
    print "  ${G}  npm.sh${N}${D}             npm package list${N}"
    print "  ${G}  gems.sh${N}${D}            Ruby gems${N}"
    print "  ${G}  pip_install.sh${N}${D}     Python packages via pip${N}"
    print "  ${G}  pip.sh / pip3.sh${N}${D}   pip package lists${N}"
    print "  ${G}  go_install.sh${N}${D}      Go packages${N}"
    print "  ${G}  rustupinstall.sh${N}${D}   Rust toolchain via rustup${N}"
    print "  ${B}${Y}EDITOR & PLUGIN INSTALLERS${N}"
    print "  ${G}  neovim_install.sh${N}${D}       Neovim setup${N}"
    print "  ${G}  vim_install.sh${N}${D}          Vim from source${N}"
    print "  ${G}  vim_plugins_install.sh${N}${D}  Vim plugin manager + plugins${N}"
    print "  ${G}  zsh_plugins_install.sh${N}${D}  Zsh plugins via zinit${N}"
    print "  ${G}  tmux_plugins_install.sh${N}${D} Tmux plugin manager + plugins${N}"
    print "  ${G}  spacemacs_install.sh${N}${D}    Spacemacs (Emacs) setup${N}"
    print "  ${B}${Y}SHARED INFRASTRUCTURE${N}"
    print "  ${G}  common.sh${N}${D}  shared installer functions used by all scripts${N}"
    print "  ${G}  zpwrInstall.sh${N}${D}  the master installer orchestrator${N}"
    print "  ${D}  Supports 20+ Linux distros, macOS, and FreeBSD.${N}"
    print "  ${D}  Detects your OS and calls the right package manager.${N}"
    print "  ${B}${Y}ZPWR VERBS FOR INSTALLATION${N}"
    print "  ${G}  zpwr install${N}${D}            run configure, make, make install${N}"
    print "  ${G}  zpwr uninstall${N}${D}          uninstall all zpwr configs${N}"
    print "  ${G}  zpwr regenconfiglinks${N}${D}   regen symlinks from \$ZPWR_INSTALL to \$HOME${N}"
    print "  ${D}  regenconfiglinks recreates dotfile symlinks after a reinstall.${N}"
    print "  ${B}${Y}THE SYMLINK STRATEGY${N}"
    print "  ${D}  zpwr doesn't copy config files to \$HOME. It symlinks them.${N}"
    print "  ${D}  .vimrc, .tmux.conf, .gitconfig - all point back to \$ZPWR_INSTALL.${N}"
    print "  ${D}  Edit once in the repo, git commit, and every machine gets it.${N}"
    print "  ${D}  ${M}zpwr regenconfiglinks${N}${D} rebuilds them if they break.${N}"
    print "  ${B}${R}PHILOSOPHY:${N} ${D}Package lists are just text files.${N}"
    print "  ${D}  Add a line to formulae.sh, and your next machine gets it.${N}"
    print "  ${D}  Your entire dev environment is version-controlled.${N}"
}
