PAGE_TITLE="Zsh Insert Mode: Basic & Movement"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ZSH INSERT MODE: BASIC & MOVEMENT >>>${N}"
    print "  ${D}the primary editing mode. where commands are born.${N}"
    print ""
    print "  ${B}${Y}LINE MOVEMENT:${N}"
    print "  ${C}Ctrl-A${N}                ${D}beginning-of-line${N}"
    print "  ${C}Ctrl-E${N}                ${D}end-of-line${N}"
    print "  ${C}Ctrl-O${N}                ${D}EOL or next tab stop${N}"
    print ""
    print "  ${B}${Y}EDITING:${N}"
    print "  ${C}Ctrl-U${N}                ${D}clear entire line${N}"
    print "  ${C}Ctrl-W${N}                ${D}delete word backward (autopair)${N}"
    print "  ${C}Ctrl-H${N}                ${D}delete char backward (autopair)${N}"
    print "  ${C}Ctrl-Y${N}                ${D}change surrounding quotes${N}"
    print "  ${C}Ctrl-Z${N}                ${D}undo${N}"
    print "  ${C}Ctrl-R${N}                ${D}redo${N}"
    print "  ${C}Ctrl-Q${N}                ${D}duplicate last word${N}"
    print ""
    print "  ${B}${Y}ZPWR SPECIAL:${N}"
    print "  ${C}Space${N}                 ${D}zpwr supernatural expand (aliases+globs)${N}"
    print "  ${C}Ctrl-@${N}                ${D}zpwr expand + terminate space${N}"
    print "  ${C}Ctrl-M (Enter)${N}        ${D}zpwr magic enter (show status on empty)${N}"
    print "  ${C}.${N}                     ${D}zpwr rationalize dot (.. -> ../..)${N}"
    print "  ${C}Ctrl-B${N}                ${D}zpwr clipboard paste${N}"
    print "  ${C}Ctrl-S${N}                ${D}git add commit push (no check)${N}"
    print "  ${C}Ctrl-K${N}                ${D}zsh-learn-Learn (flashcard)${N}"
    print ""
    print "  ${B}${Y}COMPLETION & FZF:${N}"
    print "  ${C}Tab (Ctrl-I)${N}          ${D}fzf-completion${N}"
    print "  ${C}Ctrl-D${N}                ${D}list-choices${N}"
    print "  ${C}Ctrl-L${N}                ${D}clear-screen${N}"
    print "  ${C}Ctrl-T${N}                ${D}fzf file widget${N}"
    print "  ${C}Alt-c${N}                 ${D}fzf cd widget${N}"
    print ""
    print "  ${B}${Y}HISTORY:${N}"
    print "  ${C}Ctrl-N${N}                ${D}down-history${N}"
    print "  ${C}Ctrl-P${N}                ${D}up-history${N}"
    print "  ${C}Up/Down arrows${N}        ${D}history substring search up/down${N}"
    print ""
    print "  ${B}${Y}MODE SWITCHING:${N}"
    print "  ${C}Escape${N}                ${D}enter vi command mode${N}"
    print "  ${C}jf / fj${N}              ${D}enter vi command mode (chord escape)${N}"
    print ""
    print "  ${B}${Y}SURROUND & PAIRS:${N}"
    print "  ${C}\" ' ( [ { \`${N}          ${D}auto-pair/surround insert${N}"
    print "  ${C}) ] }${N}                 ${D}autopair close${N}"
    print "  ${C}Backspace${N}             ${D}autopair-aware delete${N}"
    print ""
    print "  ${D}Space is the most powerful key: it expands aliases,${N}"
    print "  ${D}global aliases, and abbreviations before inserting.${N}"
    print ""
    print "  ${M}  // insert mode is where spells are typed${N}"
    print "  ${M}  // every keystroke is an incantation${N}"
    print ""
}
