PAGE_TITLE="Update System"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== UPDATE SYSTEM ===${N}"
    print "  ${D}// 6 verbs to stay current //${N}"
    print ""
    print "  ${C}Keep ZPWR, its dependencies, and zinit plugins up to date.${N}"
    print "  ${C}From surgical single-dep pulls to full system updates.${N}"
    print ""
    print "  ${B}${Y}CONFIG UPDATES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr update${N}${D}                # update zpwr custom configs${N}"
    print "  ${M}  zpwr updatepull${N}${D}            # pull latest config from repo${N}"
    print ""
    print "  ${B}${Y}DEPENDENCY UPDATES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr updatedeps${N}${D}            # update all dependencies${N}"
    print "  ${M}  zpwr updatedepsclean${N}${D}       # update all dependencies then clean${N}"
    print "  ${M}  zpwr updatezinit${N}${D}           # update zinit dependencies${N}"
    print ""
    print "  ${B}${Y}FULL UPDATE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr updateall${N}${D}             # update zpwr configs and all deps${N}"
    print ""
    print "  ${D}  Typical workflow: ${M}zpwr updateall${D} pulls the latest${N}"
    print "  ${D}  configs, updates brew/pip/npm/gem/zinit, and refreshes${N}"
    print "  ${D}  caches. Run ${M}zpwr updatedepsclean${D} afterward to${N}"
    print "  ${D}  reclaim disk space from stale packages.${N}"
    print ""
}
