PAGE_TITLE="Git Basics"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT BASICS ===${N}"
    print ""
    print "  ${C}Git is already a language. ZPWR makes it a dialect${N}"
    print "  ${C}you can actually speak without consulting the man page.${N}"
    print ""
    print "  ${B}${Y}THE COMMIT PIPELINE${N}"
    print "  ${M}  zpwr gitcommit \"your message here\"${N}"
    print "  ${D}  This is not just git commit. It does:${N}"
    print "  ${D}    git add -> git commit -> git push${N}"
    print "  ${D}  All in one verb. The full gacp (git add commit push).${N}"
    print "  ${D}  Because who commits without pushing? Cowards.${N}"
    print ""
    print "  ${B}${Y}CONFIG AND IGNORES${N}"
    print "  ${M}  zpwr gitconfig${N}${D}         # edit git config file${N}"
    print "  ${M}  zpwr gitglobalconfig${N}${D}   # same thing, explicit name${N}"
    print "  ${M}  zpwr gitignore${N}${D}         # edit .git/info/exclude (local)${N}"
    print "  ${M}  zpwr gitignores${N}${D}        # edit global git ignores file${N}"
    print "  ${M}  zpwr gitglobalignores${N}${D}  # same as gitignores${N}"
    print ""
    print "  ${B}${Y}STASH AND DIFF (VIA FORGIT)${N}"
    print "  ${C}ZPWR delegates interactive stash and diff to forgit:${N}"
    print "  ${M}  zpwr forgitdiff${N}${D}        # fzf-powered git diff viewer${N}"
    print "  ${M}  zpwr forgitstash${N}${D}       # fzf-powered stash browser${N}"
    print "  ${D}  See page 13 for the full forgit arsenal.${N}"
    print ""
    print "  ${B}${Y}REMOTE OPERATIONS${N}"
    print "  ${M}  zpwr gitremotes${N}${D}        # list all git remotes${N}"
    print "  ${M}  zpwr gitdir${N}${D}            # check if pwd is a git dir${N}"
    print ""
    print "  ${B}${Y}TAGS${N}"
    print "  ${M}  zpwr gitedittag${N}${D}        # print tag to \$BUFFER${N}"
    print "  ${M}  zpwr gitupdatetag${N}${D}      # print tag and latest msg to \$BUFFER${N}"
    print ""
    print "  ${B}${Y}REAL-WORLD EXAMPLE${N}"
    print "  ${G}  # You just finished a feature. Ship it:${N}"
    print "  ${M}  zpwr gitcommit \"add quantum flux capacitor\"${N}"
    print "  ${D}  # Stages everything, commits with message, pushes.${N}"
    print "  ${D}  # One line. Done. Next feature.${N}"
    print ""
    print "  ${G}  # Need to check your git config:${N}"
    print "  ${M}  zpwr gitconfig${N}"
    print "  ${D}  # Opens it in \$EDITOR. Fix, save, done.${N}"
    print ""
    print "  ${D}Git verbs follow the pattern: ${M}git${D} + action noun.${N}"
    print "  ${D}If you can name it, zpwr probably has a verb for it.${N}"
    print ""
}
