PAGE_TITLE="Turbo Mode: Deferred Loading"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== TURBO MODE: DEFERRED LOADING ===${N}"
    print "  ${D}// why load 48 plugins at startup when you can load 1? //${N}"
    print "  ${C}Turbo mode is zinit's killer feature: plugins load AFTER${N}"
    print "  ${C}the prompt appears, using zsh's sched mechanism. Your shell${N}"
    print "  ${C}is interactive instantly; plugins trickle in behind the scenes.${N}"
    print "  ${B}${Y}THE wait ICE MODIFIER${N}"
    print "  ${D}The 'wait' ice defers loading until after the first prompt:${N}"
    print "  ${M}  zinit ice wait${N}${D}            Load after prompt (default priority)${N}"
    print "  ${M}  zinit ice wait'0'${N}${D}         Same as wait (priority 0)${N}"
    print "  ${M}  zinit ice wait'0a'${N}${D}        Priority 0, sub-order a (loads first)${N}"
    print "  ${M}  zinit ice wait'0b'${N}${D}        Priority 0, sub-order b (loads second)${N}"
    print "  ${M}  zinit ice wait'0e'${N}${D}        Priority 0, sub-order e (loads later)${N}"
    print "  ${D}The letter suffix controls load order WITHIN the same priority.${N}"
    print "  ${D}a loads before b loads before c, etc. This is how ZPWR${N}"
    print "  ${D}orchestrates 48 plugins into a precise loading sequence.${N}"
    print "  ${B}${Y}THE GRADUATED LOADING SEQUENCE${N}"
    print "  ${G}  Synchronous:${N}${D}  powerlevel10k (must load before prompt)${N}"
    print "  ${G}  wait:${N}${D}          OMZ completions, libs, plugins, GH plugins${N}"
    print "  ${G}  wait'0':${N}${D}       zsh-autopair (needs ZLE ready)${N}"
    print "  ${G}  wait'0a':${N}${D}      zsh-expand + late aliases + alias cache${N}"
    print "  ${G}  wait'0b':${N}${D}      zsh-autocomplete (if ZPWR_AUTO_COMPLETE=true)${N}"
    print "  ${G}  wait'0c':${N}${D}      zsh-history-substring-search${N}"
    print "  ${G}  wait'0d':${N}${D}      zsh-autosuggestions + FZF late bindings + verbs${N}"
    print "  ${G}  wait'0e':${N}${D}      zsh-zinit-final (penultimate, final keybindings)${N}"
    print "  ${G}  wait'0f':${N}${D}      zsh-more-completions (low priority, last resort)${N}"
    print "  ${G}  wait'\${ZPWR_ZINIT_COMPINIT_DELAY}g':${N}${D}  compinit + cdreplay${N}"
    print "  ${G}  wait'\${ZPWR_ZINIT_COMPINIT_DELAY}h':${N}${D}  fast-syntax-highlighting${N}"
    print "  ${B}${Y}WHY STARTUP IS FAST${N}"
    print "  ${D}Only ONE plugin loads synchronously: powerlevel10k.${N}"
    print "  ${D}Everything else is turbo-deferred. Combined with instant${N}"
    print "  ${D}prompt, you see the prompt in ~15ms. The other 47 plugins${N}"
    print "  ${D}load in the next ~200ms while you're still thinking.${N}"
    print "  ${B}${Y}atinit AND atload HOOKS${N}"
    print "  ${D}These run code at precise moments during plugin loading:${N}"
    print "  ${G}  atinit${N}${D}   Runs BEFORE the plugin is sourced${N}"
    print "  ${G}  atload${N}${D}   Runs AFTER the plugin is sourced${N}"
    print "  ${D}ZPWR uses these extensively to bind keymaps and aliases:${N}"
    print "  ${M}  zinit ice wait'0a' atload'zpwrBindAliasesLate; zpwrCreateAliasCache'${N}"
    print "  ${D}The atload fires after zsh-expand is sourced, then late${N}"
    print "  ${D}aliases override any OMZ defaults. Precise surgical timing.${N}"
    print "  ${B}${Y}ZPWR_ZINIT_COMPINIT_DELAY${N}"
    print "  ${D}Default: 0. Controls how long to wait before running compinit.${N}"
    print "  ${D}Higher values defer completion system init even further.${N}"
    print "  ${D}Set in \$ZPWR_ENV/.zpwr_env.sh. The 'g' and 'h' suffixes on${N}"
    print "  ${D}the wait ice ensure compinit and syntax highlighting load last.${N}"
}
