PAGE_TITLE="Zinit: The Plugin Engine"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== ZINIT: THE PLUGIN ENGINE ===${N}"
    print "  ${D}// the package manager for your shell. apt-get for zsh plugins. //${N}"
    print "  ${C}Zinit (formerly zplugin) is a flexible zsh plugin manager${N}"
    print "  ${C}with turbo mode, ice modifiers, and completion management.${N}"
    print "  ${C}ZPWR uses it as the default: ZPWR_PLUGIN_MANAGER=zinit${N}"
    print "  ${B}${Y}WHAT ZINIT DOES${N}"
    print "  ${D}  - Downloads GitHub plugins to \$ZPWR_PLUGIN_MANAGER_HOME${N}"
    print "  ${D}  - Sources them into your shell (or loads as completions)${N}"
    print "  ${D}  - Manages load order with turbo mode (deferred loading)${N}"
    print "  ${D}  - Handles OMZ snippets (individual files from oh-my-zsh)${N}"
    print "  ${D}  - Compiles plugins to .zwc bytecode for speed${N}"
    print "  ${B}${Y}ZINIT LOAD vs ZINIT SNIPPET${N}"
    print "  ${G}  zinit load user/repo${N}${D}      Clone full GitHub repo, source .plugin.zsh${N}"
    print "  ${G}  zinit snippet OMZP::git${N}${D}    Download single file from OMZ plugin${N}"
    print "  ${G}  zinit snippet OMZL::git.zsh${N}${D} Download single OMZ lib file${N}"
    print "  ${D}load = full repo clone. snippet = single file download.${N}"
    print "  ${D}ZPWR uses both: load for GitHub plugins, snippet for OMZ.${N}"
    print "  ${B}${Y}THE PLUGIN ARRAYS${N}"
    print "  ${D}ZPWR organizes plugins into arrays in .zshrc:${N}"
    print "  ${G}  ZPWR_GH_PLUGINS${N}${D}   28+ GitHub repos (fzf-tab, zsh-z, forgit...)${N}"
    print "  ${G}  ZPWR_OMZ_PLUGINS${N}${D}  25+ OMZ snippets (git, python, golang...)${N}"
    print "  ${G}  ZPWR_OMZ_LIBS${N}${D}     4 OMZ lib files (git.zsh, directories.zsh...)${N}"
    print "  ${G}  ZPWR_OMZ_COMPS${N}${D}    12 OMZ completion files (ng, coffee, scala...)${N}"
    print "  ${D}Conditional plugins are appended if the command exists:${N}"
    print "  ${M}  zpwrCommandExists docker && ZPWR_GH_PLUGINS+=( zsh-docker-aliases )${N}"
    print "  ${B}${Y}PLUGIN STORAGE${N}"
    print "  ${D}Everything lives under \$ZPWR_PLUGIN_MANAGER_HOME:${N}"
    print "  ${M}  \$ZPWR_PLUGIN_MANAGER_HOME/bin/${N}${D}         zinit itself${N}"
    print "  ${M}  \$ZPWR_PLUGIN_MANAGER_HOME/plugins/${N}${D}     cloned repos${N}"
    print "  ${M}  \$ZPWR_PLUGIN_MANAGER_HOME/snippets/${N}${D}    OMZ snippets${N}"
    print "  ${M}  \$ZPWR_PLUGIN_MANAGER_HOME/completions/${N}${D}  symlinked completions${N}"
    print "  ${B}${Y}THE 48+ PLUGIN ROSTER${N}"
    print "  ${D}Total plugins managed by zpwr (from .zshplugins):${N}"
    print "  ${D}  MenkeTechnologies forks: fzf-tab, forgit, zsh-expand,${N}"
    print "  ${D}    zsh-autocomplete, zsh-z, fasd-simple, revolver, zunit...${N}"
    print "  ${D}  zdharma-continuum: fast-syntax-highlighting, zbrowse, zui...${N}"
    print "  ${D}  zsh-users: completions, autosuggestions, history-substring${N}"
    print "  ${D}  Plus: hlissner/zsh-autopair, bigH/git-fuzzy, and more.${N}"
    print "  ${B}${Y}FIRST RUN BOOTSTRAP${N}"
    print "  ${D}If \$ZPWR_PLUGIN_MANAGER_HOME/bin doesn't exist, .zshrc${N}"
    print "  ${D}auto-clones zinit from GitHub. After that, OPTIMIZE_OUT_DISK_ACCESSES=1${N}"
    print "  ${D}skips unnecessary stat() calls on subsequent starts.${N}"
}
