PAGE_TITLE="All 408 Verbs H-S"
PAGE_CHAPTER="CHAPTER 25: THE COMPLETE REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< ALL 408 VERBS: forgitdiff through recompilefpath (2/3) >>>${N}"
    print "  ${D}the middle of the alphabet is where the real work lives${N}"
    print ""
    print "  ${C}forgitdiff${N}                 ${D}interactive diff via fzf${N}"
    print "  ${C}forgitignore${N}               ${D}browse gitignore templates${N}"
    print "  ${C}forgitignoreclean${N}          ${D}clean gitignore cache${N}"
    print "  ${C}forgitignoreget${N}            ${D}fetch gitignore template${N}"
    print "  ${C}forgitignorelist${N}           ${D}list gitignore templates${N}"
    print "  ${C}forgitignoreupdate${N}         ${D}update gitignore cache${N}"
    print "  ${C}forgitinfo${N}                 ${D}repo info dashboard${N}"
    print "  ${C}forgitlog${N}                  ${D}interactive git log via fzf${N}"
    print "  ${C}forgitreset${N}                ${D}interactive unstage via fzf${N}"
    print "  ${C}forgitrestore${N}              ${D}interactive restore via fzf${N}"
    print "  ${C}forgitstash${N}                ${D}interactive stash via fzf${N}"
    print "  ${C}forgitwarn${N}                 ${D}warn about repo hazards${N}"
    print "  ${C}forked${N}                     ${D}manage forked repos${N}"
    print "  ${C}forward${N}                    ${D}port forwarding${N}"
    print "  ${C}fp${N}                         ${D}fpath info${N}"
    print "  ${C}funcrank${N}                   ${D}rank functions by usage${N}"
    print "  ${C}fwd${N}                        ${D}forward shortcut${N}"
    print "  ${C}gh${N}                         ${D}GitHub CLI integration${N}"
    print "  ${C}ghcontribcount${N}             ${D}GitHub contribution count${N}"
    print "  ${C}ghz${N}                        ${D}GitHub + z integration${N}"
    print "  ${C}gitaemail${N}                  ${D}set git author email${N}"
    print "  ${C}gitcemail${N}                  ${D}set git committer email${N}"
    print "  ${C}gitclearcache${N}              ${D}clear git cache${N}"
    print "  ${C}gitclearcommit${N}             ${D}clear a git commit${N}"
    print "  ${C}gitclearfile${N}               ${D}clear file from git${N}"
    print "  ${C}gitcommit${N}                  ${D}enhanced git commit${N}"
    print "  ${C}gitcommitcount${N}             ${D}count commits${N}"
    print "  ${C}gitcommits${N}                 ${D}browse commits${N}"
    print "  ${C}gitconfig${N}                  ${D}show git config${N}"
    print "  ${C}gitcontribcount${N}            ${D}count contributions${N}"
    print "  ${C}gitcontribcountdirs${N}        ${D}count contribs per dir${N}"
    print "  ${C}gitcontribcountlines${N}       ${D}count contributed lines${N}"
    print "  ${C}gitdir${N}                     ${D}show git directory${N}"
    print "  ${C}gitedittag${N}                 ${D}edit a git tag${N}"
    print "  ${C}gitemail${N}                   ${D}show git email${N}"
    print "  ${C}gitforalldir${N}               ${D}git cmd in all dirs${N}"
    print "  ${C}hometests${N}                  ${D}cd to test directory (alias: hometest)${N}"
    print "  ${C}loadjenv${N}                   ${D}lazy load jenv${N}"
    print "  ${C}logincount${N}                 ${D}count logins by user${N}"
    print "  ${C}regenpdf${N}                   ${D}regenerate encyclopedia PDF${N}"
    print "  ${C}subcommandsedit${N}            ${D}edit subcommand selection${N}"
    print "  ${C}subcommandslist${N}             ${D}list all subcommands${N}"
    print ""
    print "  ${D}... continued. Run zpwr verbs for the complete list.${N}"
}
