PAGE_TITLE="Vim Search and Tags"
PAGE_CHAPTER="CHAPTER 5: EDITOR MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== VIM SEARCH AND TAGS ===${N}"
    print ""
    print "  ${C}Finding files is step one. Finding definitions${N}"
    print "  ${C}inside those files is step two. Tags are step three:${N}"
    print "  ${C}jump to any symbol by name.${N}"
    print ""
    print "  ${B}${Y}VIM FILE SEARCH${N}"
    print "  ${M}  zpwr vimfilesearch${N}${D}          # fzf find file -> open in vim${N}"
    print "  ${D}  Lists files in the current tree via fzf.${N}"
    print "  ${D}  Select one, it opens in vim. No path typing.${N}"
    print ""
    print "  ${M}  zpwr vimfilesearchedit${N}${D}      # fzf find file -> path to \$BUFFER${N}"
    print "  ${D}  Same search but puts the path on your command line.${N}"
    print ""
    print "  ${B}${Y}VIM WORD SEARCH${N}"
    print "  ${M}  zpwr vimwordsearch${N}${D}          # fzf grep content -> open in vim${N}"
    print "  ${D}  Searches file contents, shows matches in fzf.${N}"
    print "  ${D}  Select a match, vim opens at that location.${N}"
    print ""
    print "  ${M}  zpwr vimwordsearchedit${N}${D}      # same but path to \$BUFFER${N}"
    print ""
    print "  ${B}${Y}FULL DISK SEARCH INTO VIM${N}"
    print "  ${M}  zpwr vimfindsearch${N}${D}          # find(1) -> fzf -> vim${N}"
    print "  ${M}  zpwr vimfindsearchedit${N}${D}      # find(1) -> fzf -> \$BUFFER${N}"
    print "  ${M}  zpwr vimlocatesearch${N}${D}        # locate -> fzf -> vim${N}"
    print "  ${M}  zpwr vimlocatesearchedit${N}${D}    # locate -> fzf -> \$BUFFER${N}"
    print ""
    print "  ${D}  The search escalation ladder from page 15 but with${N}"
    print "  ${D}  vim as the final destination instead of a pager.${N}"
    print ""
    print "  ${B}${Y}CTAGS: JUMP TO DEFINITION${N}"
    print "  ${M}  zpwr vimctags${N}${D}               # open zpwr ctags in vim${N}"
    print "  ${D}  Ctags indexes function and variable definitions.${N}"
    print "  ${D}  With tags loaded, ${M}Ctrl-]${D} on any symbol jumps to${N}"
    print "  ${D}  its definition. ${M}Ctrl-T${D} jumps back.${N}"
    print "  ${D}  Code navigation at the speed of thought.${N}"
    print ""
    print "  ${B}${Y}GNU GLOBAL TAGS${N}"
    print "  ${M}  zpwr vimgtags${N}${D}               # open zpwr GNU global tags in vim${N}"
    print "  ${M}  zpwr vimgtagsedit${N}${D}           # edit zpwr GNU global tags${N}"
    print "  ${D}  GNU Global is ctags on steroids. It indexes not just${N}"
    print "  ${D}  definitions but references too. Find every caller${N}"
    print "  ${D}  of a function, not just its definition.${N}"
    print ""
    print "  ${B}${Y}THE SEARCH MATRIX${N}"
    print "  ${G}  What you know       Verb to use${N}"
    print "  ${D}  -------------       -----------${N}"
    print "  ${C}  Filename fragment${N}${D}   ${M}vimfilesearch${N}"
    print "  ${C}  String in a file${N}${D}    ${M}vimwordsearch${N}"
    print "  ${C}  File somewhere${N}${D}      ${M}vimlocatesearch${N}"
    print "  ${C}  Symbol name${N}${D}         ${M}vimctags${D} then Ctrl-]${N}"
    print "  ${C}  All references${N}${D}      ${M}vimgtags${N}"
    print ""
}
