PAGE_TITLE="Behavior Flags"
PAGE_CHAPTER="CHAPTER 21: ZPWR ENVIRONMENT VARIABLES"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< BEHAVIOR FLAGS — THE KNOBS AND DIALS >>>${N}"
    print "  ${D}tune the machine without cracking open the engine${N}"
    print ""
    print "  ${C}ZPWR is not a take-it-or-leave-it monolith.${N}"
    print "  ${C}These boolean and string flags let you control${N}"
    print "  ${C}startup behavior, logging verbosity, and debug output${N}"
    print "  ${C}without editing a single line of source code.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_PROFILING — STARTUP PROFILER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  export ZPWR_PROFILING=true${N}"
    print "  ${G}Enables zsh startup profiling. Shows exactly where${N}"
    print "  ${G}your milliseconds go during shell init. Pair with${N}"
    print "  ${M}  zpwr bench${G} for the full picture.${N}"
    print ""
    print "  ${D}  Set it, open a new shell, and read the profiling data.${N}"
    print "  ${D}  Find the bottleneck. Kill the bottleneck. Repeat.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_DEBUG — DEBUG MODE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  export ZPWR_DEBUG=true${N}"
    print "  ${G}Turns on debug-level log messages. When something${N}"
    print "  ${G}is broken and you need the machine to talk, flip this.${N}"
    print "  ${G}Check output with ${M}zpwr logdebug${G}.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_TRACE — FULL TRACE MODE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  export ZPWR_TRACE=true${N}"
    print "  ${G}The firehose. Every function call, every expansion,${N}"
    print "  ${G}traced to the log. Use ${M}zpwr trace${G} to run commands${N}"
    print "  ${G}with tracing, or ${M}zpwr logtrace${G} to read trace logs.${N}"
    print "  ${R}  WARNING: produces enormous output. Use surgically.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_BANNER_CLEARLIST — STARTUP BANNER CONTROL${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  export ZPWR_BANNER_CLEARLIST=true${N}"
    print "  ${G}Controls whether the ZPWR banner and clearlist show${N}"
    print "  ${G}at shell startup. The banner is glorious, but if${N}"
    print "  ${G}you open 50 terminals a day, you might want silence.${N}"
    print ""
    print "  ${D}  Related verbs:${N}"
    print "  ${M}  zpwr banner${N}${D}          show the banner manually${N}"
    print "  ${M}  zpwr clearlist${N}${D}       show clearlist manually${N}"
    print "  ${M}  zpwr bannerlolcat${N}${D}    banner with rainbow colors${N}"
    print ""
    print "  ${B}${G}QUICK REFERENCE:${N}"
    print "  ${C}  ZPWR_PROFILING${N}        ${D}startup timing data${N}"
    print "  ${C}  ZPWR_DEBUG${N}            ${D}debug-level logging${N}"
    print "  ${C}  ZPWR_TRACE${N}            ${D}full execution trace${N}"
    print "  ${C}  ZPWR_BANNER_CLEARLIST${N} ${D}startup banner toggle${N}"
    print ""
    print "  ${D}  // the flags do not change the code. they reveal it.${N}"
    print "  ${D}  // debugging is not failure. it is x-ray vision.${N}"
    print ""
}
