PAGE_TITLE="Tmux Layout Save & Restore"
PAGE_CHAPTER="CHAPTER 30: TMUX DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== TMUX LAYOUT SAVE & RESTORE ===${N}"
    print "  ${D}your pane arrangement, preserved forever${N}"
    print ""
    print "  ${B}${Y}THE PROBLEM${N}"
    print "  ${C}You spent 20 minutes splitting panes, resizing them,${N}"
    print "  ${C}cd-ing into the right directories. Then tmux crashes.${N}"
    print "  ${C}Or you reboot. Or you accidentally kill the session.${N}"
    print "  ${C}All that layout work? Gone. Every time.${N}"
    print ""
    print "  ${B}${Y}THE SOLUTION${N}"
    print "  ${M}  zpwr tmuxsave dev${N}${D}             # save layout as 'dev'${N}"
    print "  ${M}  zpwr tmuxload dev${N}${D}             # restore it later${N}"
    print ""
    print "  ${B}${Y}WHAT GETS SAVED${N}"
    print "  ${G}  Windows${N}${D} ............... names and count${N}"
    print "  ${G}  Pane splits${N}${D} ........... exact geometry via select-layout${N}"
    print "  ${G}  Directories${N}${D} ........... per-pane working directory${N}"
    print "  ${G}  Running commands${N}${D} ...... full args from process tree${N}"
    print "  ${G}  Window options${N}${D} ........ synchronize-panes, auto-rename${N}"
    print "  ${G}  Session options${N}${D} ....... non-plugin tmux settings${N}"
    print "  ${G}  Active pane/window${N}${D} .... cursor position restored${N}"
    print ""
    print "  ${B}${Y}MANAGEMENT${N}"
    print "  ${M}  zpwr tmuxsave${N}${D}                 # save with timestamp name${N}"
    print "  ${M}  zpwr tmuxsave --list${N}${D}          # list saved layouts${N}"
    print "  ${M}  zpwr tmuxsave --delete dev${N}${D}    # remove a layout${N}"
    print "  ${M}  zpwr tmuxload${N}${D}                 # fzf picker (no args)${N}"
    print "  ${M}  zpwr tmuxload dev mywork${N}${D}      # restore as session 'mywork'${N}"
    print ""
    print "  ${B}${Y}KEYBINDING${N}"
    print "  ${C}  prefix W${N}${D}                      # save layout (tmux keybinding)${N}"
    print ""
    print "  ${B}${Y}ALIASES${N}"
    print "  ${M}  zpwr layoutsave${N}${D}  = ${M}zpwr tmuxsave${N}"
    print "  ${M}  zpwr layoutload${N}${D}  = ${M}zpwr tmuxload${N}"
    print ""
    print "  ${D}Layouts are stored as self-contained zsh scripts in${N}"
    print "  ${D}\$ZPWR_LOCAL/layouts/. You can edit them by hand,${N}"
    print "  ${D}version control them, or share them with your team.${N}"
    print ""
    print "  ${R}${B}PROTIP:${N}${R} Save your layout before experimenting.${N}"
    print "  ${R}If you break everything, one command brings it back.${N}"
    print ""
}
