PAGE_TITLE="Benchmarking Startup"
PAGE_CHAPTER="CHAPTER 6: PERFORMANCE CULT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== BENCHMARKING STARTUP ===${N}"
    print ""
    print "  ${C}A shell that takes 2 seconds to start is a shell${N}"
    print "  ${C}that has already lost. ZPWR takes startup time${N}"
    print "  ${C}seriously enough to build a benchmarking verb.${N}"
    print ""
    print "  ${B}${Y}THE BENCH VERB${N}"
    print "  ${M}  zpwr bench${N}"
    print "  ${D}  Runs multiple shell startup iterations and reports:${N}"
    print "  ${D}    - Mean startup time${N}"
    print "  ${D}    - Percentiles (p50, p95, p99)${N}"
    print "  ${D}    - Baseline diff (zpwr overhead vs bare zsh)${N}"
    print ""
    print "  ${B}${Y}WHAT THE NUMBERS MEAN${N}"
    print "  ${G}  < 100ms${N}${D} .... imperceptible. You are golden.${N}"
    print "  ${G}  100-200ms${N}${D} .. noticeable if you open many terminals.${N}"
    print "  ${Y}  200-500ms${N}${D} .. getting sluggish. Time to investigate.${N}"
    print "  ${R}  > 500ms${N}${D} .... something is wrong. Check your plugins.${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${C}  The bench verb spawns N fresh zsh instances,${N}"
    print "  ${C}  each running through the full init chain.${N}"
    print "  ${C}  It measures wall-clock time from fork to prompt.${N}"
    print "  ${C}  Then it does the same for bare zsh (no zpwr).${N}"
    print "  ${C}  The diff tells you exactly what zpwr costs.${N}"
    print ""
    print "  ${B}${Y}WHAT SLOWS YOU DOWN${N}"
    print "  ${D}  Common culprits in order of likelihood:${N}"
    print "  ${R}  1. ${N}${D}Too many vim/emacs plugins loading at shell init${N}"
    print "  ${R}  2. ${N}${D}nvm/pyenv/rbenv hooking into every prompt${N}"
    print "  ${R}  3. ${N}${D}Uncompiled completion files (run ${M}zpwr compile${D})${N}"
    print "  ${R}  4. ${N}${D}Network calls in your init chain (stop that)${N}"
    print "  ${R}  5. ${N}${D}Massive HISTFILE being loaded synchronously${N}"
    print ""
    print "  ${B}${Y}OPTIMIZATION CHECKLIST${N}"
    print "  ${M}  zpwr compile${N}${D}        # recompile all cache and completions${N}"
    print "  ${M}  zpwr compilefpath${N}${D}    # recompile all fpath files${N}"
    print "  ${M}  zpwr compilefiles${N}${D}    # recompile all files${N}"
    print "  ${D}  Compiled .zwc files load faster than source.${N}"
    print "  ${D}  This is the single biggest performance lever.${N}"
    print ""
    print "  ${B}${Y}BENCHMARK REGULARLY${N}"
    print "  ${G}  Run ${M}zpwr bench${G} after any config change.${N}"
    print "  ${G}  If the numbers go up, you broke something.${N}"
    print "  ${G}  If they go down, you are a performance wizard.${N}"
    print ""
    print "  ${D}Your shell starts thousands of times a year.${N}"
    print "  ${D}Every millisecond is multiplied by every terminal open.${N}"
    print "  ${D}Measure. Optimize. Measure again.${N}"
    print ""
}
