PAGE_TITLE="Tmux Prefix Keys: Layouts & Pane Configs"
PAGE_CHAPTER="APPENDIX A: KEYBINDING REFERENCE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< TMUX PREFIX KEYS: LAYOUTS & PANE CONFIGS >>>${N}"
    print "  ${D}preconfigured pane arrangements. instant workspaces.${N}"
    print ""
    print "  ${B}${Y}ZPWR LAYOUT PRESETS:${N}"
    print "  ${C}prefix D${N}              ${D}control-window layout${N}"
    print "  ${C}prefix E${N}              ${D}four vertical panes${N}"
    print "  ${C}prefix F${N}              ${D}four panes layout${N}"
    print "  ${C}prefix G${N}              ${D}eight panes layout${N}"
    print "  ${C}prefix O${N}              ${D}sixteen panes layout${N}"
    print "  ${C}prefix R${N}              ${D}thirty-two panes REPL layout${N}"
    print "  ${C}prefix T${N}              ${D}config files layout${N}"
    print "  ${C}prefix M${N}              ${D}learn layout${N}"
    print ""
    print "  ${D}Each layout sources a conf file from \$ZPWR/tmux/:${N}"
    print "  ${D}  D -> control-window.conf${N}"
    print "  ${D}  E -> fourVertical.conf${N}"
    print "  ${D}  F -> four-panes.conf${N}"
    print "  ${D}  G -> eight-panes.conf${N}"
    print "  ${D}  O -> sixteen-panes.conf${N}"
    print "  ${D}  R -> thirtytwo-panes-repl.conf${N}"
    print "  ${D}  T -> config-files.conf${N}"
    print "  ${D}  M -> learn.conf${N}"
    print ""
    print "  ${B}${Y}SYNCHRONIZE & CUSTOMIZE:${N}"
    print "  ${C}prefix S${N}              ${D}toggle synchronize-panes (type in all)${N}"
    print "  ${C}prefix C${N}              ${D}customize-mode${N}"
    print ""
    print "  ${B}${Y}BUILT-IN LAYOUTS (Alt+number):${N}"
    print "  ${C}prefix Alt-1${N}          ${D}even-horizontal${N}"
    print "  ${C}prefix Alt-2${N}          ${D}even-vertical${N}"
    print "  ${C}prefix Alt-3${N}          ${D}main-horizontal${N}"
    print "  ${C}prefix Alt-4${N}          ${D}main-vertical${N}"
    print "  ${C}prefix Alt-5${N}          ${D}tiled${N}"
    print "  ${C}prefix Alt-6${N}          ${D}main-horizontal-mirrored${N}"
    print "  ${C}prefix Alt-7${N}          ${D}main-vertical-mirrored${N}"
    print ""
    print "  ${B}${Y}WINDOW ROTATION:${N}"
    print "  ${C}prefix Ctrl-o${N}         ${D}rotate window panes${N}"
    print "  ${C}prefix Alt-o${N}          ${D}rotate window panes (reverse)${N}"
    print ""
    print "  ${D}Synchronize-panes (prefix S) sends keystrokes to ALL panes.${N}"
    print "  ${D}Perfect for running the same command across many servers.${N}"
    print ""
    print "  ${M}  // sixteen panes is not chaos${N}"
    print "  ${M}  // sixteen panes is the wizard's dashboard${N}"
    print ""
}
