PAGE_TITLE="bat: Configuration & Tricks"
PAGE_CHAPTER="CHAPTER 35: BAT — CAT WITH WINGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== BAT: CONFIGURATION & TRICKS ===${N}"
    print "  ${D}// configure your cat. teach it new tricks. make it purr. //${N}"
    print "  ${B}${Y}BAT_THEME${N}"
    print "  ${M}  export BAT_THEME=\"Dracula\"${N}"
    print "  ${D}Set this in your env to change the default theme globally.${N}"
    print "  ${D}Popular themes: Dracula, Monokai Extended, Nord, OneHalfDark,${N}"
    print "  ${D}Solarized (Dark), TwoDark, ansi. Preview them all:${N}"
    print "  ${M}  bat --list-themes | fzf --preview='bat --theme={} src/main.rs'${N}"
    print "  ${B}${Y}STYLE COMPONENTS${N}"
    print "  ${M}  bat --style=numbers,changes,header${N}"
    print "  ${D}Components: full, auto, plain, numbers, changes, header,${N}"
    print "  ${D}header-filename, header-filesize, grid, rule, snip.${N}"
    print "  ${D}Combine with commas. 'full' enables everything.${N}"
    print "  ${D}'plain' disables everything — just colored text, no chrome.${N}"
    print "  ${B}${Y}BAT AS MANPAGE COLORIZER${N}"
    print "  ${M}  export MANPAGER=\"sh -c 'col -bx | bat -l man -p'\"${N}"
    print "  ${D}This makes every man page syntax-highlighted. The -l man forces${N}"
    print "  ${D}manpage language detection, -p is --plain (no line numbers${N}"
    print "  ${D}cluttering man output). col -bx strips backspace formatting.${N}"
    print "  ${B}${Y}SYNTAX CACHE${N}"
    print "  ${M}  bat cache --build${N}${D}    # rebuild syntax/theme cache${N}"
    print "  ${M}  bat cache --clear${N}${D}    # clear and rebuild from scratch${N}"
    print "  ${D}After adding custom .sublime-syntax files to${N}"
    print "  ${D}~/.config/bat/syntaxes/, rebuild the cache to pick them up.${N}"
    print "  ${B}${Y}DEBIAN/UBUNTU GOTCHA${N}"
    print "  ${D}On Debian-based systems, the binary is ${G}batcat${D} not ${G}bat${D}${N}"
    print "  ${D}due to a name conflict with an unrelated package. Fix:${N}"
    print "  ${M}  alias bat=batcat${N}${D}     # or symlink: ln -s batcat ~/.local/bin/bat${N}"
    print "  ${B}${Y}BAT + DELTA FOR GIT DIFFS${N}"
    print "  ${D}delta is a syntax-highlighting pager for git diffs. It uses${N}"
    print "  ${D}bat's syntax themes internally. Configure in .gitconfig:${N}"
    print "  ${M}  [core] pager = delta${N}"
    print "  ${M}  [delta] syntax-theme = Dracula${N}"
    print "  ${D}delta adds line numbers, side-by-side view, and word-level${N}"
    print "  ${D}diff highlighting. bat does files, delta does diffs.${N}"
    print "  ${B}${Y}BAT_PAGER${N}"
    print "  ${M}  export BAT_PAGER=\"less -RFX\"${N}"
    print "  ${D}Customize the pager bat uses. -R for color, -F to quit if one${N}"
    print "  ${D}screen, -X to not clear screen on exit. Or set to '' to disable${N}"
    print "  ${D}paging entirely — zpwr does this with --paging never.${N}"
}
