PAGE_TITLE="Environment & Search"
PAGE_CHAPTER="CHAPTER 8: ENVIRONMENT MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== ENVIRONMENT & SEARCH ===${N}"
    print "  ${D}// 22 verbs to inspect and search the shell //${N}"
    print ""
    print "  ${C}List env vars, search keybindings, inspect zsh internals,${N}"
    print "  ${C}and navigate the cached environment.${N}"
    print ""
    print "  ${B}${Y}ENVIRONMENT VARIABLES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr ev${N}${D}                    # list all zpwr env vars${N}"
    print "  ${M}  zpwr envvars${N}${D}               # list all zpwr env vars${N}"
    print "  ${M}  zpwr environmentvars${N}${D}       # list all zpwr env vars${N}"
    print "  ${M}  zpwr environmentvariables${N}${D}  # list all zpwr env vars${N}"
    print "  ${M}  zpwr envvarsall${N}${D}            # list all env vars${N}"
    print "  ${M}  zpwr environmentvarsall${N}${D}    # list all env vars${N}"
    print "  ${M}  zpwr eva${N}${D}                   # list all env vars${N}"
    print ""
    print "  ${B}${Y}ENVIRONMENT COUNTS & CACHE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr e${N}${D}                     # count all zpwr env${N}"
    print "  ${M}  zpwr envcounts${N}${D}             # count all zpwr env${N}"
    print "  ${M}  zpwr environmentcounts${N}${D}     # count all zpwr env${N}"
    print "  ${M}  zpwr envcachesearch${N}${D}        # fzf search cached aliases, params, builtins${N}"
    print "  ${M}  zpwr environmentcachesearch${N}${D}# fzf search cached env${N}"
    print "  ${M}  zpwr envaccept${N}${D}             # accept from fzf env${N}"
    print "  ${M}  zpwr envedit${N}${D}               # edit from fzf env${N}"
    print ""
    print "  ${B}${Y}KEYBINDING SEARCH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr allsearch${N}${D}             # search all keybindings${N}"
    print "  ${M}  zpwr vimsearch${N}${D}             # search vim keybindings${N}"
    print "  ${M}  zpwr zshsearch${N}${D}             # search zsh keybindings${N}"
    print ""
    print "  ${B}${Y}ZSH INTERNALS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr reload${N}${D}                # reparse env${N}"
    print "  ${M}  zpwr modules${N}${D}               # show zsh modules via fzf${N}"
    print "  ${M}  zpwr options${N}${D}               # show zsh options via fzf${N}"
    print "  ${M}  zpwr zstyle${N}${D}                # fuzzy search zstyle${N}"
    print "  ${M}  zpwr zcompdump${N}${D}             # edit zcompdump${N}"
    print ""
}
