PAGE_TITLE="Vim Config and Sessions"
PAGE_CHAPTER="CHAPTER 5: EDITOR MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== VIM CONFIG AND SESSIONS ===${N}"
    print ""
    print "  ${C}Configuration is not a one-time event.${N}"
    print "  ${C}It is a lifestyle. ZPWR gives you session commands${N}"
    print "  ${C}that open the right config files as a group.${N}"
    print ""
    print "  ${B}${Y}THE SESSION VERBS${N}"
    print "  ${C}Each of these opens a curated set of config files${N}"
    print "  ${C}in vim buffers, ready for synchronized editing:${N}"
    print ""
    print "  ${M}  zpwr vrc${N}${D}          # vim/nvim config session${N}"
    print "  ${D}  Opens your vimrc or init.vim along with related files.${N}"
    print "  ${D}  All your editor settings in one session.${N}"
    print ""
    print "  ${M}  zpwr brc${N}${D}          # shell aliases session${N}"
    print "  ${D}  Opens the tokens file and shell alias configs.${N}"
    print "  ${D}  Where you tune your personal shell experience.${N}"
    print ""
    print "  ${M}  zpwr zrc${N}${D}          # zshrc session${N}"
    print "  ${D}  Opens the zshrc and zsh init chain.${N}"
    print "  ${D}  The root of your shell's boot sequence.${N}"
    print ""
    print "  ${M}  zpwr trc${N}${D}          # tmux.conf session${N}"
    print "  ${D}  Opens tmux configuration files.${N}"
    print "  ${D}  Pane layouts, keybindings, status bar.${N}"
    print ""
    print "  ${B}${Y}CONFIG EDITING${N}"
    print "  ${M}  zpwr vimconfig${N}${D}    # edit all zpwr configs in vim${N}"
    print "  ${D}  Opens every zpwr configuration file. The master session.${N}"
    print "  ${D}  Use :bn and :bp to navigate between buffers.${N}"
    print ""
    print "  ${M}  zpwr vimtokens${N}${D}   # vim the .tokens.sh file${N}"
    print "  ${M}  zpwr tokens${N}${D}      # same thing${N}"
    print "  ${D}  Quick jump to your personal aliases and secrets file.${N}"
    print "  ${D}  This is the file that is gitignored. Your sanctuary.${N}"
    print ""
    print "  ${B}${Y}PLUGIN INVENTORY${N}"
    print "  ${M}  zpwr vimplugincount${N}${D}  # how many vim plugins installed${N}"
    print "  ${M}  zpwr vimpluginlist${N}${D}   # list all vim plugins${N}"
    print "  ${D}  Know thy plugins. Count them. Name them.${N}"
    print "  ${D}  If the count scares you, it should.${N}"
    print ""
    print "  ${B}${Y}TYPICAL CONFIG WORKFLOW${N}"
    print "  ${G}  # Add a new shell alias:${N}"
    print "  ${M}  zpwr brc${N}"
    print "  ${D}  # Edit .tokens.sh, add your alias, :wq${N}"
    print "  ${D}  # Source it or open a new terminal${N}"
    print ""
    print "  ${G}  # Tweak a vim keybinding:${N}"
    print "  ${M}  zpwr vrc${N}"
    print "  ${D}  # Navigate to the mapping, change it, :wq${N}"
    print ""
    print "  ${D}Three letters to open any config.${N}"
    print "  ${D}No file paths. No guessing. Just intent.${N}"
    print ""
}
