PAGE_TITLE="Hook Functions: precmd, preexec, chpwd"
PAGE_CHAPTER="CHAPTER 28: ZSH INTERNALS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== HOOK FUNCTIONS: precmd, preexec, chpwd ===${N}"
    print "  ${D}// zsh calls your code at key moments. event-driven shell. //${N}"
    print "  ${C}Zsh provides hook points where you can inject code that${N}"
    print "  ${C}runs automatically before prompts, before commands, and${N}"
    print "  ${C}when directories change. ZPWR uses all three.${N}"
    print "  ${B}${Y}precmd: BEFORE EACH PROMPT${N}"
    print "  ${D}Runs after a command finishes, right before the prompt draws.${N}"
    print "  ${D}p10k's _p9k_precmd is the main user -- it updates git status,${N}"
    print "  ${D}execution time, and every prompt segment.${N}"
    print "  ${D}ZPWR adds zpwrPrecmd to the hook:${N}"
    print "  ${M}  function zpwrPrecmd(){ export ZPWR_OPTS=\"\$-\" }${N}"
    print "  ${D}This captures the current shell options before each prompt.${N}"
    print "  ${B}${Y}preexec: BEFORE EACH COMMAND${N}"
    print "  ${D}Runs after Enter but BEFORE the command executes.${N}"
    print "  ${D}Receives the command string as \$1.${N}"
    print "  ${D}ZPWR's zpwrPreexec is minimal (a placeholder hook).${N}"
    print "  ${D}p10k uses preexec to record the start timestamp for${N}"
    print "  ${D}command_execution_time segment.${N}"
    print "  ${B}${Y}chpwd: WHEN DIRECTORY CHANGES${N}"
    print "  ${D}Runs whenever \$PWD changes (cd, pushd, popd, auto_cd).${N}"
    print "  ${D}ZPWR's zpwrChpwd hook handles directory-change actions.${N}"
    print "  ${B}${Y}THE _functions ARRAYS${N}"
    print "  ${D}Zsh supports multiple hooks via arrays:${N}"
    print "  ${M}  precmd_functions+=( myHook )${N}${D}      Add a precmd hook${N}"
    print "  ${M}  preexec_functions+=( myHook )${N}${D}     Add a preexec hook${N}"
    print "  ${M}  chpwd_functions+=( myHook )${N}${D}       Add a chpwd hook${N}"
    print "  ${D}Every function in the array runs at the hook point.${N}"
    print "  ${D}Order matters: first in array = first to execute.${N}"
    print "  ${B}${Y}HOW ZPWR REGISTERS HOOKS${N}"
    print "  ${D}zpwrBindPrecmd (runs during p10k atload):${N}"
    print "  ${M}  precmd_functions=( zpwrPrecmd \${(@)precmd_functions:#zpwrPrecmd} )${N}"
    print "  ${D}This puts zpwrPrecmd FIRST, removing any duplicate. The${N}"
    print "  ${D}\${(@)array:#pattern} syntax removes matching elements.${N}"
    print "  ${B}${Y}UNDER zshrs: async_precmd${N}"
    print "  ${D}zshrs adds an ${M}async_precmd${D} hook with no zsh equivalent. Its${N}"
    print "  ${D}functions run on the worker pool AFTER the prompt paints, so${N}"
    print "  ${D}they can never stall it. zshrs also builds the prompt with its${N}"
    print "  ${D}native p10k engine, not the theme's _p9k_precmd, so no precmd${N}"
    print "  ${D}hook holds prompt content, so they are safe to defer.${N}"
    print "  ${D}zpwrBindPrecmd leaves only zpwrPrecmdDrain on precmd_functions:${N}"
    print "  ${M}  async_precmd_functions=( \${(u)merged} )${N}"
    print "  ${M}  precmd_functions=( zpwrPrecmdDrain \$keep )${N}"
    print "  ${D}Running every prompt, it also catches hooks added later by${N}"
    print "  ${D}turbo-loaded plugins. Under stock zsh nothing moves.${N}"
    print "  ${D}Hooks whose result feeds the NEXT command, not the prompt,${N}"
    print "  ${D}stay synchronous -- list them in ${M}ZPWR_PRECMD_SYNC_HOOKS${D}:${N}"
    print "  ${M}  export ZPWR_PRECMD_SYNC_HOOKS=\"_jenv_export_hook\"${N}"
    print "  ${D}_jenv_export_hook sets JAVA_HOME from .java-version, so${N}"
    print "  ${D}deferring it would run the next command on the old JDK.${N}"
    print "  ${D}zpwrBindPreexecChpwd (runs during syntax-highlighting atload):${N}"
    print "  ${M}  preexec_functions=( \${(@)preexec_functions:#zpwrPreexec} zpwrPreexec )${N}"
    print "  ${M}  chpwd_functions=( \${(@)chpwd_functions:#zpwrChpwd} zpwrChpwd )${N}"
    print "  ${D}These put zpwr hooks LAST (after p10k and other plugins).${N}"
    print "  ${B}${Y}THE HOOK COUNT IN zpwr top${N}"
    print "  ${D}The ${M}zpwr top${D} dashboard shows the total hook count:${N}"
    print "  ${M}  nhooks=\$((${N}${M}\${#precmd_functions}+\${#async_precmd_functions}${N}"
    print "  ${M}           +\${#preexec_functions}+\${#chpwd_functions}))${N}"
    print "  ${D}Typical value: 5-8 hooks total across all four arrays.${N}"
    print "  ${D}If this number grows unexpectedly, a plugin is adding hooks${N}"
    print "  ${D}you may not want. Check with: ${M}print -l \$precmd_functions${N}"
}
