PAGE_TITLE="lsofrs: Network Intelligence"
PAGE_CHAPTER="CHAPTER 33: LSOFRS — ENHANCED LSOF"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== LSOFRS: NETWORK INTELLIGENCE ===${N}"
    print "  ${D}// every open file descriptor is a signal. lsofrs reads them all. //${N}"
    print "  ${C}lsofrs is a Rust-based enhanced lsof wrapper v4.7.0 by${N}"
    print "  ${C}MenkeTechnologies. It wraps the venerable lsof with colorized${N}"
    print "  ${C}output, structured formatting, and cyberpunk-grade aesthetics.${N}"
    print "  ${B}${Y}WHY NOT RAW LSOF?${N}"
    print "  ${D}Raw lsof dumps walls of monochrome text. lsofrs adds color${N}"
    print "  ${D}coding by type, structured columns, and filtering that doesn't${N}"
    print "  ${D}require piping through 5 layers of awk and grep.${N}"
    print "  ${B}${Y}SELECTION FLAGS${N}"
    print "  ${G}  lsofrs -i [ADDR]${N}${D}   # select internet connections${N}"
    print "  ${D}  ADDR format: ${M}[4|6][proto][@host|addr][:svc|port]${N}"
    print "  ${G}  lsofrs -c COMMAND${N}${D}   # select by command name (prefix match)${N}"
    print "  ${G}  lsofrs -p PID${N}${D}       # select by PID (comma-separated, ^excludes)${N}"
    print "  ${G}  lsofrs -u USER${N}${D}      # select by login name or UID${N}"
    print "  ${G}  lsofrs -d FD${N}${D}        # select by file descriptor set${N}"
    print "  ${G}  lsofrs -g [PGID]${N}${D}    # select by process group ID${N}"
    print "  ${G}  lsofrs -a${N}${D}           # AND selections (default is OR)${N}"
    print "  ${B}${Y}NETWORK FLAGS${N}"
    print "  ${G}  lsofrs -n${N}${D}           # inhibit hostname resolution (fast mode)${N}"
    print "  ${G}  lsofrs -P${N}${D}           # inhibit port-to-name conversion${N}"
    print "  ${G}  lsofrs -N${N}${D}           # select NFS files${N}"
    print "  ${G}  lsofrs -U${N}${D}           # select UNIX domain socket files${N}"
    print "  ${B}${Y}ZPWR INTEGRATION${N}"
    print "  ${D}The ${G}zpwr lsof${D} verb pipes lsof output through fzf for${N}"
    print "  ${D}interactive process selection and killing:${N}"
    print "  ${M}  zpwr lsof${N}${D}           # fzf over lsof, select PIDs to kill${N}"
    print "  ${M}  zpwr lsofedit${N}${D}       # same but edit the kill command first${N}"
    print "  ${D}The zpwrLsoffzf widget (bound to ${G}^F^H${D} in viins and vicmd)${N}"
    print "  ${D}runs ${M}sudo lsof -i | fzf -m${D}, extracts PIDs with awk,${N}"
    print "  ${D}and inserts them into your command line. Scan the local${N}"
    print "  ${D}network like a deck jockey, pick your targets with fzf.${N}"
    print "  ${B}${Y}FILES & DIRECTORIES${N}"
    print "  ${G}  lsofrs FILE...${N}${D}      # list processes using these files${N}"
    print "  ${G}  lsofrs --dir DIR${N}${D}    # open files in DIR (one level, like +d)${N}"
    print "  ${G}  lsofrs --dir-recurse DIR${N}${D} # recursive (like +D)${N}"
}
