PAGE_TITLE="Instant Prompt: Zero Latency"
PAGE_CHAPTER="CHAPTER 26: POWERLEVEL10K & INSTANT PROMPT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== INSTANT PROMPT: ZERO LATENCY ===${N}"
    print "  ${D}// your prompt loads before .zshrc finishes. time is a flat circle. //${N}"
    print "  ${C}The single best UX trick in zpwr: the prompt appears${N}"
    print "  ${C}INSTANTLY while .zshrc is still loading behind the curtain.${N}"
    print "  ${C}Zero perceived latency. The illusion of speed IS speed.${N}"
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${D}On previous shell exit, p10k cached the prompt to a file:${N}"
    print "  ${M}  \${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh${N}"
    print "  ${D}This file contains the last rendered prompt as raw ANSI escape${N}"
    print "  ${D}sequences. On next shell start, it is sourced BEFORE .zshrc loads.${N}"
    print "  ${D}Result: the prompt appears in <10ms. The user can start typing.${N}"
    print "  ${D}.zshrc continues loading in the background. Nobody notices.${N}"
    print "  ${B}${Y}THE LOADING SEQUENCE IN .zshrc${N}"
    print "  ${G}  1.${N} ${D}zmodload zsh/datetime (timestamp)${N}"
    print "  ${G}  2.${N} ${D}Source zpwr-hash-dirs.zsh (cached hash -d entries)${N}"
    print "  ${G}  3.${N} ${D}Source p10k-instant-prompt-*.zsh (the magic file)${N}"
    print "  ${G}  4.${N} ${D}promptTimestamp=\$EPOCHREALTIME (measure prompt time)${N}"
    print "  ${G}  5.${N} ${D}...rest of .zshrc loads (plugins, aliases, etc)...${N}"
    print "  ${G}  6.${N} ${D}p10k finalize (at very end of .zshrc)${N}"
    print "  ${D}Step 3 must come before ANY console output. If something${N}"
    print "  ${D}prints to stdout before the instant prompt, p10k aborts it.${N}"
    print "  ${B}${Y}THE HASH DIR CACHE${N}"
    print "  ${D}The prompt uses %~ to show named dirs like ~ZPWR instead of${N}"
    print "  ${D}/Users/you/.zpwr. But hash -d entries are set in zpwrBindDirs,${N}"
    print "  ${D}which runs AFTER instant prompt. Chicken-and-egg problem.${N}"
    print "  ${D}Solution: zpwrBindDirs writes a cache file:${N}"
    print "  ${M}  \$ZPWR_LOCAL/zpwr-hash-dirs.zsh${N}"
    print "  ${D}This cache is sourced at line 73 of .zshrc, BEFORE instant${N}"
    print "  ${D}prompt, so %~ resolves ~ZPWR in the cached prompt correctly.${N}"
    print "  ${B}${Y}ZPWR_BANNER_CLEARLIST SUPPRESSION${N}"
    print "  ${D}zpwrClearList prints a banner + file listing on login. But if${N}"
    print "  ${D}it runs before instant prompt finalizes, it corrupts the display.${N}"
    print "  ${D}Fix: the banner is deferred until AFTER p10k finalize:${N}"
    print "  ${M}  if [[ -n \"\$__p9k_instant_prompt_active\" && \"\$ZPWR_BANNER_CLEARLIST\" == true ]]; then${N}"
    print "  ${M}      zpwrClearList || true${N}"
    print "  ${M}  fi${N}"
    print "  ${B}${Y}THE promptTimestamp MEASUREMENT${N}"
    print "  ${D}ZPWR_VARS[promptTimeMs] records how fast the prompt appeared.${N}"
    print "  ${D}Run ${M}zpwr environmentcounts${D} to see it. With instant prompt,${N}"
    print "  ${D}this is typically 0.010-0.050 seconds. Without it, 0.5-2.0s.${N}"
    print "  ${B}${Y}p10k finalize${N}"
    print "  ${D}The last line of .zshrc:${N}"
    print "  ${M}  (( ! \${+functions[p10k]} )) || p10k finalize${N}"
    print "  ${D}This tells p10k that .zshrc is done. The real prompt replaces${N}"
    print "  ${D}the cached one. Any deferred output can now safely print.${N}"
}
