PAGE_TITLE="Expansion Stats Dashboard"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== EXPANSION STATS DASHBOARD ===${N}"
    print "  ${D}your aliases are working for you — here's the proof${N}"
    print ""
    print "  ${B}${Y}zpwrExpandStats${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Every time zsh-expand fires — alias, global alias, suffix${N}"
    print "  ${G}alias, self-ref escape, native glob/hist, or spelling${N}"
    print "  ${G}correction — it logs the event. zpwrExpandStats reads${N}"
    print "  ${G}that log and shows you a ranked dashboard.${N}"
    print ""
    print "  ${M}  zpwr expandstats${N}${D}            # show full dashboard${N}"
    print "  ${M}  zpwr expandstats -h${N}${D}         # help with all options${N}"
    print "  ${M}  zpwr expandstats -t 10${N}${D}      # top 10 aliases${N}"
    print "  ${M}  zpwr expandstats -w 80${N}${D}      # wider box (80 cols)${N}"
    print "  ${M}  zpwr expandstats -r${N}${D}         # reset all stats${N}"
    print "  ${M}  zpwr expandstats -f FILE${N}${D}    # custom stats file${N}"
    print ""
    print "  ${B}${Y}WHAT IT TRACKS${N}"
    print "  ${G}  By trigger${N}${D} ......... space expansions vs history expansions${N}"
    print "  ${G}  By type${N}${D} ............ alias, global, suffix, escape, native${N}"
    print "  ${G}  Corrections${N}${D} ........ spelling fixes applied${N}"
    print "  ${G}  Total expansions${N}${D} ... how many times the engine fired${N}"
    print "  ${G}  Keystrokes saved${N}${D} ... chars you didn't have to type${N}"
    print "  ${G}  Top aliases${N}${D} ........ ranked bar chart with expansions shown${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${C}The zsh-expand plugin hooks into the zle accept-line${N}"
    print "  ${C}widget. Before each command runs, it expands aliases,${N}"
    print "  ${C}globals, and suffixes inline. Each expansion is logged${N}"
    print "  ${C}to \$ZPWR_LOCAL/zpwr-expand-stats.dat with the trigger${N}"
    print "  ${C}type, expansion type, and original alias name.${N}"
    print ""
    print "  ${B}${Y}CONFIG${N}"
    print "  ${M}  ZPWR_EXPAND_STATS_FILE${N}${D}     # override stats file path${N}"
    print "  ${M}  ZPWR_EXPAND_STATS_TOP${N}${D}      # default top N (default: 20)${N}"
    print ""
    print "  ${D}Every alias that fires is a keystroke investment paying${N}"
    print "  ${D}dividends. This dashboard shows your ROI.${N}"
    print ""
}
