PAGE_TITLE="Verb Discovery"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> VERB DISCOVERY: FINDING WHAT'S POSSIBLE <<<${N}"
    print "  ${D}you can't use what you don't know exists${N}"
    print ""
    print "  ${B}${Y}zpwr subcommands${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}List all zpwr subcommands (verbs). The master index${N}"
    print "  ${G}of everything zpwr can do.${N}"
    print ""
    print "  ${C}  \$ zpwr subcommands${N}             ${D}# all subcommands${N}"
    print ""
    print "  ${B}${Y}zpwr subcommandscount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}How many subcommands exist? The number keeps growing.${N}"
    print ""
    print "  ${C}  \$ zpwr subcommandscount${N}        ${D}# total count${N}"
    print ""
    print "  ${B}${Y}zpwr verbs${N} ${D}(alias: subcommandsfzf)${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Browse subcommands interactively with fzf.${N}"
    print "  ${G}The best way to explore when you're not sure what to try.${N}"
    print ""
    print "  ${C}  \$ zpwr verbs${N}         ${D}# fzf subcommands${N}"
    print ""
    print "  ${B}${Y}zpwr verbslist / verbsfzf / verbscount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Alternative verb-centric views of available commands.${N}"
    print ""
    print "  ${C}  \$ zpwr verbslist${N}              ${D}# list all verbs${N}"
    print "  ${C}  \$ zpwr verbs${N}               ${D}# fzf browse verbs${N}"
    print "  ${C}  \$ zpwr verbscount${N}             ${D}# count verbs${N}"
    print ""
    print "  ${B}${Y}zpwr wizard / manual / tutorial / docs${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}You're reading it right now. The interactive encyclopedia${N}"
    print "  ${G}with vim-style navigation. Very meta. All four names work.${N}"
    print ""
    print "  ${C}  \$ zpwr wizard${N}                 ${D}# start the wizard${N}"
    print "  ${C}  \$ zpwr wizard --toc${N}           ${D}# table of contents${N}"
    print "  ${C}  \$ zpwr wizard --search docker${N}  ${D}# search pages${N}"
    print "  ${C}  \$ zpwr wizard 42${N}              ${D}# jump to page 42${N}"
    print ""
    print "  ${D}  // verbsfzf is the fastest way to discover (alias: subcommandsfzf)${N}"
    print "  ${D}  // type a few letters, fzf narrows it down${N}"
    print "  ${D}  // when in doubt, fzf it out${N}"
}
