PAGE_TITLE="Miscellaneous Arsenal"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== MISCELLANEOUS ARSENAL ===${N}"
    print "  ${D}// the verbs that defy categorization //${N}"
    print ""
    print "  ${C}Animation, backups, color tools, Docker, Exercism,${N}"
    print "  ${C}looping, testing, and everything else.${N}"
    print ""
    print "  ${B}${Y}TERMINAL & COLOR${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr animate${N}${D}               # run terminal animation${N}"
    print "  ${M}  zpwr alacritty${N}${D}             # edit alacritty config${N}"
    print "  ${M}  zpwr color2${N}${D}                # turn on stderr filter${N}"
    print "  ${M}  zpwr return2${N}${D}               # turn off stderr filter${N}"
    print "  ${M}  zpwr colorsdiff${N}${D}            # colorized side diff${N}"
    print "  ${M}  zpwr colortest${N}${D}             # test colors${N}"
    print "  ${M}  zpwr colortest256${N}${D}          # test 256 colors${N}"
    print "  ${M}  zpwr figletfonts${N}${D}           # show all figlet fonts${N}"
    print "  ${M}  zpwr pygmentcolors${N}${D}         # show all pygment colors${N}"
    print ""
    print "  ${B}${Y}BACKUP & HISTORY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr backup${N}${D}                # backup files${N}"
    print "  ${M}  zpwr backuphistory${N}${D}         # backup \$HISTFILE${N}"
    print "  ${M}  zpwr hist${N}${D}                  # exec history command via fzf${N}"
    print "  ${M}  zpwr histedit${N}${D}              # edit history command via fzf${N}"
    print "  ${M}  zpwr histfile${N}${D}              # edit history file${N}"
    print ""
    print "  ${B}${Y}FILE & DIR CREATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr makedir${N}${D}               # make a dir tree${N}"
    print "  ${M}  zpwr makefile${N}${D}              # make a dir tree with file at end${N}"
    print "  ${M}  zpwr scriptnew${N}${D}             # create new script without editor${N}"
    print "  ${M}  zpwr changename${N}${D}            # mv dir into namespace and sed sub${N}"
    print "  ${M}  zpwr changenamezpwr${N}${D}        # mv into zpwr namespace and sed sub${N}"
    print ""
    print "  ${B}${Y}DOCKER & GO${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr dfimage${N}${D}               # cat Dockerfile from IMAGE_ID${N}"
    print "  ${M}  zpwr dockerwipe${N}${D}            # wipe all docker images${N}"
    print "  ${M}  zpwr goclean${N}${D}               # clean Go package artifacts${N}"
    print ""
    print "  ${B}${Y}EXERCISM${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr exercism${N}${D}              # go to Exercism home page${N}"
    print "  ${M}  zpwr exercismedit${N}${D}          # edit file in \$HOME/Exercism${N}"
    print "  ${M}  zpwr exercismdownload${N}${D}      # download all for track${N}"
    print ""
    print "  ${B}${Y}LOOPING & BACKGROUND${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr background${N}${D}            # run arg in background${N}"
    print "  ${M}  zpwr for${N}${D}                   # run first arg times for command${N}"
    print "  ${M}  zpwr for10${N}${D}                 # run 10 times for command${N}"
    print "  ${M}  zpwr fordir${N}${D}                # run first arg in following dirs${N}"
    print "  ${M}  zpwr fordirupdate${N}${D}          # run git updaters in following dirs${N}"
    print "  ${M}  zpwr whiletrue${N}${D}             # run command forever${N}"
    print "  ${M}  zpwr whilesleep${N}${D}            # run command and sleep N seconds${N}"
    print ""
    print "  ${B}${Y}TESTING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr test${N}${D}                  # run all zpwr tests${N}"
    print "  ${M}  zpwr tests${N}${D}                 # run all zpwr tests${N}"
    print "  ${M}  zpwr testall${N}${D}               # run all env tests${N}"
    print "  ${M}  zpwr testsall${N}${D}              # run all env tests${N}"
    print ""
    print "  ${B}${Y}SYSTEM & MISC${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr curl${N}${D}                  # custom curl with cleaned output${N}"
    print "  ${M}  zpwr deduppaths${N}${D}            # deduplicate PATH fpath manpath${N}"
    print "  ${M}  zpwr edit${N}${D}                  # exec \$EDITOR${N}"
    print "  ${M}  zpwr editor${N}${D}                # exec \$EDITOR${N}"
    print "  ${M}  zpwr install${N}${D}               # run configure, make, make install${N}"
    print "  ${M}  zpwr loadjenv${N}${D}              # lazy load jenv${N}"
    print "  ${M}  zpwr prettyprint${N}${D}           # pretty print with color${N}"
    print "  ${M}  zpwr altprettyprint${N}${D}        # pretty with alternating color${N}"
    print "  ${M}  zpwr reset${N}${D}                 # reset repo to latest main${N}"
    print "  ${M}  zpwr reveal${N}${D}                # show remote repo in browser${N}"
    print "  ${M}  zpwr revealrecurse${N}${D}         # recursively reveal hidden dirs${N}"
    print "  ${M}  zpwr rmconfiglinks${N}${D}         # remove sym links to \$HOME${N}"
    print "  ${M}  zpwr startauto${N}${D}             # start autocomplete${N}"
    print "  ${M}  zpwr stopauto${N}${D}              # stop autocomplete${N}"
    print "  ${M}  zpwr start${N}${D}                 # start with no tabs${N}"
    print "  ${M}  zpwr starttabs${N}${D}             # start all tabs${N}"
    print "  ${M}  zpwr timer${N}${D}                 # timer one or more commands${N}"
    print "  ${M}  zpwr uninstall${N}${D}             # uninstall all zpwr configs${N}"
    print "  ${M}  zpwr post${N}${D}                  # postfix all output${N}"
    print "  ${M}  zpwr pre${N}${D}                   # prefix all output${N}"
    print "  ${M}  zpwr zpwrCloneToForked${N}${D}     # clone repo to \$ZPWR_FORKED_DIR${N}"
    print ""
    print "  ${B}${Y}SYSTEMD SERVICES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr serviceup${N}${D}             # start and enable systemd service${N}"
    print "  ${M}  zpwr servicedown${N}${D}           # stop and disable systemd service${N}"
    print "  ${M}  zpwr restart${N}${D}               # restart zpwr systemd service${N}"
    print ""
}
