PAGE_TITLE="Vim File Operations"
PAGE_CHAPTER="CHAPTER 5: EDITOR MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== VIM FILE OPERATIONS ===${N}"
    print ""
    print "  ${C}Opening vim is easy. Opening vim with the right files${N}"
    print "  ${C}already loaded? That is where zpwr earns its keep.${N}"
    print ""
    print "  ${B}${Y}THE BIG OPENS${N}"
    print "  ${M}  zpwr vimall${N}${D}             # load ALL zpwr files into arglist${N}"
    print "  ${D}  Every .zsh, .sh, .py, .pl file in the zpwr tree.${N}"
    print "  ${D}  Hundreds of files. Ready for :argdo mass operations.${N}"
    print "  ${D}  This is the tactical nuke of text editing.${N}"
    print ""
    print "  ${M}  zpwr vimalledit${N}${D}         # fzf pick 1+ configs to edit${N}"
    print "  ${D}  Like vimall but you choose which files to open.${N}"
    print "  ${D}  Surgical precision instead of carpet bombing.${N}"
    print ""
    print "  ${B}${Y}RECENT FILES${N}"
    print "  ${M}  zpwr vimrecent${N}${D}          # edit most recently opened files${N}"
    print "  ${D}  Pulls from vim's file history. Opens the files you${N}"
    print "  ${D}  were just working on. Resume where you left off.${N}"
    print ""
    print "  ${M}  zpwr vimrecentcd${N}${D}        # cd to dir + open recent files${N}"
    print "  ${D}  Same as vimrecent but also changes to the directory.${N}"
    print "  ${D}  Your shell and editor are now in the same place.${N}"
    print ""
    print "  ${M}  zpwr vimrecentsudo${N}${D}      # sudo edit recent files${N}"
    print "  ${D}  When you need root to edit those files.${N}"
    print ""
    print "  ${M}  zpwr vimrecentsudocd${N}${D}    # cd + sudo edit recent files${N}"
    print "  ${D}  The full combo: navigate, elevate, edit.${N}"
    print ""
    print "  ${B}${Y}ZPWR SUBSYSTEMS${N}"
    print "  ${M}  zpwr vimscripts${N}${D}         # load all zpwr scripts into arglist${N}"
    print "  ${M}  zpwr vimscriptedit${N}${D}      # pick and edit 1+ scripts${N}"
    print "  ${M}  zpwr vimautoload${N}${D}        # load all autoloads into arglist${N}"
    print "  ${M}  zpwr vimtests${N}${D}           # edit all zpwr test files${N}"
    print ""
    print "  ${B}${Y}VIM CD${N}"
    print "  ${M}  zpwr vimcd${N}${D}              # edit file, cd to its directory${N}"
    print "  ${D}  Opens a file in vim, and when you exit, your shell${N}"
    print "  ${D}  is cd'd to the directory containing that file.${N}"
    print "  ${D}  Edit something, then be where it lives. Elegant.${N}"
    print ""
    print "  ${B}${Y}WORKFLOW EXAMPLE${N}"
    print "  ${G}  # Resume yesterday's work:${N}"
    print "  ${M}  zpwr vimrecentcd${N}"
    print "  ${D}  # Opens recent files, lands you in the right dir${N}"
    print ""
    print "  ${G}  # Mass rename a function across all scripts:${N}"
    print "  ${M}  zpwr vimscripts${N}"
    print "  ${M}  :argdo %s/oldFunc/newFunc/g | update${N}"
    print "  ${D}  # Done. Every script updated.${N}"
    print ""
}
