PAGE_TITLE="Forgit Ignore & Clean"
PAGE_CHAPTER="CHAPTER 20: FORGIT DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< FORGIT IGNORE & CLEAN — .GITIGNORE MANAGEMENT >>>${N}"
    print "  ${D}because node_modules should never see the inside of a commit${N}"
    print ""
    print "  ${C}The .gitignore is your repo's bouncer list. These verbs${N}"
    print "  ${C}manage it with the precision of a nightclub velvet rope.${N}"
    print ""
    print "  ${B}${Y}FORGITIGNORE — THE IGNORE BROWSER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitignore${N}"
    print "  ${G}Interactive gitignore template browser powered by${N}"
    print "  ${G}gitignore.io. Search for languages, frameworks, IDEs.${N}"
    print "  ${G}Never hand-write a .gitignore again.${N}"
    print ""
    print "  ${B}${Y}THE IGNORE FAMILY:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  forgitignorelist${N}     ${D}list available gitignore templates${N}"
    print "  ${C}  forgitignoreget${N}      ${D}fetch a specific template by name${N}"
    print "  ${C}  forgitignoreupdate${N}   ${D}update your local template cache${N}"
    print "  ${C}  forgitignoreclean${N}    ${D}clean the template cache${N}"
    print ""
    print "  ${D}  Example: generate a Python + macOS gitignore${N}"
    print "  ${M}  zpwr forgitignoreget python,macos > .gitignore${N}"
    print ""
    print "  ${D}  Example: browse all available templates${N}"
    print "  ${M}  zpwr forgitignorelist${N}"
    print ""
    print "  ${B}${Y}FORGITCLEAN — THE UNTRACKED FILE PURGE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitclean${N}"
    print "  ${G}Shows untracked files in an fzf interface with previews.${N}"
    print "  ${G}Select which ones to delete. Surgical, not scorched earth.${N}"
    print "  ${G}Unlike ${Y}git clean -fd${G}, you see before you destroy.${N}"
    print ""
    print "  ${D}  The old way:${N}"
    print "  ${R}  git clean -fd${N}${D}    # delete everything. hope for the best.${N}"
    print ""
    print "  ${D}  The forgit way:${N}"
    print "  ${M}  zpwr forgitclean${N}${D}  # browse, select, confirm, then delete.${N}"
    print ""
    print "  ${B}${G}IGNORE WORKFLOW:${N}"
    print "  ${C}  1. ${M}zpwr forgitignorelist${C}    browse templates${N}"
    print "  ${C}  2. ${M}zpwr forgitignoreget${C}     fetch what you need${N}"
    print "  ${C}  3. ${M}zpwr forgitclean${C}         purge untracked cruft${N}"
    print "  ${C}  4. ${M}zpwr forgitadd${C}           stage the clean repo${N}"
    print ""
    print "  ${D}  // a clean repo is a happy repo${N}"
    print "  ${D}  // an ignored file is a file that cannot hurt you${N}"
    print "  ${D}  // let the templates do the thinking${N}"
    print ""
}
