PAGE_TITLE="zsh-sed-sub: Inline Search & Replace"
PAGE_CHAPTER="CHAPTER 27: ZINIT & PLUGIN SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== ZSH-SED-SUB: INLINE SEARCH & REPLACE ===${N}"
    print "  ${D}global search and replace on the current command line${N}"
    print ""
    print "  ${B}${Y}THE KEYBINDING${N}"
    print "  ${C}  Ctrl-F Ctrl-P${N}${D}   in both viins and vicmd modes${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${G}  1. Type a command on the line${N}"
    print "  ${G}  2. Hit Ctrl-F Ctrl-P${N}"
    print "  ${G}  3. Enter the search pattern${N}"
    print "  ${G}  4. Enter the replacement${N}"
    print "  ${G}  5. All occurrences on the line are replaced${N}"
    print ""
    print "  ${B}${Y}EXAMPLE${N}"
    print "  ${D}  You type:  ${M}cp file.txt /old/path/ && mv file.txt /old/path/bak${N}"
    print "  ${D}  Hit Ctrl-F Ctrl-P, search: ${M}old${D}, replace: ${M}new${N}"
    print "  ${D}  Result:   ${M}cp file.txt /new/path/ && mv file.txt /new/path/bak${N}"
    print ""
    print "  ${D}  Faster than arrow keys. Works on the entire line.${N}"
    print "  ${D}  Like sed but for your command line buffer.${N}"
    print ""
    print "  ${D}Plugin: ${C}MenkeTechnologies/zsh-sed-sub${N}"
    print ""
}
