PAGE_TITLE="fd: Integration with zpwr & fzf"
PAGE_CHAPTER="CHAPTER 36: FD-FIND — FIND REPLACEMENT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== FD: INTEGRATION WITH ZPWR & FZF ===${N}"
    print "  ${D}// fd feeds fzf. fzf feeds your brain. the pipeline of knowing. //${N}"
    print "  ${B}${Y}FZF_DEFAULT_COMMAND${N}"
    print "  ${D}zpwr sets FZF_DEFAULT_COMMAND to use find + ag by default:${N}"
    print "  ${M}  export FZF_DEFAULT_COMMAND='find * | ag -v \".git/\"'${N}"
    print "  ${D}You can override this with fd for faster results:${N}"
    print "  ${M}  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'${N}"
    print "  ${D}fd is faster because it parallelizes traversal and skips${N}"
    print "  ${D}.gitignore entries without needing ag to filter them out.${N}"
    print "  ${B}${Y}FD + FZF PATTERNS${N}"
    print "  ${M}  fd -e zsh | fzf${N}${D}                 # fuzzy find zsh files${N}"
    print "  ${M}  fd -t f | fzf --preview 'bat {}'${N}${D}  # find + preview${N}"
    print "  ${M}  vim \$(fd -t f | fzf)${N}${D}             # find, select, edit${N}"
    print "  ${D}This three-tool combo (fd + fzf + bat) is the holy trinity${N}"
    print "  ${D}of file navigation. fd finds, fzf filters, bat previews.${N}"
    print "  ${B}${Y}TEMPORAL & SIZE FILTERS${N}"
    print "  ${G}  fd --changed-within 1d${N}${D}  # modified in last 24 hours${N}"
    print "  ${G}  fd --changed-before 1w${N}${D}  # modified more than a week ago${N}"
    print "  ${G}  fd --size +1m${N}${D}           # files larger than 1 megabyte${N}"
    print "  ${G}  fd --size -10k${N}${D}          # files smaller than 10 kilobytes${N}"
    print "  ${D}Units: b (bytes), k (kilobytes), m (megabytes), g (gigabytes).${N}"
    print "  ${D}Time: s (seconds), m (minutes), h (hours), d (days), w (weeks).${N}"
    print "  ${B}${Y}FD + BAT${N}"
    print "  ${M}  fd -e rs --exec bat{}${N}${D}   # colorized find results${N}"
    print "  ${M}  fd -e md -X bat${N}${D}          # cat all markdown files at once${N}"
    print "  ${B}${Y}FD vs FIND vs LOCATE${N}"
    print "  ${D}${G}find${D}   — universal. every Unix has it. slow on large trees.${N}"
    print "  ${D}         supports -exec, -newer, -perm, -prune. the Swiss Army.${N}"
    print "  ${D}${G}fd${D}     — fast parallel traversal, sane defaults, .gitignore${N}"
    print "  ${D}         aware. best for daily use in code repositories.${N}"
    print "  ${D}${G}locate${D} — instant results from a pre-built database (updatedb).${N}"
    print "  ${D}         stale until the next cron run. no real-time accuracy.${N}"
    print "  ${B}${Y}DEPTH & EXCLUSION${N}"
    print "  ${G}  fd -d 3${N}${D}              # max depth of 3 levels${N}"
    print "  ${G}  fd -E node_modules${N}${D}   # exclude a directory by name${N}"
    print "  ${G}  fd -E '*.min.js'${N}${D}     # exclude by glob pattern${N}"
    print "  ${D}Stack -E flags to build precise exclusion lists on the fly.${N}"
}
