PAGE_TITLE="The ARB Dimension"
PAGE_CHAPTER="CHAPTER 4: THE SEARCH ENGINE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE ARB DIMENSION ===${N}"
    print ""
    print "  ${C}ARB is the nervous system of zpwr.${N}"
    print "  ${C}It is wired into search, selection, navigation,${N}"
    print "  ${C}git, vim, environment browsing, and verb dispatch.${N}"
    print "  ${C}If zpwr has a UI, arb --fzf IS that UI.${N}"
    print ""
    print "  ${B}${Y}VERB DISCOVERY${N}"
    print "  ${M}  zpwr verbs${N}${D}     # fuzzy search all zpwr verbs${N}"
    print "  ${D}  Every verb, every description, in one arb --fzf window.${N}"
    print "  ${D}  This is the god-mode cheat sheet. Learn it first.${N}"
    print ""
    print "  ${B}${Y}ENVIRONMENT BROWSING${N}"
    print "  ${M}  zpwr envaccept${N}${D}          # accept from arb --fzf env${N}"
    print "  ${D}  Browse all shell environment entries (aliases, functions,${N}"
    print "  ${D}  parameters, builtins) in arb --fzf. Select one, accept it${N}"
    print "  ${D}  onto the command line.${N}"
    print ""
    print "  ${M}  zpwr envedit${N}${D}            # edit from arb --fzf env${N}"
    print "  ${D}  Same browsing but puts the result on \$BUFFER for editing.${N}"
    print ""
    print "  ${M}  zpwr envcachesearch${N}${D}     # search cached aliases, functions, etc.${N}"
    print "  ${D}  Searches the pre-built cache of your entire environment.${N}"
    print "  ${D}  Faster than envedit because it uses the cache file.${N}"
    print ""
    print "  ${B}${Y}ARB PATTERNS ACROSS ZPWR${N}"
    print "  ${C}ARB appears in dozens of verbs. The pattern is always:${N}"
    print "  ${D}  1. A data source generates lines (files, commits, dirs)${N}"
    print "  ${D}  2. Lines pipe into arb --fzf with a preview command${N}"
    print "  ${D}  3. You fuzzy-filter, select, and take an action${N}"
    print ""
    print "  ${G}  Verbs with arb --fzf built in:${N}"
    print "  ${D}    ${M}filesearch${D}     file list -> arb --fzf -> open${N}"
    print "  ${D}    ${M}wordsearch${D}     grep results -> arb --fzf -> open${N}"
    print "  ${D}    ${M}dirsearch${D}      dir list -> arb --fzf -> cd${N}"
    print "  ${D}    ${M}gitcommits${D}     git log -> arb --fzf -> show diff${N}"
    print "  ${D}    ${M}forgitadd${D}      unstaged files -> arb --fzf -> stage${N}"
    print "  ${D}    ${M}forgitlog${D}      commit log -> arb --fzf -> preview${N}"
    print "  ${D}    ${M}zcd${D}            z database -> arb --fzf -> cd${N}"
    print "  ${D}    ${M}subcommandsfzf${D} all verbs -> arb --fzf -> execute${N}"
    print ""
    print "  ${B}${Y}THE ARB KEYBINDINGS${N}"
    print "  ${M}  zpwr vimsearch${N}${D}          # search vim keybindings in arb --fzf${N}"
    print "  ${M}  zpwr allsearch${N}${D}          # search ALL keybindings in arb --fzf${N}"
    print "  ${D}  When you want to find a keybinding but do not remember${N}"
    print "  ${D}  where it is defined. Search them all.${N}"
    print ""
    print "  ${D}ARB is not optional in zpwr. It is the interface.${N}"
    print "  ${D}Master arb --fzf and you master zpwr.${N}"
    print ""
}
