PAGE_TITLE="Forgit Add & Diff"
PAGE_CHAPTER="CHAPTER 20: FORGIT DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< FORGIT ADD & DIFF — INTERACTIVE STAGING >>>${N}"
    print "  ${D}git add, but make it beautiful${N}"
    print ""
    print "  ${C}forgit is the fusion of fzf and git. It wraps the most${N}"
    print "  ${C}common git operations in fuzzy, interactive, preview-enabled${N}"
    print "  ${C}interfaces. You will never go back to raw git add.${N}"
    print ""
    print "  ${B}${Y}FORGITADD — INTERACTIVE STAGING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitadd${N}"
    print "  ${G}Opens an fzf interface showing all unstaged changes.${N}"
    print "  ${G}Each file gets a diff preview in the right pane.${N}"
    print "  ${G}Tab to select multiple files. Enter to stage them.${N}"
    print ""
    print "  ${D}  The workflow:${N}"
    print "  ${C}  1. Run ${M}zpwr forgitadd${N}"
    print "  ${C}  2. Browse files with arrow keys${N}"
    print "  ${C}  3. See the diff preview for each file${N}"
    print "  ${C}  4. Tab to multi-select${N}"
    print "  ${C}  5. Enter to stage selected files${N}"
    print ""
    print "  ${D}  No more ${R}git add -p${D} scrolling through 500-line diffs.${N}"
    print "  ${D}  No more accidentally staging that debug print.${N}"
    print ""
    print "  ${B}${Y}FORGITDIFF — VISUAL DIFF BROWSER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitdiff${N}"
    print "  ${G}Opens an fzf browser of all changed files with${N}"
    print "  ${G}a live diff preview. Read diffs without committing${N}"
    print "  ${G}to anything. Pure reconnaissance.${N}"
    print ""
    print "  ${D}  Example workflow:${N}"
    print "  ${M}  zpwr forgitdiff${N}${D}           # browse all diffs visually${N}"
    print "  ${M}  zpwr forgitadd${N}${D}            # stage what you want${N}"
    print "  ${M}  zpwr gitcommit 'msg'${N}${D}      # commit with message${N}"
    print ""
    print "  ${B}${G}WHY FORGIT > RAW GIT:${N}"
    print "  ${C}  Raw git add:${N}     ${D}type filenames from memory like a caveman${N}"
    print "  ${C}  forgitadd:${N}       ${D}browse, preview, multi-select, confirm${N}"
    print "  ${C}  Raw git diff:${N}    ${D}wall of text scrolling past${N}"
    print "  ${C}  forgitdiff:${N}      ${D}file-by-file preview with fuzzy search${N}"
    print ""
    print "  ${D}  // staging should not be a memory test${N}"
    print "  ${D}  // it should be a visual, interactive experience${N}"
    print "  ${D}  // forgit turns git into a GUI without leaving the terminal${N}"
    print ""
}
