PAGE_TITLE="Command Resolver"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== COMMAND RESOLVER ===${N}"
    print "  ${D}// what IS that command, really? //${N}"
    print ""
    print "  ${C}zpwr resolve traces a command through its full resolution${N}"
    print "  ${C}chain. Unlike 'which' or 'type', it follows the entire path${N}"
    print "  ${C}from alias to function to builtin to binary.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr resolve ll${N}${D}               # where does ll go?${N}"
    print "  ${M}  zpwr resolve ls cd git${N}${D}        # trace multiple commands${N}"
    print "  ${M}  zpwr resolve -a grep${N}${D}          # show all type -a matches${N}"
    print "  ${M}  zpwr which vim${N}${D}                # alias for resolve${N}"
    print ""
    print "  ${B}${Y}WHAT IT SHOWS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${Y}  Aliases${N}${D}          expansion, then resolves first word${N}"
    print "  ${M}  Functions${N}${D}        source file path, line count, verb mapping${N}"
    print "  ${G}  Builtins${N}${D}         identified as builtin or reserved word${N}"
    print "  ${C}  Binaries${N}${D}         full path, symlink chain, file type${N}"
    print "  ${Y}  Global aliases${N}${D}   detected and shown${N}"
    print "  ${Y}  Suffix aliases${N}${D}   detected and shown${N}"
    print ""
    print "  ${B}${Y}WHY NOT JUST 'which'?${N}"
    print "  ${D}  'which' shows one answer. 'type -a' shows all candidates.${N}"
    print "  ${D}  Neither follows the chain. If 'll' is an alias for 'eza'${N}"
    print "  ${D}  and 'eza' is a symlink to '../Cellar/eza/0.18/bin/eza',${N}"
    print "  ${D}  resolve shows the entire path from ll to the Mach-O binary.${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr exists${N}${D}                # check if identifier is valid${N}"
    print "  ${M}  zpwr deps${N}${D}                  # function dependency graph${N}"
    print "  ${M}  zpwr funcrank${N}${D}              # rank functions by usage${N}"
    print ""
}
