PAGE_TITLE="File & Process Operations"
PAGE_CHAPTER="CHAPTER 12: UTILITY ARSENAL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FILE & PROCESS OPERATIONS ===${N}"
    print "  ${D}// the everyday tools. sharpened and color-coded. //${N}"
    print ""
    print "  ${C}zpwr wraps common file and process operations with${N}"
    print "  ${C}enhanced output, color, and fzf integration. These are${N}"
    print "  ${C}the verbs you reach for twenty times a day.${N}"
    print ""
    print "  ${B}${Y}FILE LISTING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr clearlist${N}${D}                      # clear screen + list files${N}"
    print "  ${M}  zpwr clearls${N}${D}                        # alias for clearlist${N}"
    print "  ${M}  zpwr info${N}${D}                           # alias for clearlist${N}"
    print "  ${M}  zpwr list${N}${D}                           # list files (no clear)${N}"
    print "  ${M}  zpwr ls${N}${D}                             # alias for list${N}"
    print ""
    print "  ${D}  clearlist is the most-used verb after help. It clears${N}"
    print "  ${D}  the terminal and shows a fresh directory listing.${N}"
    print "  ${D}  Uses eza if available, falls back to ls.${N}"
    print ""
    print "  ${B}${Y}FILE VIEWING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cat <file>${N}${D}                     # colorized cat${N}"
    print "  ${M}  zpwr c <file>${N}${D}                       # shortest form${N}"
    print "  ${M}  zpwr catcd <dir>${N}${D}                    # cat files in a directory${N}"
    print ""
    print "  ${D}  cat/c uses bat or pygmentize for syntax highlighting${N}"
    print "  ${D}  when available. Plain cat as fallback. catcd lists the${N}"
    print "  ${D}  contents of each file in a directory.${N}"
    print ""
    print "  ${B}${Y}PROCESS MANAGEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr ps${N}${D}                             # enhanced process listing${N}"
    print "  ${M}  zpwr kill${N}${D}                           # fzf-powered process kill${N}"
    print "  ${M}  zpwr killedit${N}${D}                       # kill then edit related file${N}"
    print ""
    print "  ${D}  ${M}zpwr kill${D} is the crown jewel here. It pipes process${N}"
    print "  ${D}  listings through fzf, letting you fuzzy-search for the${N}"
    print "  ${D}  process you want to terminate. Select it, confirm, dead.${N}"
    print "  ${D}  No more guessing PIDs.${N}"
    print ""
    print "  ${B}${Y}FILE DESCRIPTORS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr lsof${N}${D}                           # list open files (enhanced)${N}"
    print "  ${M}  zpwr lsofedit${N}${D}                       # lsof then edit result${N}"
    print ""
    print "  ${D}  zpwr lsof wraps lsof with fzf filtering.${N}"
    print "  ${D}  Useful when tracking down which process holds a file${N}"
    print "  ${D}  or which files a process has open.${N}"
    print ""
    print "  ${B}${Y}FILE OPENING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr open${N}${D}                           # open file/dir with system${N}"
    print ""
    print "  ${D}  Opens the target with the system handler: Finder on macOS,${N}"
    print "  ${D}  xdg-open on Linux. Works with files, directories, URLs.${N}"
    print ""
    print "  ${B}${Y}THE COMBO MOVES${N}"
    print "  ${D}  Clear terminal, list files, check what is running:${N}"
    print "  ${M}  zpwr clearlist && zpwr ps${N}"
    print ""
    print "  ${D}  Find and kill a zombie process:${N}"
    print "  ${M}  zpwr kill${N}${D}     # fzf search -> select -> terminate${N}"
    print ""
    print "  ${D}  Find what is holding a port:${N}"
    print "  ${M}  zpwr lsof${N}${D}     # fzf through open files and ports${N}"
    print ""
}
