PAGE_TITLE="Clone & GitHub Workflow"
PAGE_CHAPTER="CHAPTER 15: NETWORK & CONTAINERS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> CLONE & GITHUB: THE FULL GIT WORKFLOW <<<${N}"
    print "  ${D}git clone is just the beginning of the relationship${N}"
    print ""
    print "  ${B}${Y}zpwr clone${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Clone a git repository with ZPWR's enhanced setup.${N}"
    print "  ${G}Handles auth, directory placement, and post-clone hooks.${N}"
    print ""
    print "  ${C}  \$ zpwr clone user/repo${N}         ${D}# clone from GitHub${N}"
    print "  ${C}  \$ zpwr clone https://...${N}       ${D}# clone any URL${N}"
    print ""
    print "  ${B}${Y}zpwr reveal${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open the current git repo's GitHub page in browser.${N}"
    print "  ${G}Instant context switch from terminal to web.${N}"
    print ""
    print "  ${C}  \$ zpwr reveal${N}                 ${D}# open repo in browser${N}"
    print ""
    print "  ${B}${Y}zpwr revealrecurse${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open GitHub pages for the repo AND its submodules.${N}"
    print "  ${G}When you need the full picture of a multi-repo project.${N}"
    print ""
    print "  ${C}  \$ zpwr revealrecurse${N}          ${D}# open all repos${N}"
    print ""
    print "  ${B}${Y}THE GITHUB WORKFLOW:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. \$ zpwr clone user/repo       # get the code${N}"
    print "  ${D}  2. \$ cd repo && hack hack hack${N}"
    print "  ${D}  3. \$ zpwr reveal                # check CI/issues${N}"
    print "  ${D}  4. \$ git push                   # ship it${N}"
    print ""
    print "  ${B}${Y}RELATED TOOLS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ zpwr killremote${N}             ${D}# kill remote sessions${N}"
    print ""
    print "  ${G}killremote terminates remote SSH/tmux sessions that${N}"
    print "  ${G}have gone stale. Cleanup for the disciplined operator.${N}"
    print ""
    print "  ${D}  // reveal is the bridge between terminal and browser${N}"
    print "  ${D}  // faster than typing github.com/user/repo${N}"
    print "  ${D}  // your fingers will thank you${N}"
}
