PAGE_TITLE="Logging System"
PAGE_CHAPTER="CHAPTER 16: THE LOGGING SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== LOGGING SYSTEM ===${N}"
    print "  ${D}// 12 verbs for structured observability //${N}"
    print ""
    print "  ${C}ZPWR has a four-level logging system: trace, debug,${N}"
    print "  ${C}info, error. Each level writes to file or console.${N}"
    print ""
    print "  ${B}${Y}LOG TO FILE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr logtrace${N}${D}              # log trace to \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr logdebug${N}${D}              # log debug to \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr loginfo${N}${D}               # log info to \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr logerror${N}${D}              # log error to \$ZPWR_LOGFILE${N}"
    print ""
    print "  ${B}${Y}LOG TO CONSOLE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr logtraceconsole${N}${D}       # log trace to console${N}"
    print "  ${M}  zpwr logdebugconsole${N}${D}       # log debug to console${N}"
    print "  ${M}  zpwr loginfoconsole${N}${D}        # log info to console${N}"
    print "  ${M}  zpwr logerrorconsole${N}${D}       # log error to console${N}"
    print ""
    print "  ${B}${Y}LOG MANAGEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr taillog${N}${D}               # colorized tail of \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr logs${N}${D}                  # colorized tail of \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr cleanlog${N}${D}              # clear \$ZPWR_LOGFILE${N}"
    print "  ${M}  zpwr logincount${N}${D}            # count of logins by user${N}"
    print ""
    print "  ${D}  Log levels from most verbose to least:${N}"
    print "  ${G}  TRACE${N} ${D}>${N} ${C}  DEBUG${N} ${D}>${N} ${Y}  INFO${N} ${D}>${N} ${R}  ERROR${N}"
    print ""
}
