PAGE_TITLE="Vim-Tmux Code Execution"
PAGE_CHAPTER="CHAPTER 30: TMUX DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== VIM-TMUX CODE EXECUTION ===${N}"
    print "  ${D}// select code in vim. execute in the pane next door. magic. //${N}"
    print "  ${C}The killer feature of the ZPWR vim+tmux integration:${N}"
    print "  ${C}write code in vim, send it to an adjacent tmux pane for${N}"
    print "  ${C}execution. No copy-paste. No switching windows.${N}"
    print "  ${B}${Y}THE TmuxRepeat FUNCTION${N}"
    print "  ${D}Defined in .vimrc, TmuxRepeat has three modes:${N}"
    print "  ${G}  'file'${N}${D}    Save the file, execute it in the right pane${N}"
    print "  ${G}  'visual'${N}${D}  Save visual selection to temp file, execute it${N}"
    print "  ${G}  'repl'${N}${D}    Paste visual selection directly into right pane${N}"
    print "  ${B}${Y}SUPPORTED LANGUAGES${N}"
    print "  ${D}TmuxRepeat detects file type by extension:${N}"
    print "  ${M}  sh, zsh, py, rb, pl, clj, tcl, vim, lisp, hs, ml,${N}"
    print "  ${M}  coffee, swift, lua, java, f90, cr${N}"
    print "  ${D}For known types, it sends the file to zpwrRunner.sh which${N}"
    print "  ${D}dispatches to the correct interpreter. For unknown types,${N}"
    print "  ${D}it falls back to TmuxRepeatGeneric (re-run previous command).${N}"
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${D}1. ${M}Ctrl-V${D} in normal/insert mode (or ${M}leader-vj${D}):${N}"
    print "  ${D}   Saves the file, then sends:${N}"
    print "  ${M}   tmux send-keys -t right 'bash \"\$ZPWR_SCRIPTS/zpwrRunner.sh\" \"file\"' C-m${N}"
    print "  ${D}2. ${M}leader-vk${D} in visual mode:${N}"
    print "  ${D}   Yanks selection to temp file \$ZPWR_HIDDEN_DIR_TEMP/.vimTempFile.<ext>,${N}"
    print "  ${D}   then sends that temp file to the right pane for execution.${N}"
    print "  ${D}3. ${M}leader-vl${D} in visual mode (REPL mode):${N}"
    print "  ${D}   Yanks selection, loads it into tmux buffer 'buffer0099',${N}"
    print "  ${D}   then pastes directly into the right pane. For REPLs like${N}"
    print "  ${D}   python, irb, node -- code runs line-by-line in the REPL.${N}"
    print "  ${B}${Y}THE PANE TARGETING${N}"
    print "  ${D}  Standard tmux: sends to pane named 'right' (the next pane).${N}"
    print "  ${D}  MacVim/GUI: sends to session 'vimmers:0.' (external tmux).${N}"
    print "  ${D}  The pane_count check ensures a target pane exists.${N}"
    print "  ${B}${Y}allPanes.zsh: BROADCAST TO ALL PANES${N}"
    print "  ${D}\$ZPWR_SCRIPTS/allPanes.zsh sends commands to all tmux panes:${N}"
    print "  ${M}  prefix + Space${N}${D}   Run command in all panes (single mode)${N}"
    print "  ${M}  prefix + v${N}${D}       Run command in all panes (multi mode)${N}"
    print "  ${M}  prefix + b${N}${D}       Open URL in all panes${N}"
    print "  ${B}${Y}SYNCHRONIZE-PANES${N}"
    print "  ${D}  ${M}prefix + S${N}${D}   Toggle synchronize-panes${N}"
    print "  ${D}When enabled, every keystroke goes to ALL panes in the window.${N}"
    print "  ${D}Useful for running identical commands on multiple servers,${N}"
    print "  ${D}or setting up parallel environments simultaneously.${N}"
    print "  ${B}${Y}GOOGLE FROM TMUX${N}"
    print "  ${D}  ${M}prefix + g${N}${D}   Google search from tmux${N}"
    print "  ${D}Runs \$ZPWR_TMUX/google.sh with the current pane content.${N}"
    print "  ${D}Select text, press prefix+g, and your browser opens${N}"
    print "  ${D}with a Google search for the selection.${N}"
}
