PAGE_TITLE="Vim Integration"
PAGE_CHAPTER="CHAPTER 5: EDITOR MASTERY"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== VIM INTEGRATION ===${N}"
    print "  ${D}// 35 verbs for the vim faithful //${N}"
    print ""
    print "  ${C}The vim verb family mirrors emacs with full parity.${N}"
    print "  ${C}Open, edit, search, navigate — all wired to vim/nvim.${N}"
    print ""
    print "  ${B}${Y}OPEN & EDIT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr vimall${N}${D}               # vim all zpwr files for :argdo${N}"
    print "  ${M}  zpwr vimalledit${N}${D}            # vim edit 1 or more configs${N}"
    print "  ${M}  zpwr vimautoload${N}${D}           # vim all autoloads :argdo${N}"
    print "  ${M}  zpwr vimscripts${N}${D}            # vim all zpwr scripts for :argdo${N}"
    print "  ${M}  zpwr vimscriptedit${N}${D}         # vim edit 1 or more scripts${N}"
    print ""
    print "  ${B}${Y}CONFIG & TOKENS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr vimconfig${N}${D}             # edit all zpwr configs${N}"
    print "  ${M}  zpwr vimemacsconfig${N}${D}        # vim edit emacs zpwr configs${N}"
    print "  ${M}  zpwr vimtokens${N}${D}             # vim the .tokens.sh file${N}"
    print "  ${M}  zpwr vimtests${N}${D}              # edit all zpwr tests${N}"
    print "  ${M}  zpwr vrc${N}${D}                   # vimrc vim session${N}"
    print "  ${M}  zpwr brc${N}${D}                   # shell aliases file vim session${N}"
    print "  ${M}  zpwr trc${N}${D}                   # tmux.conf vim session${N}"
    print "  ${M}  zpwr zrc${N}${D}                   # zshrc vim session${N}"
    print "  ${M}  zpwr tokens${N}${D}                # vim the .tokens.sh file${N}"
    print ""
    print "  ${B}${Y}NAVIGATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr vimcd${N}${D}                 # vim edit and cd to first dir${N}"
    print "  ${M}  zpwr vimrecent${N}${D}             # vim edit most recent editor files${N}"
    print "  ${M}  zpwr vimrecentcd${N}${D}           # cd and vim edit most recent files${N}"
    print "  ${M}  zpwr vimrecentsudo${N}${D}         # sudo vim edit most recent files${N}"
    print "  ${M}  zpwr vimrecentsudocd${N}${D}       # cd and sudo vim most recent files${N}"
    print ""
    print "  ${B}${Y}SEARCH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr vimsearch${N}${D}             # search vim keybindings${N}"
    print "  ${M}  zpwr vimfilesearch${N}${D}         # vim a file in a sub dir${N}"
    print "  ${M}  zpwr vimfilesearchedit${N}${D}     # edit vim a file in a sub dir${N}"
    print "  ${M}  zpwr vimfindsearch${N}${D}         # vim accept find drive for file${N}"
    print "  ${M}  zpwr vimfindsearchedit${N}${D}     # vim edit find drive for file${N}"
    print "  ${M}  zpwr vimlocatesearch${N}${D}       # vim accept locate drive for file${N}"
    print "  ${M}  zpwr vimlocatesearchedit${N}${D}   # vim edit locate drive for file${N}"
    print "  ${M}  zpwr vimwordsearch${N}${D}         # vim a file in a sub dir by word${N}"
    print "  ${M}  zpwr vimwordsearchedit${N}${D}     # edit vim a file by word${N}"
    print ""
    print "  ${B}${Y}TAGS, PLUGINS & VIMINFO${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr vimctags${N}${D}              # vim zpwr ctags tags${N}"
    print "  ${M}  zpwr vimgtags${N}${D}              # vim zpwr GNU global tags${N}"
    print "  ${M}  zpwr vimgtagsedit${N}${D}          # vim edit zpwr GNU global tags${N}"
    print "  ${M}  zpwr vimplugincount${N}${D}        # total number of vim plugins${N}"
    print "  ${M}  zpwr vimpluginlist${N}${D}         # total list of vim plugins${N}"
    print "  ${M}  zpwr catviminfo${N}${D}            # cat custom vim info file${N}"
    print "  ${M}  zpwr catrecentfviminfo${N}${D}     # cat recentf then custom vim info${N}"
    print "  ${M}  zpwr catnviminforecentf${N}${D}    # cat custom vim info then recentf${N}"
    print ""
}
