PAGE_TITLE="The Anatomy of a Verb"
PAGE_CHAPTER="CHAPTER 1: THE RED PILL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE ANATOMY OF A VERB ===${N}"
    print ""
    print "  ${C}Every zpwr command follows one sacred pattern:${N}"
    print "  ${B}${G}  zpwr <verb> [args...]${N}"
    print ""
    print "  ${B}${Y}HOW DISPATCH WORKS${N}"
    print "  ${C}When you type ${M}zpwr filesearch${C}, here is what happens:${N}"
    print "  ${D}  1. The zpwr function receives \"filesearch\" as \$1${N}"
    print "  ${D}  2. It looks up ZPWR_VERBS[filesearch] in the verb table${N}"
    print "  ${D}  3. The table entry maps to a function or alias${N}"
    print "  ${D}  4. That function is invoked with any remaining args${N}"
    print ""
    print "  ${B}${Y}THE VERB TABLE${N}"
    print "  ${G}The associative array ${M}ZPWR_VERBS${G} is the brain.${N}"
    print "  ${G}Each entry has the format:${N}"
    print "  ${M}  ZPWR_VERBS[verb]='function_or_alias=description'${N}"
    print ""
    print "  ${B}${Y}MANY NAMES, ONE FUNCTION${N}"
    print "  ${C}Verbs often have aliases for muscle memory:${N}"
    print "  ${M}  zpwr forward${N}${D}  = ${M}zpwr f${D}   = ${M}zpwr fwd${N}"
    print "  ${M}  zpwr reverse${N}${D}  = ${M}zpwr r${D}   = ${M}zpwr rvs${D} = ${M}zpwr cdup${N}"
    print "  ${M}  zpwr github${N}${D}   = ${M}zpwr gh${D}  = ${M}zpwr mygithub${N}"
    print "  ${M}  zpwr repo${N}${D}     = ${M}zpwr zp${D}  = ${M}zpwr zpwr${N}"
    print ""
    print "  ${B}${Y}TAB COMPLETION IN ACTION${N}"
    print "  ${C}  zpwr git<tab>${N}${D}     # shows: gitcommit, gitconfig, gitsearch...${N}"
    print "  ${C}  zpwr vim<tab>${N}${D}     # shows: vimall, vimrecent, vimctags...${N}"
    print "  ${C}  zpwr home<tab>${N}${D}    # shows: home, homeenv, homelocal...${N}"
    print "  ${C}  zpwr forgit<tab>${N}${D}  # shows: forgitadd, forgitlog, forgitdiff...${N}"
    print ""
    print "  ${B}${Y}INSPECT THE TABLE YOURSELF${N}"
    print "  ${M}  zpwr subcommands${N}${D}        # dump all verbs to stdout${N}"
    print "  ${M}  zpwr verbs${N}${D}     # fuzzy search verbs with fzf${N}"
    print "  ${M}  zpwr verbscount${N}${D}          # how many verbs exist${N}"
    print ""
    print "  ${B}${Y}THE EDIT SUFFIX PATTERN${N}"
    print "  ${C}Many verbs come in pairs:${N}"
    print "  ${G}  filesearch${N}${D}      -> open file after selection${N}"
    print "  ${G}  filesearchedit${N}${D}  -> type into command line for editing${N}"
    print "  ${D}The \"edit\" variant puts the result on your command line${N}"
    print "  ${D}instead of executing immediately. Power and precision.${N}"
    print ""
}
