PAGE_TITLE="Color Systems"
PAGE_CHAPTER="CHAPTER 22: CREATIVE TOOLS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< COLOR SYSTEMS — PAINTING THE VOID >>>${N}"
    print "  ${D}256 colors. true color. the terminal is not monochrome.${N}"
    print ""
    print "  ${C}Color is not cosmetic. It is information density.${N}"
    print "  ${C}A colored diff tells you more in one glance than a${N}"
    print "  ${C}monochrome one does in ten seconds. ZPWR gives you${N}"
    print "  ${C}tools to explore, test, and master terminal color.${N}"
    print ""
    print "  ${B}${Y}COLORTEST — THE 16-COLOR PALETTE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr colortest${N}"
    print "  ${G}Displays the basic 16-color ANSI palette. The foundation.${N}"
    print "  ${G}Black, red, green, yellow, blue, magenta, cyan, white —${N}"
    print "  ${G}plus their bright variants. 16 soldiers in formation.${N}"
    print ""
    print "  ${D}  Use this to verify your terminal theme is sane.${N}"
    print "  ${D}  If red looks orange, your theme needs fixing.${N}"
    print ""
    print "  ${B}${Y}COLORTEST256 — THE FULL SPECTRUM${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr colortest256${N}"
    print "  ${G}Displays all 256 extended colors. A grid of every${N}"
    print "  ${G}color code your terminal supports. From 0 to 255.${N}"
    print "  ${G}Useful for picking colors for prompts and scripts.${N}"
    print ""
    print "  ${D}  \"What number is that teal?\" Run this and find out.${N}"
    print ""
    print "  ${B}${Y}PYGMENTCOLORS — SYNTAX HIGHLIGHTING PALETTE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr pygmentcolors${N}"
    print "  ${G}Shows available Pygments color schemes. Pygments is the${N}"
    print "  ${G}syntax highlighting engine used by many ZPWR tools.${N}"
    print "  ${G}Pick a scheme that matches your aesthetic.${N}"
    print ""
    print "  ${B}${Y}PRETTYPRINT & ALTPRETTYPRINT — FORMATTED OUTPUT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr prettyprint <file>${N}"
    print "  ${M}  zpwr altprettyprint <file>${N}"
    print "  ${G}Syntax-highlighted file display. prettyprint uses one${N}"
    print "  ${G}engine, altprettyprint uses another. Both turn raw${N}"
    print "  ${G}source code into technicolor glory in your terminal.${N}"
    print ""
    print "  ${D}  Like cat, but for people who respect their eyes.${N}"
    print ""
    print "  ${B}${G}COLOR EXPLORATION WORKFLOW:${N}"
    print "  ${C}  1. ${M}zpwr colortest${C}        check basic 16 colors${N}"
    print "  ${C}  2. ${M}zpwr colortest256${C}     explore full 256 palette${N}"
    print "  ${C}  3. ${M}zpwr pygmentcolors${C}    pick a syntax theme${N}"
    print "  ${C}  4. ${M}zpwr prettyprint${C}      view files in color${N}"
    print ""
    print "  ${D}  // monochrome terminals are a war crime${N}"
    print "  ${D}  // color is data. learn to read it.${N}"
    print "  ${D}  // 256 colors and you are still using white-on-black?${N}"
    print ""
}
