PAGE_TITLE="Clipboard, Send & Tmux"
PAGE_CHAPTER="CHAPTER 14: TMUX WARFARE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== CLIPBOARD, SEND & TMUX ===${N}"
    print "  ${D}// 13 verbs for pane orchestration //${N}"
    print ""
    print "  ${C}Clipboard access, key duplication across panes, URL${N}"
    print "  ${C}handling, and tmux session management.${N}"
    print ""
    print "  ${B}${Y}CLIPBOARD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr copycommand${N}${D}           # get the command to copy with system${N}"
    print "  ${M}  zpwr pastecommand${N}${D}          # get the command to paste with system${N}"
    print "  ${M}  zpwr pastebuffer${N}${D}           # paste clipboard to \$BUFFER${N}"
    print "  ${M}  zpwr pastestring${N}${D}           # paste clipboard to stdout${N}"
    print ""
    print "  ${B}${Y}KEY DUPLICATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr startsend${N}${D}             # dup some keys to pane${N}"
    print "  ${M}  zpwr startsendfull${N}${D}         # dup all keys to pane${N}"
    print "  ${M}  zpwr stopsend${N}${D}              # stop dup keys to pane${N}"
    print ""
    print "  ${B}${Y}URL & BROWSER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr google${N}${D}                # google clipboard contents in tmux${N}"
    print "  ${M}  zpwr openurl${N}${D}               # open URL from clipboard in tmux${N}"
    print ""
    print "  ${B}${Y}SESSION MANAGEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr attach${N}${D}                # attach to tmux session${N}"
    print "  ${M}  zpwr detach${N}${D}                # detach from all tmux sessions${N}"
    print "  ${M}  zpwr killmux${N}${D}               # kill tmux server${N}"
    print "  ${M}  zpwr killremote${N}${D}            # kill tmux server and ssh${N}"
    print ""
}
