PAGE_TITLE="The Epilogue: You Are the Wizard"
PAGE_CHAPTER="CHAPTER 43: THE END"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== THE EPILOGUE: YOU ARE THE WIZARD ===${N}"
    print "  ${D}175 pages later, the terminal bows to you${N}"
    print "  ${B}${Y}WHAT YOU'VE LEARNED${N}"
    print "  ${D}  175 pages across 43 chapters. From keybindings to kernel.${N}"
    print "  ${D}  Autoloaded functions. Tmux pipelines. Fzf integration.${N}"
    print "  ${D}  Vim execution. Perl oneliners. Systemd services.${N}"
    print "  ${D}  32-pane REPL layouts. Cross-platform installers.${N}"
    print "  ${D}  A 24-hour updater loop. A 60-file test suite.${N}"
    print "  ${D}  A colorization stack five tools deep.${N}"
    print "  ${D}  And a startup banner delivered by a rainbow pony.${N}"
    print "  ${B}${Y}THE 5 COMMANDS TO MEMORIZE${N}"
    print "  ${G}  zpwr verbs${N}${D}    list every zpwr subcommand${N}"
    print "  ${G}  zpwr doctor${N}${D}   run environment health check diagnostic${N}"
    print "  ${G}  zpwr bench${N}${D}    benchmark startup with percentiles${N}"
    print "  ${G}  zpwr wizard${N}${D}   interactive guided tour (you're here)${N}"
    print "  ${G}  zpwr study${N}${D}    split-pane learning: book left, shell right${N}"
    print "  ${D}  Five commands. That's your entire onboarding.${N}"
    print "  ${B}${Y}HOW TO ADD YOUR OWN VERBS${N}"
    print "  ${D}  1. Create an autoload function in ${M}\$ZPWR/autoload/common/${N}"
    print "  ${D}  2. Add to ZPWR_VERBS in ${M}\$ZPWR_ENV/zpwr.zsh${N}"
    print "  ${D}     Format: ${G}ZPWR_VERBS[myverb]='myFunc=description'${N}"
    print "  ${D}  3. Reload: ${G}exec zsh${N}${D}. Your verb is live.${N}"
    print "  ${B}${Y}HOW TO EXTEND THE WIZARD${N}"
    print "  ${D}  Add a new page_NNN.zsh to ${M}\$ZPWR_INSTALL/wizard_pages/${N}"
    print "  ${D}  Follow the format: PAGE_TITLE, PAGE_CHAPTER, PAGE_CONTENT().${N}"
    print "  ${D}  The wizard auto-discovers pages. No registration needed.${N}"
    print "  ${B}${Y}HOW TO CONTRIBUTE${N}"
    print "  ${D}  Fork ${G}github.com/MenkeTechnologies/zpwr${N}"
    print "  ${D}  Add your feature. Write tests. Submit a PR.${N}"
    print "  ${D}  The codebase is the documentation. Read it.${N}"
    print "  ${B}${Y}THE ZPWR PHILOSOPHY${N}"
    print "  ${C}  Verbs, not scripts.${N}${D}  Discoverability over memorization.${N}"
    print "  ${C}  Speed over bloat.${N}${D}    Fallbacks over hard dependencies.${N}"
    print "  ${C}  Convention over config.${N}${D}  Your shell should just work.${N}"
    print "  ${B}${Y}ONE LAST THING${N}"
    print "  ${D}  Run ${G}zpwr about${N}${D} to see the zpwr banner.${N}"
    print "  ${D}  Then open a new terminal. Watch the pony greet you.${N}"
    print "  ${D}  You are the wizard now. The terminal is yours.${N}"
    print "  ${B}${M}  >>> END OF TRANSMISSION <<<${N}"
    print "  ${D}  ${C}// ZPWR WIZARD ENCYCLOPEDIA v1.0 // SIGNAL LOST //${N}"
    print "  ${B}${G}  May your shell be fast, your pipes be clean,${N}"
    print "  ${B}${G}  and your exit codes always zero.${N}"
}
