PAGE_TITLE="Tag Generation"
PAGE_CHAPTER="CHAPTER 10: BUILD SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== TAG GENERATION ===${N}"
    print "  ${D}// ctrl-] in vim. M-. in emacs. the tags file makes it work. //${N}"
    print ""
    print "  ${C}Tags files are indexes of symbol definitions: functions,${N}"
    print "  ${C}variables, classes, methods. Your editor uses them to jump${N}"
    print "  ${C}to definitions with a single keystroke. zpwr generates them.${N}"
    print ""
    print "  ${B}${Y}CTAGS: THE CLASSIC${N}"
    print "  ${M}  zpwr regenctags${N}${D}                     # regenerate ctags file${N}"
    print ""
    print "  ${D}  Runs exuberant-ctags or universal-ctags over the zpwr${N}"
    print "  ${D}  codebase. Produces a ${C}tags${D} file that vim and emacs read.${N}"
    print ""
    print "  ${D}  In vim: ${M}Ctrl-]${D} jumps to the definition under cursor.${N}"
    print "  ${D}  In vim: ${M}Ctrl-T${D} jumps back to where you were.${N}"
    print "  ${D}  In vim: ${M}:tag zpwrDoctor${D} jumps to zpwrDoctor.${N}"
    print ""
    print "  ${D}  ctags understands shell functions, C, Python, Ruby, and${N}"
    print "  ${D}  dozens of other languages out of the box.${N}"
    print ""
    print "  ${B}${Y}GTAGS: THE GNU GLOBAL SYSTEM${N}"
    print "  ${M}  zpwr regengtags${N}${D}                     # regenerate GNU Global tags${N}"
    print ""
    print "  ${D}  GNU Global is a more powerful tagging system. It supports:${N}"
    print "  ${D}  - Forward references (where is this defined?)${N}"
    print "  ${D}  - Backward references (where is this called from?)${N}"
    print "  ${D}  - Symbol completion${N}"
    print ""
    print "  ${D}  Produces GTAGS, GRTAGS, GPATH files in the project root.${N}"
    print "  ${D}  Query from command line: ${M}global -x zpwrDoctor${N}"
    print "  ${D}  Query references: ${M}global -rx zpwrDoctor${N}"
    print ""
    print "  ${B}${Y}GTAGS WITH PYGMENTS PARSER${N}"
    print "  ${M}  zpwr regengtagspygments${N}${D}             # gtags with Pygments backend${N}"
    print ""
    print "  ${D}  Uses the Python Pygments parser instead of the built-in${N}"
    print "  ${D}  one. Pygments understands more languages and file types.${N}"
    print "  ${D}  Requires: ${M}pip install pygments${N}"
    print ""
    print "  ${B}${Y}GTAGS BY FILE TYPE${N}"
    print "  ${M}  zpwr regengtagstype${N}${D}                 # gtags filtered by type${N}"
    print ""
    print "  ${D}  Generate tags for a specific file type only.${N}"
    print "  ${D}  Faster than a full regen when you only care about one language.${N}"
    print ""
    print "  ${B}${Y}HOW TAGS WORK WITH YOUR EDITOR${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  vim${N}${D}    reads 'tags' file. :set tags=./tags;,tags${N}"
    print "  ${D}         Ctrl-] to jump, Ctrl-T to return${N}"
    print "  ${D}         :tselect for multiple matches${N}"
    print ""
    print "  ${C}  emacs${N}${D}  reads TAGS file (etags format) or uses gtags${N}"
    print "  ${D}         M-. to find definition, M-* to return${N}"
    print "  ${D}         ggtags-mode or helm-gtags for GNU Global${N}"
    print ""
    print "  ${C}  nvim${N}${D}   same as vim, plus LSP which often replaces tags${N}"
    print "  ${D}         but tags still work as a fast fallback${N}"
    print ""
    print "  ${B}${Y}WHEN TO REGENERATE${N}"
    print "  ${D}  - After adding or renaming functions${N}"
    print "  ${D}  - After a zpwr update that adds new verbs${N}"
    print "  ${D}  - When \"tag not found\" errors appear for known functions${N}"
    print "  ${D}  - Use ${M}zpwr watch '*.zsh' 'zpwr regenctags'${D} for auto-regen${N}"
    print ""
}
