PAGE_TITLE="Counting Everything"
PAGE_CHAPTER="CHAPTER 17: INTROSPECTION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> COUNTING EVERYTHING: THE CENSUS BUREAU <<<${N}"
    print "  ${D}if you can't measure it, you can't brag about it${N}"
    print ""
    print "  ${G}ZPWR tracks the size of every component. These verbs${N}"
    print "  ${G}tell you exactly how big your installation is.${N}"
    print ""
    print "  ${B}${Y}zpwr autoloadcount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Count of autoloaded zsh functions in the framework.${N}"
    print ""
    print "  ${C}  \$ zpwr autoloadcount${N}           ${D}# how many functions?${N}"
    print ""
    print "  ${B}${Y}zpwr scriptcount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Count of shell scripts in \$ZPWR/scripts.${N}"
    print ""
    print "  ${C}  \$ zpwr scriptcount${N}             ${D}# how many scripts?${N}"
    print ""
    print "  ${B}${Y}zpwr zshplugincount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Count of installed zsh plugins (zinit, oh-my-zsh, etc).${N}"
    print ""
    print "  ${C}  \$ zpwr zshplugincount${N}          ${D}# zsh plugins loaded${N}"
    print ""
    print "  ${B}${Y}zpwr vimplugincount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Count of installed vim/neovim plugins.${N}"
    print ""
    print "  ${C}  \$ zpwr vimplugincount${N}          ${D}# vim plugins loaded${N}"
    print ""
    print "  ${B}${Y}zpwr emacsplugincount${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Count of installed emacs packages.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsplugincount${N}        ${D}# emacs pkgs loaded${N}"
    print ""
    print "  ${B}${Y}THE FULL CENSUS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  \$ zpwr autoloadcount && zpwr scriptcount && \\${N}"
    print "  ${D}    zpwr zshplugincount && zpwr vimplugincount && \\${N}"
    print "  ${D}    zpwr emacsplugincount${N}"
    print ""
    print "  ${G}Run all five to get the full picture.${N}"
    print "  ${G}ZPWR typically ships with 300+ autoloads, 50+ scripts,${N}"
    print "  ${G}and dozens of plugins across all three editors.${N}"
    print ""
    print "  ${D}  // these counts tell you the scope of ZPWR${N}"
    print "  ${D}  // hundreds of functions working in concert${N}"
    print "  ${D}  // like a small city running on your laptop${N}"
}
