PAGE_TITLE="Tmux Plugins & Extensions"
PAGE_CHAPTER="CHAPTER 30: TMUX DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== TMUX PLUGINS & EXTENSIONS ===${N}"
    print "  ${D}// tpm: the plugin manager for your multiplexer's plugins. yo dawg. //${N}"
    print "  ${C}ZPWR manages 9 tmux plugins via tpm (Tmux Plugin Manager).${N}"
    print "  ${C}They live in ~/.tmux/plugins/ and add features that tmux${N}"
    print "  ${C}does not provide out of the box.${N}"
    print "  ${B}${Y}TPM: TMUX PLUGIN MANAGER${N}"
    print "  ${D}Installed to ~/.tmux/plugins/tpm. Managed via prefix keys:${N}"
    print "  ${M}  prefix + I${N}${D}       Install plugins listed in .tmux.conf${N}"
    print "  ${M}  prefix + U${N}${D}       Update all installed plugins${N}"
    print "  ${M}  prefix + Alt-u${N}${D}   Clean plugins not in config${N}"
    print "  ${D}Plugins are declared in \$ZPWR_INSTALL/.tmux.conf:${N}"
    print "  ${M}  set-option -g @plugin 'tmux-plugins/tpm'${N}"
    print "  ${M}  set-option -g @plugin 'tmux-plugins/tmux-resurrect'${N}"
    print "  ${B}${Y}THE PLUGIN ROSTER (.tmuxplugins)${N}"
    print "  ${G}  tmux-plugins/tpm${N}${D}                Plugin manager itself${N}"
    print "  ${G}  tmux-plugins/tmux-sensible${N}${D}      Sane defaults for tmux${N}"
    print "  ${G}  tmux-plugins/tmux-resurrect${N}${D}     Session save/restore${N}"
    print "  ${G}  tmux-plugins/tmux-continuum${N}${D}      Auto-save sessions${N}"
    print "  ${G}  tmux-plugins/tmux-battery${N}${D}        Battery indicator${N}"
    print "  ${G}  tmux-plugins/tmux-prefix-highlight${N}${D} Highlight when prefix active${N}"
    print "  ${G}  tmux-plugins/tmux-yank${N}${D}           System clipboard integration${N}"
    print "  ${G}  MenkeTechnologies/tmux-thumbs${N}${D}     Quick copy with hints${N}"
    print "  ${G}  MenkeTechnologies/tmux-fzf-url${N}${D}    FZF through URLs in pane${N}"
    print "  ${B}${Y}tmux-resurrect: WHAT IT SAVES${N}"
    print "  ${D}  - Pane layouts (splits, sizes, positions)${N}"
    print "  ${D}  - Working directories for each pane${N}"
    print "  ${D}  - Running programs (@resurrect-processes ':all:')${N}"
    print "  ${D}  - Command history is NOT saved (that's zsh's job)${N}"
    print "  ${D}  Save: prefix+Ctrl-s. Restore: prefix+Ctrl-r.${N}"
    print "  ${B}${Y}tmux-continuum: AUTO-SAVE${N}"
    print "  ${D}Piggybacks on resurrect. Auto-saves every 15 minutes.${N}"
    print "  ${D}@continuum-restore is commented out in ZPWR by default.${N}"
    print "  ${D}Enable it to auto-restore on tmux server start.${N}"
    print "  ${B}${Y}tmux-fzf-url: URL PICKER${N}"
    print "  ${D}Scans the visible pane for URLs, opens them in fzf:${N}"
    print "  ${M}  prefix + e${N}${D}   FZF through URLs, open selected in browser${N}"
    print "  ${M}  prefix + u${N}${D}   FZF through URLs, search mode${N}"
    print "  ${D}Uses ZPWR_TMUX_HISTORY_LIMIT for scrollback depth.${N}"
    print "  ${B}${Y}CUSTOM SCRIPTS IN \$ZPWR_TMUX${N}"
    print "  ${D}Layout scripts create multi-pane environments:${N}"
    print "  ${M}  prefix + D${N}${D}   control-window.conf (IDE layout)${N}"
    print "  ${M}  prefix + F${N}${D}   four-panes.conf${N}"
    print "  ${M}  prefix + G${N}${D}   eight-panes.conf${N}"
    print "  ${M}  prefix + O${N}${D}   sixteen-panes.conf${N}"
    print "  ${M}  prefix + T${N}${D}   config-files.conf (brc, vrc, trc, zrc)${N}"
    print "  ${M}  prefix + M${N}${D}   learn.conf (study layout)${N}"
    print "  ${B}${Y}zpwr study: THE SPLIT-PANE LEARNING ENVIRONMENT${N}"
    print "  ${D}Creates a dedicated tmux session 'zpwr-study' with the${N}"
    print "  ${D}encyclopedia on the left and a live shell on the right.${N}"
    print "  ${D}Read the docs, try commands. Knowledge through practice.${N}"
}
