PAGE_TITLE="Git Surgery"
PAGE_CHAPTER="CHAPTER 3: THE GIT DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== GIT SURGERY ===${N}"
    print ""
    print "  ${C}Sometimes you need to rewrite history.${N}"
    print "  ${C}Not the geopolitical kind. The git kind.${N}"
    print "  ${R}${B}These are destructive operations. Use with intent.${N}"
    print ""
    print "  ${B}${Y}CLEARING THE CACHE${N}"
    print "  ${M}  zpwr gitclearcache${N}${D}     # clear old git refs and objects${N}"
    print "  ${D}  Runs garbage collection on git's internal state.${N}"
    print "  ${D}  Prunes unreachable objects, packs loose refs.${N}"
    print "  ${D}  Your .git directory gets a deep clean.${N}"
    print ""
    print "  ${B}${Y}REMOVING COMMITS${N}"
    print "  ${M}  zpwr gitclearcommit${N}${D}    # remove matching commits from history${N}"
    print "  ${R}  This is filter-branch territory.${N}"
    print "  ${R}  Rewrites history. Force push required after.${N}"
    print "  ${D}  Use when someone committed passwords, API keys,${N}"
    print "  ${D}  or that embarrassing commented-out code block.${N}"
    print ""
    print "  ${B}${Y}REMOVING FILES FROM ALL HISTORY${N}"
    print "  ${M}  zpwr gitclearfile${N}${D}      # rm file from all git refs and objects${N}"
    print "  ${R}  Nuclear option for files.${N}"
    print "  ${D}  That 200MB video someone committed in 2020?${N}"
    print "  ${D}  This removes it from every commit that ever existed.${N}"
    print "  ${D}  Your repo size drops. Your clone time drops.${N}"
    print "  ${D}  Your blood pressure drops.${N}"
    print ""
    print "  ${B}${Y}EMAIL SURGERY${N}"
    print "  ${M}  zpwr gitemail${N}${D}          # change email with git filter-branch${N}"
    print "  ${D}  Changes both author and committer email across history.${N}"
    print ""
    print "  ${M}  zpwr gitaemail${N}${D}         # change author email only${N}"
    print "  ${D}  When you committed with your personal email at work.${N}"
    print ""
    print "  ${M}  zpwr gitcemail${N}${D}         # change committer email only${N}"
    print "  ${D}  When the committer field has the wrong identity.${N}"
    print ""
    print "  ${B}${Y}WHEN TO USE THESE${N}"
    print "  ${G}  Scenario: you committed with wrong@email.com${N}"
    print "  ${M}    zpwr gitemail${N}"
    print "  ${D}    # Follow the prompts to fix every commit${N}"
    print ""
    print "  ${G}  Scenario: .env file in git history with secrets${N}"
    print "  ${M}    zpwr gitclearfile${N}"
    print "  ${D}    # Purges it from every ref and object${N}"
    print ""
    print "  ${R}${B}  REMEMBER:${N}${R} These rewrite history.${N}"
    print "  ${R}  Coordinate with your team before force pushing.${N}"
    print "  ${R}  Or do not coordinate and watch the chaos unfold.${N}"
    print ""
}
