PAGE_TITLE="Neovim: The Next Generation"
PAGE_CHAPTER="CHAPTER 38: NEOVIM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== NEOVIM: THE NEXT GENERATION ===${N}"
    print "  ${D}// vim, but the timeline where Bram had unlimited funding. //${N}"
    print "  ${C}Neovim is the modernized fork of vim. Refactored internals,${N}"
    print "  ${C}async everything, built-in LSP, Lua plugin API. In zpwr,${N}"
    print "  ${C}the default editor: ${M}ZPWR_VIM='nvim'${C} in .zpwr_env.sh.${N}"
    print "  ${B}${Y}THE INIT.VIM BRIDGE${N}"
    print "  ${D}\$ZPWR_INSTALL/init.vim is just three lines:${N}"
    print "  ${M}  set runtimepath^=~/.vim runtimepath+=~/.vim/after${N}"
    print "  ${M}  let &packpath = &runtimepath${N}"
    print "  ${M}  source ~/.vimrc${N}"
    print "  ${D}This means neovim sources the same .vimrc as vim. One config${N}"
    print "  ${D}to rule them both. All 80+ vim plugins work in either editor.${N}"
    print "  ${D}The symlink is created by plugins_install.sh:${N}"
    print "  ${M}  ln -sf \$ZPWR_INSTALL/init.vim ~/.config/nvim/init.vim${N}"
    print "  ${B}${Y}NEOVIM-SPECIFIC FEATURES${N}"
    print "  ${D}${G}Async job control${D}  — run external commands without blocking${N}"
    print "  ${D}                     the editor. vim 8 added this too, but${N}"
    print "  ${D}                     nvim's API is cleaner (jobstart/jobstop).${N}"
    print "  ${D}${G}Built-in LSP${D}       — nvim 0.5+ has a native LSP client.${N}"
    print "  ${D}                     Configure with lua: vim.lsp.start().${N}"
    print "  ${D}                     No plugin needed for basic LSP.${N}"
    print "  ${D}${G}Lua plugin API${D}     — write plugins in Lua, not just VimScript.${N}"
    print "  ${D}                     Lua runs 10-100x faster than VimScript.${N}"
    print "  ${D}${G}:terminal${D}          — built-in terminal emulator. Better than${N}"
    print "  ${D}                     vim's :terminal — proper job control,${N}"
    print "  ${D}                     scrollback, and buffer integration.${N}"
    print "  ${D}${G}True color${D}         — 24-bit color out of the box. No termguicolors${N}"
    print "  ${D}                     hacks needed (though the option exists).${N}"
    print "  ${B}${Y}PROVIDER SUPPORT${N}"
    print "  ${D}nvim uses providers for python3 and node integration:${N}"
    print "  ${M}  pip3 install pynvim${N}${D}          # python3 provider${N}"
    print "  ${M}  npm install -g neovim${N}${D}        # node.js provider${N}"
    print "  ${D}Run ${G}:checkhealth${D} to verify all providers are working.${N}"
    print "  ${B}${Y}ZPWR VIM INFO${N}"
    print "  ${D}zpwr catviminfo and zpwr catrecentfviminfo read the nvim${N}"
    print "  ${D}shada (shared data) file — the nvim equivalent of .viminfo.${N}"
}
