PAGE_TITLE="Process & Network"
PAGE_CHAPTER="CHAPTER 15: NETWORK & CONTAINERS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== PROCESS & NETWORK ===${N}"
    print "  ${D}// 15 verbs for procs, ports, and packets //${N}"
    print ""
    print "  ${C}Kill processes via fzf, monitor process trees, toggle${N}"
    print "  ${C}Tor, ping LANs, and run network diagnostics.${N}"
    print ""
    print "  ${B}${Y}PROCESS MANAGEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr ps${N}${D}                    # ps -ef | grep arg${N}"
    print "  ${M}  zpwr kill${N}${D}                  # kill from ps output via fzf${N}"
    print "  ${M}  zpwr killedit${N}${D}              # edit kill from ps output via fzf${N}"
    print "  ${M}  zpwr lsof${N}${D}                  # kill from lsof output via fzf${N}"
    print "  ${M}  zpwr lsofedit${N}${D}              # edit kill from lsof output via fzf${N}"
    print "  ${M}  zpwr pstreemonitor${N}${D}         # monitor process tree with watch${N}"
    print ""
    print "  ${B}${Y}NETWORK DIAGNOSTICS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr digs${N}${D}                  # run series of networking cmds on arg${N}"
    print "  ${M}  zpwr pi${N}${D}                    # ping all LAN devices${N}"
    print "  ${M}  zpwr ping${N}${D}                  # ping all LAN devices${N}"
    print "  ${M}  zpwr pir${N}${D}                   # run command on all devices${N}"
    print ""
    print "  ${B}${Y}TOR & IP${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr torip${N}${D}                 # get IP address via Tor and whois${N}"
    print "  ${M}  zpwr toriprenew${N}${D}            # renew Tor identity${N}"
    print "  ${M}  zpwr to${N}${D}                    # toggle external ip${N}"
    print "  ${M}  zpwr toggle${N}${D}                # toggle external ip${N}"
    print ""
    print "  ${B}${Y}POLLING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr poll${N}${D}                  # poll git remote and run command${N}"
    print ""
}
