PAGE_TITLE="Core Paths"
PAGE_CHAPTER="CHAPTER 21: ZPWR ENVIRONMENT VARIABLES"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< CORE PATHS — THE SKELETON OF THE MACHINE >>>${N}"
    print "  ${D}every system has bones. these are ZPWR's.${N}"
    print ""
    print "  ${C}ZPWR does not hardcode paths. Every directory is an${N}"
    print "  ${C}environment variable. Move the root, and the entire${N}"
    print "  ${C}system follows. This is not a dotfiles repo — it is${N}"
    print "  ${C}a relocatable operating system.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR — THE ROOT OF ALL THINGS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR${N}${D}   # typically ~/.zpwr${N}"
    print "  ${G}The root directory. Every other path derives from this.${N}"
    print "  ${G}Change this one variable and the whole tree moves.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_LOCAL — YOUR PRIVATE SANCTUM${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_LOCAL${N}${D}   # \$ZPWR/local${N}"
    print "  ${G}Gitignored. Your tokens, secrets, local overrides.${N}"
    print "  ${G}Nothing in here ever touches a remote repository.${N}"
    print "  ${G}Your .tokens.sh lives here. Guard it with your life.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_SCRIPTS — THE ARMORY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_SCRIPTS${N}${D}   # \$ZPWR/scripts${N}"
    print "  ${G}Executable scripts. Bash, Python, Perl — whatever${N}"
    print "  ${G}gets the job done. These are on your PATH.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_TMUX — THE MULTIPLEXER CONFIG${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_TMUX${N}${D}   # \$ZPWR/tmux${N}"
    print "  ${G}Tmux configuration, scripts, and status line logic.${N}"
    print "  ${G}The control center for your terminal multiplexer.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_INSTALL — THE INSTALLER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_INSTALL${N}${D}   # \$ZPWR/install${N}"
    print "  ${G}OS-specific installation scripts. macOS, Ubuntu,${N}"
    print "  ${G}Fedora, Arch — each gets its own installer.${N}"
    print "  ${G}Run ${M}zpwr install${G} and the right one fires.${N}"
    print ""
    print "  ${B}${G}THE PATH MAP:${N}"
    print "  ${C}  \$ZPWR${N}                ${D}~/.zpwr (the root)${N}"
    print "  ${C}  \$ZPWR_LOCAL${N}          ${D}\$ZPWR/local (gitignored secrets)${N}"
    print "  ${C}  \$ZPWR_SCRIPTS${N}        ${D}\$ZPWR/scripts (executables)${N}"
    print "  ${C}  \$ZPWR_TMUX${N}           ${D}\$ZPWR/tmux (multiplexer)${N}"
    print "  ${C}  \$ZPWR_INSTALL${N}        ${D}\$ZPWR/install (OS installers)${N}"
    print ""
    print "  ${D}  // paths are not strings. they are load-bearing structures.${N}"
    print "  ${D}  // hardcode a path and you weld yourself to the floor.${N}"
    print "  ${D}  // use the variables. always use the variables.${N}"
    print ""
}
