PAGE_TITLE="Emacs File Operations"
PAGE_CHAPTER="CHAPTER 13: EMACS DIMENSION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> EMACS FILE OPS: OPENING THINGS SINCE 1976 <<<${N}"
    print "  ${D}emacs: an operating system lacking only a decent editor${N}"
    print ""
    print "  ${B}${Y}zpwr emacsall${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Opens all ZPWR framework files in emacs via fzf.${N}"
    print "  ${G}Every autoload, script, config -- the whole kingdom.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsall${N}              ${D}# browse all files${N}"
    print "  ${C}  \$ zpwr emacsalledit${N}          ${D}# same but editable${N}"
    print ""
    print "  ${B}${Y}zpwr emacsrecent${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Opens recently edited files. Emacs remembers where${N}"
    print "  ${G}you have been, like a browser history for code.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsrecent${N}            ${D}# fzf recent files${N}"
    print "  ${C}  \$ zpwr emacsrecentcd${N}          ${D}# cd to recent dir${N}"
    print "  ${C}  \$ zpwr emacsrecentsudo${N}        ${D}# recent with sudo${N}"
    print "  ${C}  \$ zpwr emacsrecentsudocd${N}      ${D}# sudo + cd combo${N}"
    print ""
    print "  ${B}${Y}zpwr emacsscripts${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Browse and open ZPWR scripts directory.${N}"
    print "  ${G}Where the shell scripts live and breathe.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsscripts${N}           ${D}# browse scripts${N}"
    print "  ${C}  \$ zpwr emacsscriptedit${N}        ${D}# edit a script${N}"
    print ""
    print "  ${B}${Y}zpwr emacsautoload${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Open autoloaded zsh functions in emacs.${N}"
    print "  ${G}The beating heart of ZPWR's function library.${N}"
    print ""
    print "  ${C}  \$ zpwr emacsautoload${N}          ${D}# browse autoloads${N}"
    print ""
    print "  ${D}  // protip: emacsrecent is your daily driver${N}"
    print "  ${D}  // it learns your habits and surfaces what matters${N}"
    print "  ${D}  // sudo variants for when /etc needs surgery${N}"
}
