PAGE_TITLE="Listening Ports"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== LISTENING PORTS ===${N}"
    print "  ${D}// who is listening? and on which door? //${N}"
    print ""
    print "  ${C}zpwr ports wraps lsof to show every TCP port in LISTEN${N}"
    print "  ${C}state with the process name, PID, user, and bind address.${N}"
    print ""
    print "  ${B}${Y}THE VERB${N}"
    print "  ${M}  zpwr ports${N}${D}                 # show all listening ports${N}"
    print "  ${M}  zpwr ports 8080${N}${D}            # filter to port 8080${N}"
    print "  ${M}  zpwr ports -k 3000${N}${D}         # kill whatever is on port 3000${N}"
    print ""
    print "  ${B}${Y}COLOR CODING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${R}  Privileged ports (< 1024)${N}${D}    — RED${N}"
    print "  ${D}    These require root. sshd on 22, httpd on 80.${N}"
    print "  ${Y}  Common ports (< 10000)${N}${D}       — YELLOW${N}"
    print "  ${D}    Dev servers, databases. 3000, 5432, 8080.${N}"
    print "  ${G}  High ports (>= 10000)${N}${D}        — GREEN${N}"
    print "  ${D}    Ephemeral and user-space. Generally safe.${N}"
    print ""
    print "  ${B}${Y}THE KILL FLAG${N}"
    print "  ${D}  ${M}zpwr ports -k 3000${D} finds the PID on port 3000 and${N}"
    print "  ${D}  sends SIGTERM. Shows process name before killing.${N}"
    print "  ${D}  Use when a dev server refuses to die.${N}"
    print ""
    print "  ${B}${Y}COMPANION VERBS${N}"
    print "  ${M}  zpwr lsof${N}${D}                 # interactive fzf over all lsof output${N}"
    print "  ${M}  zpwr ps${N}${D}                   # grep through ps output${N}"
    print "  ${M}  zpwr kill${N}${D}                 # fzf kill from ps${N}"
    print ""
}
