PAGE_TITLE="Network Recon"
PAGE_CHAPTER="CHAPTER 15: NETWORK & CONTAINERS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> NETWORK RECON: SCANNING THE WIRE <<<${N}"
    print "  ${D}packets don't lie, but DNS sometimes does${N}"
    print ""
    print "  ${B}${Y}zpwr digs${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Enhanced DNS lookup. Wraps dig with cleaner output.${N}"
    print "  ${G}When you need to know where a domain really points.${N}"
    print ""
    print "  ${C}  \$ zpwr digs github.com${N}         ${D}# DNS lookup${N}"
    print "  ${C}  \$ zpwr digs example.com${N}        ${D}# check any domain${N}"
    print ""
    print "  ${G}Shows A records, CNAME chains, TTLs -- the works.${N}"
    print "  ${G}Faster than remembering dig +short +noall +answer.${N}"
    print ""
    print "  ${B}${Y}zpwr pi / zpwr ping${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Ping a host. Simple, reliable, essential.${N}"
    print "  ${G}'pi' is the short alias because typing matters.${N}"
    print ""
    print "  ${C}  \$ zpwr pi google.com${N}           ${D}# quick ping${N}"
    print "  ${C}  \$ zpwr ping 8.8.8.8${N}           ${D}# verbose ping${N}"
    print ""
    print "  ${B}${Y}zpwr pir${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Ping with extended options. More detailed network${N}"
    print "  ${G}diagnostics for when simple ping is not enough.${N}"
    print ""
    print "  ${C}  \$ zpwr pir 192.168.1.1${N}        ${D}# extended ping${N}"
    print ""
    print "  ${B}${Y}RECON WORKFLOW:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${D}  1. \$ zpwr digs suspect-domain.com  # where does it resolve?${N}"
    print "  ${D}  2. \$ zpwr pi <ip-from-dig>         # is it alive?${N}"
    print "  ${D}  3. \$ zpwr pir <ip>                 # deeper probe${N}"
    print ""
    print "  ${D}  // three verbs, complete network recon${N}"
    print "  ${D}  // digs for DNS, pi for heartbeat, pir for details${N}"
    print "  ${D}  // when in doubt, ping first -- dead hosts tell no tales${N}"
}
