PAGE_TITLE="Welcome to the Machine"
PAGE_CHAPTER="CHAPTER 1: THE RED PILL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== WELCOME TO THE MACHINE ===${N}"
    print ""
    print "  ${C}You found it. The rabbit hole.${N}"
    print "  ${C}ZPWR is not a dotfiles repo. It is not a \"framework.\"${N}"
    print "  ${C}It is a fully integrated shell operating system that happens${N}"
    print "  ${C}to run inside your terminal.${N}"
    print ""
    print "  ${B}${Y}WHAT IS ZPWR?${N}"
    print "  ${G}A 400+ verb command dispatcher built on top of zsh, tmux,${N}"
    print "  ${G}vim/nvim, fzf, and git. Every verb is a surgical tool.${N}"
    print "  ${G}Every keybinding is a weapon. Every alias is a shortcut${N}"
    print "  ${G}through the matrix.${N}"
    print ""
    print "  ${B}${Y}THE PHILOSOPHY${N}"
    print "  ${C}1. ${B}Verbs, not scripts.${N}${C} Everything is ${M}zpwr <verb>${C}.${N}"
    print "  ${C}2. ${B}Discoverability.${N}${C}   Tab completion on everything.${N}"
    print "  ${C}3. ${B}Symmetry.${N}${C}          vim* and emacs* verbs mirror each other.${N}"
    print "  ${C}4. ${B}Speed.${N}${C}             Compiled zwc files. Benchmarked startup.${N}"
    print "  ${C}5. ${B}No magic.${N}${C}          Read the source. It is all zsh.${N}"
    print ""
    print "  ${B}${Y}THE DIRECTORY TREE${N}"
    print "  ${G}\$ZPWR${N}${D} ........................ root of the kingdom${N}"
    print "  ${G}\$ZPWR_ENV${N}${D} .................... env vars and shell init${N}"
    print "  ${G}\$ZPWR_SCRIPTS${N}${D} ................ executable scripts${N}"
    print "  ${G}\$ZPWR_AUTOLOAD${N}${D} ............... autoloaded functions${N}"
    print "  ${G}\$ZPWR_LOCAL${N}${D} .................. local config (gitignored)${N}"
    print "  ${G}\$ZPWR_INSTALL${N}${D} ................ installer scripts${N}"
    print "  ${G}\$ZPWR_TMUX${N}${D} ................... tmux configuration${N}"
    print "  ${G}\$ZPWR_TEST${N}${D} ................... test suite${N}"
    print ""
    print "  ${B}${Y}YOUR FIRST COMMAND${N}"
    print "  ${M}  zpwr about${N}${D}    # behold the banner${N}"
    print "  ${M}  zpwr help${N}${D}     # list every verb in color${N}"
    print ""
    print "  ${D}Pro tip: zpwr is aliased to many short forms.${N}"
    print "  ${D}Type ${M}zpwr <tab>${D} and let the completions wash over you.${N}"
    print ""
    print "  ${R}${B}WARNING:${N}${R} Side effects may include mass alias adoption,${N}"
    print "  ${R}involuntary tab-completing in other people's terminals,${N}"
    print "  ${R}and an irrational hatred of vanilla bash.${N}"
    print ""
}
