PAGE_TITLE="The Token System"
PAGE_CHAPTER="CHAPTER 24: TIPS, TRICKS & EASTER EGGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< THE TOKEN SYSTEM — YOUR PRIVATE OVERRIDE LAYER >>>${N}"
    print "  ${D}secrets, aliases, and local config that never touch git${N}"
    print ""
    print "  ${C}ZPWR has sensible defaults. But you are not sensible.${N}"
    print "  ${C}You have API keys, custom aliases, machine-specific${N}"
    print "  ${C}paths, and opinions. The token system is where all${N}"
    print "  ${C}of that lives — safely outside version control.${N}"
    print ""
    print "  ${B}${Y}THE TOKEN FILES:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ZPWR_LOCAL/.tokens.sh${N}"
    print "  ${D}    Your main tokens file. Aliases, exports, secrets.${N}"
    print "  ${D}    This is sourced during shell init. Gitignored.${N}"
    print ""
    print "  ${C}  \$ZPWR_LOCAL/.tokens-pre.sh${N}"
    print "  ${D}    Sourced BEFORE ZPWR's main configuration.${N}"
    print "  ${D}    Override defaults before they are set.${N}"
    print "  ${D}    Set ZPWR_* variables here to change behavior.${N}"
    print ""
    print "  ${C}  \$ZPWR_LOCAL/.tokens-post.sh${N}"
    print "  ${D}    Sourced AFTER ZPWR's main configuration.${N}"
    print "  ${D}    Override anything ZPWR set. Final word.${N}"
    print "  ${D}    Your aliases here trump everything.${N}"
    print ""
    print "  ${B}${Y}THE OVERRIDE PATTERN:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Want to change a ZPWR default? Do not edit ZPWR source.${N}"
    print "  ${G}Put it in tokens-pre.sh (before) or tokens-post.sh (after).${N}"
    print ""
    print "  ${D}  Example: override in tokens-pre.sh${N}"
    print "  ${M}  export ZPWR_EXA_COMMAND=eza${N}"
    print "  ${M}  export ZPWR_KEYTIMEOUT=1${N}"
    print "  ${M}  export ZPWR_BANNER_CLEARLIST=false${N}"
    print ""
    print "  ${D}  Example: add custom aliases in tokens-post.sh${N}"
    print "  ${M}  alias k=kubectl${N}"
    print "  ${M}  alias tf=terraform${N}"
    print "  ${M}  export GITHUB_TOKEN=ghp_xxxxx${N}"
    print ""
    print "  ${B}${Y}MANAGING TOKENS:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr tokens${N}${D}           view your tokens files${N}"
    print "  ${M}  zpwr vimtokens${N}${D}        edit tokens in vim${N}"
    print "  ${M}  zpwr emacstokens${N}${D}      edit tokens in emacs${N}"
    print ""
    print "  ${B}${G}THE LOAD ORDER:${N}"
    print "  ${C}  1. ${N}tokens-pre.sh${D}      (your early overrides)${N}"
    print "  ${C}  2. ${N}ZPWR core config${D}    (the framework defaults)${N}"
    print "  ${C}  3. ${N}tokens-post.sh${D}     (your final overrides)${N}"
    print "  ${C}  4. ${N}.tokens.sh${D}         (your secrets and aliases)${N}"
    print ""
    print "  ${R}  NEVER commit token files. They are gitignored for a reason.${N}"
    print "  ${R}  API keys in git history haunt you forever.${N}"
    print ""
    print "  ${D}  // the token system is your private dimension${N}"
    print "  ${D}  // ZPWR updates without touching your config${N}"
    print "  ${D}  // your overrides survive every git pull${N}"
    print ""
}
