PAGE_TITLE="Forgit Reference"
PAGE_CHAPTER="CHAPTER 20: FORGIT DEEP DIVE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== FORGIT REFERENCE ===${N}"
    print "  ${D}// 14 verbs for fzf-powered git //${N}"
    print ""
    print "  ${C}Forgit wraps common git operations in fzf interfaces.${N}"
    print "  ${C}Interactive staging, diffing, stashing, and more.${N}"
    print ""
    print "  ${B}${Y}STAGING & DIFFING${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitadd${N}${D}             # fzf interactive git add${N}"
    print "  ${M}  zpwr forgitdiff${N}${D}            # fzf interactive git diff${N}"
    print "  ${M}  zpwr forgitreset${N}${D}           # fzf interactive git reset${N}"
    print "  ${M}  zpwr forgitrestore${N}${D}         # fzf interactive git restore${N}"
    print ""
    print "  ${B}${Y}STASH & CLEAN${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitstash${N}${D}           # fzf interactive stash show${N}"
    print "  ${M}  zpwr forgitclean${N}${D}           # fzf interactive git clean${N}"
    print ""
    print "  ${B}${Y}LOG & INFO${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitlog${N}${D}             # fzf interactive git log${N}"
    print "  ${M}  zpwr forgitinfo${N}${D}            # fzf git info${N}"
    print "  ${M}  zpwr forgitwarn${N}${D}            # fzf git warn${N}"
    print ""
    print "  ${B}${Y}GITIGNORE MANAGEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr forgitignore${N}${D}          # fzf gitignore templates${N}"
    print "  ${M}  zpwr forgitignoreclean${N}${D}     # fzf gitignore clean${N}"
    print "  ${M}  zpwr forgitignoreget${N}${D}       # fzf gitignore get${N}"
    print "  ${M}  zpwr forgitignorelist${N}${D}      # fzf gitignore list${N}"
    print "  ${M}  zpwr forgitignoreupdate${N}${D}    # fzf gitignore update${N}"
    print ""
}
