PAGE_TITLE="ripgrep: Advanced & zpwr Integration"
PAGE_CHAPTER="CHAPTER 37: RIPGREP — GREP AT LIGHT SPEED"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== RIPGREP: ADVANCED & ZPWR INTEGRATION ===${N}"
    print "  ${D}// rg --json | jq — structured grep for the data-obsessed. //${N}"
    print "  ${B}${Y}STRUCTURED OUTPUT${N}"
    print "  ${G}  rg --json PATTERN${N}${D}   # JSON output: one object per line${N}"
    print "  ${D}Each line is a JSON object with type (begin, match, end,${N}"
    print "  ${D}summary), path, line number, match offsets. Pipe to jq:${N}"
    print "  ${M}  rg --json TODO | jq 'select(.type==\"match\") | .data.path'${N}"
    print "  ${B}${Y}SEARCH & REPLACE PREVIEW${N}"
    print "  ${G}  rg --replace 'NEW' PATTERN${N}${D}  # preview replacements${N}"
    print "  ${D}This prints what the output WOULD look like with replacements${N}"
    print "  ${D}but does NOT modify files. It's a dry-run. Capture groups work:${N}"
    print "  ${M}  rg 'foo(\\w+)' --replace 'bar\$1'${N}${D}  # foo_x -> bar_x${N}"
    print "  ${B}${Y}STATISTICS${N}"
    print "  ${G}  rg --stats PATTERN${N}${D}   # show match stats after results${N}"
    print "  ${D}Prints: N matches, N matched lines, N files searched,${N}"
    print "  ${D}N files matched, bytes searched, duration. Quick audit.${N}"
    print "  ${B}${Y}CUSTOM FILE TYPES${N}"
    print "  ${M}  rg --type-add 'zpwr:*.zsh' -t zpwr PATTERN${N}"
    print "  ${D}Define a custom type inline and use it immediately.${N}"
    print "  ${D}Persist custom types in ~/.ripgreprc (set RIPGREP_CONFIG_PATH).${N}"
    print "  ${B}${Y}ZPWR INTEGRATION${N}"
    print "  ${D}zpwr grep uses ag (silver searcher) piped into fzf:${N}"
    print "  ${M}  zpwr grep${N}${D}            # ag into fzf for interactive search${N}"
    print "  ${D}zpwr wordsearch searches file contents with fzf preview:${N}"
    print "  ${M}  zpwr wordsearch${N}${D}      # search by word in subdirectory files${N}"
    print "  ${D}Both use bat-powered previews in the fzf window.${N}"
    print "  ${B}${Y}FZF + RG LIVE RELOAD${N}"
    print "  ${D}The ultimate interactive grep: rg feeds fzf, bat previews:${N}"
    print "  ${M}  rg --line-number PATTERN |${N}"
    print "  ${M}    fzf --delimiter : --preview 'bat --highlight-line {2} {1}'${N}"
    print "  ${D}rg outputs file:line:match, fzf splits on :, bat highlights${N}"
    print "  ${D}the matching line. Three tools, one seamless experience.${N}"
    print "  ${B}${Y}CONFIGURATION${N}"
    print "  ${M}  export RIPGREP_CONFIG_PATH=~/.ripgreprc${N}"
    print "  ${D}Put default flags in this file, one per line:${N}"
    print "  ${D}  --smart-case, --hidden, --glob=!.git, --max-columns=200${N}"
    print "  ${D}Also: .rgignore in any directory works like .gitignore —${N}"
    print "  ${D}project-specific patterns that rg will skip.${N}"
    print "  ${D}.ignore files (used by ag too) are also respected by rg.${N}"
}
