PAGE_TITLE="Reading Logs"
PAGE_CHAPTER="CHAPTER 16: THE LOGGING SYSTEM"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}>>> READING LOGS: THE ART OF LOG DIVING <<<${N}"
    print "  ${D}somewhere in that wall of text is the answer you seek${N}"
    print ""
    print "  ${B}${Y}zpwr taillog${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Live tail of the ZPWR log file with ccze colorization.${N}"
    print "  ${G}Watch events stream by in glorious technicolor.${N}"
    print ""
    print "  ${C}  \$ zpwr taillog${N}                ${D}# live colorized tail${N}"
    print ""
    print "  ${G}ccze automatically highlights timestamps, levels, paths,${N}"
    print "  ${G}and errors. Makes raw logs actually readable.${N}"
    print ""
    print "  ${B}${Y}WHAT TO LOOK FOR:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${R}  ERROR${N}  ${D}lines = something broke, investigate immediately${N}"
    print "  ${Y}  WARN${N}   ${D}lines = potential issue, worth noting${N}"
    print "  ${G}  INFO${N}   ${D}lines = normal operations, sanity check${N}"
    print "  ${C}  DEBUG${N}  ${D}lines = details for troubleshooting${N}"
    print "  ${M}  TRACE${N}  ${D}lines = deep internals, very verbose${N}"
    print ""
    print "  ${B}${Y}FILTERING TECHNIQUES:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${C}  \$ grep ERROR \$ZPWR_LOGFILE${N}     ${D}# errors only${N}"
    print "  ${C}  \$ grep -c ERROR \$ZPWR_LOGFILE${N}  ${D}# count errors${N}"
    print "  ${C}  \$ tail -100 \$ZPWR_LOGFILE${N}      ${D}# last 100 lines${N}"
    print ""
    print "  ${B}${Y}TMUX LOG MONITORING SETUP:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Dedicate a tmux pane to zpwr taillog:${N}"
    print ""
    print "  ${D}  1. Split pane: Ctrl-b %${N}"
    print "  ${D}  2. In new pane: zpwr taillog${N}"
    print "  ${D}  3. Work in other pane, watch logs stream${N}"
    print "  ${D}  4. Errors glow red thanks to ccze${N}"
    print ""
    print "  ${B}${Y}LOG MAINTENANCE:${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}Logs grow forever if you let them. ZPWR handles${N}"
    print "  ${G}rotation, but you can manually truncate:${N}"
    print ""
    print "  ${C}  \$ : > \$ZPWR_LOGFILE${N}            ${D}# truncate to zero${N}"
    print ""
    print "  ${D}  // taillog + ccze = the cyberpunk log experience${N}"
    print "  ${D}  // errors in red, info in green, timestamps in cyan${N}"
}
