PAGE_TITLE="Navigation Verbs"
PAGE_CHAPTER="CHAPTER 2: NAVIGATION PROTOCOL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== NAVIGATION VERBS ===${N}"
    print "  ${D}// 39 ways to get where you are going //${N}"
    print ""
    print "  ${C}Navigate the filesystem, ZPWR directories, and frecency${N}"
    print "  ${C}ranked locations with precision.${N}"
    print ""
    print "  ${B}${Y}DIRECTORY MOVEMENT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr cd${N}${D}                    # cd to directory arg${N}"
    print "  ${M}  zpwr f${N}${D}                     # cd to directory arg${N}"
    print "  ${M}  zpwr forward${N}${D}               # cd to directory arg${N}"
    print "  ${M}  zpwr fwd${N}${D}                   # cd to directory arg${N}"
    print "  ${M}  zpwr cdup${N}${D}                  # cd up tree to directory arg${N}"
    print "  ${M}  zpwr r${N}${D}                     # cd up tree to directory arg${N}"
    print "  ${M}  zpwr reverse${N}${D}               # cd up tree to directory arg${N}"
    print "  ${M}  zpwr rvs${N}${D}                   # cd up tree to directory arg${N}"
    print "  ${M}  zpwr catcd${N}${D}                 # cat and cd to first dir${N}"
    print "  ${M}  zpwr clone${N}${D}                 # clone and cd to arg${N}"
    print ""
    print "  ${B}${Y}ZPWR HOME DIRECTORIES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr home${N}${D}                  # go to \$ZPWR${N}"
    print "  ${M}  zpwr homeautoload${N}${D}          # go to \$ZPWR_AUTOLOAD${N}"
    print "  ${M}  zpwr homeautoloadcommon${N}${D}    # go to \$ZPWR_AUTOLOAD_COMMON${N}"
    print "  ${M}  zpwr homecomps${N}${D}             # go to \$ZPWR_COMPS${N}"
    print "  ${M}  zpwr homeenv${N}${D}               # go to \$ZPWR_ENV${N}"
    print "  ${M}  zpwr homeexercism${N}${D}          # cd to \$HOME/Exercism${N}"
    print "  ${M}  zpwr homeinstall${N}${D}           # go to \$ZPWR_INSTALL${N}"
    print "  ${M}  zpwr homelocal${N}${D}             # go to \$ZPWR_LOCAL${N}"
    print "  ${M}  zpwr homescripts${N}${D}           # go to \$ZPWR_SCRIPTS${N}"
    print "  ${M}  zpwr hometest${N}${D}              # go to \$ZPWR_TEST${N}"
    print "  ${M}  zpwr hometests${N}${D}             # go to \$ZPWR_TEST${N}"
    print "  ${M}  zpwr hometmux${N}${D}              # go to \$ZPWR_TMUX${N}"
    print ""
    print "  ${B}${Y}ZPWR SUBDIRECTORIES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr autoload${N}${D}              # cd to autoload directory${N}"
    print "  ${M}  zpwr comps${N}${D}                 # cd to completion directory${N}"
    print "  ${M}  zpwr completions${N}${D}           # cd to completion directory${N}"
    print "  ${M}  zpwr forked${N}${D}                # cd to \$ZPWR_FORKED_DIR${N}"
    print "  ${M}  zpwr fp${N}${D}                    # cd to \$ZPWR_FORKED_DIR${N}"
    print "  ${M}  zpwr hidden${N}${D}                # go to \$ZPWR_HIDDEN_DIR${N}"
    print "  ${M}  zpwr plugins${N}${D}               # cd to \$ZSH_CUSTOM/plugins${N}"
    print "  ${M}  zpwr repo${N}${D}                  # cd to \$ZPWR_REPO_NAME${N}"
    print "  ${M}  zpwr scripts${N}${D}               # cd to scripts directory${N}"
    print "  ${M}  zpwr web${N}${D}                   # cd to web dir${N}"
    print "  ${M}  zpwr zp${N}${D}                    # cd to \$ZPWR_REPO_NAME${N}"
    print "  ${M}  zpwr zpwr${N}${D}                  # cd to \$ZPWR_REPO_NAME${N}"
    print "  ${M}  zpwr zpz${N}${D}                   # cd to repo, checkout, rebase, push${N}"
    print ""
    print "  ${B}${Y}FRECENCY & FZF${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr z${N}${D}                     # cd to z frecency ranked dir${N}"
    print "  ${M}  zpwr zcd${N}${D}                   # list then cd to z ranked dir${N}"
    print "  ${M}  zpwr dirsearch${N}${D}             # cd to a sub dir via fzf${N}"
    print ""
}
