PAGE_TITLE="The One-Letter Verbs"
PAGE_CHAPTER="CHAPTER 24: TIPS, TRICKS & EASTER EGGS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< THE ONE-LETTER VERBS — MAXIMUM POWER, MINIMUM KEYSTROKES >>>${N}"
    print "  ${D}six letters that do the work of six paragraphs${N}"
    print ""
    print "  ${C}ZPWR has 408 verbs. Six of them are single characters.${N}"
    print "  ${C}These are not abbreviations — they are the distilled${N}"
    print "  ${C}essence of the most common operations. One keystroke${N}"
    print "  ${C}each. The speed limit of human-shell interaction.${N}"
    print ""
    print "  ${B}${Y}a — AUTOLOAD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr a${N}"
    print "  ${G}Quick access to the autoload system. When you need${N}"
    print "  ${G}to check on autoloaded functions fast.${N}"
    print ""
    print "  ${B}${Y}c — CAT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr c${N}"
    print "  ${G}The cat operation. View file contents. The most basic${N}"
    print "  ${G}read operation, compressed to one letter.${N}"
    print ""
    print "  ${B}${Y}e — EDIT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr e${N}"
    print "  ${G}Open your editor. The gateway to modification.${N}"
    print "  ${G}Uses your configured \$EDITOR.${N}"
    print ""
    print "  ${B}${Y}f — FILESEARCH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr f${N}"
    print "  ${G}File search. Find things. The single most common${N}"
    print "  ${G}operation after listing and editing.${N}"
    print ""
    print "  ${B}${Y}r — REPLAY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr r${N}"
    print "  ${G}Replay operations. Redo what you did before.${N}"
    print "  ${G}History is not just for reading.${N}"
    print ""
    print "  ${B}${Y}z — ZCD${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr z${N}"
    print "  ${G}Z-jump. Frecency-based directory navigation.${N}"
    print "  ${G}Type a partial path, z figures out the rest.${N}"
    print "  ${G}The single most addictive feature in ZPWR.${N}"
    print ""
    print "  ${B}${G}THE ONE-LETTER ARSENAL:${N}"
    print "  ${C}  a${N}   ${D}autoload system${N}"
    print "  ${C}  c${N}   ${D}cat / view files${N}"
    print "  ${C}  e${N}   ${D}edit files${N}"
    print "  ${C}  f${N}   ${D}file search${N}"
    print "  ${C}  r${N}   ${D}replay${N}"
    print "  ${C}  z${N}   ${D}z-jump directory navigation${N}"
    print ""
    print "  ${D}  // every extra character is latency between thought and action${N}"
    print "  ${D}  // one letter is the event horizon of efficiency${N}"
    print "  ${D}  // below this, there is only telepathy${N}"
    print ""
}
