PAGE_TITLE="Configuring Your Rig"
PAGE_CHAPTER="CHAPTER 1: THE RED PILL"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== CONFIGURING YOUR RIG ===${N}"
    print ""
    print "  ${C}Your terminal is a cockpit. These are the dials.${N}"
    print ""
    print "  ${B}${Y}THE FOUR CONFIG SESSIONS${N}"
    print "  ${C}Each of these opens a curated vim session with the${N}"
    print "  ${C}relevant config files already loaded in buffers:${N}"
    print ""
    print "  ${M}  zpwr brc${N}${D}    # shell aliases file vim session${N}"
    print "  ${D}               opens \$ZPWR_LOCAL/.tokens.sh and related files${N}"
    print "  ${D}               this is where YOUR personal aliases live${N}"
    print ""
    print "  ${M}  zpwr zrc${N}${D}    # zshrc vim session${N}"
    print "  ${D}               opens the zshrc and related zsh configs${N}"
    print "  ${D}               the source of all shell initialization${N}"
    print ""
    print "  ${M}  zpwr vrc${N}${D}    # vimrc/init.vim vim session${N}"
    print "  ${D}               opens vim/nvim config files${N}"
    print "  ${D}               your editor's soul laid bare${N}"
    print ""
    print "  ${M}  zpwr trc${N}${D}    # tmux.conf vim session${N}"
    print "  ${D}               opens tmux configuration${N}"
    print "  ${D}               pane and window management settings${N}"
    print ""
    print "  ${B}${Y}THE TOKENS FILE${N}"
    print "  ${M}  zpwr tokens${N}${D}       # vim the .tokens.sh file${N}"
    print "  ${M}  zpwr vimtokens${N}${D}    # same thing, explicit vim${N}"
    print "  ${M}  zpwr emacstokens${N}${D}  # same thing, emacs edition${N}"
    print "  ${D}  Located at \$ZPWR_LOCAL/.tokens.sh${N}"
    print "  ${D}  This file is gitignored. Put secrets and custom aliases here.${N}"
    print "  ${R}  Never commit this file. It is YOUR local override.${N}"
    print ""
    print "  ${B}${Y}EDITOR COMMANDS${N}"
    print "  ${M}  zpwr edit${N}${D}      # launch \$EDITOR${N}"
    print "  ${M}  zpwr editor${N}${D}    # same thing${N}"
    print "  ${M}  zpwr vimconfig${N}${D} # edit all zpwr configs in vim${N}"
    print ""
    print "  ${B}${Y}THE FULL CONFIG STACK${N}"
    print "  ${G}  \$ZPWR_LOCAL/.tokens.sh${N}${D} ... your aliases and secrets${N}"
    print "  ${G}  \$ZPWR_ENV/.zpwr_env.sh${N}${D} .. env vars and paths${N}"
    print "  ${G}  ~/.zshrc${N}${D} .................. shell entry point${N}"
    print "  ${G}  ~/.vimrc / init.vim${N}${D} ....... editor config${N}"
    print "  ${G}  ~/.tmux.conf${N}${D} .............. tmux config${N}"
    print ""
    print "  ${D}Think of it as: ${M}brc${D} for shell, ${M}zrc${D} for zsh,${N}"
    print "  ${D}${M}vrc${D} for vim, ${M}trc${D} for tmux. Four letters, four kingdoms.${N}"
    print ""
}
