PAGE_TITLE="Runtime State"
PAGE_CHAPTER="CHAPTER 21: ZPWR ENVIRONMENT VARIABLES"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< RUNTIME STATE — THE MACHINE'S SELF-AWARENESS >>>${N}"
    print "  ${D}the shell knows what it is. do you?${N}"
    print ""
    print "  ${C}These variables hold runtime state — what OS you are on,${N}"
    print "  ${C}what TTY you are using, where logs go. They are set${N}"
    print "  ${C}at startup and consulted throughout the session.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_TTY — YOUR TERMINAL IDENTITY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_TTY${N}${D}   # e.g., /dev/ttys003${N}"
    print "  ${G}The TTY device for the current shell session.${N}"
    print "  ${G}Used by ZPWR to track which terminal is which,${N}"
    print "  ${G}especially when managing multiple tmux panes.${N}"
    print ""
    print "  ${D}  The ${M}zpwr tty${D} verb shows your current TTY info.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_OS_TYPE — PLATFORM DETECTION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_OS_TYPE${N}${D}   # Darwin, Linux, etc.${N}"
    print "  ${G}Detected at startup. Used throughout ZPWR to branch${N}"
    print "  ${G}on platform-specific behavior. macOS vs Linux vs BSD,${N}"
    print "  ${G}the right code path fires automatically.${N}"
    print ""
    print "  ${D}  This is why ZPWR works on macOS and Linux without${N}"
    print "  ${D}  you changing a single setting. The OS type decides.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_LOGFILE — THE BLACK BOX${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_LOGFILE${N}"
    print "  ${G}Where ZPWR writes its log output. Debug, info, error,${N}"
    print "  ${G}trace — all levels go here when enabled.${N}"
    print ""
    print "  ${D}  Read the logs:${N}"
    print "  ${M}  zpwr loginfo${N}${D}         info-level messages${N}"
    print "  ${M}  zpwr logdebug${N}${D}        debug-level messages${N}"
    print "  ${M}  zpwr logerror${N}${D}        error-level messages${N}"
    print "  ${M}  zpwr logtrace${N}${D}        trace-level messages${N}"
    print "  ${M}  zpwr taillog${N}${D}         live tail with colorized output${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_COMPSYS_CACHE — COMPLETION CACHE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_COMPSYS_CACHE${N}"
    print "  ${G}Controls the completion system cache. Zsh completions${N}"
    print "  ${G}are expensive to regenerate. This flag keeps them cached.${N}"
    print ""
    print "  ${B}${Y}\$ZPWR_HISTFILE — HISTORY FILE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  echo \$ZPWR_HISTFILE${N}"
    print "  ${G}Your shell history file location. ZPWR manages history${N}"
    print "  ${G}with deduplication and backup. Your commands are sacred.${N}"
    print ""
    print "  ${D}  Related: ${M}zpwr backuphistory${D} and ${M}zpwr restorehistory${N}"
    print ""
    print "  ${B}${G}THE FULL ENV VAR MAP:${N}"
    print "  ${C}  Core paths:${N}      ${D}ZPWR, ZPWR_LOCAL, ZPWR_SCRIPTS, ZPWR_TMUX${N}"
    print "  ${C}  Autoload:${N}        ${D}ZPWR_AUTOLOAD, ZPWR_AUTOLOAD_COMMON${N}"
    print "  ${C}  Flags:${N}           ${D}ZPWR_PROFILING, ZPWR_DEBUG, ZPWR_TRACE${N}"
    print "  ${C}  Display:${N}         ${D}ZPWR_EXA_COMMAND, ZPWR_KEYTIMEOUT${N}"
    print "  ${C}  Runtime:${N}         ${D}ZPWR_TTY, ZPWR_OS_TYPE, ZPWR_LOGFILE${N}"
    print ""
    print "  ${D}  // the machine knows itself. every variable is a mirror.${N}"
    print "  ${D}  // read them to understand the current state of reality.${N}"
    print ""
}
