PAGE_TITLE="Polyglot Execution"
PAGE_CHAPTER="CHAPTER 19: BATCH OPERATIONS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< POLYGLOT EXECUTION — BEYOND THE SHELL >>>${N}"
    print "  ${D}zsh is the conductor, but the orchestra speaks many tongues${N}"
    print ""
    print "  ${C}Sometimes zsh loops aren't enough. Sometimes you need${N}"
    print "  ${C}Python. Sometimes you need background jobs. Sometimes${N}"
    print "  ${C}you need to poll a service until it wakes up or dies.${N}"
    print ""
    print "  ${B}${Y}EXECPY — THE PYTHON BRIDGE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr execpy <python_expression>${N}"
    print "  ${G}Fires a Python expression from the comfort of your shell.${N}"
    print "  ${G}No need to open a REPL. No need for a .py file.${N}"
    print "  ${G}Quick math, string ops, one-liners — python as a verb.${N}"
    print ""
    print "  ${D}  Example: quick calculation${N}"
    print "  ${M}  zpwr execpy '2**128'${N}"
    print "  ${D}  => 340282366920938463463374607431768211456${N}"
    print ""
    print "  ${B}${Y}BACKGROUND — THE SHADOW OPERATIVE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr background <cmd>${N}"
    print "  ${G}Sends a command into the background. Detached. Silent.${N}"
    print "  ${G}It runs in the shadows while you keep working.${N}"
    print "  ${G}Output goes to the void unless you redirect it.${N}"
    print ""
    print "  ${D}  Example: start a long build in the background${N}"
    print "  ${M}  zpwr background make -j8${N}"
    print ""
    print "  ${B}${Y}TIMER — THE STOPWATCH${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr timer <cmd>${N}"
    print "  ${G}Wraps any command in a high-resolution timer.${N}"
    print "  ${G}How long did that take? Now you know. No guessing.${N}"
    print "  ${G}Benchmarking made trivial.${N}"
    print ""
    print "  ${D}  Example: time your shell startup${N}"
    print "  ${M}  zpwr timer zsh -ic exit${N}"
    print ""
    print "  ${B}${Y}POLL — THE WATCHDOG${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr poll <cmd>${N}"
    print "  ${G}Runs a command repeatedly until it succeeds (exit 0).${N}"
    print "  ${G}Waiting for a server to come up? A build to finish?${N}"
    print "  ${G}Poll is your patient, relentless sentinel.${N}"
    print ""
    print "  ${D}  Example: wait for a port to open${N}"
    print "  ${M}  zpwr poll nc -z localhost 8080${N}"
    print ""
    print "  ${B}${G}THE BATCH OPS PHILOSOPHY:${N}"
    print "  ${C}  Loops${N}        ${D}for, for10, whiletrue, whilesleep${N}"
    print "  ${C}  Sweeps${N}       ${D}fordir, fordirupdate, execglob*${N}"
    print "  ${C}  Polyglot${N}     ${D}execpy, background, timer, poll${N}"
    print ""
    print "  ${D}  // the terminal is not a single-threaded mind${N}"
    print "  ${D}  // it is a factory floor. these verbs are the machines.${N}"
    print "  ${D}  // feed them work. they do not tire. they do not complain.${N}"
    print ""
}
