PAGE_TITLE="Transient Prompt & Visual Tweaks"
PAGE_CHAPTER="CHAPTER 26: POWERLEVEL10K & INSTANT PROMPT"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print "  ${B}${M}=== TRANSIENT PROMPT & VISUAL TWEAKS ===${N}"
    print "  ${D}// old prompts fade into ghosts. only the present matters. //${N}"
    print "  ${C}Transient prompt collapses previous prompts to a minimal${N}"
    print "  ${C}form, keeping your scrollback clean and focused. In zpwr${N}"
    print "  ${C}it is currently set to 'off' but easy to enable.${N}"
    print "  ${B}${Y}TRANSIENT PROMPT${N}"
    print "  ${D}When enabled, after you press Enter, the full multi-line${N}"
    print "  ${D}prompt collapses to just the prompt_char symbol (--- or ---).${N}"
    print "  ${D}All segments, git status, directory -- gone from old lines.${N}"
    print "  ${D}Only the current prompt shows full detail.${N}"
    print "  ${M}  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off${N}"
    print "  ${D}Change to ${G}always${D} or ${G}same-dir${D} to enable.${N}"
    print "  ${D}'same-dir' only collapses when you stay in the same directory.${N}"
    print "  ${B}${Y}HOT RELOAD${N}"
    print "  ${D}Edit .p10k.zsh and apply changes without restarting zsh:${N}"
    print "  ${M}  p10k reload${N}"
    print "  ${D}This re-sources .p10k.zsh and rebuilds the prompt in-place.${N}"
    print "  ${D}No exec zsh needed. No losing your command history buffer.${N}"
    print "  ${B}${Y}p10k configure${N}"
    print "  ${D}The interactive configuration wizard. Walks you through:${N}"
    print "  ${D}  - Font detection (powerline glyphs, nerdfont icons)${N}"
    print "  ${D}  - Style selection (rainbow, lean, classic, pure)${N}"
    print "  ${D}  - Separator shapes, line count, frame options${N}"
    print "  ${D}  - Instant prompt mode (verbose, quiet, off)${N}"
    print "  ${D}It generates a fresh .p10k.zsh. ZPWR ships a pre-configured${N}"
    print "  ${D}one in \$ZPWR_ENV/.p10k.zsh (rainbow style, nerdfont-complete).${N}"
    print "  ${D}Running the wizard overwrites it, so back up yours first.${N}"
    print "  ${B}${Y}INSTANT PROMPT vs zpwrClearList${N}"
    print "  ${D}The banner (zpwrClearList) prints colorized file listings on${N}"
    print "  ${D}login. Instant prompt redirects all stdout/stderr during init${N}"
    print "  ${D}to a buffer. If zpwrClearList runs during this window, the${N}"
    print "  ${D}output gets swallowed or garbled. ZPWR's fix:${N}"
    print "  ${D}  1. Check if __p9k_instant_prompt_active is set${N}"
    print "  ${D}  2. If so, defer zpwrClearList to AFTER p10k finalize${N}"
    print "  ${D}  3. The banner appears cleanly after the prompt settles${N}"
    print "  ${B}${Y}THE eza --classify=always FIX${N}"
    print "  ${D}Under instant prompt, fd/stdout gets redirected. eza's${N}"
    print "  ${D}--classify flag (append */ to dirs) auto-detects terminal${N}"
    print "  ${D}capabilities. When stdout is redirected, it thinks there's${N}"
    print "  ${D}no terminal and drops the indicators.${N}"
    print "  ${D}Fix: use --classify=always to force classification regardless${N}"
    print "  ${D}of fd state. ZPWR_EXA_COMMAND uses this:${N}"
    print "  ${M}  command eza --git -il --classify=always -H --color-scale -g -a${N}"
    print "  ${B}${Y}\$TTY IMMUNE TO FD REDIRECTS${N}"
    print "  ${D}Zsh sets \$TTY before rc files load. Instant prompt redirects${N}"
    print "  ${D}fds 0/1/2, but \$TTY still points to the real terminal.${N}"
    print "  ${D}ZPWR captures it: ${M}export ZPWR_TTY=\$TTY${N}"
    print "  ${D}This is used by the custom_tty prompt segment.${N}"
}
