PAGE_TITLE="The Doctor Is In (1/2)"
PAGE_CHAPTER="CHAPTER 7: HEALTH & DIAGNOSTICS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE DOCTOR IS IN ===${N}"
    print "  ${D}// every system needs a physician. yours lives at zpwr doctor. //${N}"
    print ""
    print "  ${C}Your shell is a living organism. It accumulates cruft, grows${N}"
    print "  ${C}tumors in PATH, and occasionally develops broken symlinks.${N}"
    print "  ${C}The doctor runs a full-body scan and tells you what hurts.${N}"
    print ""
    print "  ${B}${Y}INVOKE THE DOCTOR${N}"
    print "  ${M}  zpwr doctor${N}${D}              # full diagnostic scan${N}"
    print "  ${M}  zpwr doctor -h${N}${D}           # help with detailed check list${N}"
    print ""
    print "  ${B}${Y}WHAT IT CHECKS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}1. STALE .zwc FILES${N}"
    print "  ${D}     Compiled zsh files older than their source.${N}"
    print "  ${D}     Fix: ${M}zpwr recompile${N}"
    print ""
    print "  ${G}2. ZCOMPDUMP FRESHNESS${N}"
    print "  ${D}     Completion dump older than 1 week.${N}"
    print "  ${D}     Fix: ${M}zpwr regenzsh${N}"
    print ""
    print "  ${G}3. DUPLICATE PATH ENTRIES${N}"
    print "  ${D}     Every duplicate is a wasted hash lookup.${N}"
    print "  ${D}     Fix: ${M}zpwr deduppaths${N}"
    print ""
    print "  ${G}4. DUPLICATE/MISSING FPATH ENTRIES${N}"
    print "  ${D}     Same disease, different organ.${N}"
    print ""
    print "  ${G}5. BROKEN SYMLINKS${N}"
    print "  ${D}     Dangling symlinks in \$ZPWR.${N}"
    print ""
    print "  ${D}  Continued on next page...${N}"
    print ""
}
