PAGE_TITLE="The Learning System"
PAGE_CHAPTER="CHAPTER 4: THE SEARCH ENGINE"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== THE LEARNING SYSTEM ===${N}"
    print "  ${D}// your shell remembers what you learn //${N}"
    print ""
    print "  ${C}The zsh-learn plugin turns your shell into a persistent${N}"
    print "  ${C}knowledge base backed by MySQL. Save commands, search them,${N}"
    print "  ${C}quiz yourself, and build a personal learning collection.${N}"
    print ""
    print "  ${B}${Y}CORE VERBS${N}"
    print "  ${M}  zpwr learn${N}${D}                  # save a learning entry${N}"
    print "  ${M}  zpwr searchl${N}${D}                # search the collection${N}"
    print "  ${M}  zpwr quiz${N}${D}                   # quiz yourself${N}"
    print "  ${M}  zpwr quizall${N}${D}                # quiz all entries${N}"
    print "  ${M}  zpwr redo${N}${D}                   # redo last search as SQL update${N}"
    print ""
    print "  ${B}${Y}SEARCH VARIANTS${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr se${N}${D}                     # basic search${N}"
    print "  ${M}  zpwr see${N}${D}                    # category search${N}"
    print "  ${M}  zpwr seee${N}${D}                   # timestamp search${N}"
    print "  ${M}  zpwr ser${N}${D}                    # random search${N}"
    print "  ${M}  zpwr sef${N}${D}                    # search into fzf${N}"
    print "  ${M}  zpwr searchall${N}${D}              # entire collection into fzf${N}"
    print "  ${M}  zpwr searchfull${N}${D}             # entire collection into fzf${N}"
    print "  ${M}  zpwr searchle${N}${D}               # category search (alias for see)${N}"
    print "  ${M}  zpwr searchlee${N}${D}              # timestamp search (alias for seee)${N}"
    print "  ${M}  zpwr learnsearch${N}${D}            # search the collection${N}"
    print "  ${M}  zpwr rsql${N}${D}                   # redo into vim${N}"
    print "  ${M}  zpwr redosql${N}${D}                # redo into vim${N}"
    print ""
    print "  ${B}${Y}MANAGEMENT${N}"
    print "  ${M}  zpwr learndel${N}${D}               # delete entry${N}"
    print "  ${M}  zpwr learndelete${N}${D}            # delete entry (alias)${N}"
    print "  ${M}  zpwr delid${N}${D}                  # delete by ID${N}"
    print "  ${M}  zpwr editl${N}${D}                  # edit entry by ID${N}"
    print "  ${M}  zpwr getlearn${N}${D}               # get all entries${N}"
    print "  ${M}  zpwr learnget${N}${D}               # get all entries${N}"
    print "  ${M}  zpwr createlearningcollection${N}${D} # create MySQL table${N}"
    print "  ${M}  zpwr droplearningcollection${N}${D}   # drop MySQL table${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${D}  Entries are stored in a MySQL database (configurable via${N}"
    print "  ${D}  \$ZPWR_SCHEMA_NAME and \$ZPWR_TABLE_NAME). Each entry has${N}"
    print "  ${D}  a category, timestamp, and content. The quiz system pulls${N}"
    print "  ${D}  random entries and tests your recall.${N}"
    print ""
    print "  ${D}  Plugin: ${C}MenkeTechnologies/zsh-learn${N}"
    print ""
}
