PAGE_TITLE="Loop Warriors"
PAGE_CHAPTER="CHAPTER 19: BATCH OPERATIONS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< LOOP WARRIORS — THE REPETITION TOOLKIT >>>${N}"
    print "  ${D}because doing things once is for civilians${N}"
    print ""
    print "  ${C}The batch operations verbs are the assault rifles${N}"
    print "  ${C}of the ZPWR arsenal. Point them at a problem,${N}"
    print "  ${C}pull the trigger, and watch every target fall.${N}"
    print ""
    print "  ${B}${Y}THE FOR LOOP — YOUR BASIC INFANTRY${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr for <cmd> <args...>${N}"
    print "  ${G}Executes a command for each argument passed to it.${N}"
    print "  ${G}Stdin becomes your ammo belt — pipe lines in, each one fires.${N}"
    print ""
    print "  ${D}  Example: run a command against multiple targets${N}"
    print "  ${M}  echo 'file1.txt\nfile2.txt' | zpwr for wc -l${N}"
    print ""
    print "  ${B}${Y}FOR10 — THE BURST-FIRE VARIANT${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr for10 <cmd>${N}"
    print "  ${G}Runs your command 10 times. No arguments, no mercy.${N}"
    print "  ${G}Perfect for stress testing, benchmarking, or just${N}"
    print "  ${G}asserting dominance over your CPU.${N}"
    print ""
    print "  ${D}  Example: benchmark a command 10 times${N}"
    print "  ${M}  zpwr for10 zpwr bench${N}"
    print ""
    print "  ${B}${Y}WHILETRUE — THE INFINITE LOOP${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr whiletrue <cmd>${N}"
    print "  ${G}Runs your command forever. Ctrl-C is your only exit.${N}"
    print "  ${G}For monitoring, watching, waiting. The sentinel loop.${N}"
    print ""
    print "  ${D}  Example: watch disk usage forever${N}"
    print "  ${M}  zpwr whiletrue df -h /${N}"
    print "  ${R}  WARNING: ${N}${D}there is no break condition. You ARE the break.${N}"
    print ""
    print "  ${B}${Y}WHILESLEEP — THE PATIENT SNIPER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr whilesleep <seconds> <cmd>${N}"
    print "  ${G}Like whiletrue, but sleeps between rounds.${N}"
    print "  ${G}Polling with grace. Surveillance with manners.${N}"
    print ""
    print "  ${D}  Example: check a URL every 30 seconds${N}"
    print "  ${M}  zpwr whilesleep 30 curl -s -o /dev/null -w '%{http_code}' https://example.com${N}"
    print ""
    print "  ${B}${G}TACTICAL SUMMARY:${N}"
    print "  ${C}  for${N}          ${D}iterate over stdin lines${N}"
    print "  ${C}  for10${N}        ${D}run 10 times, no questions asked${N}"
    print "  ${C}  whiletrue${N}    ${D}infinite loop, Ctrl-C to escape${N}"
    print "  ${C}  whilesleep${N}   ${D}infinite loop with naptime between rounds${N}"
    print ""
    print "  ${D}  // in the loop, there is no time, only iterations${N}"
    print "  ${D}  // the loop does not end. the operator ends the loop.${N}"
    print ""
}
