PAGE_TITLE="Command Replay"
PAGE_CHAPTER="CHAPTER 11: MONITORING & AUTOMATION"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}=== COMMAND REPLAY ===${N}"
    print "  ${D}// your history is a script. replay it on demand. //${N}"
    print ""
    print "  ${C}The ${M}replay${C} verb plays back the last N commands from your${N}"
    print "  ${C}shell history. Three modes: look, execute, or tmux pane.${N}"
    print "  ${C}It is a VCR for your terminal.${N}"
    print ""
    print "  ${B}${Y}BASIC USAGE${N}"
    print "  ${M}  zpwr replay${N}${D}                         # preview last 10 commands${N}"
    print "  ${M}  zpwr replay 20${N}${D}                      # preview last 20${N}"
    print "  ${M}  zpwr replay 5 exec${N}${D}                  # execute last 5 with timing${N}"
    print "  ${M}  zpwr replay 10 tmux${N}${D}                 # replay in a tmux split pane${N}"
    print ""
    print "  ${B}${Y}THE THREE MODES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print ""
    print "  ${G}PREVIEW MODE${N}${D} (default, safe)${N}"
    print "  ${M}  zpwr replay${N}"
    print "  ${M}  zpwr replay 20 preview${N}"
    print "  ${D}  Lists the commands with line numbers. Nothing executes.${N}"
    print "  ${D}  Use this to review what you did before replaying it.${N}"
    print "  ${D}  The output shows helpful hints for switching to exec/tmux.${N}"
    print ""
    print "  ${G}EXEC MODE${N}${D} (runs in current shell)${N}"
    print "  ${M}  zpwr replay 5 exec${N}"
    print "  ${D}  Executes each command sequentially in your current shell.${N}"
    print "  ${D}  Each command shows:${N}"
    print "  ${D}  - Command number [1/5]${N}"
    print "  ${D}  - The command being run${N}"
    print "  ${D}  - Exit status (green ok or red exit code)${N}"
    print "  ${D}  - Elapsed time in milliseconds${N}"
    print ""
    print "  ${R}  WARNING:${N}${R} This runs real commands. If your last 5 commands${N}"
    print "  ${R}  included ${M}rm -rf something${R}, it will do it again.${N}"
    print "  ${R}  Always preview first.${N}"
    print ""
    print "  ${G}TMUX MODE${N}${D} (runs in a new pane)${N}"
    print "  ${M}  zpwr replay 10 tmux${N}"
    print "  ${D}  Opens a new tmux split pane and replays commands there.${N}"
    print "  ${D}  Your current pane is untouched. You can watch the replay${N}"
    print "  ${D}  happen side-by-side with your current work.${N}"
    print "  ${D}  The pane waits for Enter when done, then cleans up.${N}"
    print "  ${D}  Requires an active tmux session.${N}"
    print ""
    print "  ${B}${Y}USE CASES${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${G}  Reproduce a bug:${N}${D}       zpwr replay 3 exec${N}"
    print "  ${G}  Demo your workflow:${N}${D}     zpwr replay 20 tmux${N}"
    print "  ${G}  Audit what you did:${N}${D}     zpwr replay 50${N}"
    print "  ${G}  Re-run a build chain:${N}${D}   zpwr replay 4 exec${N}"
    print ""
    print "  ${B}${Y}HOW IT WORKS${N}"
    print "  ${D}  Uses ${C}fc -rl -N${D} to extract the last N history entries.${N}"
    print "  ${D}  Reverses them to chronological order. In exec mode,${N}"
    print "  ${D}  each command is eval'd with timing via EPOCHREALTIME.${N}"
    print "  ${D}  In tmux mode, a temp script is built and executed in${N}"
    print "  ${D}  a split pane with a 0.5s delay between commands for${N}"
    print "  ${D}  readability. The script self-destructs after completion.${N}"
    print ""
}
