PAGE_TITLE="Directory Sweeps"
PAGE_CHAPTER="CHAPTER 19: BATCH OPERATIONS"
PAGE_CONTENT() {
    local C=$'\033[36m' G=$'\033[32m' Y=$'\033[33m' R=$'\033[31m'
    local M=$'\033[35m' B=$'\033[1m' D=$'\033[2m' N=$'\033[0m'
    print ""
    print "  ${B}${M}<<< DIRECTORY SWEEPS — CARPET BOMBING YOUR FILESYSTEM >>>${N}"
    print "  ${D}one directory at a time, or all of them at once${N}"
    print ""
    print "  ${C}Single-file loops are amateur hour.${N}"
    print "  ${C}Real operators sweep directories. They glob patterns.${N}"
    print "  ${C}They parallelize. These verbs are your air support.${N}"
    print ""
    print "  ${B}${Y}FORDIR — THE DIRECTORY CRAWLER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr fordir <cmd>${N}"
    print "  ${G}Iterates into each subdirectory of the current dir${N}"
    print "  ${G}and executes the command inside it. cd in, run, cd out.${N}"
    print "  ${G}Like a SWAT team clearing rooms one by one.${N}"
    print ""
    print "  ${D}  Example: check git status in every project dir${N}"
    print "  ${M}  cd ~/repos && zpwr fordir git status -s${N}"
    print ""
    print "  ${B}${Y}FORDIRUPDATE — THE MASS UPDATER${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr fordirupdate${N}"
    print "  ${G}Enters every subdirectory and runs git pull.${N}"
    print "  ${G}Your entire project portfolio, synced in one command.${N}"
    print "  ${G}Monday morning? Run this first. Coffee second.${N}"
    print ""
    print "  ${D}  Example: update all repos under ~/repos${N}"
    print "  ${M}  cd ~/repos && zpwr fordirupdate${N}"
    print ""
    print "  ${B}${Y}EXECGLOB — GLOB AND EXECUTE${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr execglob <glob> <cmd>${N}"
    print "  ${G}Finds files matching a glob pattern and runs your command${N}"
    print "  ${G}against each one. Pattern matching meets execution.${N}"
    print "  ${G}The regex sniper rifle of file operations.${N}"
    print ""
    print "  ${D}  Example: lint every Python file in the tree${N}"
    print "  ${M}  zpwr execglob '*.py' pylint${N}"
    print ""
    print "  ${B}${Y}EXECGLOBPARALLEL — CONCURRENT DEVASTATION${N}"
    print "  ${D}──────────────────────────────────────────────────────────${N}"
    print "  ${M}  zpwr execglobparallel <glob> <cmd>${N}"
    print "  ${G}Same as execglob, but fires all jobs in parallel.${N}"
    print "  ${G}Every CPU core gets drafted into service.${N}"
    print "  ${R}  Your fan will spin up. This is normal. This is power.${N}"
    print ""
    print "  ${D}  Example: format every .rs file in parallel${N}"
    print "  ${M}  zpwr execglobparallel '*.rs' rustfmt${N}"
    print ""
    print "  ${B}${G}CHOOSING YOUR WEAPON:${N}"
    print "  ${C}  fordir${N}             ${D}run cmd in each subdirectory${N}"
    print "  ${C}  fordirupdate${N}       ${D}git pull in each subdirectory${N}"
    print "  ${C}  execglob${N}           ${D}glob match + execute sequentially${N}"
    print "  ${C}  execglobparallel${N}   ${D}glob match + execute in parallel${N}"
    print ""
    print "  ${D}  // sequential is predictable. parallel is fast.${N}"
    print "  ${D}  // choose based on whether output order matters.${N}"
    print "  ${D}  // when in doubt, go parallel. life is short.${N}"
    print ""
}
