brew install --cask ableton-live-suite
brew install --cask adobe-acrobat-reader
brew install --cask alacritty
brew install --cask alfred
brew install --cask anaconda
brew install --cask android-platform-tools
brew install --cask android-sdk
brew install --cask android-studio
brew install --cask appcode
brew install --cask arduino
brew install --cask audacity
brew install --cask balsamiq-wireframes
brew install --cask bettertouchtool
brew install --cask bitwig-studio
brew install --cask blackhole-16ch
brew install --cask blender
brew install --cask chromedriver
brew install --cask clion
brew install --cask cycling74-max
brew install --cask datagrip
brew install --cask db-browser-for-sqlite
brew install --cask discord
brew install --cask disk-inventory-x
brew install --cask dotnet-sdk
brew install --cask duet
brew install --cask electric-sheep
brew install --cask firefox
brew install --cask fl-studio
brew install --cask folx
brew install --cask gimp
brew install --cask goland
brew install --cask google-chrome
brew install --cask hex-fiend
brew install --cask intellij-idea
brew install --cask iterm2
brew install --cask keyboard-maestro
brew install --cask kicad
brew install --cask latexit
brew install --cask libreoffice
brew install --cask mactex
brew install --cask mattermost
brew install --cask melodics
brew install --cask microsoft-teams
brew install --cask multibit-hd
brew install --cask obs
brew install --cask onyx
brew install --cask phpstorm
brew install --cask postico
brew install --cask postman
brew install --cask pycharm
brew install --cask rar
brew install --cask react-studio
brew install --cask reaper
brew install --cask rider
brew install --cask robo-3t
brew install --cask rowanj-gitx
brew install --cask rstudio
brew install --cask rubymine
brew install --cask scenebuilder
brew install --cask slack
brew install --cask spotify
brew install --cask the-unarchiver
brew install --cask thunderbird
brew install --cask tor-browser
brew install --cask transmission
brew install --cask tunnelblick
brew install --cask vagrant
brew install --cask visual-studio-code
brew install --cask vnc-viewer
brew install --cask webstorm
brew install --cask wireshark
brew install --cask xld
brew install --cask xquartz
brew install --cask zoom
brew install --cask zotero
