brew install --cask adafruit-arduino
brew install --cask adobe-acrobat-reader
brew install --cask adoptopenjdk8
brew install --cask alacritty
brew install --cask alfred
brew install --cask android-platform-tools
brew install --cask android-studio
brew install --cask appcode
brew install --cask audacity
brew install --cask balsamiq-wireframes
brew install --cask bettertouchtool
brew install --cask bitwig-studio
brew install --cask clion
brew install --cask cycling74-max
brew install --cask datagrip
brew install --cask db-browser-for-sqlite
brew install --cask discord
brew install --cask disk-inventory-x
brew install --cask docker
brew install --cask duet
brew install --cask eclipse-jee
brew install --cask electric-sheep
brew install --cask emacs
brew install --cask firefox
brew install --cask fl-studio
brew install --cask font-codenewroman-nerd-font
brew install --cask font-fantasquesansmono-nerd-font
brew install --cask font-hack-nerd-font
brew install --cask font-inconsolata-nerd-font
brew install --cask font-sourcecodepro-nerd-font
brew install --cask gimp
brew install --cask goland
brew install --cask google-chrome
brew install --cask hex-fiend
brew install --cask intellij-idea
brew install --cask iterm2
brew install --cask java
brew install --cask java11
brew install --cask java6
brew install --cask java8
brew install --cask karabiner
brew install --cask keyboard-maestro
brew install --cask kicad
brew install --cask kitty
brew install --cask latexit
brew install --cask libreoffice
brew install --cask macs-fan-control
brew install --cask mactex
brew install --cask macvim
brew install --cask mattermost
brew install --cask microsoft-teams
brew install --cask multibit-hd
brew install --cask mysqlworkbench
brew install --cask ngrok
brew install --cask onyx
brew install --cask opera
brew install --cask phpstorm
brew install --cask postico
brew install --cask postman
brew install --cask processing
brew install --cask pycharm
brew install --cask qt-creator
brew install --cask racket
brew install --cask rar
brew install --cask react-studio
brew install --cask rider
brew install --cask robo-3t
brew install --cask rowanj-gitx
brew install --cask rstudio
brew install --cask rubymine
brew install --cask scenebuilder
brew install --cask skim
brew install --cask skype
brew install --cask slack
brew install --cask soundflower
brew install --cask splice
brew install --cask spotify
brew install --cask station
brew install --cask sublime-text
brew install --cask switchresx
brew install --cask sysex-librarian
brew install --cask tcl
brew install --cask texmaker
brew install --cask the-unarchiver
brew install --cask thunderbird
brew install --cask tor-browser
brew install --cask tunnelblick
brew install --cask vagrant
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask vnc-viewer
brew install --cask webstorm
brew install --cask wine-stable
brew install --cask wireshark
brew install --cask xld
brew install --cask xquartz
brew install --cask zotero
