brew install aalib
brew install ack
brew install activemq
brew install adns
brew install aften
brew install akka
brew install algol68g
brew install alpine
brew install ansible
brew install ant
brew install aom
brew install apache-spark
brew install apr
brew install apr-util
brew install arduino-cli
brew install argon2
brew install aria2
brew install asciidoc
brew install asciidoctor
brew install asciinema
brew install aspcud
brew install aspell
brew install assimp
brew install atk
brew install autoconf
brew install automake
brew install autossh
brew install aview
brew install avrdude
brew install awscli
brew install bash
brew install bash-completion
brew install bash-snippets
brew install bashdb
brew install bats
brew install bdw-gc
brew install berkeley-db
brew install berkeley-db@4
brew install bison
brew install bmon
brew install boost
brew install boxes
brew install brotli
brew install browserpass
brew install bsdmake
brew install c-ares
brew install ca-certificates
brew install cabal-install
brew install cairo
brew install cassandra
brew install catimg
brew install ccrypt
brew install ccze
brew install chapel
brew install chkrootkit
brew install cjson
brew install clingo
brew install clisp
brew install clojure
brew install cmake
brew install cmatrix
brew install cmocka
brew install colordiff
brew install conan
brew install confuse
brew install coreutils
brew install cowsay
brew install cpanminus
brew install cpptoml
brew install crystal
brew install cscope
brew install ctags
brew install ctop
brew install cunit
brew install curl
brew install cython
brew install dart
brew install dav1d
brew install dbus
brew install dcraw
brew install dhex
brew install dialog
brew install diff-so-fancy
brew install docbook
brew install docbook-xsl
brew install double-conversion
brew install doxygen
brew install eigen
brew install elixir
brew install elm
brew install emacs
brew install erlang
brew install etcd
brew install exa
brew install exercism
brew install expat
brew install faac
brew install faad2
brew install fb303
brew install fbthrift
brew install ffmpeg
brew install fftw
brew install figlet
brew install fish
brew install fizz
brew install flac
brew install fluid-synth
brew install fmt
brew install folly
brew install fontconfig
brew install fop
brew install fortune
brew install fpc
brew install fping
brew install freetds
brew install freetype
brew install frei0r
brew install fribidi
brew install fswatch
brew install fzf
brew install gawk
brew install gcc
brew install gd
brew install gdbm
brew install gdk-pixbuf
brew install geckodriver
brew install geoip
brew install gettext
brew install gflags
brew install gforth
brew install ghc
brew install ghostscript
brew install giflib
brew install gifsicle
brew install git
brew install glassfish
brew install glib
brew install glib-networking
brew install global
brew install glog
brew install gmp
brew install gnu-cobol
brew install gnu-getopt
brew install gnu-prolog
brew install gnu-sed
brew install gnupg
brew install gnutls
brew install go
brew install go-md2man
brew install gobject-introspection
brew install googletest
brew install gpatch
brew install gperftools
brew install gpgme
brew install gradle
brew install grails
brew install grap
brew install graphene
brew install graphicsmagick
brew install graphite2
brew install graphviz
brew install grc
brew install greed
brew install grep
brew install groonga
brew install groovy
brew install gsasl
brew install gsettings-desktop-schemas
brew install gst-plugins-bad
brew install gst-plugins-base
brew install gst-plugins-good
brew install gst-plugins-ugly
brew install gstreamer
brew install gtk+3
brew install gts
brew install guile
brew install harfbuzz
brew install heroku
brew install heroku-node
brew install hexedit
brew install hicolor-icon-theme
brew install hidapi
brew install hping
brew install html2text
brew install htop
brew install httpd
brew install httpie
brew install httrack
brew install hub
brew install hunspell
brew install hwloc
brew install hydra
brew install icu4c
brew install ifstat
brew install ilmbase
brew install imagemagick
brew install imagemagick@6
brew install imap-uw
brew install imath
brew install imlib2
brew install iperf
brew install iperf3
brew install isl
brew install jansson
brew install jasper
brew install java-service-wrapper
brew install jbig2dec
brew install jemalloc
brew install jenv
brew install jnettop
brew install john-jumbo
brew install jpeg
brew install jpeg-turbo
brew install jpeg-xl
brew install jq
brew install kafka
brew install kotlin
brew install krb5
brew install kubernetes-cli
brew install lame
brew install leiningen
brew install leptonica
brew install less
brew install lftp
brew install libao
brew install libarchive
brew install libass
brew install libassuan
brew install libavif
brew install libb2
brew install libbluray
brew install libcaca
brew install libcbor
brew install libcroco
brew install libcuefile
brew install libde265
brew install libepoxy
brew install libev
brew install libevent
brew install libffi
brew install libfido2
brew install libftdi
brew install libftdi0
brew install libgcrypt
brew install libgit2
brew install libgit2-glib
brew install libgpg-error
brew install libgtop
brew install libheif
brew install libice
brew install libiconv
brew install libid3tag
brew install libidn
brew install libidn2
brew install libksba
brew install liblqr
brew install libmaxminddb
brew install libmetalink
brew install libmikmod
brew install libmms
brew install libmng
brew install libmodplug
brew install libmpc
brew install libmpdclient
brew install libnet
brew install libnfs
brew install libnghttp2
brew install libnice
brew install libogg
brew install libomp
brew install libpng
brew install libpq
brew install libproxy
brew install libpsl
brew install libpthread-stubs
brew install libpython-tabulate
brew install libraw
brew install libreplaygain
brew install librist
brew install librsvg
brew install libsamplerate
brew install libscrypt
brew install libshout
brew install libsigsegv
brew install libsm
brew install libsmi
brew install libsndfile
brew install libsodium
brew install libsoup
brew install libsoup@2
brew install libsoxr
brew install libssh
brew install libssh2
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libunistring
brew install libupnp
brew install libusb
brew install libusb-compat
brew install libusrsctp
brew install libuv
brew install libvidstab
brew install libvmaf
brew install libvorbis
brew install libvpx
brew install libvterm
brew install libx11
brew install libxau
brew install libxaw
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxft
brew install libxinerama
brew install libxml2
brew install libxmu
brew install libxpm
brew install libxrender
brew install libxt
brew install libyaml
brew install libzip
brew install links
brew install liquibase
brew install little-cms2
brew install llvm
brew install llvm@11
brew install llvm@12
brew install llvm@13
brew install lua
brew install lua@5.1
brew install luajit
brew install luajit-openresty
brew install luarocks
brew install luv
brew install lynis
brew install lz4
brew install lzo
brew install m4
brew install macos-term-size
brew install mad
brew install mailutils
brew install makedepend
brew install man2html
brew install maven
brew install mbedtls
brew install md4c
brew install mecab
brew install mecab-ipadic
brew install mercurial
brew install meson
brew install midnight-commander
brew install minicom
brew install minimal-racket
brew install mksh
brew install mongocli
brew install mongosh
brew install moreutils
brew install mp3blaster
brew install mpc
brew install mpd
brew install mpdecimal
brew install mpfr
brew install mpg123
brew install msgpack
brew install mtr
brew install musepack
brew install mutt
brew install mysql
brew install mysql-client
brew install mytop
brew install nasm
brew install ncdu
brew install ncmpcpp
brew install ncurses
brew install neovim
brew install netpbm
brew install nettle
brew install nghttp2
brew install nginx
brew install nim
brew install ninja
brew install ninvaders
brew install nmap
brew install nnn
brew install node
brew install node@14
brew install node@16
brew install npth
brew install numpy
brew install nvm
brew install nyancat
brew install ocaml
brew install ocamlbuild
brew install oniguruma
brew install opam
brew install open-mpi
brew install openblas
brew install opencore-amr
brew install openexr
brew install openjdk
brew install openjdk@11
brew install openjpeg
brew install openldap
brew install openshift-cli
brew install openssl@1.1
brew install openssl@3
brew install openvpn
brew install opus
brew install opusfile
brew install orc
brew install p11-kit
brew install p7zip
brew install pandoc
brew install pango
brew install pass
brew install pcre
brew install pcre2
brew install peco
brew install perl
brew install pg_top
brew install pgcli
brew install php
brew install phpunit
brew install pidof
brew install pinentry
brew install pinentry-mac
brew install pipes-sh
brew install pixman
brew install pkcs11-helper
brew install pkg-config
brew install polyml
brew install ponysay
brew install popt
brew install portaudio
brew install portmidi
brew install postgresql
brew install protobuf
brew install proxychains-ng
brew install pssh
brew install pstree
brew install pv
brew install py2cairo
brew install py3cairo
brew install pygobject3
brew install python-tabulate
brew install python@3.10
brew install python@3.8
brew install python@3.9
brew install qrencode
brew install qt
brew install r
brew install rakudo-star
brew install ranger
brew install rav1e
brew install raylib
brew install rbspy
brew install rc
brew install re2c
brew install readline
brew install reattach-to-user-namespace
brew install rebar
brew install rebar3
brew install redis
brew install ripgrep
brew install rlwrap
brew install rsync
brew install rtmpdump
brew install rubberband
brew install ruby
brew install ruby@3.0
brew install rust
brew install rustup-init
brew install s-lang
brew install s-search
brew install sbt
brew install scala
brew install screenfetch
brew install sdl
brew install sdl2
brew install sdl2_image
brew install sdl2_mixer
brew install sdl2_ttf
brew install sdl_image
brew install sdl_mixer
brew install sdl_ttf
brew install shared-mime-info
brew install shellcheck
brew install shfmt
brew install six
brew install sl
brew install slurm
brew install smpeg
brew install snappy
brew install sntop
brew install socat
brew install source-highlight
brew install sox
brew install spaceinvaders-go
brew install spark
brew install speedtest-cli
brew install speex
brew install sphinx-doc
brew install sqlite
brew install srt
brew install srtp
brew install subversion
brew install swi-prolog
brew install swig
brew install taglib
brew install tal
brew install tbb
brew install tcl-tk
brew install tcptraceroute
brew install telnet
brew install tesseract
brew install texi2html
brew install texinfo
brew install the_silver_searcher
brew install thefuck
brew install theora
brew install tidy-html5
brew install tig
brew install tmux
brew install toilet
brew install tokei
brew install tokyo-cabinet
brew install tomcat
brew install tomcat@9
brew install tomee-plume
brew install tor
brew install torsocks
brew install tree
brew install tree-sitter
brew install two-lame
brew install ufraw
brew install unbound
brew install unibilium
brew install unison-language
brew install universal-ctags
brew install unixodbc
brew install urlview
brew install utf8proc
brew install vala
brew install vim
brew install vnstat
brew install w3m
brew install wangle
brew install watch
brew install watchman
brew install webp
brew install weechat
brew install wget
brew install with-readline
brew install wren
brew install wren-cli
brew install wren-console
brew install wxwidgets
brew install x264
brew install x265
brew install xmlto
brew install xorgproto
brew install xterm
brew install xvid
brew install xxhash
brew install xz
brew install yamllint
brew install yasm
brew install zbar
brew install zeromq
brew install zimg
brew install zlib
brew install zookeeper
brew install zplug
brew install zsh
brew install zsh-lovers
brew install zshdb
brew install zstd
brew install zzz
