gem install actioncable
gem install actionmailer
gem install actionpack
gem install actionview
gem install activejob
gem install activemodel
gem install activerecord
gem install activestorage
gem install activesupport
gem install addressable
gem install arel
gem install ast
gem install backports
gem install bigdecimal
gem install bindex
gem install builder
gem install bundler
gem install byebug
gem install capybara
gem install childprocess
gem install cmath
gem install coderay
gem install coffee-rails
gem install coffee-script
gem install coffee-script-source
gem install colorator
gem install concurrent-ruby
gem install crass
gem install csv
gem install daemons
gem install date
gem install dbm
gem install debase
gem install debase-ruby_core_source
gem install did_you_mean
gem install diff-lcs
gem install docile
gem install em-websocket
gem install erubi
gem install erubis
gem install etc
gem install eventmachine
gem install execjs
gem install fcntl
gem install ffi
gem install fiddle
gem install fileutils
gem install forwardable-extended
gem install github-markup
gem install globalid
gem install http_parser.rb
gem install i18n
gem install io-console
gem install ipaddr
gem install jaro_winkler
gem install jbuilder
gem install jekyll
gem install jekyll-feed
gem install jekyll-sass-converter
gem install jekyll-seo-tag
gem install jekyll-watch
gem install json
gem install kramdown
gem install liquid
gem install listen
gem install loofah
gem install mail
gem install marcel
gem install mercenary
gem install method_source
gem install mimemagic
gem install mini_mime
gem install mini_portile2
gem install minima
gem install minitest
gem install minitest-power_assert
gem install multi_json
gem install mustermann
gem install mysql2
gem install net-telnet
gem install nio4r
gem install nokogiri
gem install openssl
gem install parallel
gem install parser
gem install pathutil
gem install power_assert
gem install powerpack
gem install pry
gem install psych
gem install public_suffix
gem install puma
gem install rack
gem install rack-protection
gem install rack-test
gem install rails
gem install rails-dom-testing
gem install rails-html-sanitizer
gem install railties
gem install rainbow
gem install rake
gem install rb-fsevent
gem install rb-inotify
gem install rdoc
gem install redcarpet
gem install rouge
gem install rspec
gem install rspec-core
gem install rspec-expectations
gem install rspec-mocks
gem install rspec-support
gem install rubocop
gem install ruby-debug-ide
gem install ruby-progressbar
gem install ruby_dep
gem install rubygems-update
gem install rubyzip
gem install safe_yaml
gem install sass
gem install sass-listen
gem install sass-rails
gem install scanf
gem install sdbm
gem install selenium-webdriver
gem install shotgun
gem install simplecov
gem install simplecov-html
gem install sinatra
gem install sinatra-contrib
gem install spring
gem install spring-watcher-listen
gem install sprockets
gem install sprockets-rails
gem install stringio
gem install strscan
gem install test-unit
gem install thin
gem install thor
gem install thread_safe
gem install tilt
gem install tmuxinator
gem install travis-cli
gem install turbolinks
gem install turbolinks-source
gem install tzinfo
gem install uglifier
gem install unicode-display_width
gem install web-console
gem install webrick
gem install websocket-driver
gem install websocket-extensions
gem install xdg
gem install xmlrpc
gem install xpath
gem install yard
gem install zlib
