npm i -g @angular
npm i -g @aweary
npm i -g actionhero
npm i -g all-the-package-names
npm i -g appdmg
npm i -g ask-cli
npm i -g axios
npm i -g babel-cli
npm i -g bash-language-server
npm i -g cat-me
npm i -g chalksay
npm i -g cli
npm i -g cli-github
npm i -g coffeescript
npm i -g cordova
npm i -g cowsay
npm i -g create-elm-app
npm i -g create-react-app
npm i -g electron
npm i -g ember-cli
npm i -g eslint
npm i -g expect
npm i -g express-generator
npm i -g fix-yarn-global-packages
npm i -g generator-jhipster-kotlin
npm i -g glob
npm i -g globby
npm i -g grunt-cli
npm i -g gtop
npm i -g gulp
npm i -g how-to-npm
npm i -g how2
npm i -g html-minifier
npm i -g httpster
npm i -g idea
npm i -g ionic
npm i -g ios-sim
npm i -g istanbul
npm i -g jade
npm i -g jasmine
npm i -g jest
npm i -g jquery
npm i -g learnyoumongo
npm i -g lib
npm i -g locus
npm i -g lolcatjs
npm i -g mancy
npm i -g mocha
npm i -g mongo-hacker
npm i -g neovim
npm i -g node-dev
npm i -g nodemon
npm i -g npm
npm i -g npm-home
npm i -g npm-run-all
npm i -g parse-dashboard
npm i -g pkg
npm i -g pug
npm i -g pure-prompt
npm i -g raspberry
npm i -g react-devtools
npm i -g react-native-cli
npm i -g react-scripts
npm i -g react-tools
npm i -g redis-commander
npm i -g reload
npm i -g remote-share-cli
npm i -g rtop
npm i -g serve
npm i -g shelobsay
npm i -g should
npm i -g sinon
npm i -g spoof
npm i -g sprity
npm i -g sprity-cli
npm i -g termcolors
npm i -g tern
npm i -g ts-node
npm i -g tv4
npm i -g typescript
npm i -g uglify-js
npm i -g vtop
npm i -g vue-cli
npm i -g webpack
npm i -g webpack-cli
npm i -g yarn
npm i -g yosay
