pip install arrow
pip install Babel
pip install backports-abc
pip install backports.functools-lru-cache
pip install bashate
pip install BeautifulSoup
pip install blessings
pip install bottle
pip install bpython
pip install certifi
pip install chardet
pip install click
pip install colorama
pip install cssselect
pip install curtsies
pip install docutils
pip install enum
pip install enum34
pip install futures
pip install Glances
pip install greenlet
pip install howdoi
pip install icc-rt
pip install idna
pip install intel-numpy
pip install intel-openmp
pip install lockfile
pip install lxml
pip install maybe
pip install mercurial
pip install mkl
pip install mkl-fft
pip install mkl-random
pip install netifaces
pip install numpy
pip install parse
pip install parse-type
pip install pbr
pip install platformio
pip install powerline-mem-segment
pip install powerline-status
pip install psutil
pip install Pygments
pip install pync
pip install pyportmidi
pip install pyquery
pip install pyserial
pip install pysqlite
pip install python-dateutil
pip install python-ptrace
pip install pytz
pip install requests
pip install requests-cache
pip install selenium
pip install semantic-version
pip install singledispatch
pip install six
pip install snakeviz
pip install tornado
pip install typing
pip install urllib3
pip install virtualenv
pip install wcwidth
pip install yasm
