python3 -m pip install aiofiles
python3 -m pip install ajsonrpc
python3 -m pip install alabaster
python3 -m pip install aniso8601
python3 -m pip install ansicolor
python3 -m pip install anyio
python3 -m pip install appnope
python3 -m pip install argon2-cffi
python3 -m pip install asgiref
python3 -m pip install asn1crypto
python3 -m pip install astroid
python3 -m pip install async-generator
python3 -m pip install atomicwrites
python3 -m pip install attrs
python3 -m pip install Babel
python3 -m pip install backcall
python3 -m pip install backports.entry-points-selectable
python3 -m pip install backports.shutil-get-terminal-size
python3 -m pip install banknumber
python3 -m pip install behave
python3 -m pip install bleach
python3 -m pip install blessings
python3 -m pip install bottle
python3 -m pip install bpython
python3 -m pip install cachetools
python3 -m pip install certifi
python3 -m pip install cffi
python3 -m pip install chardet
python3 -m pip install charset-normalizer
python3 -m pip install cli-helpers
python3 -m pip install click
python3 -m pip install clingo
python3 -m pip install colorama
python3 -m pip install configobj
python3 -m pip install cryptography
python3 -m pip install cursor
python3 -m pip install curtsies
python3 -m pip install cwcwidth
python3 -m pip install cycler
python3 -m pip install Cython
python3 -m pip install debugpy
python3 -m pip install decorator
python3 -m pip install defusedxml
python3 -m pip install distlib
python3 -m pip install Django
python3 -m pip install docopt
python3 -m pip install docutils
python3 -m pip install entrypoints
python3 -m pip install enum34
python3 -m pip install filelock
python3 -m pip install flake8
python3 -m pip install Flask
python3 -m pip install Flask-PyMongo
python3 -m pip install Flask-RESTful
python3 -m pip install fonttools
python3 -m pip install future
python3 -m pip install Glances
python3 -m pip install gpg
python3 -m pip install greenlet
python3 -m pip install gunicorn
python3 -m pip install h11
python3 -m pip install h5py
python3 -m pip install halo
python3 -m pip install html5lib
python3 -m pip install httpie
python3 -m pip install humanize
python3 -m pip install idna
python3 -m pip install ifaddr
python3 -m pip install imageio
python3 -m pip install imageio-ffmpeg
python3 -m pip install imagesize
python3 -m pip install importlib-metadata
python3 -m pip install importlib-resources
python3 -m pip install iniconfig
python3 -m pip install ipykernel
python3 -m pip install ipython
python3 -m pip install ipython-genutils
python3 -m pip install ipywidgets
python3 -m pip install isort
python3 -m pip install itsdangerous
python3 -m pip install jedi
python3 -m pip install Jinja2
python3 -m pip install joblib
python3 -m pip install jsonschema
python3 -m pip install jupyter-client
python3 -m pip install jupyter-core
python3 -m pip install jupyterlab-pygments
python3 -m pip install jupyterlab-widgets
python3 -m pip install Kivy-Garden
python3 -m pip install kiwisolver
python3 -m pip install lazy-object-proxy
python3 -m pip install log-symbols
python3 -m pip install lxml
python3 -m pip install Markdown
python3 -m pip install MarkupSafe
python3 -m pip install marshmallow
python3 -m pip install matplotlib
python3 -m pip install matplotlib-inline
python3 -m pip install mccabe
python3 -m pip install mdv
python3 -m pip install mercurial
python3 -m pip install meson
python3 -m pip install mistune
python3 -m pip install more-itertools
python3 -m pip install MouseInfo
python3 -m pip install moviepy
python3 -m pip install msgpack
python3 -m pip install mycli
python3 -m pip install mysqlclient
python3 -m pip install nbclient
python3 -m pip install nbconvert
python3 -m pip install nbformat
python3 -m pip install neovim
python3 -m pip install neovim-remote
python3 -m pip install nest-asyncio
python3 -m pip install notebook
python3 -m pip install numpy
python3 -m pip install olefile
python3 -m pip install opencv-python
python3 -m pip install outcome
python3 -m pip install packaging
python3 -m pip install paho-mqtt
python3 -m pip install pandas
python3 -m pip install pandocfilters
python3 -m pip install parse
python3 -m pip install parse-type
python3 -m pip install parso
python3 -m pip install pendulum
python3 -m pip install pexpect
python3 -m pip install pgcli
python3 -m pip install pgspecial
python3 -m pip install pickleshare
python3 -m pip install Pillow
python3 -m pip install pip
python3 -m pip install platformdirs
python3 -m pip install platformio
python3 -m pip install pluggy
python3 -m pip install powerline-mem-segment
python3 -m pip install powerline-status
python3 -m pip install prettytable
python3 -m pip install proglog
python3 -m pip install prometheus-client
python3 -m pip install prompt-toolkit
python3 -m pip install psutil
python3 -m pip install psycopg2
python3 -m pip install ptyprocess
python3 -m pip install py
python3 -m pip install pyaes
python3 -m pip install PyAutoGUI
python3 -m pip install pycairo
python3 -m pip install pycodestyle
python3 -m pip install pycparser
python3 -m pip install pydf
python3 -m pip install pyelftools
python3 -m pip install pyflakes
python3 -m pip install PyGetWindow
python3 -m pip install Pygments
python3 -m pip install PyGObject
python3 -m pip install pylint
python3 -m pip install pymongo
python3 -m pip install PyMsgBox
python3 -m pip install PyMySQL
python3 -m pip install pynvim
python3 -m pip install pyobjc
python3 -m pip install pyobjc-core
python3 -m pip install pyobjc-framework-Accessibility
python3 -m pip install pyobjc-framework-Accounts
python3 -m pip install pyobjc-framework-AddressBook
python3 -m pip install pyobjc-framework-AdServices
python3 -m pip install pyobjc-framework-AdSupport
python3 -m pip install pyobjc-framework-AppleScriptKit
python3 -m pip install pyobjc-framework-AppleScriptObjC
python3 -m pip install pyobjc-framework-ApplicationServices
python3 -m pip install pyobjc-framework-AppTrackingTransparency
python3 -m pip install pyobjc-framework-AudioVideoBridging
python3 -m pip install pyobjc-framework-AuthenticationServices
python3 -m pip install pyobjc-framework-AutomaticAssessmentConfiguration
python3 -m pip install pyobjc-framework-Automator
python3 -m pip install pyobjc-framework-AVFoundation
python3 -m pip install pyobjc-framework-AVKit
python3 -m pip install pyobjc-framework-BusinessChat
python3 -m pip install pyobjc-framework-CalendarStore
python3 -m pip install pyobjc-framework-CallKit
python3 -m pip install pyobjc-framework-CFNetwork
python3 -m pip install pyobjc-framework-ClassKit
python3 -m pip install pyobjc-framework-CloudKit
python3 -m pip install pyobjc-framework-Cocoa
python3 -m pip install pyobjc-framework-Collaboration
python3 -m pip install pyobjc-framework-ColorSync
python3 -m pip install pyobjc-framework-Contacts
python3 -m pip install pyobjc-framework-ContactsUI
python3 -m pip install pyobjc-framework-CoreAudio
python3 -m pip install pyobjc-framework-CoreAudioKit
python3 -m pip install pyobjc-framework-CoreBluetooth
python3 -m pip install pyobjc-framework-CoreData
python3 -m pip install pyobjc-framework-CoreHaptics
python3 -m pip install pyobjc-framework-CoreLocation
python3 -m pip install pyobjc-framework-CoreMedia
python3 -m pip install pyobjc-framework-CoreMediaIO
python3 -m pip install pyobjc-framework-CoreMIDI
python3 -m pip install pyobjc-framework-CoreML
python3 -m pip install pyobjc-framework-CoreMotion
python3 -m pip install pyobjc-framework-CoreServices
python3 -m pip install pyobjc-framework-CoreSpotlight
python3 -m pip install pyobjc-framework-CoreText
python3 -m pip install pyobjc-framework-CoreWLAN
python3 -m pip install pyobjc-framework-CryptoTokenKit
python3 -m pip install pyobjc-framework-DataDetection
python3 -m pip install pyobjc-framework-DeviceCheck
python3 -m pip install pyobjc-framework-DictionaryServices
python3 -m pip install pyobjc-framework-DiscRecording
python3 -m pip install pyobjc-framework-DiscRecordingUI
python3 -m pip install pyobjc-framework-DiskArbitration
python3 -m pip install pyobjc-framework-DVDPlayback
python3 -m pip install pyobjc-framework-EventKit
python3 -m pip install pyobjc-framework-ExceptionHandling
python3 -m pip install pyobjc-framework-ExecutionPolicy
python3 -m pip install pyobjc-framework-ExternalAccessory
python3 -m pip install pyobjc-framework-FileProvider
python3 -m pip install pyobjc-framework-FileProviderUI
python3 -m pip install pyobjc-framework-FinderSync
python3 -m pip install pyobjc-framework-FSEvents
python3 -m pip install pyobjc-framework-GameCenter
python3 -m pip install pyobjc-framework-GameController
python3 -m pip install pyobjc-framework-GameKit
python3 -m pip install pyobjc-framework-GameplayKit
python3 -m pip install pyobjc-framework-ImageCaptureCore
python3 -m pip install pyobjc-framework-IMServicePlugIn
python3 -m pip install pyobjc-framework-InputMethodKit
python3 -m pip install pyobjc-framework-InstallerPlugins
python3 -m pip install pyobjc-framework-InstantMessage
python3 -m pip install pyobjc-framework-Intents
python3 -m pip install pyobjc-framework-IntentsUI
python3 -m pip install pyobjc-framework-IOSurface
python3 -m pip install pyobjc-framework-iTunesLibrary
python3 -m pip install pyobjc-framework-KernelManagement
python3 -m pip install pyobjc-framework-LatentSemanticMapping
python3 -m pip install pyobjc-framework-LaunchServices
python3 -m pip install pyobjc-framework-libdispatch
python3 -m pip install pyobjc-framework-LinkPresentation
python3 -m pip install pyobjc-framework-LocalAuthentication
python3 -m pip install pyobjc-framework-LocalAuthenticationEmbeddedUI
python3 -m pip install pyobjc-framework-MailKit
python3 -m pip install pyobjc-framework-MapKit
python3 -m pip install pyobjc-framework-MediaAccessibility
python3 -m pip install pyobjc-framework-MediaLibrary
python3 -m pip install pyobjc-framework-MediaPlayer
python3 -m pip install pyobjc-framework-MediaToolbox
python3 -m pip install pyobjc-framework-Metal
python3 -m pip install pyobjc-framework-MetalKit
python3 -m pip install pyobjc-framework-MetalPerformanceShaders
python3 -m pip install pyobjc-framework-MetalPerformanceShadersGraph
python3 -m pip install pyobjc-framework-MetricKit
python3 -m pip install pyobjc-framework-MLCompute
python3 -m pip install pyobjc-framework-ModelIO
python3 -m pip install pyobjc-framework-MultipeerConnectivity
python3 -m pip install pyobjc-framework-NaturalLanguage
python3 -m pip install pyobjc-framework-NetFS
python3 -m pip install pyobjc-framework-Network
python3 -m pip install pyobjc-framework-NetworkExtension
python3 -m pip install pyobjc-framework-NotificationCenter
python3 -m pip install pyobjc-framework-OpenDirectory
python3 -m pip install pyobjc-framework-OSAKit
python3 -m pip install pyobjc-framework-OSLog
python3 -m pip install pyobjc-framework-PassKit
python3 -m pip install pyobjc-framework-PencilKit
python3 -m pip install pyobjc-framework-Photos
python3 -m pip install pyobjc-framework-PhotosUI
python3 -m pip install pyobjc-framework-PreferencePanes
python3 -m pip install pyobjc-framework-PubSub
python3 -m pip install pyobjc-framework-PushKit
python3 -m pip install pyobjc-framework-QTKit
python3 -m pip install pyobjc-framework-Quartz
python3 -m pip install pyobjc-framework-QuickLookThumbnailing
python3 -m pip install pyobjc-framework-ReplayKit
python3 -m pip install pyobjc-framework-SafariServices
python3 -m pip install pyobjc-framework-SceneKit
python3 -m pip install pyobjc-framework-ScreenSaver
python3 -m pip install pyobjc-framework-ScreenTime
python3 -m pip install pyobjc-framework-ScriptingBridge
python3 -m pip install pyobjc-framework-SearchKit
python3 -m pip install pyobjc-framework-Security
python3 -m pip install pyobjc-framework-SecurityFoundation
python3 -m pip install pyobjc-framework-SecurityInterface
python3 -m pip install pyobjc-framework-ServiceManagement
python3 -m pip install pyobjc-framework-ShazamKit
python3 -m pip install pyobjc-framework-Social
python3 -m pip install pyobjc-framework-SoundAnalysis
python3 -m pip install pyobjc-framework-Speech
python3 -m pip install pyobjc-framework-SpriteKit
python3 -m pip install pyobjc-framework-StoreKit
python3 -m pip install pyobjc-framework-SyncServices
python3 -m pip install pyobjc-framework-SystemConfiguration
python3 -m pip install pyobjc-framework-SystemExtensions
python3 -m pip install pyobjc-framework-UniformTypeIdentifiers
python3 -m pip install pyobjc-framework-UserNotifications
python3 -m pip install pyobjc-framework-UserNotificationsUI
python3 -m pip install pyobjc-framework-VideoSubscriberAccount
python3 -m pip install pyobjc-framework-VideoToolbox
python3 -m pip install pyobjc-framework-Virtualization
python3 -m pip install pyobjc-framework-Vision
python3 -m pip install pyobjc-framework-WebKit
python3 -m pip install pyOpenSSL
python3 -m pip install pyparsing
python3 -m pip install PyPDF2
python3 -m pip install pyperclip
python3 -m pip install PyRect
python3 -m pip install pyrsistent
python3 -m pip install PyScreeze
python3 -m pip install pyserial
python3 -m pip install PySocks
python3 -m pip install pytest
python3 -m pip install python-dateutil
python3 -m pip install python-docx
python3 -m pip install pytweening
python3 -m pip install pytz
python3 -m pip install pytzdata
python3 -m pip install pywatchman
python3 -m pip install pyxdg
python3 -m pip install PyYAML
python3 -m pip install pyzmq
python3 -m pip install relativetimebuilder
python3 -m pip install requests
python3 -m pip install requests-toolbelt
python3 -m pip install rubicon-objc
python3 -m pip install scikit-learn
python3 -m pip install scipy
python3 -m pip install selenium
python3 -m pip install semantic-version
python3 -m pip install Send2Trash
python3 -m pip install setproctitle
python3 -m pip install setuptools
python3 -m pip install setuptools-scm
python3 -m pip install simplegeneric
python3 -m pip install six
python3 -m pip install sklearn
python3 -m pip install sniffio
python3 -m pip install snowballstemmer
python3 -m pip install sortedcontainers
python3 -m pip install speedtest-cli
python3 -m pip install Sphinx
python3 -m pip install sphinxcontrib-applehelp
python3 -m pip install sphinxcontrib-devhelp
python3 -m pip install sphinxcontrib-htmlhelp
python3 -m pip install sphinxcontrib-jsmath
python3 -m pip install sphinxcontrib-qthelp
python3 -m pip install sphinxcontrib-serializinghtml
python3 -m pip install sphinxcontrib-websupport
python3 -m pip install spinners
python3 -m pip install sqlparse
python3 -m pip install starlette
python3 -m pip install tabulate
python3 -m pip install termcolor
python3 -m pip install terminado
python3 -m pip install terminaltables
python3 -m pip install testpath
python3 -m pip install threadpoolctl
python3 -m pip install toml
python3 -m pip install tomli
python3 -m pip install tornado
python3 -m pip install tqdm
python3 -m pip install traitlets
python3 -m pip install trio
python3 -m pip install trio-websocket
python3 -m pip install typed-ast
python3 -m pip install typing
python3 -m pip install typing_extensions
python3 -m pip install urllib3
python3 -m pip install uvicorn
python3 -m pip install vim-vint
python3 -m pip install virtualenv
python3 -m pip install wcwidth
python3 -m pip install webencodings
python3 -m pip install websockets
python3 -m pip install Werkzeug
python3 -m pip install wheel
python3 -m pip install widgetsnbextension
python3 -m pip install wrapt
python3 -m pip install wsproto
python3 -m pip install xlrd
python3 -m pip install xlwt
python3 -m pip install yapf
python3 -m pip install youtube-dl
python3 -m pip install zeroconf
python3 -m pip install zipp
