CPU_Stresser.sh
archetypeShower.sh
autoUpdater.sh
backgroundMastery.sh
backupBashConfig.sh
banner.pl
batchRename.sh
blueText.sh
blueUpperText.sh
boiler_gen.py
boldText.sh
boxPrint.pl
c.pl
clearTrash.sh
colorLogger.sh
connectionShower.sh
coolFormatter.sh
createScriptButDontOpenSublime.sh
createTextFile.sh
customTerminalInstaller
directoryContentsSize.sh
dsDownloader.sh
duplicateLineDeleter.sh
encrypt.sh
escapeRemover.pl
evilSkull.sh
eyes.sh
forever.sh
fsWatchLongRunning.sh
genericDisplayer.sh
genericDisplayerLolcat.sh
gitRemoteRepoInformation.sh
gitSdiffColorizer.pl
gitgo.sh
goForward.sh
headerSummarizer.sh
help2comp.py
indenterAndDuplicateLineDeleter.sh
info.sh
inotifyWatchLogAndEmailIfNAS.sh
iostatShower.sh
listAllCommands.sh
logs.sh
macOnly
menkeTech.sh
menkeTechLolcat.sh
minifySpaces.pl
myWatchMaintainEscapes.sh
myWatchNoBlink.sh
myWatchNoBlinkColorized.sh
mywatch.sh
odroidtemp.sh
oldCounter.sh
openAll.sh
picture_finder.sh
pingordie.sh
pipUpdater.sh
powerTo.sh
printHeader.sh
pydfShower.sh
rcBackups
readFIFO.sh
redText.sh
regexreplace.pl
remoteRepoMonitorDaemon.sh
removeSpaces.sh
rpiDownloader.sh
rpiSoftwareUpdater.sh
runner.sh
saygoogle.sh
sdiffColorizer.pl
secureDelete.sh
shebangChanger.sh
sixLangDisplayer.sh
sortedArrayCounter.sh
splitReg.sh
sshTunnelVnc.sh
sshTunnelVnc2.sh
storageShower.sh
sync.sh
t t.sh
templater.sh
test.sh
textmessage.sh
tgzLocalInstaller.sh
timeConverter.sh
transfer.sh
upLoadDS.sh
upLoadPi.sh
upLoadPi2.sh
updater.sh
updaterEmail.sh
updaterForLaunchCtl.sh
uploadWebDS.sh
uploadWebPi.sh
userRootRemover.sh
watchServiceFSWatchGit.sh
watchServiceFSWatchLS-ALH.sh
watchServiceFSWatchPiDesktop.sh
watchServiceFSWatchPiWeb.sh
watchServiceFSWatchRustCompile.sh
watchtree1.sh
watchtree1Color.sh
watchtree2.sh
zshcompgen.sh
