# vim: set ft=tmux:

rename-session zpwr
rename-window main
selectp -t 0 # select the first (0) pane
splitw -h -p 50 # split it into two vertical halves
selectp -t 0 # select the first (0) pane
splitw -v -p 50 # split it into two horizontal halves
selectp -t 0 # select the top left pane
# handle errors/copy-mode
send-keys C-C
send-keys C-C
send-keys ' :; "builtin" command sudo -E env PATH="$PATH" htop' C-m
selectp -t 1 # select the middle pane
send-keys ' "builtin" command sudo -E env PATH="$PATH" bash '"$ZPWR_SCRIPTS/colorLogger.sh" C-m

splitw -v -p 40 # split it into two horizontal halves
selectp -t 2
send-keys 'storageshower' C-m

selectp -t right # select the new, second (1) pane
splitw -v -p 30
if-shell "uname | grep -q Darwin" \
        'send-keys "sudo -E ~/.cargo/bin/iftoprs -f \"not port mdns and not port ssdp and not port llmnr and not port upnp-discovery\"" C-m' \
        'send-keys "sudo -E ~/.cargo/bin/iftoprs" C-M'
selectp -t right # select top right pane
